### ISSUE TITLE
Typescript is not working .vue sfc

### ISSUE THREAD

**Issue by hareku** [vuejs/composition-api#100]
I tried the code below and Typescript didn't work.

```vue
<template>
  <div>{{ msg }}</div>
</template>

<script lang="ts">
import { createComponent } from '@vue/composition-api'

interface Props {
  msg: string
}

export default createComponent<Props>({
  props: {
    msg: {}
  },

  setup(props, ctx) {},
});

</script>
```

![8f90349081e9c2448de73510121856a0](https://user-images.githubusercontent.com/17667652/63844477-42523400-c9c3-11e9-9bcf-29ed6c834bd2.png)

However, I changed to `.tsx` and Typescript worked out.

```tsx
import { createComponent, createElement as h } from '@vue/composition-api'

interface Props {
  msg: string
}

const MyComponent = createComponent<Props>({
  props: { 
     msg: {}  // required by vue 2 runtime
  },
  setup(props) {
    return () => h('div', props.msg)
  }
})
```

Does anyone know a solution?

**Comment by posva** [comment]
does this help: https://github.com/vuejs/composition-api/issues/90#issuecomment-525555406

**Comment by hareku** [comment]
@posva 
It worked! Thank you very much.
