### ISSUE TITLE
props { default: () => ) not unwrap 

### ISSUE THREAD

**Issue by TrungRueta** [vuejs/composition-api#102]
Hi!

i found that when set `Ref<T>` variable as default of `props` it not unwrap, but in case props provided value by parent component via template ex: `<child :me="me"/>` then `me` auto unwrap in child component.

[demo when default prop is Ref](https://jsfiddle.net/trungrueta/81qomwe6/20/)

so now we have 3 case, let call prop named `me`:
1. `me` assign value from parent `:me="other"`. In any case , value always be unwrap before used inside child's `setup` or child's `template`.
2. `me` not assigned by parent, so it use default (like my demo) and now it require unwrap by hand (in template, use `{{ me.value }}` instead of `{{ me }}`.
3. if we dont want change template from `{{ me }}` to `{{me.value}}`, we can change default prop: from `default: () => refMe` to `default: () => refMe.value` but this will lead to losing reactive value.

hope we can check this case and find best solution.
Thank!

**Comment by liximomo** [comment]
It makes no sense to pass a ref as prop value. Why not `default : () => meValue`
