### ISSUE TITLE
Template ref variable's type is not inferred as expected

### ISSUE THREAD

**Issue by HermitSun** [vuejs/composition-api#105]
I noticed that when I use `ref` like this, the template ref variable's type is not inferred as expected:

```
const foo = ref(document.createElement('input'));
```

I couldn't call its inner method, and its type will be inferred as `string`:

```typescript
onMounted(() => {
    foo.value.focus(); // TS2339: Property 'focus' does not exist on type 'string'.
});
```

And I found that when I defined the variable like this, it works well:

```typescript
const foo = ref<HTMLInputElement>(document.createElement('input'));
```

Maybe you can see the online example in [codesandbox](https://codesandbox.io/s/vue-typescript-example-gtlz9).

Did something go wrong during the process of unwrapping? I noticed that you use statements like `[K in keyof T]: UnwrapRef2<T[K]>;` to unwrap the ref value.

Or, did I get something wrong? And how could I use `ref` correctly?

**Comment by leopiccionia** [comment]
I think the error occurs because `HTMLInputElement.prototype.value` is a `string`, and `Ref<T>` seems to be [resolved "recursively"](https://github.com/vuejs/composition-api/blob/dbaca0ab3989dfca3fac1a8660e43c190bdd36d4/src/reactivity/ref.ts) on TypeScript.

**Comment by HermitSun** [comment]
By the way, I tried to use `ref` with render function as the doc says, but I couldn't get the ref( and I couldn't assign ref variables to render function's data option `ref`). I noticed that after mounted, it still seems to be `null`:
```ts
import {createComponent, createElement as h, ref} from '@vue/composition-api';

export default createComponent({
  setup() {
    const root = ref(null);

    onMounted(() => {
      console.log(root); // null
    });

    return () => h('div', {
      ref: root as any
    });
  }
});
```

**Comment by liximomo** [comment]
@HermitSun Read this https://github.com/vuejs/composition-api#template-refs

**Comment by HermitSun** [comment]
😅 I'm sorry, I should read all the docs carefully. And what about the previous question? tks.

**Comment by liximomo** [comment]
type infer of `ref` can't work always as expected now. Explicitly specifying type using `ref<Type>` is fine.

**Comment by HermitSun** [comment]
OK.  Thanks a lot.
