### ISSUE TITLE
prop with `required: true` have type undefined

### ISSUE THREAD

**Issue by kevinmarrec** [vuejs/composition-api#106]
# Description
As Vue handle `required` validation and throws an error if a component is missing a required prop, the resulting type of a `required `prop shouldn't be "possibly" `undefined`.

# Markup

```ts
import { createComponent } from '@vue/composition-api'

export default createComponent({
  props: {
    defaultNumber: {
      type: Number,
      default: 2
    },
    requiredNumber: {
      type: Number,
      required: true
    }
  },
  setup ({ defaultNumber, requiredNumber }) {
    return {
      defaultNumber,
      requiredNumber
    }
  }
})
```

# Prop with `default` value 👍
![image](https://user-images.githubusercontent.com/25272043/63973389-f5498d00-caaa-11e9-981b-bf46b0d339e0.png)

# Prop `required` ❌
![image](https://user-images.githubusercontent.com/25272043/63973405-fbd80480-caaa-11e9-899d-6b654e5c1861.png)
**`requiredNumber`** is expected to be of type **`number`**, not **`number | undefined`**
# Notes
I guess there's something wrong around https://github.com/vuejs/composition-api/blob/master/src/component/componentProps.ts#L20

# Workaround

@lbssousa mentionned casting props to `const` and it works.
But I think it shouldn't be needed and there is something to fix around types.

**Comment by lbssousa** [comment]
You may need to put `as const` at the end of `props: { ... }`

**Comment by kevinmarrec** [comment]
@lbssousa Nice catch, but isn't there an issue around the types (see Notes section) that would make it work without having casting to `const` ?

Also, I'm wondering why we don't have Intellisense for `type`, `default`, `required` and `validator` like we used to with `Vue.extend` :
![image](https://user-images.githubusercontent.com/25272043/63974173-9d138a80-caac-11e9-8e4c-ca4357c886ac.png)

**Comment by liximomo** [comment]
@kevinmarrec Why did it not work for me? 🤔 

![image](https://user-images.githubusercontent.com/9816225/63995096-c9212100-cb29-11e9-9826-c2723621dd10.png)

**Comment by kevinmarrec** [comment]
@liximomo Which installed version of TypeScript have you in the workspace of this snippet ?

**Comment by kevinmarrec** [comment]
And about the original creation of this issue, can you confirm casting to `const` is the way to go ? There isn't types change we could do to not having to cast type of props ?

**Comment by liximomo** [comment]
The `as const` is required. We need to use `as const` to narrow down the inferred type from `boolean` to `true`.

**Comment by liximomo** [comment]
In fact, we can get rid of `as const`.

**Comment by kevinmarrec** [comment]
Nice :)

**Comment by bbugh** [comment]
In case anyone else like me ends up here from a web search wondering about props with an inferred `any`, or missing intellisense for `createComponent` like mentioned above, note the readme states:

> This plugin requires TypeScript version >3.5.1. If you are using vetur, make sure to set `vetur.useWorkspaceDependencies` to true.

https://github.com/vuejs/composition-api#typescript

Upgrading our TypeScript fixed the intellisense and type inference.
