### ISSUE TITLE
Properties of reactive object passed through toRefs() aren't unwrapped into templates

### ISSUE THREAD

**Issue by IlCallo** [vuejs/composition-api#107]
```vue
<script lang="ts" src="./projects.ts">
export default createComponent({
  setup() {
    const rxrx = toRefs(reactive({
      x: 'randomString',
    }));

    return { rxrx, ...rxrx };
  },
});
</script>

<template>
  <div>
    {{ rxrx.x }} <!-- I expected this to be unwrapped, instead I get the Ref object -->
    {{ rxrx.x.value }} <!-- Not unwrapped, works -->
    {{ x }} <!-- Unwrapped, works -->
  </div>
</template>
```

May be a "works as intended" scenario, but it's not explicited on the RFC so I prefer to report it.

**Comment by liximomo** [comment]
It indeed works as intended. 

https://vue-composition-api-rfc.netlify.com/api.html#torefs
> Convert a reactive object to a **plain object,** where each property on the resulting object is a ref pointing to the corresponding property in the original object.

https://vue-composition-api-rfc.netlify.com/#ref-unwrapping
> We can expose **a ref as a property** on the render context. Internally, Vue will perform special treatment for refs so that when a ref is encountered on the render context, the context directly exposes its inner value.
