### ISSUE TITLE
ts中render this上读取不到定义的值

### ISSUE THREAD

**Issue by Qymh** [vuejs/composition-api#108]
![image](https://user-images.githubusercontent.com/29172211/64058764-7fe0d800-cbe2-11e9-848b-183a60963a88.png)

可以正常渲染,但ts会报错,请问一哈是使用方法有问题吗?

还是我得去手动指定this的绑定值呀

**Comment by liximomo** [comment]
`createComponent` 本身是个新加的 api， 所以没有对旧的render 提供类型支持，建议直接在 setup 中返回 `render` 函数，或者在 `render` 中声明 `this` 为 `any`： `render(this: any, h)`
