### ISSUE TITLE
TypeError: undefined is not iterable! appears when using watch()

### ISSUE THREAD

**Issue by deviant-F** [vuejs/composition-api#109]
I have defined my watch function below:
`watch([a, b], ([currentA,currentB], [prevA, prevB]) => { ... }`

During the first iteration, prevA & prevB are undefined at the beginning, which causes `TypeError: undefined is not iterable! `

It's not a breaking error. My app can still run. But it's better to fix the error in the console.

**Comment by liximomo** [comment]
This is expected. You should regard the `[valA, valB]` as a single whole
value. So the pre value of the first run should be `undefined`.

deviant-F <notifications@github.com> 于 2019年8月31日周六 23:02写道：
