### ISSUE TITLE
async reactive mutation in setup does not cause rerender with render function

### ISSUE THREAD

**Issue by btoo** [vuejs/composition-api#114]
I'm using a simple `setTimeout` to asynchronously add a key to a `reactive` key-value store in my `setup` and then displaying the values of this key-value store through a render function returned in the `setup`, [as specified here](https://vue-composition-api-rfc.netlify.com/api.html#setup), but it seems doing so does not force a rerender of the the UI. It isn't until I include an additional `ref` directly in the template and mutate the `ref` at the same time I mutate the `reactive` that I am able to have my mutations reflected in the UI. Am I using the API correctly?

See my issue in the following codesandbox by swapping between `Works` and `DoesntWork`:

[![Edit Vue Template](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vue-template-t8hf8?fontsize=14)

**Comment by liximomo** [comment]
Since we are using vue 2, the [caveats](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats) still remains.

**Comment by liximomo** [comment]
Since we are using vue 2, the [caveats](https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats) still remains.

```js
setup() {
    const keyValueStore = reactive({ firstKey: "firstValue" , secondKey: '' });
    
    setTimeout(() => {
       keyValueStore.secondKey = 'secondValue';
    }, 888);

    return () => h("div", Object.values(keyValueStore).join(" "));
  }
```

**Comment by btoo** [comment]
ah i see. thanks @liximomo. however, im now wondering - is not even
```javascript
setTimeout(() => Vue.set(keyValueStore, "secondKey", "secondValue"))
```
supposed to work?

**Comment by liximomo** [comment]
Unfortunately, No. It's equivalent to the below which could not work.

```js
const state = Vue.observable({ firstKey: "firstValue" });
const DoesntWork = createComponent({
  create() {
    setTimeout(() => {
      Vue.set(state, "secondKey", "secondValue");
    }, 888);
  },
  render(h) {
    return h("div", Object.values(state).join(" "));
  }
});
```

`Object.values(keyValueStore)`  tells vue to watch 'firstKey' property of `keyValueStore`. So it will not reactive to a modification of `secondKey`.

It works in this way:
```js
const state = Vue.observable({ data: { firstKey: "firstValue" } });
const DoesntWork = createComponent({
  created() {
    setTimeout(() => {
      Vue.set(state.data, "secondKey", "secondValue");
    }, 888);
  },
  render(h) {
    return h("div", Object.values(state.data).join(" "));
  }
});
```
