### ISSUE TITLE
api=> createComponent  bug错误    类型错误

### ISSUE THREAD

**Issue by Polaris-z** [vuejs/composition-api#115]
![image](https://user-images.githubusercontent.com/28984303/64237898-e5f59400-cf2f-11e9-9218-bc86f03080f9.png)
![image](https://user-images.githubusercontent.com/28984303/64237913-f0b02900-cf2f-11e9-926a-ded36ca9332d.png)
![image](https://user-images.githubusercontent.com/28984303/64237928-f7d73700-cf2f-11e9-8bf4-e083ac6d0678.png)

期望：
![image](https://user-images.githubusercontent.com/28984303/64238096-500e3900-cf30-11e9-8f7c-21d0089fbea4.png)
![image](https://user-images.githubusercontent.com/28984303/64238201-8d72c680-cf30-11e9-806b-b01d8a6e4b83.png)

**Comment by liximomo** [comment]
Please provide a reproduction?
