### ISSUE TITLE
not working on ios9 safari

### ISSUE THREAD

**Issue by Rockcookies** [vuejs/composition-api#116]
Hello,

I found a critical bug with composition-api on iOS 9 Safari. The problem is that the page can't be loaded but `setup`  function is invoked.

Any help is appreciated, I spent some time on debuging this and it's only happening on iOS 9 devices. On iOS 8 devices it's working, but the loading is extremely long.

**Comment by liximomo** [comment]
Have you tried the `no-setup` way?

**Comment by Rockcookies** [comment]
here: https://github.com/Rockcookies/vue-composition-api-ios9

in my android 4.4
![image](https://user-images.githubusercontent.com/3498265/64308742-e55f0b00-cfcc-11e9-8188-ebc27067efd7.png)

in my ios9.3.4
![image](https://user-images.githubusercontent.com/3498265/64308810-1b9c8a80-cfcd-11e9-8246-0b20ed021301.png)

**Comment by F-happy** [comment]
@Rockcookies you need Reflect polyfill

**Comment by zhiquan-yu** [comment]
@Rockcookies 
Add `import 'core-js/features/reflect/own-keys'` in your index.js, because composition-api uses [Reflect](https://github.com/vuejs/composition-api/blob/master/src/install.ts#L16) which not work on iOS 9

**Comment by HcySunYang** [comment]
The problem is caused here: https://github.com/vuejs/composition-api/blob/master/src/utils.ts#L5

In IOS 9, we should check `hasSymbol` with:
```
export const hasSymbol =
    typeof Symbol !== 'undefined' && isNative(Symbol) &&
    typeof Reflect !== 'undefined' && isNative(Reflect.ownKeys);
```
This code is copied from `vue`.

**Comment by zhiquan-yu** [comment]
@liximomo please publish a patch version
