### ISSUE TITLE
 Which hook should I initiate the request on?

### ISSUE THREAD

**Issue by xieyezi** [vuejs/composition-api#117]
as we konw,now setup() ,which is called after the beforeCreate hook and before the created hook.
in the Vue2.x,we initate quest in created hook. 
and now, ‘’this‘’ is not available inside setup().
so Whcih hook should I inintate my request best?

**Comment by LinusBorg** [comment]
> Whcih hook should I inintate my request best?

Directly in setup

> and now, ‘’this‘’ is not available inside setup().

Why is that a problem?

**Comment by xieyezi** [comment]
@LinusBorg  thank you!

**Comment by xieyezi** [comment]
like this:
```
 created() {
	this.getList();		
 }
```
become:
```
setup(){
  this.getList();
}
```
right?

@LinusBorg

**Comment by LinusBorg** [comment]
No. As you said yourself, `this` is not available

But I have no idea what `getList` is or where it comes from, so I don't know what to recommend.

**Comment by xieyezi** [comment]
this is my `getList()`:
```
function getList() {
      this.$axios.get("rul").then(res => {
          console.log(res);
        })
        .catch(err => {
          console.log(err);
        });
    }
```

@LinusBorg
