### ISSUE TITLE
Unable to render data？

### ISSUE THREAD

**Issue by xieyezi** [vuejs/composition-api#118]
this is my `setup()`:
```js
  setup() {
    const dataList = reactive([]);
    function getList() {
      axios.get("https://www.mxnzp.com/api/music/recommend/list").then(res => {
          dataList.value = res.data.data;
          console.log(dataList.value);
        })
        .catch(err => {
          console.log(err);
        });
    }
    getList();

    return {
      dataList,
      getList
    };
  }
```
and this is my `template`:
```js
<template>
  <div>
    <div v-for="(item, index) in dataList.value" :key="index">
      <p> {{item.title}}</p>
      <img :src="item.pic_big"/>
    </div>
  </div>
</template>
```
but my data unable render in `template`?

**Comment by xieyezi** [comment]
`console log(dataList.value)`  already able to output values,but not render in `template`.

**Comment by pangao66** [comment]
you needn't  write .value in template part . you can see the docs https://vue-composition-api-rfc.netlify.com/#basic-example

**Comment by xieyezi** [comment]
like this:
```
<template>
  <div>
    <div v-for="(item, index) in dataList" :key="index">
      <p> {{item.title}}</p>
      <img :src="item.pic_big"/>
    </div>
    <div> {{test}} </div>
  </div>
</template>
```
but still can not render data in template.

@pangao66

**Comment by doncatnip** [comment]
You should use ref instead of reactive here. If using reactive, you'd need to set a property like so:

    const dataList = reactive({theList:[]})

So, ref is better suited.

**Comment by xieyezi** [comment]
@doncatnip  thank you,I got it. 
But I still don't know the difference between `ref` and `reactive`.
I know `reactive`  takes an object and returns a reactive proxy of the original. but `ref`,what does "ref" do? When should I use it?  And what is the difference between them?
Hope to receive your reply！

**Comment by doncatnip** [comment]
Basically, you can use reactive when working with objects:

    const user = reactive({name:'bob',surname:'ross',isOnline:false})

and ref for anything else:

    const userList = ref([])
    userList.value.push(user)

( Although, in this example userList.value.push would make bob ross reactive, even if it is a plain object. )

**Comment by xieyezi** [comment]
ok,I think I understand,thank you! @doncatnip
