### ISSUE TITLE
ctx.root.$emit() is not working

### ISSUE THREAD

**Issue by hareku** [vuejs/composition-api#119]
`ctx.emit()` is working, but `ctx.root.$emit()` is not working.
Is this correct behavior?

**Comment by LinusBorg** [comment]
Can You please provide a reproduction on codesandbox?

**Comment by LinusBorg** [comment]
Hi there!

I close this issue because of inactivity. If you want to follow up on this issue, please open a new one, and provide the necessary information (a working reproduction etc.) in that issue.
