### ISSUE TITLE
Bug in the cookbook of the Component

### ISSUE THREAD

**Issue by MrJmpl3** [vuejs/composition-api#122]
The composition-api example repeat in the tab of class-api.

Proof: 

https://imgur.com/a/j0sZ0Wb

**Comment by LinusBorg** [comment]
The website in your screenshot is not affiliated with this repository. You should find their GitHub and open an issue there

**Comment by MrJmpl3** [comment]
@LinusBorg well, it's embarrassing , i confused the repos when create the issue , please delete this issue.
