### ISSUE TITLE
TSX: components included in render() gives ComponentRenderProxy not a constructor function for JSX elements error

### ISSUE THREAD

**Issue by drewstewart** [vuejs/composition-api#123]
plugin: 0.3.0
babel-preset-vca-jsx: 0.1.0

```
const Child = createComponent({
  props: {
    msg: String,
  },
  setup(props) {
    return () =>
      <div>{props.msg}</div>
  },
})

const Parent = createComponent({
  setup(props) {
    return () =>
      <Child msg="Child"></Child>
  }
})
```

Error in VSCode: 
`
JSX element type 'ComponentRenderProxy<ExtractPropTypes<{ msg: StringConstructor; }, true>, { [x: string]: unknown; }, ExtractPropTypes<{ msg: StringConstructor; }, false>>' is not a constructor function for JSX elements.
  Type 'ComponentRenderProxy<ExtractPropTypes<{ msg: StringConstructor; }, true>, { [x: string]: unknown; }, ExtractPropTypes<{ msg: StringConstructor; }, false>>' is missing the following properties from type 'ElementClass': $el, $options, $children, $scopedSlots, and 18 more.ts(2605)
`

Sorry, don't know how to fix this typing error. Any ideas?

**Comment by liximomo** [comment]
https://github.com/vuejs/composition-api#tsx

**Comment by drewstewart** [comment]
@liximomo thank you very much!
