### ISSUE TITLE
How to listen to events in Typescript TSX?

### ISSUE THREAD

**Issue by dvic** [vuejs/composition-api#129]
I read in the Vue JSX documentation that you have to use `onEVENTNAME` in order to use event listeners (the Babel plugin translates that properly). However, the Typescript compiler complains that it does not know these kind of attributes (because they are not defined as props).

What is the recommended way of doing this? Define an optional prop with the same name and signature? Or not use events at all but instead a `Ref` to callback function returned from `setup()`? This is what I was trying to do but then in the `render()` I was not able to access the props etc (because I guess `this` is not linked to the setup return value).

Thanks!

**Comment by liximomo** [comment]
I would suggest defining an optional prop with the same name.

**Comment by dvic** [comment]
Yeah that's what I also had in mind, but I might replace events with function props. I'm aware in Vue events are more preferred but this approach gives me type-safety and I'm willing to give it a try 👍.

For other readers: note that this prop must not start with `on`, otherwise Babel plugin will catch it and process it as an event listener, e.g., 

```
  save: { type: (Function as unknown) as () => (_: SaveKind) => void, required: true },
```

instead of
```
  onSave: { type: (Function as unknown) as () => (_: SaveKind) => void, required: true },
```
