### ISSUE TITLE
Using Hooks in class based components

### ISSUE THREAD

**Issue by dreyZZ** [vuejs/composition-api#135]
Can I use newly created hooks such as this, in the old class based components?

![image](https://user-images.githubusercontent.com/26909815/65037928-72a04900-d957-11e9-8f50-1ef7fadd91d2.png)

When i try to put the x and y values in the template, it gives me error;

![image](https://user-images.githubusercontent.com/26909815/65038430-9d3ed180-d958-11e9-9a64-25c7330aebaa.png)

And, can setup() function work peacefully alongside data()?

**Comment by liximomo** [comment]
```
import { ref } from '@vue/composition-api'; // not "vue"!
```

**Comment by dreyZZ** [comment]
Still not working. Can setup() work alongside data()?

![image](https://user-images.githubusercontent.com/26909815/65119719-3b807500-d9f5-11e9-8369-fc5b395b1105.png)

**Comment by liximomo** [comment]
Do you read the README.md?

**Comment by dreyZZ** [comment]
Sorry, i forgot to do Vue.use(plugin) step.
