### ISSUE TITLE
Possible can i use composition api and vue-property-decorator typescript together?

### ISSUE THREAD

**Issue by cuongdevjs** [vuejs/composition-api#136]

**Comment by CuongStf** [comment]
I use setup function in 
`
export default class class_name extends Vue {
   setup() {}     
}`
but it's not working?

**Comment by PatrykWalach** [comment]
Not sure if It'll help or not, but you should start by registering the hook, 
```javascript
Component.registerHooks([
  'setup'
])
```

**Comment by CuongStf** [comment]
> Not sure if It'll help or not, but you should start by registering the hook,
> 
> ```js
> Component.registerHooks([
>   'setup'
> ])
> ```

where i can place it? main.js right?

**Comment by rndmerle** [comment]
Yes, in main.js I've:
```
import Component from 'vue-class-component'

Component.registerHooks(['setup', 'beforeRouteUpdate', 'beforeRouteEnter', 'beforeRouteLeave'])
```

**Comment by CuongStf** [comment]
thank for your help :)

**Comment by pikax** [comment]
Seems the issue is resolved, if not, please reopen or create a new issue.

---
Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by CharlieBrownCharacter** [comment]
I have done the following:

main.js
```
import Component from 'vue-class-component';
// On why we do this visit: https://github.com/vuejs/composition-api/issues/136
Component.registerHooks(['setup']);
```

Then on my component:
```
import { Component, Vue } from 'vue-property-decorator';

@Component
export default class MyComponent extends Vue {
   setup() {
       console.log('setup function executed');
   }
}
```

But the console log never shows. Any idea?

**Comment by BernhardSchlegel** [comment]
Hey @CharlieBrownCharacter since `setup` has no this available "Because the component instance is not yet created when setup is executed, there is no this inside a setup option." ([source: official doc](https://stackoverflow.com/questions/64983076/how-to-use-vue-class-component-with-composition-api-in-vue2-by-typescript)) I think it makes sense for it to reside in the `@Component` decorator and not in the actual `class` where you might be tempted to use an (undefined) `this` operator.

**Comment by fobdy** [comment]
Unfortunately, I have problems with type validation in that scenario using Vue 2 with `@vue/composition-api`
<img width="1068" alt="изображение" src="https://user-images.githubusercontent.com/1515734/107746420-dc787a00-6d26-11eb-9811-2ec7765a6e1d.png">

Any thoughts on that, guys?

**Comment by bogdan-kuternoga** [comment]
@pikax ,
Unfortunately in our project we have the same issue as @fobdy described.
So could you please reopen this ticket?

Thanks

**Comment by pikax** [comment]
That seems to be an issue using the `vue-property-decorator` which is not maintained or supported by us, if you can reproduce using the `defineComponent` provided by `@vue/composition-api` I can have a look on it.

**Comment by yoyo930021** [comment]
> Unfortunately, I have problems with type validation in that scenario using Vue 2 with `@vue/composition-api`
> <img alt="изображение" width="1068" src="https://user-images.githubusercontent.com/1515734/107746420-dc787a00-6d26-11eb-9811-2ec7765a6e1d.png">
> 
> Any thoughts on that, guys?

TypeScript can't support any method for let decorator effect type.
So you should consider other ways.
Maybe https://github.com/vuejs/vue-class-component/issues/465?
