### ISSUE TITLE
Best practices for reusable code?

### ISSUE THREAD

**Issue by farcasmihai91** [vuejs/composition-api#137]
I am having trouble with code organization. I want to have typescript files for different entities - something like the old mixins.
For example, the `UserEntity.ts` entity will contain CRUD operations for a user.
I am using the `vue-apollo` plugin, which makes the $apollo available on the `setupContext`.

I am having trouble exporting methods and other properties since I have to wrap everything inside the `createComponent` method.

```js
createComponent({
  setup(props, setupContext) {
    const apollo = setupContext.root.$apollo;

    const createUser = async (input: CreateUserInput) => {
      try {
        const result: FetchResult<CreateUserMutation> = await apollo.mutate({
          mutation: CREATE_USER,
          variables: input
        })
        if (!result || !result.data || !result.data.createUser || !result.data.createUser.user) {
          return notifyError(errorMessages.value.GENERIC_ERROR);
        }
        return result.data.createUser.user.userId;
      } catch (error) {
        return notifyError(errorMessages.value.GENERIC_ERROR);
      }
    }
  }
})
```

How do I reuse the `createUser` function in different components? Any recommendations for different code organization styles?
Thanks!

**Comment by tommy-dev** [comment]
in ./api.ts
```
const useApi = (props, { root }: SetupContext) => {
  const createUser = async () => {}

  return {
    createUser,
  }
}

```

in component.tsx

```
createComponent({
  setup(props, setupContext) {
    const {  createUser } = useApi(props, setupContext)
  }
})

```
