### ISSUE TITLE
How to assign to reactive object?

### ISSUE THREAD

**Issue by zzachattack2** [vuejs/composition-api#138]
Is there a way to assign a new value to a reactive object without losing reactivity? If we have an object we expect to be re-assigned, is nesting within a ref the only option?

**Comment by LinusBorg** [comment]
Making sure I understand the requirement - you arer asking how to do the following reactively:
```javascript
let reactiveObj = reactive({ /* ... */ })

// ...later:

reactiveObj = reactive({ /* ... a new reactive object ... */})
```
...and want it to be reactive?

Then yes, the wa to do that is to use a ref:

```javascript
const reactiveObj = ref({ /* ... */ })

// ...later:

reactiveObj.value = reactive({ /* ... a new reactive object ... */})
```

**Comment by zzachattack2** [comment]
Thank you! The idea is that I have some reference object that regularly needs reassigned with a different value. Something like "selectedItem". Wasn't sure if there was a better method. 

Anyways, is wrapping the new value in reactive really necessary?

Instead of:
`reactiveObj.value = reactive({ /* ... a new reactive object ... */})`

Isn't this sufficient:
`reactiveObj.value = { /* ... */}`

Or is there something I'm missing?

**Comment by LinusBorg** [comment]
Oh so you only want to reassign a property?  That has always worked like you expect it and will work like that here as well of course

**Comment by amav96** [comment]
@LinusBorg A question. Why shouldn't I use reactive({})?

**Comment by LinusBorg** [comment]
reassigning variables can't be reactive, we can only observe property assignments.

**Comment by amav96** [comment]
@LinusBorg Well, I ask you because I have an object = const credentials = reactive({}), and when I want to set credentials with Object.assign(credentials, newCredentials), it is not reactive. It is only reactive with ref, but I understand that ref is for primitive values.

**Comment by LinusBorg** [comment]
Refs are usually more useful with primitivd values bur can be used with anything.
