### ISSUE TITLE
Computed property does not react to dynamic property changes.

### ISSUE THREAD

**Issue by tracid** [vuejs/composition-api#140]
Is it possible to listen to dynamic property changes, like intended in the code below?
The computed property `changedProperties` in the example just fires once after creation, but not after changing any property of `item` via v-model ( like` <input v-model="item.text" type="text"/>` in the component `useThis` is used in).

```
export const useThis = ({oldItem, initValues}) => {

    const item = ref({})

    item.value = reactive(initValues)

    const changedProperties = computed(() => {

        let properties = []
        
        for (let property in item.value) {
            if (item.value.hasOwnProperty(property)) {
                if (oldItem.hasOwnProperty(property)) {
                    if (!isEqual(item.value[property], oldItem[property])) {
                        properties.push(property)
                    }
                } else {
                    properties.push(property)
                }
            }
        }

        return properties
    })

    /* ... */
}
```

The analog code works just fine In a normal vue instance.
Thanks!

**Comment by LinusBorg** [comment]
is the `text` property part of `initValues`? if so, the code is fine and should work. Similar code works fine for me.

Can you share a complete, runnable example?

**Comment by tracid** [comment]
Its really strange, in the sandbox, it works fine!

https://codesandbox.io/embed/vue-template-t60bj

Thanks!
