### ISSUE TITLE
 build tsx  to web components

### ISSUE THREAD

**Issue by git-net** [vuejs/composition-api#141]
I use 
`vue-cli-service build --target wc --name wc-el "src/components/*.tsx "`
create web component 
when src/components **only single tsx file** , it works .
entry-wc.js   like this
`import wcEl from '~root/src/components/HelloWorld.tsx?shadow'`
`window.customElements.define('wc-el', wrap(Vue, wcEl))`

but if src/components has two tsx file or more , i got
`Failed to compile with 1 errors  ` 
`Module parse failed: Unexpected token (10:17)`
and entry-wc.js 
`import HelloWorld.tsx from '~root/src/components/HelloWorld.tsx?shadow'`
//line 10, why has **.tsx** here?
`window.customElements.define('wc-el-hello-world.tsx', wrap(Vue, HelloWorld.tsx))
`
`import test.tsx from '~root/src/components/test.tsx?shadow'`
`window.customElements.define('wc-el-test.tsx', wrap(Vue, test.tsx))`

**Comment by LinusBorg** [comment]
This seems unrelated to this repository, it seems to be about vue-cli

If you plan on opening a new issue there, make sure to provide a runnable reproduction or your issue will likely be closed again by the vuebot.
