### ISSUE TITLE
How to declare model option in createComponent?

### ISSUE THREAD

**Issue by AlllenShen** [vuejs/composition-api#142]
I just found that there is no model option in the interface of ComponentOptions. So how to handle v-model with createComponent?

**Comment by timshannon** [comment]
What error are you seeing?  I can declare it fine:
```typescript
export default createComponent({
  components: {
   ...
  },
  model: {
    prop: "open",
    event: "change",
  },
  props: {
    open: { type: Boolean, default: false },
  },
  setup(props, context) {
   ...
    return {
        ...
    };
  },
});
```

```

**Comment by AlllenShen** [comment]
Oh thank you! I just read the RFC document of composition API and it doesn't mention the model option. I'll try it in my project soon.
