### ISSUE TITLE
请问这种情况只能通过 as any 来解决了吗？

### ISSUE THREAD

**Issue by Richard-Choooou** [vuejs/composition-api#153]
![image](https://user-images.githubusercontent.com/23492006/66285031-662b6280-e8fd-11e9-94f9-01c5d701e9f2.png)

@liximomo 求教。

**Comment by SilentDepth** [comment]
Element UI 类型声明居然没有暴露 Popup 的 open 方法。也许你手动 augment 一下可解？

**Comment by beeplin** [comment]
这应该是ElementUI typing的缺陷，去那边提issue呗？

**Comment by Richard-Choooou** [comment]
> 这应该是ElementUI typing的缺陷，去那边提issue呗？

自己定义的一个组件，内部 暴露了一个 open 函数，和 element ui 没关系。

**Comment by pangao66** [comment]
https://github.com/vuejs/composition-api/issues/88    跟这个问题一样, 其实并没有解决

**Comment by liximomo** [comment]
请参考https://github.com/vuejs/composition-api/issues/88#issuecomment-527009626
