### ISSUE TITLE
Ref unwrap not working in TSX/JSX

### ISSUE THREAD

**Issue by jcdickinson** [vuejs/composition-api#155]
Demo: https://github.com/jcdickinson/vue-composition-api-tsx-example/commit/c5c8ddb7a53cf9d484a8fe66ff44e23532f4a206

When composition-api is used with TSX or JSX, automatic ref unwrapping does not work. Unwrapping the ref manually works in all cases (but does not seem like the intended design).

# Unwrapping in Attributes/Binding Attributes

```jsx
const value1 = ref(null);
return () => (<input vModel={value1}></input>);
```

Results in `[Object object]` and the binding is unusable.

# Unwrapping in a Text Node

```jsx
const value1 = ref(null);
return () => (<span>{value1}</span>);
```

Results in an error: `TypeError: can't define property "isRootInsert": Object is not extensible` (`createElm()` in vue.runtime.esm.js).

**Comment by liximomo** [comment]
![image](https://user-images.githubusercontent.com/9816225/66647756-593fa380-ec5c-11e9-9ddd-342ec3009442.png)

Unwrapping only works in template.
