### ISSUE TITLE
Type infer error if interface has "value" property

### ISSUE THREAD

**Issue by 404157386** [vuejs/composition-api#157]
define an interface A:
```javasciprt
interface A {
	id:string
	...
	value:string
}
```
if using with **toRefs**
```javascript
toRefs(reactive({a:<A[]>[]}))
```
as an export use function:
```javascript
function useValue(){
	return toRefs(reactive({a:<A[]>[]}))
}
const { a } = useValue()
```

here, type infer is error, **a is to be Ref<string[]>, not be Ref<A[]>**
if A has no property value, it works ok.

**Comment by vintprox** [comment]
Yep, changed `value` to something else, and error's gone. What is this magic xD

**Comment by pikax** [comment]
This will be fixed by https://github.com/vuejs/composition-api/pull/311

![image](https://user-images.githubusercontent.com/4620458/79685727-d31b9f80-8232-11ea-9a7a-d0ff198b60e3.png)
