### ISSUE TITLE
SSR - how to call async function server side (onServerPrefetch)

### ISSUE THREAD

**Issue by rebeccarich** [vuejs/composition-api#158]
Hi there,

We have a server side rendered `Vue (v2.6.10)` app using the `composition-api plugin (v0.3.1)`. We are trying to make a server side async call from within the component's `setup` function.

I have made the change from this PR locally https://github.com/vuejs/composition-api/pull/80 and the `onServerPrefetch` hook is being called and I can see async function being called server side, but I'm not sure how to assign the result of the call to a reactive property to be used in the template.

**Question 1:** Are there any plans to merge https://github.com/vuejs/composition-api/pull/80?
**Question 2:** If this change is merged, what is the correct way to assign the result of a server side async call to a reactive property?

Related to: https://github.com/vuejs/composition-api/issues/36

**Sample code:**

```
import { createComponent, reactive, watch, onServerPrefetch } from '@vue/composition-api'
import gql from 'graphql-tag'

async function useCourses(client) {
  return client
    .query({
      query: gql`
        query getCourses {
          courses {
            id
            title
            author
            description
            topic
            url
          }
        }
      `
    })
    .then(res => res.data.courses)
}

const Courses = createComponent({
  name: 'Courses',
  components: {
    'c-course': () => import('./Course.vue')
  },

  setup(initialProps, context) {
    const { defaultClient: apolloClient } = context.root.$apolloProvider

    const state = reactive({
      courses: []
    })

    onServerPrefetch(async () => {
      // Working: the gql call is being made
      const result = await useCourses(apolloClient)
      // console.log(result)
      // Not working: Can't assign the result to state.courses
      watch(async () => {
        state.courses = result
      })
    })

    // Working: client side call and assignment
    watch(async () => {
      state.courses = await useCourses(apolloClient)
    })

    return { state }
  }
})
export default Courses
```

**Comment by posva** [comment]
I think you can have the discussion on the PR #80 or the issue #36 
I added a comment on the PR
