### ISSUE TITLE
Suggestion : Add the method "valueOf", "toString", "Symbol.toPrimitive" to the "ref" type

### ISSUE THREAD

**Issue by masx200** [vuejs/composition-api#164]
Suggestion : Add the method "valueOf", "toString", "Symbol.toPrimitive" to the "ref" type
For implicit type conversion to work properly.
```js
const num=ref(8)
const xxx=ref(4)
const yyy=ref("hello")

num+xxx
//expected  : 12
//[object Object][object Object]
//
num*xxx
//expected  : 32
//NaN
yyy+xxx
//expected  : "8hello"
//[object Object][object Object]
```

**Comment by LinusBorg** [comment]
This is not part of the spec.

If you want to propose this as an improvement of the underlying proposal, please do so in the RFC #42
