### ISSUE TITLE
TypeError: Cannot create property 'value' on boolean 'false'

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/composition-api#165]
I'm getting this error:
> TypeError: Cannot create property 'value' on boolean 'false'

When I'm trying this in my setup:
```js
  props: {
    done: { type: Boolean },
  },
  setup (props, { emit }) {
    const rDone = ref(props.done)
    watch(() => props.done, newVal => { rDone.value = newVal })
    const cDone = computed({
      get: () => rDone.value,
      set: val => { rDone.value = val; emit('update:done', val) }
    })
    const cCheckbox = computed(() => cDone.value ? '[✔]' : '[　]')

    // this works:
    cDone.value = !cDone.value

    // but if I try this in the template I get:
    // > TypeError: Cannot create property 'value' on boolean 'false'

    return {
      cDone,
      cCheckbox,
    }
  }
```

My template:
```html
<div
  @click="cDone.value = !cDone.value"
>{{ cCheckbox }}</div>
```

**Comment by mesqueeb** [comment]
Apparently the reason is because when a "ref" is used in a template it's automatically resolved to the `value` inside the ref...

I'm not sure why...? If anyone can link me up to documentation explaining this, and **how we can best modify ref() values directly from the template**, that would be awesome!

**Comment by posva** [comment]
Yes, that's the reason. More on the documentation and the RFC: https://vue-composition-api-rfc.netlify.com

**Comment by leonheess** [comment]
I don't understand. Should I be using `.value` or not to read and write?
