### ISSUE TITLE
createComponent should also accept `SetupFunction` as param

### ISSUE THREAD

**Issue by Amorites** [vuejs/composition-api#166]
according docs: https://vue-composition-api-rfc.netlify.com/api.html#createcomponent

the code should work

```typescript
import { createComponent } from 'vue'

// provide props typing via argument annotation.
export default createComponent((props: { foo: string }) => {
  props.foo
})
```

**Comment by Amorites** [comment]
And it has been implemented in vue-next. Should this project catch up with vue-next?

**Comment by rijkvanzanten** [comment]
Would you accept a pull request for this @liximomo?

**Comment by antfu** [comment]
Supported by v0.6.0. Closing now.
