### ISSUE TITLE
document on the migration from function-api?

### ISSUE THREAD

**Issue by swuecho** [vuejs/composition-api#170]
find the original repo is in achive mode, but did not find any doc on how to upgrade

**Comment by swuecho** [comment]
"export 'value' was not found in '@vue/composition-api'

"export 'value' was not found in 'vue'

**Comment by LinusBorg** [comment]
You can read the updated RFC and learn that there's no more `value`, we now have `ref`.

**Comment by swuecho** [comment]
Yes. but some doc alway helps. General user should not have to read the RFC to use a feature. I know there are docs, but can be overwhelming.

**Comment by antfu** [comment]
Closing this for now. Same reason as #176. Thanks for understanding.
