### ISSUE TITLE
can not use Symbol to judge Reflect exists or not

### ISSUE THREAD

**Issue by Qymh** [vuejs/composition-api#175]
there will be something wrong in ios9
because ios9 supports `Symbol` but doesn't support `Reflect`
there is [Symbol Compatibility](https://caniuse.com/#feat=mdn-javascript_builtins_symbol)
there is [Reflect Compatibility](https://caniuse.com/#feat=mdn-javascript_builtins_reflect)

So the following codes `var keys = hasSymbol ? Reflect.ownKeys(from) : Object.keys(from);` may not work well

``` javascript
function mergeData(to, from) {
    if (!from) return to;
    var key;
    var toVal;
    var fromVal;
    var keys = hasSymbol ? Reflect.ownKeys(from) : Object.keys(from);

    for (var i = 0; i < keys.length; i++) {
      key = keys[i]; // in case the object is already observed...

      if (key === '__ob__') continue;
      toVal = to[key];
      fromVal = from[key];

      if (!hasOwn(to, key)) {
        to[key] = fromVal;
      } else if (toVal !== fromVal && isPlainObject(toVal) && !isRef(toVal) && isPlainObject(fromVal) && !isRef(toVal)) {
        mergeData(toVal, fromVal);
      }
    }

    return to;
  }
```

**Comment by rndmerle** [comment]
Hello.
It has been fixed here https://github.com/vuejs/composition-api/commit/e1b9757d0695643ca940518ada986862c651efba
but a new version hasn't been released
