### ISSUE TITLE
Will Vue 3/Composition API support TypeScript types in props?

### ISSUE THREAD

**Issue by aaf-ww** [vuejs/composition-api#180]
I haven't been able to find anything online about props supporting TypeScript types in the next version of Vue.

Is this something that is being considered or will it come naturally as a result of moving the code base to TypeScript?

It would be nice to use TypeScript typing in the props of a component like so:

```ts
export default createComponent({
  props: {
    prop1: CustomType[],
    prop2: OtherType
  }
})
```

**Comment by LinusBorg** [comment]
That's not possible.

We can't replace these Typescript types with someJavascript during compilation, that's not how TS works. Types are simply removed from the code, so the result would be:

```javascript
export default createComponent({
  props: {
    prop1: ,
    prop2: 
  }
})
```

..which is invalid Javascript syntax, which is why it's also invalid in Typescript.

**Comment by aaf-ww** [comment]
Appreciate the answer, thank you.

**Comment by xmsz** [comment]
Is there solution to resolve jsx props types?
