### ISSUE TITLE
The child component did not get props values for its parent

### ISSUE THREAD

**Issue by SGAMERyu** [vuejs/composition-api#183]
Hello, I have a problem that when I gave props interface type pairs in the setup function, I passed props to the parent component and the children did not get the corresponding props values
![20191106193000](https://user-images.githubusercontent.com/17926105/68294752-df200480-00cb-11ea-80b1-ecff17212690.jpg)
![20191106193011](https://user-images.githubusercontent.com/17926105/68294760-e2b38b80-00cb-11ea-9deb-55aed7e8c14e.jpg)
Why aren't you getting props

**Comment by antfu** [comment]
@SGAMERyu Can you share a reproducible repo? It's hard to see from your two screenshots. Thanks

**Comment by antfu** [comment]
Closing for now. Feel free to reopen if you still find the issue.
