### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by sydney-d** [vuejs/composition-api#190]
Hello,

Is this library compatible with the same browsers as vue 2.x ? 
Or does it use some recent javascript features to improve reactivity ? (proxies or wathever ?)

Thanks

**Comment by LinusBorg** [comment]
it does use Vue 2's reactivity so it'S compatible with the same browsers

**Comment by sydney-d** [comment]
Ok, thanks for the clarification

So I guess these issues still apply : 
https://vuejs.org/v2/guide/reactivity.html#Change-Detection-Caveats

**Comment by LinusBorg** [comment]
Yes they do.
