### ISSUE TITLE
$on not working correctly, throws "Error in data(): "TypeError: Cannot read property '_events' of undefined""

### ISSUE THREAD

**Issue by milky2028** [vuejs/composition-api#196]
$on is not working correctly with the composition api. I've made a minimal reproduction repo [that's available here](https://github.com/milky2028/vue3-minimal-repro).

```typescript
<script lang="ts">
import Vue from 'vue';
import { createComponent } from '@vue/composition-api';

export default createComponent({
  name: 'HelloWorld',
  props: {
    msg: String,
  },
  setup(_, { emit, root: { $on } }) {
    setTimeout(() => {
      emit('thing');
    }, 3000);
    
    $on('thing', () => console.log('Event hit'))
  }
});
</script>
```

Destructuring from root in this way breaks $on and causes the error, ""Error in data(): "TypeError: Cannot read property '_events' of undefined"" to throw.

If you just use root and call root.$on, the event never fires.

**Comment by posva** [comment]
Don't restructure the `context`, it loses the value of `this` when calling functions
