### ISSUE TITLE
Use returned props from setup in old 2.0 options

### ISSUE THREAD

**Issue by mesqueeb** [vuejs/composition-api#207]
I am trying to incrementally introduce the composition-api to extract some parts of the logic of big components.

I read: [Usage Alongside Existing API](https://vue-composition-api-rfc.netlify.com/#usage-alongside-existing-api)

> Properties returned from `setup()` will be exposed on this and will be accessible inside 2.x options.

However, this seems to not work yet...? I wasn't successful. (see my snippet down below)

### Is this possible with this plugin? Or do we have to wait until 3.0 until we can do this.

```js
export default {
  props: ['x'],
  setup (props) {
    const y = props.x + 1
    return { y }
  }
  data () {
    console.log(this.y) // undefined
    console.log(this.$options.y) // undefined
  }
}
```

**Comment by antfu** [comment]
You don't have access to `this` in `data`

You can access the returning object of `setup` as you would normally do in Vue 2.

```ts
export default defineComponent({
  props: ['x'], // 1
  setup (props) {
    const y = props.x + 1
    return { y }
  },
  mounted() {
    console.log(this.y) // 2
  }
})
```
