### ISSUE TITLE
Function PropType

### ISSUE THREAD

**Issue by rndmerle** [vuejs/composition-api#208]
Hello.

This [Vue issue](https://github.com/vuejs/vue/issues/9692) and this [commit](https://github.com/vuejs/vue/commit/df4af4bd1906b9f23b62816142fdfbd6336d3d2f) refer to allowing:
```
props: {
  fn: Function as PropType<() => any>
}
```
Would it be possible to replicate this change on componentProps.d.ts's PropConstructor type please?

Thanks for your work :)

**Comment by genie-youn** [comment]
Hi @posva 😄 
I made a PR and be so happy if you could check it.

Thanks you.
