### ISSUE TITLE
Sync modifier updates the parent component with error

### ISSUE THREAD

**Issue by vallemar** [vuejs/composition-api#209]
When you use a .sync modifier to receive the update event of a child component on a constant or reactive variable in the parent, the value in vue devtools appears the new and updated value but if you access the object from a setup method of the parent component it always has the value with which you initialized the reactive object.

However, as in the vue devtools, I am passing this reactive object to another child component as a property and this if it correctly receives the update of the object in the watch method that I have implemented.

![image](https://user-images.githubusercontent.com/15719383/71312815-f0c92b80-242f-11ea-8680-759d5738767e.png)

**Comment by posva** [comment]
do you have a boiled down repro on a code sandbox?

**Comment by vallemar** [comment]
Here is an example:
[this](https://codesandbox.io/embed/vue-composition-api-example-xjxiq?fontsize=14&hidenavigation=1&theme=dark)

1st Click repeatedly on (Button child1 increment).
2nd Click (check parent alert).

You can see how in all the components the value has increased less in the value of the parent component.

**Comment by posva** [comment]
The problem comes from using `reactive` and trying to **replace the whole** variable, that leaves the reactive object used in `setup` unused. Use a `ref` if you need to modify the object the variable contains instead of properties:

```js
setup(props, context) {
    const valueOtherComponent = ref({ checkValue: 0 });
    const check = {
      checkValueParentAlert: () => {
        console.log(valueOtherComponent.value);
      }
    };
    return {
      valueOtherComponent,
      check
    };
```

**Comment by vallemar** [comment]
ok, I took this point into account but when I saw the replacement in vue devtools and in the second child it confused me.

If this is going to be like that, wouldn't it make sense that the change is not made anywhere? The behavior is confusing

Thank you.
