### ISSUE TITLE
Throw "template or render function not defined" when returning render function from setup()

### ISSUE THREAD

**Issue by AlllenShen** [vuejs/composition-api#210]
my component
```
export default createComponent({
    components: { Input },
    props: {
        model: Object,
        config: Object,
        context: Object,
    },
    setup: (props, ctx) => {
        return h(Input, {
            props: {
                model: props.model[props.config.key],
                ...props.config,
            },
            on: {
                input: v => ctx.emit('change', v),
            },
        })
    },
})
```
and this exported component will be used in another render function.

Some errors occur when mounted.

```
[Vue warn]: Error in data(): "TypeError: Cannot convert undefined or null to object"

[Vue warn]: Failed to mount component: template or render function not defined.

```
I try to use render() other than setup(), but it cannot read the context param.

I think Vue does not recognize composition api correctly cause in options api, only functional components can receive context.

So how can i make Vue use composition api correctly?

**Comment by jacekkarczmarczyk** [comment]
https://vue-composition-api-rfc.netlify.com/api.html#setup
```js
return () => h('div', [
      count.value,
      object.foo
    ])
```

**Comment by AlllenShen** [comment]
thank you very much. I forgot this point.

**Comment by hisuwh** [comment]
@jacekkarczmarczyk this link appears to be out of date.  What was the take away here?
