### ISSUE TITLE
Not working in browser

### ISSUE THREAD

**Issue by antfu** [vuejs/composition-api#214]
Reproduce: https://codepen.io/antfu/pen/WNbOGZQ

![image](https://user-images.githubusercontent.com/11247099/71455983-4efc6280-27d2-11ea-9f81-f97e4b2f349d.png)

`vueCompositionApi` seems not exposing.

**Comment by jacekkarczmarczyk** [comment]
https://codepen.io/jkarczm/pen/RwNgMQj?editors=1010

**Comment by antfu** [comment]
OK. With the vueCompositionApi.default the problem solves. Thanks!
