### ISSUE TITLE
vue-router do not support export object using createComponent at tsx

### ISSUE THREAD

**Issue by Phinome** [vuejs/composition-api#220]
## Question:

An Example [Repository](https://github.com/liximomo/vue-composition-api-tsx-example) with TS and TSX support is provided to help you start, that it do not render component with vue-router.

[demo code](https://codesandbox.io/s/vue-composition-api-tsx-example-97tuz)

main files:

`Home.tsx`:

```typescript
import { createComponent } from '@vue/composition-api';

import HelloWorld from '@/components/HelloWorld';

export default createComponent({
  name: 'home',
  setup() {
    return () => {
      <div class="home">
        <img alt="Vue logo" src="../assets/logo.png" />
        <HelloWorld msg="Welcome to Your Vue.js App" />
      </div>;
    };
  },
});
```

`routes.ts`:

```typescript
import Vue from 'vue';
import VueRouter from 'vue-router';
import Home from '@/views/Home';

Vue.use(VueRouter);

const routes = [
  {
    path: '/',
    name: 'home',
    component: Home,
  },
];

const router = new VueRouter({
  mode: 'history',
  base: process.env.BASE_URL,
  routes,
});

export default router;
```

## What is expected?

render home component or how to support it 

## What is actually happening?

it not render

**Comment by daggerok** [comment]
@Phinome 
so you closed it, what solution for TSX component RouteConfig?
