### ISSUE TITLE
Destructuring assignment not working on props

### ISSUE THREAD

**Issue by AlllenShen** [vuejs/composition-api#221]
I destructured a base prop object like this
```
export const baseProp = {
    formKey: { type: String, default: 'default' },
    disabled: Boolean,
    hint: { type: String, default: '' },
}

export default createComponent({
    props: {
        ...baseProp,
    },
})
```
but Vue reminds
```
Property or method  is not defined on the instance but referenced during render. 
```

**Comment by jacekkarczmarczyk** [comment]
It seems that you forgot to add some code, as the one you've provided doesn't show the warning
https://codepen.io/jkarczm/pen/mdyqRoR?editors=0010

https://stackoverflow.com/help/minimal-reproducible-example

**Comment by AlllenShen** [comment]
I tried this code in a mini demo and it works. I'll figure out why it shows warning later.

**Comment by posva** [comment]
Open a new issue with a repro if you manage to reproduce it :)
