### ISSUE TITLE
Not understanding how to have a ref to an Array in Typescript

### ISSUE THREAD

**Issue by delaneyj** [vuejs/composition-api#223]
```
interface Info {
  id: string
  from: string
  time: number
  view: ViewSettings
}
const arr = ref<Array<Info>>([])
```
When trying to using it ala `arr.map(...` I get a ` arr.value.map is not a function`.  Is there something about the generics from Typescript that is causing a problem?

**Comment by lmiller1990** [comment]
This works fine for me:

<img width="489" alt="image" src="https://user-images.githubusercontent.com/19196536/71898422-fd29e400-31a4-11ea-8c27-d8b657dfcb2e.png">

What version of TS are you on?

**Comment by LinusBorg** [comment]
@lmiller1990 He forgot `.value`:

> When trying to using it ala **arr.map(...** I get a arr.value.map is not a function

*(emphasis mine)*

**Comment by LinusBorg** [comment]
Works well here too ...

**Comment by delaneyj** [comment]
Sorry everyone, got into a state where a bad json parse had corrupted localstorage.  When parsed it 100% wasn't a valid state and was the root cause.  Sorry to waste your time.
