### ISSUE TITLE
Vuex + composition API + vapper.js

### ISSUE THREAD

**Issue by mikimoresi** [vuejs/composition-api#225]
Hello,
I'm writing again, I cannot find a good solution, it could be me doing something wrong but i really tried anything so I made up a super simple example repository to reproduce my problem, it could be used for your examples once fixed and I'm sure it will be helpful to someone else.

Here is my repo:
[https://github.com/mikimoresi/vapcompvuex](url)

There is a store with a simple "blink" property changing value any 1 second.
There are then two components: **blinker** and **blinkerstandard**, the first made with composition API and the secondo made with standard API.

What happens is that while the standard reacts correctly to ste store changes the composition components stay always the same, no errors, no changes, no anything, for him the store exists but never change.

I hope you can help me and that a solution exists.
I'm sorry if it's me doing something wrong but I really tried my best to reach a solution, I'm sure this issue could be helpful to someone else.

Thank you

**Comment by lmiller1990** [comment]
I am not familiar with getCurrentInstance but it looks like that caused the bug. I got this working with the following changes:

main.js
```js
import Vue from 'vue';


import createRouter from './createRouter';
import App from './App.vue';
import { store } from './store';
import VueCompositionApi from "@vue/composition-api";

Vue.use(VueCompositionApi);


Vue.config.productionTip = false;






// Export factory function
export default function createApp ({ type, req}) {
	  // 1. Create a router instance
	//console.log(req.headers.host);
	if(type == "server") {

		global.window = {};
		global.document = false;
		

	} 
	window.Vue = Vue;
	
	const router = createRouter();

  	// 2. Create a app instance
  	const app = new Vue({
		router,
		store,
		head: {},
		data: {},
		render: h => h(App),
		
		methods: {
			
		}
		
  	});

  	// 3. return
  	return { app, router, store }
}


```

Blinker.vue

```vue
<template>
	<div>
		<h2>blinker component made with composition API</h2>
		<h1 v-if="blink">BLINK :)</h1>
		<h1 v-else>WAITING BLINK :(</h1>
	</div>
	
</template>

<script>

	import Vue from 'vue';
	import VueCompositionApi from "@vue/composition-api";

	Vue.use(VueCompositionApi);
	import { useStore } from '@/store';
	
	import { computed } from '@vue/composition-api';
	

	export default {
		name: 'blinker',
		setup(props,{root}) {
			
console.log()
			var store =  useStore().state;
			
			
console.log(store.blink)
			// const blink = computed(() => root.$store.state.blink);
			const blink = computed(() => root.$store.state.blink);
			

			return {
				blink
				
			}

		}
	}

  	
</script>

<!-- Add "scoped" attribute to limit CSS to this component only -->
<style scoped>
	h2 {
		color: grey;
		border-top:1px solid black;
	}

</style>

```

store.js

```
import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

function createStore(req) {
	return new Vuex.Store({
		
		state: {
			blink: false,
		},

		mutations: {
			SET_BLINK: function(state,bool) {
				state.blink = bool;		
			},
		},

		actions: {
			fetchInitialState: async function(context,data) {
				var _this = this;
				setInterval( function() {
					context.commit('SET_BLINK',!context.state.blink);
				},1000);
			},
		},
	});
}

export const store = createStore()
export const useStore = () => store


```

**Comment by mikimoresi** [comment]
Lachlan thank you so much, 
now anything is finally working, was obviously my lack of deep experience with node mechanisms. You helped me also understand these better.
I fixed my repo in case someone else needs to mix these APIs.

Thank you again, priceless.

**Comment by lmiller1990** [comment]
no problem... close this issue if you are happy with the solution!
