### ISSUE TITLE
setup() return error on null values

### ISSUE THREAD

**Issue by ronssij** [vuejs/composition-api#231]
Am I missing something or does the Vue 3.x does not allow return on null value variables?

>
    setup () {
     let cookies = Cookies.get('apiUrl') ? Cookies.get('apiUrl') : null
     let state = reactive({
       apiUrl: ''
     })
     
     let test = null

     return {
       state,
       cookies,
       test
     }
    }

> vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in data(): "TypeError: Cannot convert undefined or null to object"

> TypeError: Cannot convert undefined or null to object

**Comment by jdmerinor** [comment]
I got the same issue, I'm pretty sure this has to simply be a mistake

**Comment by coolhome** [comment]
Just tested in vue 3.0 and returning null is not a problem! 

This next part has not been validated yet... Now with vue 2.0 I think I've traced the desired and that the `isReactive` is throwing the error

https://github.com/vuejs/composition-api/blob/3b7eadfbb3868fd2fc67b538ea8ded4af4905832/src/setup.ts#L197

https://github.com/vuejs/composition-api/blob/3b7eadfbb3868fd2fc67b538ea8ded4af4905832/src/reactivity/reactive.ts#L24

This `isReactive` is likely trying to convert the null to object.

https://github.com/vuejs/composition-api/blob/e1b9757d0695643ca940518ada986862c651efba/src/utils.ts#L37-L40

![image](https://user-images.githubusercontent.com/700740/73502604-8c3aae00-4397-11ea-8fea-c86827542981.png)

**Comment by clementmas** [comment]
I had the same problem and the error "TypeError: Cannot convert undefined or null to object" was not very helpful.
Thanks for the PR @coolhome. Hope it gets merged soon.

**Comment by antfu** [comment]
Fixed in v0.6.1
