### ISSUE TITLE
Composition API outside of Vue?

### ISSUE THREAD

**Issue by delaneyj** [vuejs/composition-api#234]
I've been using this library as the core of some reactive apps.  The interesting thing is except for a few templates it has almost not to do with Vue.  Heavily relying on `ref` and `computed` and was wondering what would it take to get it them to update outside of a Vue context.  Or would it be better to just have own es6 proxies handlers that mimic `ref` and `computed`?

**Comment by jacekkarczmarczyk** [comment]
You can try using reactivity API from vue3

**Comment by posva** [comment]
This library depends on Vue to work, but as @jacekkarczmarczyk pointed out, try out the @vue/reactivity package (from vue 3)
