### ISSUE TITLE
Typing Object props

### ISSUE THREAD

**Issue by rijkvanzanten** [vuejs/composition-api#235]
As per https://github.com/vuejs/vue/issues/9692#issue-420446580, I expected to be able to type Object props using TypeScript as follows:

```vue
<script lang="ts">
import { PropType } from 'vue';
import { createComponent } from '@vue/composition-api';

interface Options {
	labelOn: string;
	labelOff: string;
}

export default createComponent({
	props: {
		options: {
			type: Object as PropType<Options>,
			default: false
		}
	},
	setup(props) {
		props.options;
	}
});
</script>
```

However, as soon as I add `as PropType<Options>` to the mix, I get an error in Vetur and Vue CLI serve:

```
No overload matches this call.
  Overload 1 of 2, '(options: ComponentOptionsWithoutProps<never, unknown>): VueProxy<never, unknown>', gave the following error.
    Type '{ value: { type: BooleanConstructor; default: null; }; readonly: { type: BooleanConstructor; default: boolean; }; options: { type: PropType<Options>; default: boolean; }; }' is not assignable to type 'undefined'.
```

I saw that https://github.com/vuejs/composition-api/issues/208 mentioned adding support for the above for function calls, but I'm wondering if the "original" functionality exists in the Composition API to begin with.

![image](https://user-images.githubusercontent.com/9141017/72761758-ffc80880-3baa-11ea-9b86-39fbd282cf22.png)

![image](https://user-images.githubusercontent.com/9141017/72761766-09517080-3bab-11ea-8361-a54ee974a6b9.png)

![image](https://user-images.githubusercontent.com/9141017/72761771-0e162480-3bab-11ea-920e-e46206b1b0b8.png)

Is what I'm trying to do supported, or am I using it wrong? If that's the case, how can one type Object type props properly in TypeScript? Thanks for all your great work 🙂

**Comment by rijkvanzanten** [comment]
The function workaround mentioned in https://github.com/vuejs/vue/pull/6856#issuecomment-417183243 luckily does work in this instance, eg:

```vue
<script lang="ts">
import { PropType } from 'vue';
import { createComponent } from '@vue/composition-api';

type Options = {
	labelOff: string;
	labelOn: string;
};

export default createComponent({
	props: {
		options: {
			type: Object as () => Options,
			required: true
		}
	},
	setup(props) {
		props.options;
	}
});
</script>
```

**Comment by LinusBorg** [comment]
This package exports its own `PropType` type which you should use when using this plugin
