### ISSUE TITLE
Any attempt to use "readonly" gives "TypeError: Object(...) is not a function"

### ISSUE THREAD

**Issue by jonjanisch** [vuejs/composition-api#238]
I tried using readonly for the first time and kept getting:

`TypeError: Object(...) is not a function`

I modified the App.vue with the example taken directly from the [documentation](https://vue-composition-api-rfc.netlify.com/api.html#readonly) and the problem persists:

```
import {reactive, watch, readonly} from '@vue/composition-api';
export default {
  name: 'app',
  setup() {
    const original = reactive({ count: 0 })
    const copy = readonly(original)

    watch(() => {
      console.log(copy.count)
    })

    return {
      original,
      copy,
    }
  }
}
```

IntelliJ marks the import { readonly } as a warning. Should it be imported some other way?

Using composition API version 0.3.4

**Comment by sisou** [comment]
I believe `readonly` is not actually available in the plugin for Vue 2. It will be available in Vue 3, which the RFC and the documentation is ultimately for.

**Comment by oswaldofreitas** [comment]
if I knew `readonly` wasn't available in this plugin I wouldn't even try to use it as I want to make my store's state readonly and make it mutate only by store mutations. Please, add this information to https://github.com/vuejs/composition-api/blob/master/README.md#Limitations

**Comment by giona69** [comment]
@oswaldofreitas you can use `computed`in the meantime

**Comment by oswaldofreitas** [comment]
nice, thank you @giona69

**Comment by pikax** [comment]
`readonly` is not supported on `@vue/composition-api` because of the Vue reactivity system caveats.

you can have a "fake" `readonly` typed: 
```ts
// FAKE readonly
export function readonly<T extends object>(target: T): Readonly<Ref<T>> {
  return computed(() => target) as any;
}
```

**Comment by antfu** [comment]
Document updated. Thanks!
