### ISSUE TITLE
Error thrown when using Vue Composition API in component library

### ISSUE THREAD

**Issue by willtpwise** [vuejs/composition-api#239]
I've noticed an issue with the Vue Composition API when used inside of a third party library.

The Vue Composition API throws an error when a component library (using the composition api) attempts to use one of the API methods (e.g. `ref()`).

```[Vue warn]: Error in data(): "Error: [vue-composition-api] must call Vue.use(plugin) before using any function."```

The consumer of the package using the Vue Composition API has already called `Vue.use(CompositionAPI)`.

I've set up a reproduction of the issue below which should hopefully details the issue:
https://github.com/willtpwise/vue-comp-package

**Related to:**
* https://github.com/vuejs/composition-api/issues/61
* https://github.com/vuejs/composition-api/issues/181

**Comment by posva** [comment]
This is the same problem as with linked packages (https://github.com/vuejs/composition-api/issues/228). The lib is using a copy of the library and it doesn't work

**Comment by willtpwise** [comment]
Thanks Posva. #228 helped solve the problem 👍
