### ISSUE TITLE
Can't use refs inside child

### ISSUE THREAD

**Issue by gjuchault** [vuejs/composition-api#240]
Hello,

It seems that whenever we make a variable go through more than one `setup`, it looses all reactivity.

Here is a simple code example: https://codesandbox.io/s/confident-resonance-s8nv9

`value` is passed from App to Child, and is updated in the tree. Whenever the value goes through Child setup, it looses reactivity (ie. we get `updated value` instead of `updated updated`).

Thanks

**Comment by gjuchault** [comment]
After a bit more of investigation, it seems that destructuring `props` is the source of the bug

**Comment by posva** [comment]
props cannot be destructured or reactivity is lost because only the value is being passed instead of the variable

**Comment by gjuchault** [comment]
@posva I think it deserves to be in the docs :pray:

**Comment by posva** [comment]
Yes, it will be. For the moment a PR to make that clear at https://vue-composition-api-rfc.netlify.com/api.html#setup is welcome (https://github.com/vuejs/composition-api-rfc)
