### ISSUE TITLE
Error in getter for watcher, TypeError

### ISSUE THREAD

**Issue by darrenjennings** [vuejs/composition-api#242]
```js
// [Vue warn]: Error in getter for watcher 
// TypeError: Cannot read property 'id' of undefined 
try {
  watch(() => `/api/profile?id=` + data.value.id)
} catch {
  // do nothing
}
```

Is there a way to `try`/`catch` watcher errors? (background: would like to allow users of a custom hook to pass in access errors to build a type of dependency cascade for multiple hooks similar to https://github.com/zeit/swr#dependent-fetching). There's a way around it currently, but it involves users checking truthiness of ref values.

**Comment by pikax** [comment]
I don't think catching errors on the `watcher` function is possible on your example I recommend something like: 

```ts
function useSWR(cb: Function){
  const safeCb = ()=> {
    try{
      cb()
    }catch(e){
      //handle error
    }
  }

  // ... 
  watch(safeCb); //etc
}
```
