### ISSUE TITLE
What is the lifespan and scope of a provided/injected value using the composition API?

### ISSUE THREAD

**Issue by geekox86** [vuejs/composition-api#243]
Greetings,

By lifespan, I mean when will the provided value be garbage collected, if ever?
Is it tied to the lifespan of the component provider that called provide in first time?
Or also tied to the injecting components?

By scope, I mean where can I inject the provided value?
Anywhere in the app or only in the children components of the parent component provider?
Or also can be injected inside sibling and grandparent components?

Thank you.

**Comment by posva** [comment]
Provided values are accessible only to descendant and can be garbage collected once the component providing the variable is released itself
