### ISSUE TITLE
Is this plugin safe to be used in SSR?

### ISSUE THREAD

**Issue by isneezy** [vuejs/composition-api#245]
Hello, I'm having so much fun developing things with this plugin, i know it's an RFC but I got a flea behind my ear when I saw this part of the code:

https://github.com/vuejs/composition-api/blob/e1b9757d0695643ca940518ada986862c651efba/src/runtimeContext.ts#L1-L14

Is it safe to use this in SSR since the `currentVue` and `currentVM` are global variables?  
I saw someone talking about it here https://github.com/vuejs/composition-api/pull/80#issuecomment-545441907 but with no followup

**Comment by LinusBorg** [comment]
> I saw someone talking about it here #80 (comment) but with no followup

Was  [Akryum're reply](https://github.com/vuejs/composition-api/pull/80#issuecomment-560172578) not satisfactory?

> the global variables are used only during setup as it's processing the different components. So for a different request it will be overridden by each component one at a time.

**Comment by isneezy** [comment]
My bad I didn't saw that.
I know that this has noting to do with the plugin itself but just to confirm, this means setup method is never gets called in parallel even if there are two or more requests the same time? 🤔️

**Comment by LinusBorg** [comment]
Well, node (JavaScript) is single-threaded so nothing ever runs in parallel.

As the setup function is called synchronously, and these global variable aare set and unset immediately before & after setup is run, there can't be any race conditions where a reference from one request leaks into another

**Comment by isneezy** [comment]
@LinusBorg Thanks for your clear explanation.
I'm closing this issue.
