### ISSUE TITLE
Unwrap ref from function in template

### ISSUE THREAD

**Issue by utlime** [vuejs/composition-api#248]
I'm not sure is it issue or not, but it's really annoying behavior.
I have function(`fn`) which return ref, but this ref will not unwrapped in template:

![Screenshot from 2020-02-11 17-37-24](https://user-images.githubusercontent.com/9943271/74229551-3817be00-4cf5-11ea-82b0-aeb835d2b692.png)

I want to have similar result as for `fn2`
link to codepen:
https://codepen.io/utlime/pen/gOppBGj

**Comment by posva** [comment]
Doing an implicit conversion here could lead to unexpected behaviors and also being unable to pass the ref itself to another function.

The only properties that do not require the `.value` in template are the ones returned in the `setup` function

**Comment by utlime** [comment]
Hi @posva , what if we change toString method for ref?
raw example:
> Object.getPrototypeOf(vueCompositionApi.ref(null)).toString = function toString() {return this.value.toString()}

I updated codepen
https://codepen.io/utlime/pen/gOppBGj
