### ISSUE TITLE
Augmenting ComponentRenderProxy

### ISSUE THREAD

**Issue by IlyaSemenov** [vuejs/composition-api#249]
With options API, I used to inject "global" variables into the render context with:

```ts
Vue.mixin({
	computed: {
		$store: () => store,
	},
})

declare module 'vue/types/vue' {
	interface Vue {
		$store: Store
	}
}
```

and then refer to it with:

```vue
<template>
  <div>store = {{ $store }}</div>
</template>
```

How would I do the same with composition API? `node_modules/@vue/composition-api/dist/component/component.d.ts` seems to be exporting a non-augmentable type `ComponentRenderProxy` with hardcoded set of properties:

```ts
export declare type ComponentRenderProxy<P = {}, S = {}, PublicProps = P> = {
    $data: S;
    $props: PublicProps;
    $attrs: Data;
    $refs: Data;
    $slots: Data;
    $root: ComponentInstance | null;
    $parent: ComponentInstance | null;
    $emit: (event: string, ...args: unknown[]) => void;
} & P & S;
```

so the template fails to validate:

![image](https://user-images.githubusercontent.com/128121/74332446-4edb1500-4dc8-11ea-9c44-f85cf0e5cd61.png)

Any ideas?

Also (I'm sure I'm missing something!) why doesn't `ComponentRenderProxy` simply extend `Vue`?

**Comment by posva** [comment]
Use `provide`/`inject` for that by providing the store at the root of the application and injecting wherever needed. There is more info at https://github.com/vuejs/rfcs/pull/117
FYI the global mixin with a computed property is a security vulnerability when doing SSR (leads to sharing the store instance among different request).
The validation message comes from Vetur, the VScode plugin, you might want to get more info from them first to see if there is anything we can do to to help them with that validation message

**Comment by IlyaSemenov** [comment]
I knew I had to use something else rather than `$store` for the sample variable name... The problem is generic and not particularly related to Vuex and/or other store pattern. It could as well be `myFancyGlobalMethod` or a global filter like `| format_currency` or anything similar.

(Thank you for the heads up on the SSR. I am one of the maintainers of (now deprecated) https://ream.js.org/, arguably the second most popular Vue SSR framework at the time, so more or less understand how things work. The example in question is of course deliberately trimmed.)
