### ISSUE TITLE
Something wrong when I have 'value' in reactive object

### ISSUE THREAD

**Issue by xmsz** [vuejs/composition-api#250]
![image](https://user-images.githubusercontent.com/5879146/74410096-3b38b880-4e73-11ea-84d8-ee4303b18067.png)

**Comment by LinusBorg** [comment]
Screenshots like this are making it hard for us to understand what you mean.

And impossible t help you. 

Please provide actual code, and explain the problem

**Comment by jsmith** [comment]
Pretty sure this is just a duplicate of #157

**Comment by xmsz** [comment]
> Pretty sure this is just a duplicate of #157

Yes, Same issue

**Comment by LinusBorg** [comment]
Then I'll close as a duplicate.

I think a PR addressing #157 is already in the works
