### ISSUE TITLE
How to use it in nuxt project

### ISSUE THREAD

**Issue by akvaliya** [vuejs/composition-api#251]
I am new to nuxt. So i am not sure how to use this in nuxt project.

Can anyone explain me how to use it.

**Comment by posva** [comment]
Add a plugin: `plugins/vue-composition.js`

```js
import Vue from 'vue'
import VueCompositionApi from '@vue/composition-api'

Vue.use(VueCompositionApi)
```

Add the plugin to `nuxt.config.js`

```js
plugins: ['~/plugins/vue-composition']
```
