### ISSUE TITLE
watch should type old value as possibly undefined

### ISSUE THREAD

**Issue by alekseymvt** [vuejs/composition-api#253]
Docs: https://vue-composition-api-rfc.netlify.com/api.html#watch (Watching Multiple Sources)
Test:
```
setup() {
    const test = ref({a: 0, b: 0}); //reactive({a: 0, b: 0});
    watch(
        () => [test.a, test.b],
        ([newA, newB], [oldA, oldB]) => console.log(newA, oldA, newB, oldB)
    );
}
```
Result
![изображение](https://user-images.githubusercontent.com/22454101/74590521-3d8c4580-5020-11ea-80cb-317532b374b2.png)

Test:
```
setup() {
    const test = reactive({a: 0, b: 0});
    watch(
        () => [test.a, test.b],
        (newValues, oldValues) => console.log(newValues, oldValues)
    );
}
```
Result:
Array[0, 0], undefined

**Comment by posva** [comment]
On the first run, the old value is undefined, so the error makes sense.
However, the typings are not right (https://github.com/vuejs/vue-next/issues/719) and they should follow the same fix as https://github.com/vuejs/vue-next/commit/c6a9787941ca99877d268182a5bb57fcf8b80b75

**Comment by cnschwarz** [comment]
@posva do I get it right, that more or less the same fix as you mentioned for vue-next has to be applied to the corresponding files here?

I would like to work on this. Let me know if this is still ready to take :)

**Comment by posva** [comment]
@cnschwarz This is still up! I believe the fix is indeed very similar to the fix on vue-next

**Comment by pikax** [comment]
Can you check if this is still a problem on `^0.6.1`?

**Comment by antfu** [comment]
Closing this for now. If you still facing the issue, feel free to reopen it.
