### ISSUE TITLE
createComponent create vue component, how to call self component

### ISSUE THREAD

**Issue by GouJieShinee** [vuejs/composition-api#254]
Components created through createComponent：
```tsx
// tree-node.vue
interface treeProps {
    node: { label: string, value: string|number, children: Array<any> },
    .....
}
export default createComponent({
    name: 'TreeNode',
    setup( props: treeProps ) {
        return () => {
            <div>
                <span>{props.label}</span>
                 // here i want to call <TreeNode> component self, how to call
            </div>
        }
    }
    ...
})
```
i use typescript + vue3.x.  How to invoke the component itself to implement the circular invocation

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

This is related to jsx. I imagine there is a syntax that allows you to use `TreeNode` (maybe `tree-node`) but I'm not aware of it
