### ISSUE TITLE
TypeError: _vm.myFunction is not a function

### ISSUE THREAD

**Issue by bob-lee** [vuejs/composition-api#258]
I have `useHelpers` composition function which returns `myFunction`:
```
function useHelpers() {
  const myFunction = (var1) => (var2) => {
    console.log(var1, var2)
    return var1 && var2
  }
  return {
    myFunction
  }
}
```
and in my component's template, I am passing it over to my child:
```
<template>
      <MyComponent
        :helper-function="myFunction"
      />
</template>
<script>
import MyComponent from './MyComponent.vue'
import { useHelpers } from './compositions'
export default {
  setup() {
    const helpers = useHelpers()
    return {
      ...helpers,
    }
  },
```
and my spec is getting `TypeError: _vm.myFunction is not a function` error:
```
  it('renders properly', () => {
    wrapper = mountFunction({ })
    expect(wrapper.html()).toMatchSnapshot()
  })
```

Not sure how to get over this..
`@vue/composition-api@0.3.4`

**Comment by LinusBorg** [comment]
Hard to say anything about this as you don't show the part that is actually trying to call `myFunction`

**Comment by bob-lee** [comment]
@LinusBorg thanks for reply. I am still skipping tests for my composition functions for this issue and looking for a solution. My project is using composition api and working well in real world. Just in case, is there a separate plugin to test it?

**Comment by pikax** [comment]
@bob-lee you need to add the plugin to tests

Something similar to: 
```js
// jest.config.js
setupFiles: [
  "<rootDir>/__tests__/setupTest.js"
}

// __tests__/setupTest.js
const Vue = require("vue/dist/vue.common");
const plugin = require("@vue/composition-api").default;

Vue.config.productionTip = false;
Vue.config.devtools = false;
Vue.use(plugin);
```

On `jest.config.js`
https://github.com/pikax/vue-composable/blob/master/jest.config.js#L13

The file
https://github.com/pikax/vue-composable/blob/master/__tests__/setupTest.js#L2-L8

**Comment by bob-lee** [comment]
@pikax thanks, that's what I was missing.
