### ISSUE TITLE
callback of watcher with source is first called before mounted

### ISSUE THREAD

**Issue by aimergenge** [vuejs/composition-api#260]
In *Callback Flush Timing* section of [vca rfc doc](https://vue-composition-api-rfc.netlify.com/api.html#watch):

![image](https://user-images.githubusercontent.com/13799160/75087574-17fdbf80-557d-11ea-84cc-2efa6703be67.png)

The first call should be after the component mounted.

But when the watcher has a source to watch, the first run will occur before mounted.

Is this intentional?

**Comment by Landen13** [comment]
I wanted to implement watcher in cmp-api but without first run (like immediate: false).
As I understand this issue is about my problem, right?
