### ISSUE TITLE
Adjust watch behaviour to match latest RFC update

### ISSUE THREAD

**Issue by trygveaa** [vuejs/composition-api#266]
The documentation for watch states:

>  It also is lazy by default - i.e. the callback is only called when the watched source has changed.

However, when I use it, I see that the callback is called even if the data I watch doesn't change after I called watch. If I set the option `{ lazy: true }`, the callback is not called before the data change.

I also think the documentation should state that this is the same option as `immediate` in 
Vue 2. Unless there are any differences? If so, they should be stated.

**Comment by LinusBorg** [comment]
The RFC was changed in that regard 10 hours ago, see [here](https://github.com/vuejs/rfcs/pull/125#issuecomment-592288476).

This plugin has to be updated to match the change in he RFC.
