### ISSUE TITLE
"Computed" causes a memory overflow

### ISSUE THREAD

**Issue by wcldyx** [vuejs/composition-api#267]
### After the global "reactive" object is used in the component's "computed" function, it will not automatically release memory as the component is destroyed, resulting in memory overflow
store.js
1. Create a globally Shared reactive object
```javascript
import { reactive } from '@vue/composition-api'

class Item {
  constructor (index) {
    this.index = index
  }
}

class Store {
  list = new Array(100000).fill('').map((_, i) => new Item(i))
}
const store = reactive(new Store())
export default store;

```
Example.vue
2. Use the global Shared reactive object in the "computed" function in the "Item" component
```vue
<template>
  <div>
    {{ls.length}}
  </div>
</template>
<script>
  import { createComponent, computed } from '@vue/composition-api'
  import store from './store'

  export default createComponent({
    setup (props, ctx) {
      return {
        ls: computed(() => store.list)
      }
    }
  })
</script>

<style lang="scss">

</style>

```
App.vue
3. On the "App" component, use the "toggle" button to continuously create and destroy the "Item" component
```vue
<template>
  <div>
    <example v-if="show"></example>
    <button @click="show = !show">toggle</button>
  </div>
</template>
<script>
  import { createComponent, ref} from '@vue/composition-api';
  import Example from './Example.vue';
  export default createComponent({
    components: { Example },
    setup (props, ctx) {
      return {
        show: ref(false)
      }
    }
  })
</script>

<style lang="scss">

</style>

```
Then you will find that your memory keeps growing, and the added memory will not be destroyed with the destruction of the "Item" component.

**Comment by posva** [comment]
You should pass a plain object to `reactive` not a class instance.
When reporting a memory leak, please provided a runnable boiled down reproduction in an HTML file so it can be easily tested. Open a new issue with the repro if you still see the leak after using a plain object
