### ISSUE TITLE
vuetify form reset

### ISSUE THREAD

**Issue by sagar98ch** [vuejs/composition-api#273]
How to reset form validation of a Vuetify form component in composition api, as it uses methods on this.$refs.form to reset  ?

example :

```html
<template>
  <v-form
    ref="form"
    v-model="valid"
    lazy-validation
  >
    <v-btn
      color="error"
      @click="reset"
    >
      Reset Form
    </v-btn>

    <v-btn
      color="warning"
      @click="resetValidation"
    >
      Reset Validation
    </v-btn>
  </v-form>
</template>
```
```javascript
  export default {
    methods: {
      reset () {
        this.$refs.form.reset()
      },
      resetValidation () {
        this.$refs.form.resetValidation()
      },
    },
  }
```

how this can be done in composition api ?

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
