### ISSUE TITLE
Question: about the difference between watchEffect and watch

### ISSUE THREAD

**Issue by galenjiang** [vuejs/composition-api#280]
According to document descripted below,
> Compared to watchEffect, watch allows us to:
> - Perform the side effect lazily;

I not know why it said Perform side effect lazily, In my opinion watchEffect is also lazily.

And the document also said that about watchEffect below 
> Vue's reactivity system buffers invalidated effects and flush them asynchronously to avoid unnecessary duplicate invocation when there are many state mutations happening in the same "tick". Internally, a component's update function is also a watched effect. When a user effect is queued, it is always invoked after all component update effects:

Mybe the asyncchronously and lazily are the different thing?

**Comment by galenjiang** [comment]
Oops, I found the document was outdated, and `lazily` is meaning the hook will not trigger when component mounted, not to be concerned with that the callback applied asynchronously .

**Comment by posva** [comment]
`watchEffect` is not present on this lib yet but you can have both behaviors by using the `lazy` option of `watch`. When `lazy` is set to `false`, it's the same behavior as `watchEffect`.
The second mention you are referring to is customizable through the `flush` option.

Note: The RFC reflects Vue 3
