### ISSUE TITLE
Can we use this package for migration vue version 2 to 3?

### ISSUE THREAD

**Issue by rchaser53** [vuejs/composition-api#282]
This question is just curiosity. Can we use this package for migration from vue 2 to 3? 
Or shouldn't we use this for migration? (As far as I saw the note, we should not use it...)
If we should not use this package, is there alternative way?

**Comment by LinusBorg** [comment]
If you want to start using to composition functions now, you can use this plugin although you should probably be careful in components that are performance-critical.

The API is close enough to make migration to Vue 3 easy and straightforward imho.

But I would not try and move a whole app to the composition API now, except for side projects.

**Comment by rchaser53** [comment]
I see. Thank you for that!
When we migrated from vue version 1 to 2, we used [vue-migration-helper](https://github.com/vuejs/vue-migration-helper).
Do your or vue team have the plan to create the migration tool like vue-migration-helper?

**Comment by LinusBorg** [comment]
Yes we do. We also plan to provide actual codemode scripts to automate migration for those parts that can be automated.

It's on the roadmap: https://github.com/vuejs/vue/projects/6

**Comment by rchaser53** [comment]
Really? It's so great. I can't wait for it.
