### ISSUE TITLE
Issue when refreshing page and using inject on app

### ISSUE THREAD

**Issue by iksaku** [vuejs/composition-api#284]
I'm using `v0.4.0` and using the `inject` function to persist the state of a Sidebar.

Upon serving the project using `vue-cli`, no error is shown, but when loading the window in Firefox, the following error is shown:
![image](https://user-images.githubusercontent.com/4632429/76908088-7ad93280-686d-11ea-9bcb-9db1f91c82e5.png)

For reference, the full project is available at [iksaku/uanl-repo-search@f136d0e](https://github.com/iksaku/uanl-repo-search/tree/f136d0e408f844d6bae911ec25aa8321a96899c6)

I'm already enabling the `@vue/composition-api` plugin calling the [`src/plugins/composition-api.ts`](https://github.com/iksaku/uanl-repo-search/blob/f136d0e408f844d6bae911ec25aa8321a96899c6/src/plugins/composition-api.ts) file from [`src/main.ts`](https://github.com/iksaku/uanl-repo-search/blob/f136d0e408f844d6bae911ec25aa8321a96899c6/src/main.ts#L2) file.

The [`src/App.vue`](https://github.com/iksaku/uanl-repo-search/blob/f136d0e408f844d6bae911ec25aa8321a96899c6/src/App.vue#L34) file is calling the `useSidebar` funciton, defined in [`src/plugins/store/sidebar.ts`](https://github.com/iksaku/uanl-repo-search/blob/f136d0e408f844d6bae911ec25aa8321a96899c6/src/plugins/store/sidebar.ts#L14) file.

The steps to reproduce the error are:
1. Comment out lines `21`, `32` and `34` from the `App.vue` file and serve the project. This will allow the project to load properly in the browser.
2. Remove the comment marks previously added and save, the project will re-load properly in the browser and will log the injected object in the console.
3. Reload the browser window in the browser without making changes to the code, then the project will not load, and will log the previously mentioned error in the console.

Any thoughts on this?

**Comment by LinusBorg** [comment]
Theissue is that the code in `plugins/store/sidebar.ts will run directly on import - and it's being imported *before* you actually call `Vue.use(...)`

App.vue -> Sidebar.vue -> plugins/stroe/sidebar.ts

I assume you are aware of this behaviour and tried to mitigate it by having this line before importing `App.vue` in `main.js`:

```
require('@/plugins/composition-api')
```

But According to the ESM Spec, imports are hoisted to the very top of the file, so the *true* code order is:

```javascript
import Vue from 'vue';
import App from './App.vue';

require('@/assets/styles.pcss')
require('@/plugins/composition-api')
```

...which explains why your App.vue import chain is evaluated before the plugin has been installed.

Solution: Use an ES6 import.

```typescript
import '@/assets/styles.pcss'
import '@/plugins/composition-api'

import Vue from 'vue';
import App from './App.vue';
```

**Comment by iksaku** [comment]
Thanks @LinusBorg! This solved the issue :rocket:.
