### ISSUE TITLE
ValueWrap 的嵌套存在问题，https://gist.github.com/aimwhy/dffbc1e03d85436fe8a76d7a5e9f9e03

### ISSUE THREAD

**Issue by aimwhy** [vuejs/composition-api#29]
上方的 Test.vue 是 问题用例

下方的 vue-function-api.js ：是自己 对于 value 和 state 的实现方式。 可以解决

希望能给作者提供思路

[vue-function-api.js ValueWrap 嵌套的问题](https://gist.github.com/aimwhy/dffbc1e03d85436fe8a76d7a5e9f9e03)

**Comment by liximomo** [comment]
什么问题呢，能不能用语言描述下，你的期望是什么，现在的结果是什么？

**Comment by aimwhy** [comment]
> 什么问题呢，能不能用语言描述下，你的期望是什么，现在的结果是什么？

https://gist.github.com/aimwhy/dffbc1e03d85436fe8a76d7a5e9f9e03  Test.vue 是出错的用例
