### ISSUE TITLE
Typescript: 'Function' type of PropType introduced in 0.5.0 is annoying when using Vetur

### ISSUE THREAD

**Issue by gertqin** [vuejs/composition-api#291]
When using Vetur's template interpolation service, object props cannot be used directly in the template from 0.5.0, without getting syntax errors:

![ss](https://user-images.githubusercontent.com/17803278/77511845-3273d300-6e72-11ea-88f3-399a4a1fd3ac.png)

Exposing the user through setup, i.e.
```ts
export default defineComponent({
  props: {
    user: Object as PropType<IUser>,
  },
  setup(props) {
    return { user: props.user as IUser }
  }
});
```
works for Vetur, but then the console will print warnings:

```
[Vue warn]: The setup binding property "user" is already declared as a prop.
```

**Comment by jaryn-kubik** [comment]
This isn't just a problem with Vetur by the way, if you wanna use the prop in setup, you'll run into the same problem.
PropType is just broken in 0.5.0.

**Comment by LinusBorg** [comment]
@ktsn this sounds like a problem for your Type skills ... Got an idea?

**Comment by ktsn** [comment]
This might be a bug of TypeScript... I've filed an issue on the repo. https://github.com/microsoft/TypeScript/issues/37734
