### ISSUE TITLE
why computed doesn't recalculate in shared resource?

### ISSUE THREAD

**Issue by wizardnet972** [vuejs/composition-api#292]
In my app.vue I have two components `foo` and `bar`. both are connected to `ready` computed from js file.

Even though they point to same reference (computed function), **only one gets update**

Why? how to solve this? its a bug?

[The code on codesandbox](https://codesandbox.io/s/ancient-wildflower-dhmos)

Both point to the same reference but I got difference results:
![image](https://user-images.githubusercontent.com/4997825/77514411-7c16ea80-6e7f-11ea-8640-fb5dfad4ffe7.png)

use-something.js:
```
import { computed, ref } from "@vue/composition-api";

function timeout(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

export const useSomething = () => {
  const isReady = ref(false);

  const ready = computed(() => isReady);

  const exec = () =>
    timeout(2000).then(() => {
      isReady.value = true;
    });

  return { exec, ready };
};

```
bar.vue:
```
<template>
  <div id="bar">ready in bar? {{ready}}</div>
</template>

<script>
import { useSomething } from "./use-something";

export default {
  name: "Bar",
  setup() {
    const { ready } = useSomething();

    return { ready };
  }
};
</script>
```
foo.vue:
```
<template>
  <div id="foo">ready in foo? {{ready}}</div>
</template>

<script>
import { useSomething } from "./use-something";

export default {
  name: "Foo",
  setup() {
    const { ready, exec } = useSomething();

    exec();

    return { ready };
  }
};
</script>
```

app.vue:
```
<template>
  <div id="app">
    <div>bar component:
      <br>
      <Bar/>
      <br>
      <br>
      <br>foo component:
      <br>

      <Foo/>
    </div>
  </div>
</template>

<script>
import Foo from "./foo.vue";
import Bar from "./bar.vue";

export default {
  name: "App",
  components: {
    Bar,
    Foo
  }
};
</script>
```

**Comment by LinusBorg** [comment]
You call `useSomething` 2 times, and each time, a new, different instand of the `ready` computed prop is returned. Those are independent instances, and both reference their own, independent instances of the `isReady` ref.

since you only call `exec` for one of the two, the other never gets started and consequently never updates.

The reason for this is more rooted in how Javascript works than this plugin.
