### ISSUE TITLE
Reactiveness works only in component that made change.

### ISSUE THREAD

**Issue by gibkigonzo** [vuejs/composition-api#294]
Hello :vulcan_salute: 
I'm not sure is this a bug or more a question.
I have two components.
Parent:
```
<template>
  <div>
    Parent: {{ state }}
    <Child />
  </div>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api'
import useState from './useState'
import Child from './child.vue'

export default defineComponent({
  setup() {
    const { state } = useState()
    return { state }
  },
  components: {
    Child
  }
})
</script>
```

Child:
```
<template>
  <div>Child: {{ state }}</div>
</template>

<script lang="ts">
import { defineComponent } from '@vue/composition-api'
import useState from './useState'

export default defineComponent({
  setup() {
    const { state } = useState()
    setInterval(() => {
      state.value = state.value + 1
    }, 2000)
    return { state }
  }
})
</script>
```
and both component use same state:
```
import { ref, toRefs } from '@vue/composition-api'

export default () => {
  const state = ref('test')
  return toRefs({
    state
  })
}
```

What expected?
I expect that `state` will be reactive and will change in both components.

What happens?
State only is changing in component that makes change. In that example state is only changed in child component, but if I will put this interval into parent, then state will only change in parent component.

version: 0.5.0

**Comment by posva** [comment]
If you want both to share the state, you need both of them to use the same variable. By calling the function you are creating two different `ref`, you could instead cache it to use the same variable:

```js
let state
export default () => {
  if (!state) state = ref('test')
  return toRefs({
    state
  })
}
```
