### ISSUE TITLE
Reactive property of a negative ref won't reactive

### ISSUE THREAD

**Issue by tiepnguyen** [vuejs/composition-api#297]
Hi guys,

According to this reference https://vue-composition-api-rfc.netlify.com/api.html#ref -> Access in Reactive Objects, a `ref` will be unwrapped when use as a `reactive` object property, which is nice. 
```js
const isMale = ref(true)
const user = reactive({
  male: isMale // reactive
});
```
However if I negative the ref, then the reactive property no longer reactive to the ref value
```js
const isMale = ref(true)
const user = reactive({
  male: !isMale // no longer reactive
});
```

[Codesandbox Example](https://codesandbox.io/s/quiet-leftpad-u3v7t)

On second though I don't think this really is an issue, but it should be documented somewhere, since it got me confuse at the beginning

**Comment by posva** [comment]
This is expected as you are not supposed to write `!` in front of a ref (an object), you are basically passing `true` to the `male` property instead of the actual ref
