### ISSUE TITLE
Component with mixin-only props definition

### ISSUE THREAD

**Issue by LeBenLeBen** [vuejs/composition-api#299]
I have the following component:

```js
import { defineComponent } from '@vue/composition-api';
import TabsMixin from './mixin';

interface TabListProps {
  bare?: boolean;
}

export default defineComponent<TabListProps>({
  name: 'CTabList',

  mixins: [TabsMixin],

  setup(props) {
    return {
      bare: props.bare,
    };
  },
});
```

Using the following mixin:

```js
export default {
  props: {
    bare: {
      type: Boolean,
      default: false,
    },
  },
};
```

Because there’s no `props` key on the component, when accessing `props.bare` in the setup function, TypeScript throws the following error.

> (parameter) props: unknown
> Object is of type 'unknown'. ts(2571)

A workaround is to add an empty `props: {}` object on the component, but that's kinda ugly and requires a comment to explain why so it doesn't get removed. Am I doing something wrong? Could this be handled by the types somehow?

**Comment by MartinMalinda** [comment]
You can share props between multiple components through spreading:

```ts
const baseProps = {
 bare: {
      type: Boolean,
      default: false,
    },
};

component A:

```ts
props {
  ...baseProps,
  otherProp: String
}
```

component B:

```ts
props {
  ...baseProps,
  yetAnotherProp: String
}
```

**Comment by LeBenLeBen** [comment]
@MartinMalinda Thanks for the clean & simple tip! However this syntax seems unsupported by vue-docgen-api which is used to automatically parse props for documentation 😔

**Comment by MartinMalinda** [comment]
@LeBenLeBen oh :( seems strange, in the end result the prop definition should be completely same, unless the docgen is just parsing the file somehow and picking props from there (why?!)

Storybook definitely has no issues with this

**Comment by LeBenLeBen** [comment]
@MartinMalinda That's weird, Storybook use vue-docgen-api in the background. I just tested it with vue-docgen-cli and it wasn't able to pick-up the prop when it was spreaded while it worked with the mixin.
