### ISSUE TITLE
HELP!! How to export Object(Api Function) when return jsx in setup

### ISSUE THREAD

**Issue by zen0822** [vuejs/composition-api#302]
```tsx
...
setup({ value }) {
  function api () {
    console.log(`get ${ value }`)
  }
  
  // How to merge function api to context ?
  
  return (): VNode => (
    <div>zen</div>
  )
}
...
```

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

you need a `render` function for vue 2:https://github.com/vuejs/composition-api#template-refs

**Comment by zen0822** [comment]
> Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
> 
> you need a `render` function for vue 2:https://github.com/vuejs/composition-api#template-refs

Thx

**Comment by zen0822** [comment]
@posva Sorry, I really want to know you consider define method or hook we can merge our var to setupContext ?

I want a hook like that React useimperativehandle <https://reactjs.org/docs/hooks-reference.html#useimperativehandle>

**Comment by startblingbling** [comment]
@zen0822  Have you solved this problem？I have the same problem now
