### ISSUE TITLE
Reactive does not react vue-i18n

### ISSUE THREAD

**Issue by gokhantaskan** [vuejs/composition-api#303]
I'm using composition API in some components. The code below is not working when the page loads initially.

```js
setup(props, vm) {
  const state = reactive({
    routes: [
      {
        name: vm.root.$i18n.t("titles.overview"),
        icon: "overview",
        path: { name: "Overview" },
        isFor: ["retailer", "consumer"]
      },
      ...
  return { ...toRefs(state) };
}
```

`vue-i18n.esm.js?a925:33 [vue-i18n] Cannot translate the value of keypath 'labels.settings'. Use the value of keypath as default.`

But there is nothing wrong. In another component, it is working.

```js
<page-heading
    :title="$t('titles.overview')"
    has-datepicker
    show-date
>
</page-heading>
```

![image](https://user-images.githubusercontent.com/45636599/78536473-92656480-77f6-11ea-921e-4f6b9bbd333f.png)

After changing something that causes hot reload (like console.log("x") just before `const state,` the sidebar shows the title normally but when the initial load, the text is just `titles.blabla`.

**Comment by gokhantaskan** [comment]
I tested it for every page.I refreshed every page that contains the new composition API and the result is the same (during initial load). I guess the problem is about `setup`or `vm.root.$i18n`.

**Comment by noobdw** [comment]
hi, did you solve this, i got same problem, how you done with this?

**Comment by Stanislavsky69** [comment]
> hi, did you solve this, i got same problem, how you done with this?

Hi, use this  [package]( https://github.com/intlify/vue-i18n-composable)
