### ISSUE TITLE
How to inject mock value in test?

### ISSUE THREAD

**Issue by MartinMalinda** [vuejs/composition-api#305]
I have a component that does, let's say, `useStore`, `provideStore` was done by a top level component.

But in the unit test the parent component does not exist.

I cannot call `provideStore` randomly because it can only be called in `setup()`.

Any workarounds? Thanks!

**Comment by MartinMalinda** [comment]
I'm trying

```
    inject: {
      [storeKey]: {
        from: storeKey,
        default: $fakeStore
      }
    },
```

With no success. I'm not sure if the `vue-test-utils` feature is compatible with composition-api.

**Comment by MartinMalinda** [comment]
So far I'm going with this solution. It's a bit ugly, I don't like if checks for test environment, but it works.

```ts
let __testContainer = {};

export function clearTestContainer(): void {
  __testContainer = {};
}

export function provideStore(store): void {
  if (process.env.NODE_ENV === 'test') {
    __testContainer[storeKey] = auth;
    return;
  }

  provide(storeKey, store);
}

export function useStore(): Store<any> {
  let store: Store<any> | void;
  if (process.env.NODE_ENV === 'test') {
    store = __testContainer[storeKey];
  } else {
    store = inject(storeKey);
  }

  if (!store) {
    throw new Error(`Store has not been provided!`);
  }

  return store;
}
```

**Comment by LinusBorg** [comment]
You could use the `parentComponent` option. Pass it a minimal component that contains a setup function which calls `provideStore()`

**Comment by MartinMalinda** [comment]
@LinusBorg Thanks! That works. This is now how I do it:

```
parentComponent: createProviderComponent({ $store }),
```

**Comment by LinusBorg** [comment]
I'll close this issue as sufficient solutions have been provided and true support for the composition api will arrive in the test utils lib sooner or later.
