### ISSUE TITLE
Ref value confusing with the objects value

### ISSUE THREAD

**Issue by SeyyedKhandon** [vuejs/composition-api#306]
I asked this question on stack, but didnt get the answer, so i thought i would open an issue for this problem in the vue-itself.
I am using vue composition API  and using a ref for an array of objects which each object has a value property, it seems that the typescript confusing ref's value with the property value inside of each array:

[![enter image description here][1]][1]

As you see in the above picture, typescript telling us the type of arr is an array of object which contains name and value, but when i used ref, it detects the wrong type. even if i used as conversion like below the problem wont solve:

    const arr2 = ref(arr as { name: string; value: number }[]);

But when i change the value property to value2 or something else, it will work:
[![enter image description here][2]][2]

**update**:

here is another problem which i have faced today:

[![enter image description here][3]][3]

I'm wondering how should i solve this type error?

  [1]: https://i.stack.imgur.com/PPXso.png
  [2]: https://i.stack.imgur.com/CCcq6.png
  [3]: https://i.stack.imgur.com/auhcN.png

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/composition-api/issues/157?

**Comment by SeyyedKhandon** [comment]
yes , its seems the same in the context.
