### ISSUE TITLE
Why object's array returns undefined？

### ISSUE THREAD

**Issue by xmsz** [vuejs/composition-api#307]
```
    const state = reactive({
      awardList: [
        {
          num: 1,
        },
      ],
    });
```
```
<div>
          {state.awardList}
          {state.awardList[0].num}
          {JSON.stringify(state.awardList)}
</div>
```

```
          {state.awardList} => undefined
          {state.awardList[0].num} =>  1
          {JSON.stringify(state.awardList)} => "[{num:1}]"
```

![image](https://user-images.githubusercontent.com/5879146/79407312-c5181580-7fcb-11ea-8324-1ae8ced032e5.png)

It works fine with number's array or string's array
```
    const state = reactive({
      awardList: [0],
    });
```

**Comment by posva** [comment]
can you provide a repro, please?

**Comment by xmsz** [comment]
> can you provide a repro, please?

https://github.com/xmsz/vue-jsx-object-array-returns-undefined

```
npm run serve
```

**Comment by posva** [comment]
Something without jsx nor TS (a boiled down), in a jsfiddle, codepen or similar

**Comment by xmsz** [comment]
> Something without jsx nor TS (a boiled down), in a jsfiddle, codepen or similar

This is my own mistake,  https://vuejs.org/v2/guide/render-function.html shows children will only be treated as string or vNode
