### ISSUE TITLE
Missing function `toRef`

### ISSUE THREAD

**Issue by larvanitis** [vuejs/composition-api#313]
The _Reactivity Utility_ [`toRef`](https://composition-api.vuejs.org/api.html#toref) is not implemented.

**Comment by pikax** [comment]
I've already implemented that in the PR I'm working https://github.com/vuejs/composition-api/pull/311 :)

https://github.com/pikax/vue-function-api/blob/feat/vue3_API/src/reactivity/ref.ts#L136
