### ISSUE TITLE
[Bug report] Can't change one of the array element.

### ISSUE THREAD

**Issue by annder** [vuejs/composition-api#314]
## Descript
When I want to build a simple application, I found I using reactive array can't assign to one of the element.

## Instance
For instance:

```vue
<template>
  <div class="card">
    <ul>
      <li v-for="(item, index) in list" :key="index">
        {{ item }}
      </li>
    </ul>
    <button @click="change">change</button>
    <button @click="push">push</button>
  </div>
</template>

<script>
import { ref, reactive } from '@vue/composition-api';
export default {
  setup() {
    let counter = 1;
    const list = ref([reactive({ text: '1' })]);
    const push = () => {
      list.value.push(reactive({ text: counter++ }));
    };
    const change = () => {
      list.value[0] = reactive({ });
    };
    return { list, change, push };
  },
};
</script>

<style lang="scss"></style>
```

##  Step recurrence
I clicked the `push` event then correct update to page, but when I click the `change` event, it can't re-render,just const.

Now, I found if you first time click `change` event then you click `push` event ,the top of item change to the '{}' data.

## Development env

- Operation system: Windows 10.0.17763
- Nodejs version: 12.13.0
- Packager: 1.12.4

**Comment by posva** [comment]
Please see https://vuejs.org/v2/guide/reactivity.html#For-Arrays

Use `splice` to replace an item in an array instead.
