### ISSUE TITLE
Typing the return of `toRefs`

### ISSUE THREAD

**Issue by absolutejam** [vuejs/composition-api#315]
Howdy,

First of all, I just want to say how much I enjoy using Vue and the new composition api is amazing. Great job 👍 

I'm using Typescript in my project and I've generally been using pretty basic interfaces and inference where possible, but I hit a problem yesterday wherein the return type of `toRefs()` wasn't valid.

I spent quite a while poking around in the composition-api source, inspecting type definitions, and eventually I realised that I could create the following type which will wrap an existing type/interface's properties in `Ref`.

```ts
type Refs<T> = {
  [P in keyof T]: Ref<T[P]>;
};
```

But I couldn't see something available/documented to provide this. Is this something that should be part of the library or would people be expected to provide something themselves?

Regards,
James.

**Comment by LinusBorg** [comment]
> I hit a problem yesterday wherein the return type of toRefs() wasn't valid.

Sounds like a bug.

**Comment by pikax** [comment]
Created a pull on vue-next https://github.com/vuejs/vue-next/pull/1037

I can add that to the PR https://github.com/vuejs/composition-api/pull/311 👍

**Comment by LinusBorg** [comment]
Awesome, do that after the vue-next PR is accepted, just to be sure that we stay in sync.

Thanks!
