### ISSUE TITLE
how can I pass ref to child component

### ISSUE THREAD

**Issue by wulucxy** [vuejs/composition-api#317]
I notice in the docs:

https://vue-composition-api-rfc.netlify.app/api.html#ref

```
When a ref is returned as a property on the render context (the object returned from setup()) and accessed in the template, it automatically unwraps to the inner value. There is no need to append .value in the template:
```

but sometimes I need to get deep parent's ref like this:

```
<div id="stage" ref="imgWrapperRef">
  zoom {{ zoom }}
  <div>select: {{ state.annotations.value }}</div>
  <ZoomContainer :controlled="true" :filter="filter" v-bind="zoom">
    <div class="ref">
      <div class="imgWrapper">
        <img :src="currentImg">
      </div>
      <TooltipContainer>
        <!-- vue can not pass ref, sucks~ -->
        <Canvas :imgWrapperRef="imgWrapperRef" v-bind="$props" />
      </TooltipContainer>
    </div>
  </ZoomContainer>
</div>
```

what I wish is I can pass the original `imgWrapperRef` to the `Canvas` component。
Since `ref` is automate `unwrap`, I can only the the `HtmlElement`, instead of the original `Ref` Object。

do you have any `hack` solution for this?

**Comment by LinusBorg** [comment]
First off, it's not recommended to mutate props, so if you follow general and don't mutate props (emitting events instead), you should be fine with only the value instead of the ref.

If you think that you have an edge case where you need to mutate a prop and therefore need the ref, wrap it in a function that returns the ref, then you can call it in the child to get the ref.

```javascript
setup() {
  // ...
  const imgWrapperRefFn = () => imageWrapperRef
  // ...
}
```
```html
<Canvas :imgWrapperRef="imgWrapperRefFn" v-bind="$props" />
```

**Comment by Flamenco** [comment]
@LinusBorg As much as I like to follow the 'do not mutate props' mindset, I have found myself more and more passing around reactive properties.

Would a directive like this be possible, to instruct Vue to not unwrap?

```html
<Canvas :imgWrapperRef.ref="imageWrapperRef" v-bind="$props" />
```

**Comment by LinusBorg** [comment]
> As a side-note, you **cannot** embed the function as shown here, because Vue will still unwrap the ref.
> 
> ```
> <Canvas :imgWrapperRef="() => imageWrapperRef" v-bind="$props" />
> ```

Not sure what you mean. Works fine [here](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcbmltcG9ydCBDb21wIGZyb20gJy4vQ29tcC52dWUnXG5jb25zdCBtc2cgPSByZWYoJ0hlbGxvIFdvcmxkIScpXG5jb25zdCBmbiA9ICgpID0+IG1zZ1xuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAgPGgxPnt7IG1zZyB9fTwvaDE+XG4gIDxDb21wIDp0ZXN0PVwiZm5cIiAvPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiQ29tcC52dWUiOiI8c2NyaXB0IHNldHVwPlxuaW1wb3J0IHsgcmVmIH0gZnJvbSAndnVlJ1xuXG5jb25zdCBwcm9wcyA9IGRlZmluZVByb3BzKHtcbiAgdGVzdDoge1xuICAgIHR5cGU6IEZ1bmN0aW9uLFxuICAgIHJlcXVpcmVkOiB0cnVlLFxuICB9XG59KVxuPC9zY3JpcHQ+XG5cbjx0ZW1wbGF0ZT5cbiAge3sgcHJvcHMudGVzdCgpLnZhbHVlIH19XG48L3RlbXBsYXRlPiJ9)



> @LinusBorg As much as I like to follow the 'do not mutate props' mindset, I have found myself more and more passing around reactive properties.
> 
> Would a directive like this be possible, to instruct Vue to not unwrap?
> 
> ```
> <Canvas :imgWrapperRef.ref="imageWrapperRef" v-bind="$props" />
> ```

I don't think that will get support.

**Comment by Flamenco** [comment]
Yes, @LinusBorg , it works, but the syntax is verbose, cumbersome, difficult to manage, and requires the reviewer to inspect the function to see if it does more than just pass in a ref to the component. The suggested directive property would make it very clear as the intent when searching source code and debugging.

It would be nice to have the same succinct syntax in Vue as demonstrated by other directive properties such as `stop` and `prevent`.

As I have fully embraced Vue Composition API, almost all of my functions now take MaybeRef arguments, and more often than not I unwrap parameters.  

Anyway I just wanted to open that option for discussion, as it relates 100% to this closed issued, and won't pursue it further if convinced that the suggestion has no merit.

**Comment by LinusBorg** [comment]
If you want to start the discussion, there's the RFCs repo for that.

**Comment by Flamenco** [comment]
@LinusBorg Take another look at the side-note method  I posted.  I was pointing out that you cannot embed a callback function returning the ref in the template.  You need to define the function in your script...

```ts
<Canvas :imgWrapperRef="() => imageWrapperRef" v-bind="$props" />
```

**Comment by Bond-Addict** [comment]
I too am running into this issue. I need to pass a ref for a form element down to the child which is where the validate method is used to validate the form.  The issue is that the ref is present but the value is undefined.

**Comment by Fernando12mais** [comment]
What I did was putting the ref inside the father component, then on the onMounted hook, i get the first children on the father component and assign it to a ref
  
  onMounted(() => {
  if (!fatherRef.value) return;
  childrenRef.value = fatherRef.value.children[0] as HTMLElement;
  manageAnimation("expand");
});

```
<template>
<div ref="fatherRef">
<slot></slot>
</div>
</template>
```


if this is a wrapper component i could


```
<WrapperComponent>

<button>the children ref inside wrapper component has the ref for this button now</button>
 </WrapperComponent>
```
