### ISSUE TITLE
computed property was considered to be data property in vue-devtools

### ISSUE THREAD

**Issue by iulo** [vuejs/composition-api#318]
![image](https://user-images.githubusercontent.com/6769037/80173222-b5c74680-8621-11ea-8dc9-649daebff916.png)

![image](https://user-images.githubusercontent.com/6769037/80173054-3d608580-8621-11ea-9cef-d8e073f74559.png)

`disabled` is a computed property, but in devtools it is considered to be data property.

**Comment by LinusBorg** [comment]
Showing up under `data` is a side-Effect of the implementation of `computed()` in and `setup() `this plugin - it's expected.

the error message you are seeing has likely a different reason, but I can't say without seeing reproduction code.

**Comment by iulo** [comment]
The error occurs when change the checkbox of computed property, as you say `it's expected`, it should not be a bug.

**Comment by Made-of-Clay** [comment]
@iulo It would seem the error you see is regarding the computed properties missing a `setter`. Computed properties can't be assigned values directly unless the setter exists. See [Computed Setter](https://vuejs.org/v2/guide/computed.html#Computed-Setter) docs for more.

I agree with your initial question regarding the computed showing as data being confusing. That's what brought me here in the first place. I wonder if computed can be inferred from the type? (i.e. `ComputedRef<T>`)
