### ISSUE TITLE
Production Usage

### ISSUE THREAD

**Issue by Austio** [vuejs/composition-api#321]
:wave: 

Howdy, now that this concept is in Vue3 for the beta release, is this package considered stable for using in production applications?

**Comment by posva** [comment]
I think this package will hit stable once it reaches parity with Vue 3. It will probably be released as v1 at that time as well

**Comment by oswaldofreitas** [comment]
any plans for releasing a v1 soon?

**Comment by LinusBorg** [comment]
I don't see any reason to release a v1 before we hit the RC for Vue 3.

Until then, breaking changes are still a possibility that I think we don't want to risk happening after we have released v1 for this plugin.

**Comment by Austio** [comment]
Thanks all :)
