### ISSUE TITLE
API can't support parameter type recognition in typescript for logic extracted from setup

### ISSUE THREAD

**Issue by yangdan8** [vuejs/composition-api#326]
1.Please provide the following specific types of any type, preferably the type can be inferred automatically
2.nextTick cannot be imported and used from Vue in vue2, resulting in incorrect usage in the document and direct error reporting，Is it unreasonable to use ctx.root. $nexttick? Is ctx.root equal to this? What about CTX?

api对从setup中抽离逻辑在typescript支持参数类型识别还不行
1.请提供以下any类型的具体类型，最好是能自动推断类型
2.nextTick无法在vue2中从vue导入使用，导致文档中的使用方式不正确，直接报错使用ctx.root.$nextTick是否不合理？莫非ctx.root等于原来的this?那ctx呢？

```javascript
const props = {
  type: String,
};

const typeComputedFn = (props: any, ctx: any) =>
  computed(() => props.type + '_computed');

const getData = (props: any, ctx: any) =>
  reactive({
    typeInner: props.type + '_inner',
  });

const getElWidth = (props: any, ctx: any) =>
  () => ctx.root.$nextTick(() => {
    console.warn(window.getComputedStyle(ctx.root.$el).width);
  });

export default createComponent({
  props,
  setup(props, ctx) {
    const data = getData(props, ctx);
    const typeComputed = typeComputedFn(props, ctx);
    onMounted(getElWidth(props, ctx));
    return {
      ...toRefs(data),
      typeComputed,
    };
  },
});
```

**Comment by yangdan8** [comment]
`1.Please provide the following specific types of any type, preferably the type can be inferred automatically
2.nextTick cannot be imported and used from Vue in vue2, resulting in incorrect usage in the document and direct error reporting，Is it unreasonable to use ctx.root. $nexttick? Is ctx.root equal to this? What about CTX?

api对从setup中抽离逻辑在typescript支持参数类型识别还不行
1.请提供以下any类型的具体类型，最好是能自动推断类型
2.nextTick无法在vue2中从vue导入使用，导致文档中的使用方式不正确，直接报错使用ctx.root.$nextTick是否不合理？莫非ctx.root等于原来的this?那ctx呢？

const props = {
  type: String,
};

const typeComputedFn = (props: any, ctx: any) =>
  computed(() => props.type + '_computed');

const getData = (props: any, ctx: any) =>
  reactive({
    typeInner: props.type + '_inner',
  });

const getElWidth = (props: any, ctx: any) =>
  ctx.root.$nextTick(() => {
    console.warn(window.getComputedStyle(ctx.root.$el).width);
  });

export default createComponent({
  props,
  setup(props, ctx) {
    const data = getData(props, ctx);
    const typeComputed = typeComputedFn(props, ctx);
    onMounted(getElWidth);
    return {
      ...toRefs(data),
      typeComputed,
    };
  },
});`

**Comment by yangdan8** [comment]
`const props = {
  type: String,
};

const typeComputedFn = (props: any, ctx: any) =>
  computed(() => props.type + '_computed');

const getData = (props: any, ctx: any) =>
  reactive({
    typeInner: props.type + '_inner',
  });

const getElWidth = (props: any, ctx: any) =>
  ctx.root.$nextTick(() => {
    console.warn(window.getComputedStyle(ctx.root.$el).width);
  });

export default createComponent({
  props,
  setup(props, ctx) {
    const data = getData(props, ctx);
    const typeComputed = typeComputedFn(props, ctx);
    onMounted(getElWidth);
    return {
      ...toRefs(data),
      typeComputed,
    };
  },
});`

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).

---

You can import `Vue` and call `Vue.nextTick`. It's the same as `this.$nextTick`. Your `getElWidth` and other functions should type the things they use like the `type` property and the `$el` property. It's easier if you pass them directly as well

**Comment by yangdan8** [comment]
Can you provide the revised code? Any here is really a problem. Type cannot be defined every time

**Comment by yangdan8** [comment]
By reading the source code and d.ts code, I found the types of props and ctx, and share them with you,thanks!

```javascript
const props = {
  type: String,
};

type PropType = ExtractPropTypes<typeof props>;

const typeComputedFn = (props: PropType, ctx: SetupContext) =>
  computed(() => props.type + '_computed');

const getData = (props: PropType, ctx: SetupContext) =>
  reactive({
    typeInner: props.type + '_inner',
  });

const getElWidth = (props: PropType, ctx: SetupContext) =>
  () => ctx.root.$nextTick(() => {
    console.warn(window.getComputedStyle(ctx.root.$el).width);
  });

export default createComponent({
  props,
  setup(props, ctx) {
    const data = getData(props, ctx);
    const typeComputed = typeComputedFn(props, ctx);
    onMounted(getElWidth(props, ctx));
    return {
      ...toRefs(data),
      typeComputed,
    };
  },
});
```
