### ISSUE TITLE
Missing function isReactive

### ISSUE THREAD

**Issue by cerino-ligutom** [vuejs/composition-api#327]
The _Reactivity Utility_ [`isReactive`](https://composition-api.vuejs.org/api.html#isreactive) is not implemented.

![image](https://user-images.githubusercontent.com/6721822/80855762-5a770300-8c76-11ea-98bf-4d853ea4eaf1.png)

**Comment by pikax** [comment]
Will be added by https://github.com/vuejs/composition-api/pull/311
