### ISSUE TITLE
The "Basic Example" of official doc

### ISSUE THREAD

**Issue by Guobacai** [vuejs/composition-api#331]
Hi,
This is probably not the best place to ask this question. But, I could figure out anywhere else. This might not be an issue. Just try to understand the motivation behind that code.

https://vue-composition-api-rfc.netlify.app/#basic-example

In the "Basic Example", it assign a "computed property" to a state (The data in the Vue).
```
    const state = reactive({
      count: 0,
      double: computed(() => state.count * 2)
    })
```
Is that recommended way of writing the composition API? I try to understand what is the benefit of doing this?
As I understand, one of potential problem is the "double" could be changed at other places.

**Comment by posva** [comment]
`reactive` allows to automatically unwrap containers like `ref` and `computed` so you don't have to append the `.value`.

```js
let double = computed(() => state.count * 2)
let state = reactive({
  count: 1,
  double,
})

double.value // 1
state.double // 1
```

You can use that automatic unwrapping in many ways but mainly, `reactive` is like an object internally that changes.

I think the best place to talk about it with other people is the [Discord chat](https://vue-land.js.org/), you will be able to see what others are doing and learn

**Comment by Guobacai** [comment]
Thank you @posva. I should have read the doc more carefully.
