### ISSUE TITLE
Issue with $emit on context

### ISSUE THREAD

**Issue by matthewhardern** [vuejs/composition-api#332]
Using $emit on context with event 'input'

```conext.root.$emit```

It throws an error of ```Cannot read property 'input' of undefined```,  however when doing the same via a method with ```this.$emit``` it works. 

Thanks for the great work

**Comment by posva** [comment]
that doesn't look like it comes from this lib. Did you seek for help 
 on the [forum](http://forum.vuejs.org/) or, the [Discord server](https://vue-land.js.org/)?

We will need a boiled down reproduction to check it

**Comment by matthewhardern** [comment]
```
<template>
    <label>
        <span v-if="label">{{label}}</span>
        <input :value="value" @input="input($event)" type="text" class="" >
    </label>
</template>

<script>
    export default {
        name: "TextInput",
        props: {
            value: {
                type: String,
            },
            label: {
                type: String
            },
        },
        // setup(props, context) {
        //     const input = (event) => {
        //         console.log('test');
        //         context.root.$emit('input', event.target.value)
        //     }
        //     return {
        //         input,
        //     }
        // },
        methods: {
            input(event){
                this.$emit('input', event.target.value);
            }
        }
    }
</script>

<style scoped>

</style>
```

In this context it does not work at all, now if you destructure the context object and do 
```{ root: { $emit } }```
you will get my error.

Its your library that I am importing to do the setup function, don't think there is another one

**Comment by posva** [comment]
> Its your library that I am importing to do the setup function, don't think there is another one

I meant the problem could come from your code. The error you pasted `Cannot read property 'input' of undefined` doesn't seem to appear in that piece of code you pasted.

You cannot have both a method and a property named the same returned inside of `setup`. They do very different things btw, the one that does `context.root.$emit` will trigger any event attached through `this.$on` at the root of your app while the other one, `this.$emit` will trigger an event listener attached through `@input` on your `TextInput` (which is probably what you want).
So you should use `context.emit` instead:

```js
defineComponent({
  setup(props, { emit }) {
    function input(event) {
      emit(event.target.value)
    }
    return { input }
  }
})
```

BTW, using `defineComponent` you will get type hints, it will help you!

**Comment by matthewhardern** [comment]
@posva thanks you very much greatly appreciated, I get that I can not have both I was simply commenting one in and out. However the information on context is very useful thanks.
