### ISSUE TITLE
Question: How common is to do useFunctions shared between components?

### ISSUE THREAD

**Issue by wizardnet972** [vuejs/composition-api#333]
I'm using vue composition and I sperate the logic from the component. 

For that I create `useXXX` functions. sometimes I want to share this function so every component gets the same result. but the way I'm using it I can't.

For example: I have `use-article.ts` with the following content:

    const useArticle = () => {
      const article = ref(null);
    
      const { route, router } = useRouter();
    
      const articleToLoad = computed(() => route.value.params.articleId);
    
      watch(() => articleToLoad.value, (v) => {
        if (!v) { return; }
    
        ...
        article.value = articleFromApi;
      });
    
      return { article };
    }
    
    In the component I use this function as follow:
    const { article } = useArticle();

But if I run this in another component:
```
const { article } = useArticle();
```
I'll trigger again the `useArticle` and get another instance. 

(Well, After a lot of thinking I decided to wrap the function with memory function for share the instance.)

Why I do it? because I want to keep my components separate as possible. each component can read the route params and do **its own** logic, regardless to another component. 

But, this is best practices? it is "over use"? Should I do it for every component logic in my application? This is "api composition"?

**Comment by pikax** [comment]
If you want to share with multiple components the same instance, you can use [provide/inject](https://vue-composition-api-rfc.netlify.app/api.html#dependency-injection)

**Comment by wizardnet972** [comment]
@pikax Thank you, I'll check this solution :)
