### ISSUE TITLE
[typescript] unit testing, how to get show setup data

### ISSUE THREAD

**Issue by tokidoki11** [vuejs/composition-api#336]
Currently I try to get the attributes inside my vue component while using vue-test-utils
I have included the VueCompositionAPI

here is my code
`
import Vue from 'vue'
import VueCompositionApi from '@vue/composition-api'
Vue.use(VueCompositionApi)

import { shallowMount } from '@vue/test-utils'
import Test from '@/components/Test.vue'

describe('has member', () => {
  const wrapper = shallowMount(VideoPlayer, {
      propsData
    })

 //i want to access value in using wrapper.vm.<val> but typescript return error

});
`

I could set wrapper type as any but i dont think it is good idea

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
