### ISSUE TITLE
UI not updated when change variable in method by accessing from ref

### ISSUE THREAD

**Issue by wizardnet972** [vuejs/composition-api#337]
My foo component have `items` and `ready` variables and `start` method.
```
<div>im foo: {{items}}</div>
```
the `items` and `ready ` are changes after I do some logic and only via `start` method.

**I want to pass the items using ref instance and not by props** because I want to do some logic and calculation which not fit to `props` and `watch` and `computed`.

So, in my app component I invoke the `start` method by access to `foo` instance. ( `vm.$refs.fooRef.start({ items: [1, 2, 3, 4] });` )

The `start` is invoked and change the `items` variable (inside `foo`).

The `ready` variable is updated as expected but the problem is  **`items` doesn't updated in the ui.**

Here I made an example of the problem in [codesandbox.io](https://codesandbox.io/s/vue-composition-ref-95exo?file=/src/main.js)

**What is expected?** 
 `foo` should be display [1,2,3,4]

**What is happens?**
 `foo` display empty array.

Why vue doesn't update the items variable? something broken? and how to fix that?

**Comment by wizardnet972** [comment]
@posva  my mistake! didn't see the names (`items`) are the same.

**Comment by posva** [comment]
Right, variable shadowing 🤦‍♂️
