### ISSUE TITLE
Feature request: reactivity-aware proxy

### ISSUE THREAD

**Issue by MartinMalinda** [vuejs/composition-api#339]
I was thinking how could I implement a `useLocalStorage` hook in the most user friendly way. The most convenient usage would be like so:

```ts
setup() {
const ls = useLocalStorage();
console.log(ls.name);
ls.foo = 'bar'; // saved to LS

// or even pass to template, v-model, etc.
return {
  ls
}
}
```

`ls` here would be a reactive object that would pick up its state from localStorage and when mutated, it would also persist to localStorage.

I could probably create this with combination of `new Proxy()` and `reactive()`. But I have to target IE11 and since Vue already has some workarounds how to target IE11 it would be great if those would be exposed.

This is how it could look like then:

```ts
export default function useLocalStorage() {
  const rootKey = '_appState';

  function getState() {
    const state = localStorage.getItem(rootKey);
    try {
      return state && JSON.parse(state);
    } catch (e) {
      console.error('could not parse', state);
    }
  }

  if (!getState()) {
    localStorage.setItem(rootKey, '{}');
  }

  return proxy({
    get(key) {
      return getState()[key];
    },
    
    set(key, value) {
      const newState = {
        ...getState(),
        [key]: value
      };
      localStorage.setItem(rootKey, newState);

      // return newState? return value?
    }
  });
}
```

**Comment by posva** [comment]
Unfortunately, there is no such `proxy` magic that could work on IE 11. You would have to create an api with `get` and `set` methods to work around it. Even worse, `Vue.set` doesn't work on `reactive` objects (https://github.com/vuejs/composition-api/issues/334)

**Comment by MartinMalinda** [comment]
Perhaps it would work if the keys were known before hand? It would work for the localStorage usecase.

But I see, thanks.

**Comment by posva** [comment]
yes, adding the keys beforehand already works! You can totally design an API around that
