### ISSUE TITLE
Computed property not unwrapped in template

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/composition-api#342]
Using the Vue i18n library we want our navigation links to translate when the language is changed. This works fine when using a `computed` property:

```js
export default defineComponent({
  setup(_, context) {
    const mainNavigationLinks = reactive([
      {
        label: computed(() => context.root.$t('navigationMenu.home')),
        name: 'home',
        to: '/',
      },
    ])

   return { mainNavigationLinks }
  },
```

To use this in the `<template>` we need to add `.value` to the label:

```js
<template>
   <q-item-section>{{ link.label.value }}</q-item-section>
```

It says in the [docs](https://vue-composition-api-rfc.netlify.app/#api-introduction):
> In addition, when a ref is nested as a property under a reactive object, it is also automatically unwrapped on access:

Am I missing something obvious here? Thank you for your help.

**Comment by posva** [comment]
It's because you have an array. Unwrapping in arrays lead to other problems when using find and n'y other comparison method

**Comment by pikax** [comment]
That's a plugin limitation: 
[Should not use `ref` in a plain object when working with `Array`](https://github.com/vuejs/composition-api#should-not-use-ref-in-a-plain-object-when-working-with-array)

**Comment by DarkLite1** [comment]
Thank you for the help. So in this case it might be better to simply use one object containing multiple objects instead of an `array`. I'll give that a go, thanks :)

**Comment by DarkLite1** [comment]
In the end I settled for [using an object instead](https://vuejs.org/v2/guide/list.html) of an `array` like this::
```typescript
import { computed, reactive, SetupContext, ref } from '@vue/composition-api'

export const useApplications = (root: SetupContext['root']) => {
  const applications = reactive({
    1: {
      name: ref(root.$t('application.name')),
    },
    2: {
      name: ref('test'),
    },
  })

  return {
    applications: computed(() => applications),
  }
}
```
Then it can simply be used like this:
```html
<template>
  <q-page padding>
    <div class="q-pa-md row items-start q-gutter-md cursor-pointer">
      <app-application-card
        v-for="(card, id) in applicationCards"
        :key="id"
        :name="card.name"
        :shortDescription="card.shortDescription"
        :formComponentName="card.formComponentName"
      />
    </div>
  </q-page>
</template>
```
```typescript
<script lang="ts">
import { defineComponent, reactive } from '@vue/composition-api'
import { useApplications } from 'src/composables/useApplications'

export default defineComponent({
  setup(_, { root }) {
    const { applications: applicationCards } = useApplications(root)

    return { applicationCards }
  },
  components: {
    appApplicationCard: () => import('src/components/ApplicationCard.vue'),
  },
})
</script>
```

Advantages:

* Reactivity is preserved
* A unique `id` is available for each application
* No errors in vscode

On a side note, it makes no difference in using `ref()` or `computed()` for the translated `name` string. Both work fine. In the end we make it `read only` by exporting it as a `computed` property.

Hope this helps others who end up here with similar questions.
