### ISSUE TITLE
Volunteer to help maintaining this project

### ISSUE THREAD

**Issue by antfu** [vuejs/composition-api#343]
This library as a very good transition for users from Vue 2 to Vue 3's new API, does not seem to be actively maintained from my perspective. Especially at this moment when Vue 3 is already in beta stage for some while, this library has a lot of misalignment with the latest API specs.

**Me @antfu, volunteer myself to help with maintaining this project**. 

Some relevant info of me:
- [Contributed to this project several times](https://github.com/vuejs/composition-api/graphs/contributors) and upcoming #300
- Author of [VueUse](https://github.com/antfu/vueuse), a collection of compositional functions for Vue 2 and 3.
- One of the maintainers of [@wenyan-lang](https://github.com/wenyan-lang)
- I love Vue and the Composition API!

It would be my great pleasure if I am able to do some help with this project. Thanks!

Sorry to disturb you, but please allow me to use the mention here.
@yyx990803 @liximomo @LinusBorg

**Comment by yyx990803** [comment]
This is great, thank you @antfu! I've sent an invite.

**Comment by antfu** [comment]
Thank you!
