### ISSUE TITLE
[bug] typing for `reactive` w/ `computed` inside

### ISSUE THREAD

**Issue by beeplin** [vuejs/composition-api#346]
The following reactive `state1` with a computed `state1.b` referring to `state1.a` cannot be correctly typed:  
![image](https://user-images.githubusercontent.com/13058150/83376208-0b062d00-a404-11ea-9146-51c015a1eee7.png)

Now we have to use the following workaround to make type inference work:

![image](https://user-images.githubusercontent.com/13058150/83376187-fa55b700-a403-11ea-95b5-54f09dde65d8.png)

**Comment by antfu** [comment]
I am not sure if Typescript is capable to handle this recursive reference.

A workaround could be something like your second screenshot or assign a type explicitly:
```ts
interface StateType {
  a: number, 
  b: number 
}

const state1: StateType = reactive({
  a: 1,
  b: computed(() => state1.a + 1)
})
```

**Comment by pikax** [comment]
Currently there's no way to do that: https://github.com/vuejs/vue-next/issues/963

This is a typescript issue not vue types
