### ISSUE TITLE
onBeforeUnmount and onUnmounted don't work on hot reload

### ISSUE THREAD

**Issue by crutch12** [vuejs/composition-api#351]
I use vue-loader which includes hot reload.

I call onBeforeUnmount/onUnmounted in setup function and when I
- switch page with vue-router - it calls hooks fine
- hot reload - it doesn't call hooks

Hooks beforeDestroy/destroyed always works fine.

**Comment by crutch12** [comment]
Tried to give reproduction link, but it works fine on CodeSandbox:
Vue cli - https://codesandbox.io/s/nameless-sun-24gvm?file=/src/components/Test.vue
Nuxt (SPA) - https://codesandbox.io/s/affectionate-johnson-ev1w3?file=/components/Logo.vue

Probably the problem is somewhere in my project... I'll try to find it out later

**Comment by antfu** [comment]
Closing for now. Feel free to reopen it if you made the reproduction. Thanks.
