### ISSUE TITLE
Cannot use composition package

### ISSUE THREAD

**Issue by noook** [vuejs/composition-api#356]
I wrote a package to deal with paginated APIs [here](https://github.com/noook/vue-composition-paginate/blob/master/src/index.ts). Unfortunately, when I use it I have the following error in my console and the component cannot render.

```
[vue-composition-api] must call Vue.use(plugin) before using any function."
```
I can use the composition API nicely, but when I call `usePaginate` I get the error. Do I have to call `Vue.use(CompositionApi)` in my ilbrary aswell ?

```js
import { defineComponent, reactive } from "@vue/composition-api";
import usePaginate from "vue-composition-paginate";

export default defineComponent({
  name: "Results",
  setup(props, { root }) {
    const paginate = usePaginate({
      instance: root.$axios,
      url: "/results/project/" + root.$user.getProject().id,
      dataTransformer: response => response.data,
      totalPageTransformer: response => response.pagination.totalPage
    });

    return {
      ...paginate,
    };
  }
}
```

**Comment by antfu** [comment]
Since your package is a utility function, I think the `Vue.use` is better to be called on the user side.

**Comment by pikax** [comment]
`Vue.use` needs to be called in the user side, check some implementations: https://github.com/kefranabg/awesome-vue-composition-api#-composition-api-functions

**Comment by noook** [comment]
It is already called on the user side. I can make use of the Composition API but not of my package. That's what I don't get. This is also the first thing I `use` in `main.js`

**Comment by pikax** [comment]
Make sure the user side has the **same** `@vue/composition-api` version as your package. 

It is recommended using `peerDependencies` for `@vue/composition-api`

**Comment by noook** [comment]
@pikax This is my very first library and thus don't know a lot about those. I had a peek at the link you gave me, and inspected packages. Should I add `axios` to `peerDependencies` aswell, and `vue` in `devDependencies` ?

I'll bump the dependency version and try again with the same versions.

**Comment by pikax** [comment]
> Should I add `axios` to `peerDependencies` aswell, and `vue` in `devDependencies` ?

It depends if you expect to people use your library without concerning if you use axios or not. Axios plays nicely with multiple versions. 

One command I find quite helpful to check that issue is: `yarn why @vue/composition-api`, this should only show one version, if shows more you will have issues.

**Comment by noook** [comment]
Axios is listed in dependencies only to import the `AxiosInstance` type.

Tried your command:
Not sure this is the expected output
![image](https://user-images.githubusercontent.com/19751938/84047196-4d52df80-a9ab-11ea-9482-15d10f08df72.png)

**Comment by pikax** [comment]
That command is more for debug your dependencies, you need to use `yarn` instead of `npm`, I don't know what the npm equivalent 😅

**Comment by noook** [comment]
Alright. I fixed the dependencies, and upgraded `@vue/composition-api` to `0.6.1` and it worked like a charm. 😄 

(I generated the `yarn.lock` to use your command)
