### ISSUE TITLE
toRefs(props) throws warning

### ISSUE THREAD

**Issue by rijkvanzanten** [vuejs/composition-api#357]
Heya! I just updated from 0.5.0 to 0.6.1 and noticed a new warning popping up:

```
[Vue warn]: toRefs() expects a reactive object but received a plain one.
```

I noticed this is caused by code like

```ts
export default defineComponent({
  props: {
    whatever: String,
  },
  setup(props) {
    const { whatever } = toRefs(props);
  }
});
```

That pattern has been working wonderfully before, and I was under the impression that `props` was in fact a reactive object, which in turn would mean `toRefs(props)` should be valid. 

Is this a bug, or am I misunderstanding the reactivity of the `props` parameter?

**Comment by pikax** [comment]
> Is this a bug, or am I misunderstanding the reactivity of the `props` parameter?

It shouldn't `warn` when using `props`, `props` are reactive. I will create a PR to fix that

**Comment by rijkvanzanten** [comment]
Thanks for the impressively fast turnaround on this @pikax & @antfu! Y'all rock ❤️
