### ISSUE TITLE
lack of life cycle method `serverPrefetch`

### ISSUE THREAD

**Issue by TooBug** [vuejs/composition-api#36]
There is no life cycle method `serverPrefetch` , so can not be fully used on SSR.

In order to support SSR, the only choice is to remain `serverPrefetch()` method. And then, all methods and data properties used by `serverPrefetch()` has to be remained. And then, very little code can be ported into `setup()` method. And the code is in "mixed style", very ugly.

**Comment by LinusBorg** [comment]
I think this is a limitation of this plugin in Vue 2. Making the new API work with SSR will require change to internals that we will do in Vue 3, but not Vue 2.

**Comment by posva** [comment]
@liximomo if this is indeed a limitation we can label it as wont fix and close it

**Comment by liximomo** [comment]
@posva I think It's feasible. Assigning the param of `onServerPrefetch` to `$options.serverPrefetch` should be enough.

**Comment by sh7dm** [comment]
not sure how to test this one, but I can implement it.

**Comment by TooBug** [comment]
#80 

There exists a pull request.
