### ISSUE TITLE
Watcher doesn't fire for initial prop value anymore

### ISSUE THREAD

**Issue by rijkvanzanten** [vuejs/composition-api#362]
I have some watchers based on a prop as follows:

```ts
export default defineComponents({
  props: {
    collection: String,
  },
  setup(props) {
    watch(() => props.collection, doSomething);
  }
});
```

In 0.5.0, this would fire on creation, with a previous value of `null`, meaning that that watcher would fire on first load, and whenever the `collection` prop changes. 

In 0.6.1, it only seems to fire when the prop changes.

Is this new behavior the expected behavior? 

_I thought this was caused by the breaking change mentioned in the release (from https://github.com/vuejs/composition-api/issues/266), but seeing I didn't rely on `lazy` before, I don't think it's the same thing._

**Comment by antfu** [comment]
Yes. With the lastest RFC, the `watch` is "lazy" by default now. If you want it to fire along with the initial declaration, you would need to specify `immediate: true`.

**Comment by rijkvanzanten** [comment]
Ah I didn't realize `lazy` was `false` by default before. Thanks 👍
