### ISSUE TITLE
Global TSX attributes (key, ref, on, class, etc.) fail type check

### ISSUE THREAD

**Issue by LachlanStuart** [vuejs/composition-api#363]
Vue defines `key` and `ref` as [special attributes](https://vuejs.org/v2/api/#Special-Attributes), which can be used with all VNodes. However, the type definitions in `@vue/composition-api` don't allow TSX to use these attributes, unless they're explicitly defined as props in the component definition. The workaround of declaring them as props can't be used with inferred prop types, because Vue emits a warning a component contains declarations for "key" or "ref" props.

There are also many other special attributes that are handled by Vue or by createElement, such as `on` (event handlers that are wired up by `createElement`) and `class` (which Vue merges into the component's DOM node's `class`, unless `class` has been defined as a prop. Related issue #173 ). Vue's typings suggest that `createElement` can receive all the fields defined in [`VNodeData`](https://github.com/vuejs/vue/blob/982d5a492fb95577217e2dacaa044eabe78a8601/types/vnode.d.ts#L41-L66), even if they're not defined as props.

Minimal reproduction:

```tsx
import { createComponent } from '@vue/composition-api'

const Item = createComponent({
  props: { text: String },
  render(h, { props }) {
    return <div>{props.text}</div>
  },
})

const List = createComponent({
  render(h, { props }) {
    const items = ['a', 'b', 'c']
    return <div>{items.forEach(item => <Item key={item} ref={item} text={item} />)}</div>
  },
})
```

Output:
```
Error:(17, 46) TS2322: Type '{ key: string; ref: string; text: string; }' is not assignable to type 'ExtractPropTypes<{ text: StringConstructor; }, false>'.
  Property 'key' does not exist on type 'ExtractPropTypes<{ text: StringConstructor; }, false>'.
// And if "key" is removed, ref causes a similar error:
Error:(17, 46) TS2322: Type '{ ref: string; text: string; }' is not assignable to type 'ExtractPropTypes<{ text: StringConstructor; }, false>'.
  Property 'ref' does not exist on type 'ExtractPropTypes<{ text: StringConstructor; }, false>'.
```

**Comment by antfu** [comment]
Can you share a codesandbox/jsfiddle or Github repo so that we can investigate with your setup? Thanks.

**Comment by pikax** [comment]
I think `TSX` should be handled by `vuejs` not by the plugin

**Comment by LachlanStuart** [comment]
My bad. I was on an old version of `@vue/composition-api`. The issue isn't present in the latest version. Now all unrecognized props (including `key`, `ref` and `class`) seem to be accepted by the type checker without any errors.
