### ISSUE TITLE
About reactive function, It will changes the type of array elements

### ISSUE THREAD

**Issue by JohnZengshi** [vuejs/composition-api#374]
Reactive changes the type of array elements in the state data so that I cannot get elements value！🤔
just like:
<img width="279" alt="WX20200612-105718@2x" src="https://user-images.githubusercontent.com/29040673/84460195-e465b300-ac9b-11ea-8d86-bcbda939a6b9.png">
<img width="368" alt="WX20200612-105743@2x" src="https://user-images.githubusercontent.com/29040673/84460203-edef1b00-ac9b-11ea-9e38-c1837eb0f2b2.png">

**Comment by antfu** [comment]
Can you show me the code? Thanks.

**Comment by JohnZengshi** [comment]
> Can you show me the code? Thanks.

```typescript
```

**Comment by JohnZengshi** [comment]
> Can you show me the code? Thanks.

```typescript
  interface _state {
    shopList: Array<{ value: string; label: string }>;
  }
  const state: _state = {
    shopList: [{ value: "", label: "" }]
  };

  state.shopList  // => (property) shopList: {value: string;label: string; }[]
  reactive(state).shopList  // => (property) shopList: string[]
```
<img width="318" alt="WX20200612-160458@2x" src="https://user-images.githubusercontent.com/29040673/84480116-a2059b80-acc6-11ea-992c-b67f26f8948e.png">

<img width="379" alt="WX20200612-160534@2x" src="https://user-images.githubusercontent.com/29040673/84480140-aaf66d00-acc6-11ea-9002-691ffc55c1ba.png">


After using Reactive
I can't get it's elements properly 😑

**Comment by jacekkarczmarczyk** [comment]
I guess you're on old version, try upgrading to 0.6.3

**Comment by JohnZengshi** [comment]
> I guess you're on old version, try upgrading to 0.6.3

Upgrade to 0.6.3, problem solved, thanks！
