### ISSUE TITLE
Idea: "next" tag for npm package redirecting to "vue-next"

### ISSUE THREAD

**Issue by antfu** [vuejs/composition-api#377]
I would propose to publish `next` tag for this package npm for this package that redirecting to `@vue/runtime-core` from `vue-next`. So that when users eventually upgrade to Vue 3, updating this package and things just work. (and then users can gradually replace the usage of this package to `vue`) 

Furthermore, this could also benefit library/utils users to share composable functions work for both versions much easier. 

### In Vue 3:
```ts
import { ref, reactive } from "@vue/composition-api"
```
Will just equivalent to 
```ts
import { ref, reactive } from "vue"
```

And after Vue 3 released, we can add a `postinstall` warning in `next` for developers to migrate the changes.

**Comment by jacekkarczmarczyk** [comment]
What if there will be another `next` version (2.0 or whatever) of the plugin?

**Comment by antfu** [comment]
My plan would be:

"2.x" for this plugin becoming production-ready. (`latest` tag)

"3.x" for this plugin to redirecting to "vue-next". (`next` tag)

and for the current phase, it would go with something like `3.0.0-alpha.1(next)`

**Comment by pikax** [comment]
I don't agree, `vue-next` is a completely different framework, I hope people using `@vue/composition-api` are aware this is vue-2 only.

**Comment by antfu** [comment]
Yeah, you are right. Migration would be a simple replace-all. Maybe it's no need to make things complicated. Thanks. Closing.
