### ISSUE TITLE
watchEffect getter work problem

### ISSUE THREAD

**Issue by WARJY** [vuejs/composition-api#388]
```
const data = ref([1,1,1,1,1])
const data2 = ref([])

watchEffect(()=>{
    data2.value = data.value.slice(1,1)
},{
    flush: "sync"
})
```

```
vue.runtime.esm.js?2b0e:1888 RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at classify (vue.runtime.esm.js?2b0e:610)
    at formatComponentName (vue.runtime.esm.js?2b0e:648)
    at eval (vue.runtime.esm.js?2b0e:685)
    at Array.map (<anonymous>)
    at generateComponentTrace (vue.runtime.esm.js?2b0e:683)
    at warn (vue.runtime.esm.js?2b0e:614)
    at logError (vue.runtime.esm.js?2b0e:1884)
    at globalHandleError (vue.runtime.esm.js?2b0e:1879)
```
when watchEffect getter function include some function who return a anonymous variable（such as Array.slice）,it will cause a infinity loop

**Comment by posva** [comment]
This is expected as you are modifying the `data` inside of the function that watches it. Use a `watch` (https://composition-api.vuejs.org/api.html#watch) instead to control what should be observed

**Comment by WARJY** [comment]
as i know , ```slice``` will not modify the source array , and if i use it this way, it will work
```
const data = ref([1,1,1,1,1])
const data2 = ref([])

watchEffect(()=>{
    data2.value[0] = data.value[0]
},{
    flush: "sync"
})
```
and i'm confused about when to use watchEffect and when to use watch

**Comment by posva** [comment]
Ah, I read `splice`

**Comment by WARJY** [comment]
> Ah, I read `splice`

first time commit issue, XD, it feels good to commucation with developer ⁄(⁄ ⁄ ⁄ω⁄ ⁄ ⁄)⁄

**Comment by pikax** [comment]
Thank you for raising it

Looking into this, as for now I recommend using `watch` until this is fixed :)

**Comment by WARJY** [comment]
> Thank you for raising it
> 
> Looking into this, as for now I recommend using `watch` until this is fixed :)

okkkkkkk,XD
