### ISSUE TITLE
How to access the element (aka $el) reference?

### ISSUE THREAD

**Issue by thenikso** [vuejs/composition-api#39]
This is more a clarification on how would one (or should one?) access what's now presented as the `this.$el` HTML root template element.

Have I missed it in the RFC?

My workaround is to manually add an `ref="el"` to the root template element and use `context.refs.el` in, say, the `onMounted` callback.

**Comment by PaulKujawa** [comment]
`context.refs.el` gave me the vue component instance. I had to go with `context.refs.$el` for the object of type `Element`. but that worked for now 🙌

**Comment by kidonng** [comment]
TL;DR: you can access `this` in lifecycle functions such as `onMounted`, see [demo](https://stackblitz.com/edit/vue-function-api-39).

I think `vue-function-api` provides the `context` parameter in order to to make up for the absence of `this`, which is slightly different from the RFC - but that doesn't mean you can never get `this` (see above).

**Comment by liximomo** [comment]
> My workaround is to manually add an ref="el" to the root template element and use context.refs.el in, say, the onMounted callback.

It's fine to use ref.

**Comment by MatanYadaev** [comment]
@kidonng I have a question, how should I access `$route` inside `computed`? Should I just not use arrow function? Should I declare some `vm` variable? Direct access to `Vue`?

**Comment by beeplin** [comment]
```js
setup(props, context) {
  const a = computed(() => context.root.$route)
}
```

@MatanYadaev

**Comment by MatanYadaev** [comment]
@beeplin Thanks!

**Comment by tiepnguyen** [comment]
@thenikso anytime I need to access `$el` or `$children` (which I usually do), I have to use onMounted function (not arrow function) in order to have `this`

```js
onMounted(function() {
  this.$el
  this.$children
})
```
I cannot `ref` to children elements in case it's a `slot`

Any better idea, guys?

**Comment by kidonng** [comment]
@tiepnguyen I can't get you. `context.slots` doesn't do?

**Comment by pikax** [comment]
You can access `refs` using `ref` https://composition-api.vuejs.org/api.html#template-refs

I will close this issue, if you need please reopen or create a new issue.

---

Remember you use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/).

**Comment by SeyyedKhandon** [comment]
@pikax I'm trying to access the dom element using ref as the docs says, but i could only get the element using `$el` like       

```
  const dropdown = ref(null as unknown) as Ref<HTMLElement>;
const dropdownHeight = dropdown.value.$el.clientHeight;
```

which has a typescript Error. what is the rightway in to access it?

**Comment by pikax** [comment]
@SeyyedKhandon  you don't need `$el`

**Comment by SeyyedKhandon** [comment]
@pikax here is the type error: which it seems to work with: `  const dropdown = ref(null as unknown) as Ref<HTMLElement>;`

```
64:22 Conversion of type 'Ref<null>' to type 'Ref<HTMLElement>' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'null' is not comparable to type 'HTMLElement'.
    62 |   },
    63 |   setup(_props, context) {
  > 64 |     const dropdown = ref(null) as Ref<HTMLElement>;
       |                      ^
    65 |     const dropdownHeight = dropdown.value.clientHeight;
```

also, I found out that when using ref on vue component, it will return a Vue instance which has reference to its dom with `dropdown.value.$el`, and when using on the raw HTML element, it will return the element itself.(there were nothing about this in the docs)

**Comment by pikax** [comment]
Typescript is right, you create a `ref` with a value of `null` and then you assign the type that doesn't overlap with `null`

This is more correct, because the `ref` will only be assigned after `mount` you will need to do null checks.
`const dropdown = ref(null) as Ref<HTMLElement | null>;`

**Comment by jacekkarczmarczyk** [comment]
@pikax why not just `const dropdown = ref<HTMLElement>()`? Also as I understand `dropdown` is not a native `select`, so it should be more like `const dropdown = ref<SomeComponentOrGenericVueInstanceClass>()`
