### ISSUE TITLE
toRaw does not undo props auto unwrapping

### ISSUE THREAD

**Issue by vmihailenco** [vuejs/composition-api#392]
composition-api v0.6.5 toRaw does not unwrap reactive:

```js
toRaw(reactive({ "ref": ref(1) }))
```

In vue-next same code works as expected.

**Comment by antfu** [comment]
It seems to work for me: https://codepen.io/antfu/pen/zYrZdbQ

Can you share a reproduce demo?

**Comment by vmihailenco** [comment]
Looks like the problem with props auto unwrapping - https://codepen.io/vmihailenco/pen/wvMJxYB
