### ISSUE TITLE
Auto unwrapped template props are not considered reactive by toRefs

### ISSUE THREAD

**Issue by vmihailenco** [vuejs/composition-api#393]
Following code

```js
toRefs(props.foo)
```

logs following error

```
toRefs() expects a reactive object but received a plain one
```

Even though `props.foo` *is* a reactive object because of template auto unwrapping and it makes sense to use `toRefs` on such props.

Same code works fine with vue-next.

**Comment by jacekkarczmarczyk** [comment]
?
https://codepen.io/jkarczm/pen/qBbrrgB?editors=0011

**Comment by antfu** [comment]
@vmihailenco Can you share more details about your props?

**Comment by vmihailenco** [comment]
Done - https://codepen.io/vmihailenco/pen/bGEqjQd
