### ISSUE TITLE
Removed "ref()" overload which allowed an easy way to specify it as "surely not undefined"

### ISSUE THREAD

**Issue by IlCallo** [vuejs/composition-api#407]
In version `0.5.x`, `const compRef = ref<MyComponent>(undefined)` return type was `Ref<MyComponent>`.
In version `0.6.x`, the same code now return type `Ref<MyComponent | undefined>`.

This was a comfy way to type references **we knew** would be initialized later on.

I think previous behaviour was unintended, but overall quite good, as we cannot use `!` TS operator on refs like `const compRef = ref<MyComponent>()!`, because they wrap the inner type.

The only solution now is to cast them as `const compRef = ref() as Ref<MyComponent>`

This is expecially painful for those template refs which are only used into the template itself, as Vetur won't understand TS syntax into `<template>` section (not comments disabling ESLint warnings).

Any possibility this feature could come back in the future as shortcut for devs to say TS "we know what we're doing"?

A possible other way is to use the provided type to make a conditional check with a marker wrapper type.
For example, it's possible to detect when the provided type is wrapped into build-in `Required` type and avoid adding `undefined` to resulting ref type
`const compRef = ref<MyComponent>()` -> `Ref<MyComponent | undefined>`
`const compRef = ref<Required<MyComponent>>()` -> `Ref<MyComponent>`

Yet, adding `Required` is pretty verbose too (but at least it isn't a type cast)

**Comment by antfu** [comment]
I am pretty sure it works the same as Vue 3. If you assign a value to the `ref()` it the `undefined` won't be included - `ref<number>(0)` -> `Ref<number>`, `ref<number>()` -> `Ref<number | undefined>`

And as for the template refs, it IS `undefined` before the component mounted. I think the current behavior is expected. Changing it as you describe might confuse other users. If you do like the Ref to be non-undefined, I think you already find the workaround :)

Thank you for the proposal. But sorry I think I am going to close it for now.

**Comment by IlCallo** [comment]
No problem, was mostly to make other people aware of this change
