### ISSUE TITLE
Function Based Prop issues

### ISSUE THREAD

**Issue by brantcdolling** [vuejs/composition-api#410]
I have searched for any issues that pertain to this, but I am having issues with my props not being reactive when passed through to a feature based function. 

For Example: 
```
function useNameTitle( props ) {
  const title = computed(() => props.name );

  return {
    title,
  }
}

export default {
  props: {
    name: String
  },
  setup( props ) {
    const nameTitle = useNameTitle( props );

    return {
      ...toRefs( nameTitle ),
    }
  }
}
```

I have also tested pulling the props out in the setup function and putting them in `ref` objects, and the reactiveness still doesn't go past the setup function to the feature function.

**Comment by posva** [comment]
You can simply spread nameTitle without calling toRefs since it’s already an object of refs

**Comment by pikax** [comment]
You don't need `toRefs`

`toRefs` should only be used on `reactive` objects but you are returning a plain object on `useNameTitle`.

A warning is being logged: ` toRefs() expects a reactive object but received a plain one.`

In your example you can remove `toRefs` it should work.

**Comment by brantcdolling** [comment]
Sorry that was a type in my simplified version. With the toRefs removed when the props change it is still no reactive.

**Comment by pikax** [comment]
Works for me: https://codesandbox.io/s/amazing-turing-61hgn?file=/src/App.vue

**Comment by brantcdolling** [comment]
I am on version 0.6.5 so let me try update to 0.6.7.

**Comment by brantcdolling** [comment]
So I think I drilled down the issue I was having. The parent component wasn't sending a reactive object down to the child component. Also when I was declaring the prop in the feature function I wasn't declaring it as reactive. Once I did those two things it started to work. Thanks for the help the codepen was very helpful.
