### ISSUE TITLE
Impossible to use TSX after upgrading to 1.0.0-beta1

### ISSUE THREAD

**Issue by lonk** [vuejs/composition-api#421]
Hi,

After upgrading composition-api to 1.0.0-beta, I have this issue when using TSX:
<img width="766" alt="Capture d’écran 2020-07-03 à 21 48 02" src="https://user-images.githubusercontent.com/2729398/86494787-e096ef00-bd76-11ea-8ae4-3d9ff43b89dc.png">

It even happens with a component as simple as:
`export default {
    name: 'App',

    setup() {
        return () => <div></div>
    }
};`

Is there any breaking changes I missed about that ?

Thank you !

**Comment by antfu** [comment]
Yes. It's probably because that `createElement` renamed to `h`.

/cc @luwanquan could you help update the plugin toward the changes in 1.0? Thanks.

**Comment by antfu** [comment]
It already has a PR https://github.com/luwanquan/babel-preset-vca-jsx/pull/12

**Comment by luwanquan** [comment]
Late update, the plugin has been updated to v0.3.6
