### ISSUE TITLE
can`t responseable to reactive after upgrade from v1.0.0-beta.1 to v1.0.0-beta.2

### ISSUE THREAD

**Issue by jasonandjay** [vuejs/composition-api#431]
After upgrading composition-api to 1.0.0-beta.2, I have this problem when my view canot get reposneable from my reactive data;
This is my code
```js
<template>
	<view class="one">
		<div class="nav">
                        <span 
			  v-for="(item,index) in data.title" :key="index"
			  @click="tab(index)"
			  :class="ind === index? 'active': ''" 
			>
			  {{item}}
			</span>
                 </div>
	</view>
</template>

<script lang="ts">
	import Vue from 'vue';
	import { defineComponent, reactive, Ref, ref } from '@vue/composition-api'
	export default defineComponent ({
	     setup(){
			 let ind:Ref<number> = ref(0)
			 let data = reactive({
				 title:["全部","Javascript","React","Vue","小程序","项目","webpack","布局","多端","业务场景","TypeScript","算法","兼容","node","工具","服务端","编程题"]
			 })
			 //tab切换
			 function tab(index:number){
				 console.log(index)
				 ind.value = index
			 }
			 return {
				 data,
				 ind,
				 tab
			 }
		 }
	})
</script>
```
Expected a title list with tag span, but now get nothing.
env:
 "@dcloudio/uni-mp-weixin": "^2.0.0-alpha-28020200701002",
 "vue": "^2.6.11",
 "@vue/composition-api": "^1.0.0-beta.2",
 "typescript": "^3.0.0"

**Comment by antfu** [comment]
Tried with your code in vue-cli and it works well. Can you double-check if there is anything related to your app environment or other dependencies?

**Comment by cyocun** [comment]
I'm in the same situation.
`yarn create nuxt-app` with nuxtjs in a typescript configuration I created it.
plugins, etc., and tried the following components, but the following An error message is displayed.

```html
<template>
  <div>{{ result }}</div>
</template>

<script lang="ts">
import { defineComponent, ref } from '@vue/composition-api'

export default defineComponent({
  setup() {
    const result = ref('abc')
    return {
      result,
    }
  },
})
</script>
```
> [Vue warn]: Property or method "result" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

"nuxt": "^2.13.0"
"@vue/composition-api": "^1.0.0-beta.2"
"typescript": "3.8.3"

**Comment by antfu** [comment]
Did you install this plugin by `Vue.use(VueCompositionAPI)`?

**Comment by cyocun** [comment]
Oh, I'm sorry.
I had the plugin installed, but it seems that I renamed nuxt.config.js to nuxt.config.config.ts, so it looks like config wasn't loaded because I renamed nuxt.config.js to nuxt.

I changed the name back to nuxt.config.js and it worked fine.
Thank you.🙃

**Comment by fangyang921017** [comment]
@jasonandjay I think you should pass `()=>tab(index)` to `@click`

**Comment by jasonandjay** [comment]
> @jasonandjay I think you should pass `()=>tab(index)` to `@click`

no, the same result, maybe ites the problem of uni-app, it works in other project

**Comment by jasonandjay** [comment]
> Tried with your code in vue-cli and it works well. Can you double-check if there is anything related to your app environment or other dependencies?

in vue-cli is ok，its not responsable in uni-app, wxapp

**Comment by pikax** [comment]
@jasonandjay Are you still having issues? If so can you provide a reproduction repo or codesanbox?

**Comment by jasonandjay** [comment]
> @jasonandjay Are you still having issues? If so can you provide a reproduction repo or codesanbox?

sorry, i tried, but its a project with clound function, before reproduction need to build cloud db & function, so troublesome
and i downgrade to beta1, its work
