### ISSUE TITLE
Route guards - beforeRouteLeave not working inside a component

### ISSUE THREAD

**Issue by LorenRd** [vuejs/composition-api#433]
![image](https://user-images.githubusercontent.com/11414362/86903963-55b84a80-c110-11ea-8a16-1c1b0cb4cc0a.png)
Using nuxt and composition-api plugin.

The execution is not going inside, beforeRouteLeave is never called even if is a console.log it doesn't work.
The behaviour is the same if is not async.

**Comment by BradenM** [comment]
I am also witnessing this behavior while using the `composition-api` _without_ nuxt.

**Comment by posva** [comment]
`beforeRoute*` guards must go on view components that are associated with a route. You cannot add it to `root`

Closing as no reproduction has been provided and the problem likely comes from what I said above
