### ISSUE TITLE
A default setter without effect for computed properties ?

### ISSUE THREAD

**Issue by Lyokolux** [vuejs/composition-api#434]
I am currently using computed properties without cache and typescript. So as the [documentation](https://composition-api.vuejs.org/api.html#computed) says, an object is passed to `computed()`:
```typescript
    const plusOne = computed({
      cache: false,
      get: () => count.value + 1,
      set: (val) => {
        count.value = val - 1;
      }
    });
```
However a setter function must still be passed to the computed property, even if the property `plusOne` is not reassigned.

Which setter should then be passed to follow the Vue best practices ? For now, this make the work :
```typescript
    const plusOne = computed({
      cache: false,
      get: () => count.value + 1,
      set: (value) => plusOne
});
```
The setter has no effect as expected.
Is it a good thing ?

**Comment by pikax** [comment]
There's no `cache` on `computed`.

On the link you provided:
```ts
const count = ref(1)
const plusOne = computed({
  get: () => count.value + 1,
  set: val => {
    count.value = val - 1
  }
})

plusOne.value = 1
console.log(count.value) // 0
```

[Example](https://github.com/vuejs/composition-api/blob/master/test/apis/computed.spec.js#L37-L41)




> However a setter function must still be passed to the computed property, even if the property `plusOne` is not reassigned.

If you want to have a writable computed you need to pass the `set`.

```ts
      set: (value) => plusOne
``` 

This is only returning `plusOne` not assigning the value to `count.value`.

---

Please remember you can post questions on [Forum](https://forum.vuejs.org/) or [Discord](https://vue.land)
