### ISSUE TITLE
Export utility types

### ISSUE THREAD

**Issue by NickBolles** [vuejs/composition-api#435]
I have a wrapper function that I would like to take a typed `SetupFunction` type, but at some point recently `SetupFunction` stopped being exported. I don't see any issues with exporting utility types like that. Can it be added to the exported types again?

**Comment by antfu** [comment]
It's internal type and you shouldn't rely on it as it isn't a part of Vue 3 as well. Any reason you want to have access to it?

**Comment by NickBolles** [comment]
Actually the reason I wanted access to it was resolved by `nuxt-composition-api` which added `onGlobalSetup` I'll close this now.
