### ISSUE TITLE
Where is the cloneVNode function?

### ISSUE THREAD

**Issue by ddenev** [vuejs/composition-api#437]
Evan You says we can use the cloneVNode function - https://github.com/vuejs/vue-next/issues/815#issuecomment-598255232 - but I cannot find it in the composition API.

Tried `import { cloneVNode } from 'vue'` and `import { cloneVNode } from '@vue/composition-api'` but none works.

I'm using Vue 2 with the `@vue/composition-api` package so what is the proper way to import the `cloneVNode` function?

Thank you.

**Comment by pikax** [comment]
That's quite low-level API, I've created a draft PR, but the implementation is hacky since vue 2.x doesn't expose this internals in a good way. 

Even if it gets ported there will be some limitations.

**Comment by pikax** [comment]
`cloneVNode` and other low level APIs are not part of the composition-api, so they won't be supported here.

Also the vdom of v2 is different than v3 making the port of this api not ideal.
