### ISSUE TITLE
`onUnmounted` called before transition is complete

### ISSUE THREAD

**Issue by dougalg** [vuejs/composition-api#443]
It seems that when using `<transition>` the `onUnmounted` hook gets called at the same time as the transition is started. This is confusing to me, as the element is still completely in the DOM, so I am surprised that it counts as "unmounted" already.

I suppose the alternative to use the various transition callbacks to handle this use case, but I'm mostly just curious if this is expected behaviour or not. EDIT: The transition callbacks would make my particular use case pretty gnarly as it involves an async component being transitioned, and I want to run some cleanup inside the async component after the transition has completed.

Thanks for all the great work!

**Comment by pikax** [comment]
Can you provide reproduction code? :)

**Comment by posva** [comment]
I think this is consistent (and expected) with when `destroyed` is called

**Comment by dougalg** [comment]
I found this issue in vue core (https://github.com/vuejs/vue/issues/6983), and it does sound like this is indeed expected behaviour. I will consider my options, and thank you for the help.
