### ISSUE TITLE
Infinite update loop in 0.6.2 - 1.0.0-beta.6

### ISSUE THREAD

**Issue by drafu** [vuejs/composition-api#448]
The bug triggering "You may have an infinite update loop in a component render function" happens in unexpected places on unexpected reasons.

It did not happen with @vue/composition-api up until 0.6.1 and started happening in 0.6.2 and still persists.

I have recreated a minimal app with this problem
https://github.com/drafu/vue-composition-infinite-loop

**This bug strangely disappears if I:**
Remove A.vue component from App.vue
**OR**
Remove pattern prop from inside of A.vue component
**OR**
Remove div v-for iteration in App.vue
**OR**
Remove B.vue component from App.vue
**OR**
Remove emit from onMounted from B.vue

Which is highly strange all things considered, like, how is A.vue component, which is completely static, triggers infinite loop.

This bug is happening in some other places in my projects, but I cannot trace any consistent pattern.

**Comment by kahirokunn** [comment]
Excuse me, it looks like a test has been added, is @vue/composition-api@latest already solve this problem? :eyes:
