### ISSUE TITLE
What's the best way to share props/directives using composition api?

### ISSUE THREAD

**Issue by zgayjjf** [vuejs/composition-api#451]
I'm refactoring my codebase from `Option API` to `Composition API`.
However, I can't find a proper way to deal with shareable props.
With old option API, we can use mixin to share `props/data/computed/methods` among components like this:
```javascript
export const mixin = {
  directives: {
    yell: {
      name: 'yell',
      bind(el) {
        console.log(el)
      }
    }
  },
  props: {
    height: {
      type: Number,
      default: 20,
      validator: value => value > 12 && value < 20
    },
  },
  computed: {
    heightPx: function() {
      return this.height + 'px'
    }
  },
  methods: {
    echo() {
      console.log(this.heightPx)
    }
  }
}

export default {
  mixins: [mixin]
}
```
With composition API, we can share `data/props/computed/methods` like this:
```javascript
export const useHeightProps = {
  height: {
      type: Number,
      default: 20,
      validator: value => value > 12 && value < 20
    },
}

export yell = {
  name: 'yell',
  bind(el) {
    console.log(el)
}

export function useHeight (props) {
  const heightPx = computed(() => props.height + 'px')
  function echo {
    console.log(heightPx)
  }
  return {
    heightPx,
    echo
  }
}

// in components
export default {
  directives: {
    yell,
  },
  props: {
    ...useHeightProps
  },
  setup(props) {
    const { heightPx, echo } = useHeight(props)
    return {
      heightPx,
      echo,
    }
  }
}
```
**We can notice that we have to split props with other parts and compose them separately, which seems not very elegant.**

Even if we can still use mixin to share props and directives, it will cause new issues like TypeScript error. Not to mention the problems with mixin itself.

Is there any best practice for these situations?

**Comment by pikax** [comment]
Please use the issue for bugs or features requests, not questions.

You can ask questions on the [forum](http://forum.vuejs.org/) or [Discord server](https://vue-land.js.org/)
