### ISSUE TITLE
reactive inside computed starts tracking root / top level objects

### ISSUE THREAD

**Issue by vmihailenco** [vuejs/composition-api#454]
For example see https://codepen.io/vmihailenco/pen/RwrXLGN

Because `data` is not reactive `bar` computed should never be updated. But it looks like call to `reactive` starts tracking changes in `data` (not the whole data - only the top level keys) and because of that `bar` is re-computed every time `data` changes.

Same code works fine in Vue 3 - message is properly toggled on click. `bar` is computed once.

**Comment by pikax** [comment]
This probably is caused because the `reactive` mutates the original object.

After you call `reactive(data)` it will convert `data` into a reactive object.

This is one of the limitations of using `Vue.observe`

![image](https://user-images.githubusercontent.com/4620458/89329301-88f5e700-d686-11ea-8e05-7555900f0ac5.png)

**Comment by vmihailenco** [comment]
@pikax it does not seem to be related to reactive limitation. The same problem applies to computed+ref as well - https://codepen.io/vmihailenco/pen/gOrbNmP . Vue-next works fine.

**Comment by pikax** [comment]
> The same problem applies to computed+ref as well - https://codepen.io/vmihailenco/pen/gOrbNmP

I fail to understand what are you trying to do there.

**Comment by vmihailenco** [comment]
At least it is not reactive limitation this time :)

**Comment by pikax** [comment]
**It is** a limitation of [reactivity in Vue 2.x](https://vuejs.org/v2/guide/reactivity.html#For-Objects)

**Comment by vmihailenco** [comment]
The link you posted is about Vue not able to `detect property addition or deletion`. How it is relevant here?

**Comment by pikax** [comment]
In your example you are adding a new property to the object data and expecting the render to update

**Comment by antfu** [comment]
@vmihailenco `reactive` mutates the object in Vue 2, which means the `var data` you declared becomes reactive after the first run with `computed`, it also collected as a reative dependency of `bar`. So every time you change the `bar.test`, the computed is triggered. Hope this answers your question.

**Comment by antfu** [comment]
Not very sure what you are trying to do here, but if you only want to make the computed run once, try with `const data = markRaw({ test: true });`

**Comment by vmihailenco** [comment]
>In your example you are adding a new property to the object data and expecting the render to update

I do not. See https://codepen.io/vmihailenco/pen/zYqxgYV as even simpler example. And If you check the output you will see that in fact it re-renders on click. The problem is that also unnecessary updates computed. 

>reactive mutates the object in Vue 2, which means the var data you declared becomes reactive after the first run of the computed, and it also collected as a reactive dependency of bar

That is true. But it also happens with `ref` which supposedly should not have this problem. https://codepen.io/vmihailenco/pen/zYqxgYV is an example with ref.

**Comment by vmihailenco** [comment]
>and it also collected as a reactive dependency of bar

Yes, this is the problem. II see that if I am using `shallowRef` the problem goes away. So at least one improvement would be to use `shallowRef` instead of `ref` for primitive types (bool, number).

**Comment by vmihailenco** [comment]
`shallowReactive` does not have this problem too so I guess similar "fix" can be applied for `reactive` too.

What is the reason `reactive` does not copy the object just like `shallowReactive` does? The cost of cloning large objects?
