### ISSUE TITLE
`getCurrentInstance` in the click function return `null`

### ISSUE THREAD

**Issue by liaoliaojun** [vuejs/composition-api#455]
**Describe the bug**
When external code calls `getCurrentInstance`, it returns `null`.  
It's my pseudo-code：

```
import {getCurrentInstance} from '@vue/composition-api'

{
  template: `
   <div>
      <button @click="handleClick">click</button>
   </div>
  `,
  setup () {
     const handleClick = () => {
       console.log(getCurrentInstance()) // null
     }
     return { handleClick }
  },
}
```

**Versions**
"vue": "2.6.11",
"@vue/composition-api": "^1.0.0-beta.6",
"@vue/apollo-composable": "^4.0.0-alpha.10",

Thanks!

**Comment by antfu** [comment]
`getCurrentInstance()` is only avaliable in `setup` and lifecycle hooks. You may need to change your code to this:

```js
  const vm = getCurrentInstance()
  const handleClick = () => {
    console.log(vm) // null
  }
```

**Comment by gd4Ark** [comment]
首先是到底什么时候才能访问通过 `getCurrentInstance()`  当前实例：

1. 只要在 `setup()` 内部调用的任何方法，都能获取到当前实例，无论函数调用栈有多深
2. 但只能在同步代码中才能访问，其它的诸如 `setTimeout`、 `DOM 事件` 、 `Promise` 这类异步代码均无法访问

无法访问的原因是：

1. Composition API 会在调用组件的 `setup()` 前，先拿一个变量存放当前实例，以供调用 `getCurrentInstance()` 时返回，源码：[mixin.ts#L95](https://github.com/vuejs/composition-api/blob/master/src/mixin.ts#L95) 和 [instance.ts#L116](https://github.com/vuejs/composition-api/blob/master/src/utils/instance.ts#L116)
2. 执行完 `setup()` 以后，会把用于存放当前实例的变量值恢复到以前的模样（也就是 `null` ），源码：[instance.ts#L126](https://github.com/vuejs/composition-api/blob/master/src/utils/instance.ts#L126)
3. 所以，当 Composition API 内部执行到我们组件的 `setup()` 时，所有的同步代码都能访问到当前实例，但那些异步代码再去访问时，它已经恢复成 `null`  了。

原文: https://4ark.me/post/87ba8d8b.html

----------------- google translate ----------------------

when will the access be passed getCurrentInstance() Current instance:
1. As long as in `setup()` Any method called internally can obtain the current instance, no matter how deep the function call stack is.
2. However, it can only be accessed in the synchronization code. For example`setTimeout`  `DOM 事件`  `Promise` This type of asynchronous code cannot be accessed

The reason why the access is unavailable is:
1. The Composition API calls `setup()` Before, take a variable to store the current instance for calling `getCurrentInstance()` When returned, source code: [mixin.ts#L95](https://github.com/vuejs/composition-api/blob/master/src/mixin.ts#L95) And [instance.ts#L116](https://github.com/vuejs/composition-api/blob/master/src/utils/instance.ts#L116)
2. Executed `setup()` Later, the variable value used to store the current instance will be restored to its previous appearance (that is `null`), source code: [instance.ts#L126](https://github.com/vuejs/composition-api/blob/master/src/utils/instance.ts#L126)
3. Therefore, when the Composition API is internally executed to `setup()` When, all the synchronous code can access the current instance, but when the asynchronous code is accessed again, it has been restored null Yes.

source post: https://4ark.me/post/87ba8d8b.html
