### ISSUE TITLE
Vue 3 `readonly` API doesn't exist

### ISSUE THREAD

**Issue by Dan503** [vuejs/composition-api#459]
I wanted to try implementing this new Context technique:

https://markus.oberlehner.net/blog/context-and-provider-pattern-with-the-vue-3-composition-api/

But the [`readonly` API](https://composition-api.vuejs.org/api.html#readonly) doesn't seem to exist.

![readonly api error when importing](https://user-images.githubusercontent.com/10610368/89401345-81067780-d758-11ea-979b-3f9235ff527f.png)

**Comment by pikax** [comment]
Is not possible to reproduce the `readonly` using `Vue.observe`

![image](https://user-images.githubusercontent.com/4620458/89401457-37dd0600-d70d-11ea-9b03-0cc598333466.png)
