### ISSUE TITLE
ref lost reative

### ISSUE THREAD

**Issue by okxiaoliang4** [vuejs/composition-api#462]
use @vue/composition-api@1.0.0-beta.7 in vue2

`t` always empty

```html
<template>
    <div>t: {{t}}<div>
<template>

<script>
export default defineComponent({
    setup() {
        let t = ref('')
        setTimeout(()=>{
           t.value = '123'
        }, 1000)
        return {t}
    }
})
</script>
```

**Comment by okxiaoliang4** [comment]
i use @vue/composition-api refactor a page,the day before yesterday ref reative still working,i see 1.0.0-beta.7 has a break change,but i don't know how upgrade.

**Comment by okxiaoliang4** [comment]
Maybe this is a bug?

**Comment by Picknight** [comment]
I tried but it didn't reproduce: [codesandbox](https://codesandbox.io/s/vue-composition-test-1ttpo?file=/src/main.js)
Can you post a codesandbox url？

**Comment by okxiaoliang4** [comment]
maybe my setup affected by other codes. Let me check what's wrong
