### ISSUE TITLE
Data rendering issues in the onServerPrefetch lifecycle

### ISSUE THREAD

**Issue by YongMaple** [vuejs/composition-api#466]
Here's some code that gets the data when console.log(navigation) is present, but in Vue Devtools, navigation is an empty object.This is a NUXT project
下面是部分代码，console.log(navigation)可以获取到数据，但是在Vue Devtools工具中，navigation却是一个空对象。这是一个nuxt项目。
```javascript
setup(props, { root }) {
  let navigation = reactive({})
  onServerPrefetch(async () => {
      navigation = await root.context.$request.getNavigation()
      console.log(navigation)
  })
  return {
    navigation
  }
}
```

**Comment by posva** [comment]
You still need a way to serialize the data to send it to the client. You can use the store (which is what you normalize use with `serverPrefetch` or use https://composition-api.now.sh since you are using Nuxt, which will handle this out of the box
