### ISSUE TITLE
Error in data(): "TypeError: Cannot read property 'dep' of undefined" in beta9

### ISSUE THREAD

**Issue by hmmhmmhm** [vuejs/composition-api#473]
A project that had no errors in beta8 is experiencing the following errors in beta9.
I am not using the prop called `dep` (it also same with my modules)
and the problem was solved when I went back to beta8.

> Terminal

<img width="663" alt="스크린샷 2020-08-13 오후 4 34 10" src="https://user-images.githubusercontent.com/38493722/90106911-073b4300-dd83-11ea-938b-9cb1267164c0.png">

> package.json
```
"@vue/composition-api": "^1.0.0-beta.9"
```

> client/pages/index.vue

<img width="399" alt="스크린샷 2020-08-13 오후 4 38 46" src="https://user-images.githubusercontent.com/38493722/90107237-7add5000-dd83-11ea-901e-82218fa3c152.png">

> .bind() (vue-state-store/src/store.ts)
<img width="584" alt="스크린샷 2020-08-13 오후 4 40 31" src="https://user-images.githubusercontent.com/38493722/90107468-d0196180-dd83-11ea-8616-2242f1765464.png">

Maybe it can be possible the setting `deep` is used in the composition api as a `dep`,
and some changes makes the problem and that is might be problem...?

**Comment by pikax** [comment]
Thank you from bring this up, I know how to fix this, but can't reproduce this.

The error seems to be caused by https://github.com/vuejs/composition-api/commit/13bfed1#diff-928f1642d5b2a527058c32372d5bdf1eR325

I would like to understand how you can have a reactive value without `dep`.

Can you provide an reproduction codesandbox? 

> Note: Is much better if you post the code in text rather than image.

**Comment by hmmhmmhm** [comment]
@pikax Yup I Uploaded,

> Codesandbox Image
![스크린샷 2020-08-13 오후 5 46 07](https://user-images.githubusercontent.com/38493722/90113864-e841ae80-dd8c-11ea-944d-c86339da4ab6.png)


codesandbox
https://codesandbox.io/s/jovial-kirch-t7klt?file=/client/pages/index.vue:573-703

github template
https://github.com/AhaOfficial/nuxt-template

**Comment by hmmhmmhm** [comment]
@pikax 🤔  Is this have some wrong..? i want to help

**Comment by pikax** [comment]
I still can't find the root cause, I need to understand what's causing the reactive/ref to lose the `__ob__` and still be consider reactive, if you can provide an example without using `nuxt` or external libraries it would be a great help
