### ISSUE TITLE
Nested reactive values (ref / computed) no unwrapped in template

### ISSUE THREAD

**Issue by visualjerk** [vuejs/composition-api#475]
Since `1.0.0-beta.7` nested reactive values are no longer unwrapped when used inside a template. This worked as expected in previous versions.

Example:

https://codesandbox.io/s/composition-api-nested-ref-in-template-2xy8h

### Steps to reproduce

Create a component like this:

```vue
<template>
  <div :id="attributes.id">test</div>
</template>

<script>
import { ref } from "@vue/composition-api";

export default {
  name: "App",
  setup() {
    const id = ref("test");
    return {
      attributes: {
        id
      }
    };
  }
};
</script>

```

### Expected Behavior

`id` in rendered result has the value "test".

### Current Behavior

`id` in rendered dom has the value "[object Object]".

**Comment by pikax** [comment]
This is working as intended, check the changelog and the Vue next PR

https://github.com/vuejs/composition-api/blob/master/CHANGELOG.md#breaking-changes

**Comment by visualjerk** [comment]
Came across this directly after submitting the issue. Sorry for the disturbance 😄 

And thanks for the blazingly fast response!

**Comment by visualjerk** [comment]
Just in case somebody comes across this.

If nested `ref` or `computed` values should be bound as attributes inside a template, make the object around them `reactive`:

```vue
<template>
  <div :id="attributes.id">test</div>
</template>

<script>
import { ref, reactive } from "@vue/composition-api";

export default {
  name: "App",
  setup() {
    const id = ref("test");
    return {
      attributes: reactive({
        id
      })
    };
  }
};
</script>

```
