### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by yuanzhou3118** [vuejs/composition-api#484]
I tried using vue-cli3 and jsx for the first time and kept getting:

> TypeError: Object(...) is not a function

I modified the App.vue with the example taken directly from the documentation and the problem persists:

```javascript
import { defineComponent } from '@vue/composition-api';
export default defineComponent({
  name: 'test',
  setup() {
    return <div>123</div>;
  },
});
```

Using composition API version 0.6.7

**Comment by jacekkarczmarczyk** [comment]
> Using composition API version 0.6.7

Try the latest one maybe?

**Comment by yuanzhou3118** [comment]
> > Using composition API version 0.6.7
> 
> Try the latest one maybe?

I will try the latest, but why the old version cannot?

**Comment by yuanzhou3118** [comment]
> > Using composition API version 0.6.7
> 
> Try the latest one maybe?

OMG!! I use the latest version and this bug has fixed!!

**Comment by screetBloom** [comment]
@yuanzhou3118  

Which @vue/composition-api version did you use to solve this problem?
