### ISSUE TITLE
props are mutable as unwanted side-effect

### ISSUE THREAD

**Issue by qhantom** [vuejs/composition-api#485]
### Scenario

Below you can see that the passed prop is mutable for some reason. It doesn't matter if I declare `tag` as `ref` or `reactive`. Why does the reference still exists to the prop and mutates it?

`tagsView.vue`

```
<ul>
   <li
       v-for="(tag, index) in tags"
       :key="index"
        class="py-2 border-b last:border-b-0 border-soft"
        >
        <single-tag v-model="tags[index]" @tag-deleted="tagDeleted" />
   </li>
 </ul>
```

`singleTag.vue`

```
<script lang="ts">
  import { defineComponent, PropType, reactive } from '@vue/composition-api'
  import { Tag } from '@/types/tag'

  export default defineComponent({
    name: 'Tag',
    props: {
      value: {
        type: Object as PropType<Tag>,
        required: true,
      },
    },
    setup(props) {
      // props.value: original state of the tag as it was passed here
      // tag: copy of the prop in order to modify it
      const tag = reactive(props.value)
      tag.content = 'EDITED'
      console.log('TAG:', tag.content) // gives back 'TAG: EDITED'
      console.log('PROP:', props.value.content) // gives back 'PROP: EDITED'
    },
  })
</script>
```

**Comment by posva** [comment]
This is expected with Objects as they are passed by reference in JS. See the note at https://vuejs.org/v2/guide/components-props.html#One-Way-Data-Flow

BTW `reactive` doesn't create a copy, it reuses the same object

**Comment by qhantom** [comment]
Got it. But why does Vue not warn me in the console or during the build process?

**Comment by pikax** [comment]
![image](https://user-images.githubusercontent.com/4620458/90757736-eb312780-e2d5-11ea-86fe-69b0879f511f.png)

> But why does Vue not warn me in the console or during the build process?

@qhantom what warning are you expecting in this case? I'm not sure what sort of warning it should

**Comment by qhantom** [comment]
I expect this:

https://blog.jongallant.com/2019/01/vuejs-avoid-mutating-error/000049.png

**Comment by qhantom** [comment]
Sometimes it can happen that you accidentally mutate a prop and it's crucial to have such a warning ...

**Comment by jacekkarczmarczyk** [comment]
It will give you a warning in Vue 3

**Comment by qhantom** [comment]
Thanks. So I assume to assign a prop (that is an array or an object) to a variable I just create a brand-new object / array with i.e. Object.assign / Array.from or the corresponding spread-ops?

**Comment by pikax** [comment]
You technically not mutating the `prop`, you are mutating a `property` of the `prop`, which is different.

**Comment by qhantom** [comment]
@pikax And that tells me what? Even though it is just a property of the prop, this shouldn't be supposed to be edited.

**Comment by pikax** [comment]
> Even though it is just a property of the prop, this shouldn't be supposed to be edited

This is v2.x behaviour.

**Comment by qhantom** [comment]
Thanks pikax. So it's changed in Vue 3?

**Comment by qhantom** [comment]
I found it in the Vue 3 docs. For people who ask the same:

> In addition, every time the parent component is updated, all props in the child component will be refreshed with the latest value. This means you should not attempt to mutate a prop inside a child component. If you do, Vue will warn you in the https://v3.vuejs.org/guide/component-props.html#one-way-data-flow
