### ISSUE TITLE
Error: [vue-composition-api] already installed after upgrading @vue/composition-api

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/composition-api#489]
**Describe the bug**
After updating the package `@vue/composition-api`. we're receiving the error below and the page is not rendered:
 > Error: [vue-composition-api] already installed.

This works fine:
```
// package.json
"dependencies": {
    "@vue/apollo-composable": "^4.0.0-alpha.10",
    "@vue/composition-api": "1.0.0-beta.10",
```

This does not:
```
// package.json
"dependencies": {
    "@vue/apollo-composable": "^4.0.0-alpha.10",
    "@vue/composition-api": "1.0.0-beta.11",
```

Quasar boot file:
```typescript
import Vue from 'vue'
import VueCompositionApi from '@vue/composition-api'

Vue.use(VueCompositionApi)
```

**Comment by pikax** [comment]
There's nothing on the commits that can cause that, can you provide a reproduction repo/codesandbox?

**Comment by DarkLite1** [comment]
Sure thing. I'm just a beginner at all this so these are the steps to reproduce:

1. git clone git@github.com:DarkLite1/hip.git
2. run `yarn` to install the dependencies
3. run `yarn dev` and notice the browser will open correctly
4. `yarn upgrade --latest`
5. run `yarn dev` again and notice the error in the browser console

**Comment by pikax** [comment]
I'm having issues running it, but can you provide the output for `yarn why @vue/composition-api` 

I guess this is caused by `vue-demi` 

/cc @antfu

**Comment by Petercopter** [comment]
I'm not sure if this is related, but upgrading from vue-composition-api beta 10 to beta 11 causes this error in my jest/vue-test-utils suite:

```
[vue-composition-api] only works with Vue 2, v1.0.0-beta.11 found.

localVue.use(VueCompositionApi)
         ^
```

**Comment by antfu** [comment]
@Petercopter, It should be the exporting conflict with vue-demi, working on the fix now.

**Comment by antfu** [comment]
@Petercopter just released `vue-demi@0.3.2`, can you try to remove the lock and `node_modules` and then reinstalled again? Thanks

**Comment by Petercopter** [comment]
👍  That did the trick. I can't delete my yarn.lock right now, so I tracked down that `@vue/apollo-composable` was using `vue-demi latest`, and upgraded that as well. Everything looks fine from here, thanks for jumping on that! You are appreciated  🤗

**Comment by DarkLite1** [comment]
> yarn why @vue/composition-api

Of course:
```T:\Test\Brecht\Node\prod\hip-frontend [test]> yarn why @vue/composition-api
yarn why v1.22.4
[1/4] Why do we have the module "@vue/composition-api"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@vue/composition-api@1.0.0-beta.10"
info Has been hoisted to "@vue/composition-api"
info Reasons this module exists
   - Specified in "dependencies"
   - Hoisted from "@vue#apollo-composable#vue-demi#@vue#composition-api"
info Disk size without dependencies: "264KB"
info Disk size with unique dependencies: "320KB"
info Disk size with transitive dependencies: "320KB"
info Number of shared dependencies: 1
Done in 1.30s.
```

I have to say I was/am not using `vue-demi` as a dependency but if I understand it correctly it's used by the module `vue#composition-api`. Should I try the fix to remove the `node_modules` folder and run yarn again as suggested? Or was that not related to my issue?

**Comment by antfu** [comment]
@DarkLite1 `@vue/apollo-composable ` relies on `vue-demi` https://github.com/vuejs/vue-apollo/blob/1e7a5c6a3b5d40fe800d104d2235aa6b121d2cb3/packages/vue-apollo-composable/package.json#L38

Guess all you need to do is to remove the `App.use` for VCA

```diff
import Vue from 'vue'
import VueCompositionApi from '@vue/composition-api'

- Vue.use(VueCompositionApi)
```

**Comment by pikax** [comment]
Can you run `yarn why @vue/composition-api` after you update to `1.0.0-beta.11`

**Comment by DarkLite1** [comment]
So I tried the suggestion above, upgrade to `1.0.0-beta.11` and remove the `node_modules` folder and the `yarn.lock` file. This solved my issue too. So I guess it's related to the `vue-demi` package that is a dependency of `@vue/composition-api`.

When everything is working now, after the actions above I get this when running `yarn why @vue/composition-api`:

```
yarn why v1.22.4
[1/4] Why do we have the module "@vue/composition-api"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@vue/composition-api@1.0.0-beta.11"
info Has been hoisted to "@vue/composition-api"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "320KB"
info Disk size with unique dependencies: "376KB"
info Disk size with transitive dependencies: "376KB"
info Number of shared dependencies: 1
Done in 1.26s.
```

For me the issue is now resolved and can be closed if you want. Maybe add a minimal required version of `vue-demi` to the dependency list to avoid this issue?

On a side note, when commenting out `Vue.use(VueCompositionApi)` I get this error: So I really need to load the plugin, but that's ok as all is working as it should now. Thanks for the help :)

> [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.

**Comment by pikax** [comment]
> On a side note, when commenting out Vue.use(VueCompositionApi) I get this error: So I really need to load the plugin, but that's ok as all is working as it should now. Thanks for the help :)

You might need to hack it by importing `vue-apollo` on your `boot`, because you get the error because `vue-apollo` wasn't imported when you first use the composition-api

**Comment by DarkLite1** [comment]
You're right, if I replace the content of my boot file form this:

```javascript
import Vue from 'vue'
import VueCompositionApi from '@vue/composition-api'

Vue.use(VueCompositionApi)
```

To this:
```javascript
import '@vue/apollo-composable'
```

It works too. Is that what you meant? I really thought I had to load the `VueCompositioinApi` as a plugin with `Vue.Use()`. Appears this is not needed at all. Thanks for the tip :_

**Comment by antfu** [comment]
> I really thought I had to load the VueCompositioinApi as a plugin with Vue.Use()

in this case, importing `@vue/apollo-composable` did that for you :)

**Comment by pikax** [comment]
> It works too. Is that what you meant? I really thought I had to load the `VueCompositioinApi` as a plugin with `Vue.Use()`. Appears this is not needed at all. Thanks for the tip :_

You need to always use `Vue.use(VueCompositionApi)` but because `@vue/apollo-composable` is using [vue-demi](https://github.com/antfu/vue-demi) it will do [Vue.use automatically](https://github.com/antfu/vue-demi/blob/master/lib/v2/index.esm.js#L4)

**Comment by DarkLite1** [comment]
I see, thanks for the clarification on this. Maybe it's better to stick with my initial boot file then? Because the moment `@vue/apollo-composable` is no longer loading the plugin for me the app will break. What would be best practice in this case? I just want to be future proof.

**Comment by antfu** [comment]
The `already installed` warning is actually no harm and does nothing if it's already installed.

@pikax should we expose the [`isPluginInstalled`](https://github.com/vuejs/composition-api/blob/026a78aab73df4f1c601a085dc8aa2cbe9e8bcb4/src/runtimeContext.ts#L10-L12) function to the entry so users can explicitly prevent duplicate installs. Something like

```ts
import VueCompositionAPI, { isPluginInstalled } from '@vue/composition-api`

if (isPluginInstalled()){
  Vue.use(VueCompositionAPI)
}
```

Another way might be just ignoring duplicate install and do not throw the warning. But this does not sound very good.

**Comment by pikax** [comment]
The [isVueRegistered](https://github.com/vuejs/composition-api/blob/026a78aab73df4f1c601a085dc8aa2cbe9e8bcb4/src/runtimeContext.ts#L14) also sounds a good candidate.

I personally don't like a dependency of a dependency to add `Vue.use`, for me the best solution would be a way allow `vue-demi` to install or not install the `Vue.use(VueCompositionAPI)` automatically, and let the devs to to choose if they want to install or not via `vue-demi`
