### ISSUE TITLE
Nested ref gets type error: Type 'Ref<boolean>' is not assignable to type 'boolean'.

### ISSUE THREAD

**Issue by MikeBlandford** [vuejs/composition-api#490]
vue 2.6.12
vue/composition-api 1.0.0-beta.11
typescript 4.0.2

```
import { ref, defineComponent, Ref } from '@vue/composition-api';
export default defineComponent({
  setup() {
    const acts = ref<Activity[]>([]);
    const updateActivities = (newActs: Activity[]) => {
      acts.value = newActs;
    };
    return {
      acts
    };
  }
});
class Activity {
  constructor() {
  }
  isCurrent: Ref<boolean> = ref<boolean>(true);
}
```

The line setting acts.value = newActs says "Type 'Ref<boolean>' is not assignable to type 'boolean'"

isCurrent is updated in setInterval based on current time (code not shown)

Note: It actually seems to update the UI if isCurrent is just a boolean and not a ref (although I'm not sure if it's guaranteed to work like that?)

**Comment by pikax** [comment]
Does it work with the 3.9.x?

**Comment by MikeBlandford** [comment]
typescript 3.9.7 also had this error

**Comment by pikax** [comment]
I'm on a phone so can't really test this, but seems like is because is `unwrapping` you class.

Is this boolean? 
```ts
acts.value[0].isCurrent = true
```
