### ISSUE TITLE
$style not defined on getCurrentInstance() in typescript

### ISSUE THREAD

**Issue by gregveres** [vuejs/composition-api#496]
I am using typescript and the composition api. I am trying to access $style in the setup function and typescript doesn't believe that $style is part of the object returned from getCurrentInstance().

This seems to be an oversight on the type definition of getCurrentInstance().

I am trying to use the approach suggested [here](https://github.com/vuejs/composition-api/issues/21#issuecomment-583947620)

**Comment by pikax** [comment]
typing for `getCurrentInstance` comes from `vue`  directly and not managed by the `composition-api` plugin
