### ISSUE TITLE
Problem with composition api 

### ISSUE THREAD

**Issue by aissa-bouguern** [vuejs/composition-api#505]
Hi,
I'm trying to create a vue composable hook to toggle sidebar menu.

```js
import { reactive, toRefs } from '@vue/composition-api';

const useToggleMenu = () => {
  const state = reactive({
    isMenuOpen: true,
  });

  const toggleMenu = () => {
    state.isMenuOpen = !state.isMenuOpen;
  };

  return {
    ...toRefs(state),
    toggleMenu,
  };
};

export default useToggleMenu;
```
the problem I'm facing is when using `isMenuOpen` state in one component (ex: Layout), and use `toggleMenu` in another component (ex: BurgerButton).

```js
// BurgerButton.vue

import { useToggleMenu } from '../hooks';

export default {
  name: 'BurgerButton',
  setup() {
    const { toggleMenu } = useToggleMenu();
    return {
      // use this in template to show/hide menu.
      toggleMenu,
    };
  },
  
  ...
};
```

```js
// Layout.vue

import { useToggleMenu } from '../hooks';

export default {
  name: 'Layout',
  setup() {
    const { isMenuOpen } = useToggleMenu();

    return {
      // use this in template to add some classes to <body>
      isMenuOpen,
    };
  },
};
  
  ...
};
```

the issue is when I click burger button and trigger the `toggleMenu` function, that does not make any change! the `isMenuOpen` boolean is not reactive.

I hope that is clear, and thanks to anyone trying to help.

**Comment by antfu** [comment]
Exact logic into functions to "reuse" not "sharing". In every component, the function will create a fresh new `isMenuOpen` which will not be associated with the other usages. To share a reference, you may want to declare them on the top level of a module and directly import them(global state) or pass it down via props.

**Comment by aissa-bouguern** [comment]
Thanks @antfu, so there is no way here to use idea of react.js custom hooks ?

**Comment by antfu** [comment]
```
const craeteToggleMenu = () => {
  const state = reactive({
    isMenuOpen: true,
  });
 const useToggleMenu ()=> {
  const toggleMenu = () => {
    state.isMenuOpen = !state.isMenuOpen;
  };

  return {
    ...toRefs(state),
    toggleMenu,
  };
}

return useToggleMenu
};

export const useToggleMenu = createToggleMenu()
```

this would do. Sorry for the formating, I am just editing it on GitHub

**Comment by aissa-bouguern** [comment]
Wow,  i get the idea!
Thank you so much, really appreciate your help.
Have a nice week.
