### ISSUE TITLE
"export 'createElement' (imported as 'baseCreateElement') was not found in '@vue/composition-api'

### ISSUE THREAD

**Issue by Dahkenangnon** [vuejs/composition-api#506]
I'm using vue js with electron and feathersVuex. And i get this error:

WARNING  Compiled with 1 warnings                                                                                                    
 warning  in ./node_modules/feathers-vuex/dist/FeathersVuexPagination.js

"export 'createElement' (imported as 'baseCreateElement') was not found in '@vue/composition-api'

**Comment by jacekkarczmarczyk** [comment]
it's `h`, not `createElement`

**Comment by posva** [comment]
You probably need to downgrade your version of @vue/composition-api until they support the new version. You should also check existing issues in feathers-vuex and open a new one if it hasn't been reported yet
