### ISSUE TITLE
can't watch reactive object deep

### ISSUE THREAD

**Issue by southpush** [vuejs/composition-api#507]
here is my sandbox https://codesandbox.io/s/floral-https-kul8d?file=/src/App.vue

watch not work, I cant watch manager.test

```

<template>
  <div id="app">
    <button @click="test">test</button>
    {{ manager.test }}
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, watch } from "@vue/composition-api";

export default defineComponent({
  name: "App",

  setup() {
    const manager = reactive({
      test: {}
    });

    let count = 0;

    const test = () => {
      manager.test[count] = count;
      count++;
      console.log(manager.test);
    };

    watch(
      () => manager.test,
      v => {
        console.log("in watch: ", v);
      }
    );

    return {
      manager,
      test
    };
  }
});
</script>

```

"vue": "^2.6.10",
"@vue/composition-api": "^1.0.0-beta.11",

**Comment by posva** [comment]
See the limitation about `set` in readme: https://github.com/vuejs/composition-api#limitations.

**Comment by antfu** [comment]
The reactivity system of Vue 2 is different from Vue 3's. You will need to use `set()` when adding new properties to an object.

https://codesandbox.io/s/winter-glitter-t9fhm

**Comment by jaysaurus** [comment]
see also: https://composition-api.vuejs.org/api.html#customref

**Comment by Rigo-m** [comment]
`set` does not trigger a watch on a `reactive` value in Vue 2.x, but `del` does. Why?
