### ISSUE TITLE
Array passed as prop not reactive

### ISSUE THREAD

**Issue by aux09092020** [vuejs/composition-api#508]
I wrote a component that takes an Array as a prop and has a computed property for the length of that array. The array passed to the component is initially empty, then populated after an api call. My issue is that the computed property ```isEmpty``` is always true.

Here is a snippet of code:
```
props: {
    items: {
        type: Array,
        required: true
    }
},
setup(props) {
    const items = ref(props.items);
    const isEmpty = computed(() => !items.value.length);
    return { isEmpty }
}
```
Is this a bug or am I doing something wrong?

**Comment by posva** [comment]
Directly access props.items and remove the line where you create the ref

**Comment by Stefano1990** [comment]
I'm not sure if I'm struggling with the same problem.

In my child component I got:
```javascript
export default {
  name: 'ConversationPartial',

  components: { UserAvatar },

  props: {
    conversation: {
      type: Object,
      required: true
    }
  },

setup ({ conversation }, ctx) {
    const isLastMessageUnread = computed(() => { return conversation.messages[0].readNotifications.filter(rn => rn.userId === currentUser.value.id).length === 0
    })

    return {
      isLastMessageUnread
    }
  }
```

In the template this will not update when the parent updates the `conversation`. However, if I put that `.filter` straight into the template it updates as expected.

So there is definitely some kind of issue with the computed props.
