### ISSUE TITLE
Future of the plugin

### ISSUE THREAD

**Issue by sarahdayan** [vuejs/composition-api#513]
Hi there!

[Vue 3](https://github.com/vuejs/vue-next) is in release candidate at the time of this writing. Vue CLI lets you install Vue 3 and the documentation for Vue 3 is available, prompting more users to go and try it out directly.

With all that considered, **I'm wondering what is the future of this plugin**. Will it be maintained and available for an undetermined amount of time, even after Vue 3 is stable and officially out? Or will it be deprecated to encourage Vue 2 users who adopted it to upgrade to Vue 3?

Of course I realize that this plugin serves a different purpose than Vue 3; it makes the Composition API (which is only one aspect of Vue 3) available in Vue 2. Yet, given that the Composition API was intended to be used in Vue 3 (with optimal performance and no limitations), it's worth asking. This is important to know for library maintainers who expose Vue Composition functions, so they can make educated choices regarding whether it's worth the effort of maintaining a compatibility layer or not.

Thanks in advance!

**Comment by pikax** [comment]
Hi :)

Currently there's no plans to deprecate this plugin, we hope to bring it to v1 stable at the same time as the release of vue3. 

Realistically even when the vue3 gets released it will take time to the ecosystem to upgrade, until the most of the popular vue ecosystem is using vue3, developers and companies will keep using vue 2, this plugin serves as a way for developers exploring the new API without moving the stack to v3. 

There're works to mitigate some of the vue2 limitations when using VCA and the 2.7 will bring some APIs closer to vue3.

There's a few libraries that are compatible with vue2 + vue3 
- [vue-composable](https://github.com/pikax/vue-composable) & [vueuse](https://github.com/antfu/vueuse) - utils lib
- [vue-demi](https://github.com/antfu/vue-demi) - Universal Vue Libraries for Vue 2 & 3
- [@vue/apollo-composable](https://github.com/vuejs/vue-apollo/tree/v4/packages/vue-apollo-composable) - composable library compatible with vue 2 & 3 powered by vue-demi.

**Comment by sarahdayan** [comment]
Thanks for the super quick reply @pikax! If I understand correctly, [vue-demi](https://github.com/antfu/vue-demi) is where the magic happens, by re-routing the static calls to the right dependency. This is a really interesting solution!
