### ISSUE TITLE
在data 和computed 里 获取不到this  

### ISSUE THREAD

**Issue by zzzz-Z** [vuejs/composition-api#516]
<img width="440" alt="WX20200915-100614@2x" src="https://user-images.githubusercontent.com/28984303/93157061-0f005580-f73c-11ea-9468-bca2f0abd0e5.png">

**Comment by pikax** [comment]
Not related with `composition-api`.

---

For questions please use the [forum](https://forum.vuejs.org/) or [discord](vue.land)
