### ISSUE TITLE
App breaks after upgrade from `1.0.0-beta.11` to `1.0.0-beta.12` and later

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/composition-api#517]
We have a web app in this [GitHub repo](https://github.com/DarkLite1/hip) that works perfectly fine with `@vue/composition-api` version `1.0.0-beta.11` but not after upgrading to `1.0.0-beta.12` or `13`. Navigation breaks and pages don't get loaded:

Given that the only thing changed is the ugprade of the vue composition api I'm wondering what changed or what we dan do to make it work again? It seems hard to troubleshoot. We think it might be related to [calling the graphql backend](https://github.com/DarkLite1/hip/blob/master/src/pages/Index.vue) as at that page the data is no longer loaded/fetched and the web-page blocks and keeps on showing "All accounts: loading" which means it's not getting data from the backend.

In a normal flow a promise is triggered after authentication ([handleResponse](https://github.com/DarkLite1/hip/blob/master/src/services/auth/authService.ts)) that sets the Vue reactive property ([setAccount](https://github.com/DarkLite1/hip/blob/master/src/store/authStore.ts)) for authentication and the home page is loaded and a graphql query is triggered. But now, after a the upgrade it's stuck here and navigating away from this wrong page seems to be not possible.

![image](https://user-images.githubusercontent.com/10828570/93208028-30713980-f75c-11ea-9dda-6139480a53b5.png)

Any help would be appreciated.

![image](https://user-images.githubusercontent.com/10828570/93206710-21898780-f75a-11ea-9c71-8a7ae33f43d6.png)

![image](https://user-images.githubusercontent.com/10828570/93206751-3239fd80-f75a-11ea-86bc-f0bf4e041ad9.png)

**Comment by pikax** [comment]
Thank you for raising this, I have a few guesses why this is happening, but can't reproduce on my machine. 

Can you provide an example where I can test a fix for that?

If you can't provide an example, can you reach out to me on [discord](https://vue.land) on the #composition-api channel?

**Comment by DarkLite1** [comment]
I will contact you on Discord. Thanks for offering help. Waiting the 10 min wait time on Discords :P

**Comment by DarkLite1** [comment]
Thank you for trying to help out @pikax , really appreciate it. Let's hope someone from the vue apollo team might see what's going wrong here. And sorry for not being able to provide you with a clean reproduction. I'm just too much of a newbie to be able to set that up.

**Comment by pikax** [comment]
No worries, the problem was caused by circular dependency, minimal repo:
```ts
    const a = {
      b: 1,
    }
    a.a = a

    reactive(a)
```

**Comment by DarkLite1** [comment]
We just tested it in version ` @vue/composition-api@1.0.0-beta.14` and it's fixed now. 
Thank you for the great help and support, much appreciated.
