### ISSUE TITLE
watch() type problem

### ISSUE THREAD

**Issue by tomexx** [vuejs/composition-api#519]
There is a problem with unwrapping of variables inside `watch(...)`

See the signature of incoming `ref`
![image](https://user-images.githubusercontent.com/2822756/93233449-607c0500-f77b-11ea-8320-c80f348dfd6d.png)

and the argument with _new_ value
![image](https://user-images.githubusercontent.com/2822756/93233467-6540b900-f77b-11ea-8877-1b6cb26e8959.png)

There are missing fields when you compare it with the used type definition
![image](https://user-images.githubusercontent.com/2822756/93233794-c799b980-f77b-11ea-8dfb-ed58cca1e6a0.png)

**Comment by pikax** [comment]
you may need to do `as const` 

```ts
watch([category, assignee, timeframe] as const, /* ... */)
```

If that doesn't work, please provide an reproduction code, instead of printscreen.

**Comment by antfu** [comment]
Closing for now. If the error still occurs, please open a new issue with reproduction. Thanks.
