### ISSUE TITLE
"reactive" doesn't work well with Array

### ISSUE THREAD

**Issue by zippaaa** [vuejs/composition-api#521]
_I have read `reame.md` and other questions, but have not found an answer._

**Vue3:**
```
const a = reactive([1]);

watch(
    () => a.length,
    length => console.log('watch:', length),
);

const sum = computed(() => {
    let sum = 0;
    a.forEach(item => {
        sum += item;
    });
    return sum;
});

setTimeout(() => {
    a.push(3);
    console.log('setTimeout:', sum.value);
}, 3000);

console.log('default:', sum.value);
```

**Results:**
```
default: 1
setTimeout: 4
watch: 2

```

**Vue2 + composition-api beta 13**
```
default: 1
setTimeout: 1

```

**Comment by pikax** [comment]
Seems there's still some ironing to do with reactive, there's works on the way to improve the reactivity system, but that might take some time, we will had back the reactivity array caveats to the readme.

**Comment by hypocrite66** [comment]
I got the same situation appeared with API `ref(Array)`, It seems like `computed()` method could not track the dependency of Array's mutation in Vue 2, so I wonder how to solve this problem or change my implementation?
