### ISSUE TITLE
Usage and typings for custom directives

### ISSUE THREAD

**Issue by ivansieder** [vuejs/composition-api#523]
I was wondering, whether or not the composition API plugin is supposed to expose typings/functionality for the "new" way to define custom directives, as in `app.directive("my-directive", { beforeMount() {...} })` vs `Vue.directive("my-directive", { bind() {...} })`.

In Typescript it tells me that "beforeMount" is not valid. Typings seem to come from Vue 2, so my insecurity was mostly, if it's just missing typings from the composition API plugin or if I'm missing something.

**Comment by pikax** [comment]
Directives has nothing to do with the composition api, therefore there's no typings for it.

**Comment by ivansieder** [comment]
Jeez, thank you @pikax, guess I got confused as I defined the component with defineComponent and that allowed me to use app.directive(...), but it's actually just the basic Vue 2 directive typings which come back from that. Thanks again!
