### ISSUE TITLE
can i use it for Production ?

### ISSUE THREAD

**Issue by spongege** [vuejs/composition-api#527]

**Comment by pikax** [comment]
yes.

---

For questions please use [VueJS Forum](https://forum.vuejs.org/) or [Discord](https://vue.land)

**Comment by maxpou** [comment]
@pikax are you sure? Documentation say it's not recommended.

**Comment by pikax** [comment]
> @pikax are you sure? Documentation say it's not recommended.

@maxpou where does it say that?

**Comment by maxpou** [comment]
https://composition-api.vuejs.org/#adoption-strategy

> The current implementation is up-to-date with this proposal, but may contain minor inconsistencies due to technical constraints of being a plugin. It may also receive braking changes as this proposal is updated, so we do not recommend using it in production at this stage.

**Comment by pikax** [comment]
That documentation is in regards to the composition-api generally, that information is out-of-date, and the .

Please check the project [readme](https://github.com/vuejs/composition-api), the not recommended for production was removed on https://github.com/vuejs/composition-api/pull/390

**Comment by maxpou** [comment]
This is a great news! Thank you @pikax!
