### ISSUE TITLE
Watcher of prop dependent computed is not triggered

### ISSUE THREAD

**Issue by jd-0001** [vuejs/composition-api#528]
I am just learning composition API and I found this issue, I don't know if I have to take care of something or this is a bug.

I have parent component `App.vue` Create from vue-cli:

```vue
<template>
  <h1>Hey Vue 3</h1>
  <test :count="count" />
  <button @click="count++">Increase from Parent</button>
</template>

<script>
import Test from './components/Test.vue'
import { ref } from 'vue'

export default {
  name: 'App',
  components: {
    Test
  },
  setup() {
    let count = ref(0)

    return {
      count
    }
  }
}
</script>

```

And I have child component named `Test.vue`:
```vue
<template>
  <p>Child Computed Counter: {{ computedCounter }}</p>
</template>

<script>
import { computed, watchEffect } from 'vue'

export default {
  props: {
    count: {
      type: Number,
      required: true
    }
  },
  setup(props) {

    const computedCounter = computed(() => props.count + 1)

    watchEffect(() => {
      console.log('computed-counter Updated :>> ', computedCounter);
    })

    return {
      computedCounter
    }
  }
}
</script>
```

According to what I have read in composition API docs I think `watchEffect` in `Test.vue` is not triggering the log if I update the prop from the parent.

Reproduction Steps:

* Created new vue-cli project (Vue 3)
* Update `App.vue` with above code of App.vue
* Renamed `HelloWorld` to `Test`
* Use above `Test.vue` code for `Test` component
* Click on `Increase from Parent` button and the value will get updated but that `watchEffect` which logs to the console isn't get triggered.

Regards.

**Comment by jacekkarczmarczyk** [comment]
```js
console.log('computed-counter Updated :>> ', computedCounter.value);
```

**Comment by jd-0001** [comment]
@jacekkarczmarczyk Yup. It's working. Sorry for the trouble. My bad.
