### ISSUE TITLE
`isReactive`/`reactive` doesn't work in SSR (regression in beta 14)

### ISSUE THREAD

**Issue by danielroe** [vuejs/composition-api#537]
`reactive` doesn't work on SSR. In a vanilla Nuxt project using just `@vue/composition-api`, `isReactive(reactive({}))` prints `false` on server-side but `true` on client-side.

**Reproduction**: https://codesandbox.io/s/sweet-dubinsky-ilbt1?file=/pages/index.vue

**Linked issue**: https://github.com/nuxt-community/composition-api/issues/244

**Comment by antfu** [comment]
Did some rough research, this probably becomes the obj return by [`observe`](https://github.com/vuejs/composition-api/blob/f204daaab4248590e254bac06690e33e507fb0de/src/reactivity/reactive.ts#L100) function does not contain the `__ob__` attribute. The newly introduced [`getRegisteredVueOrDefault`](https://github.com/vuejs/composition-api/blob/5484bb7fec15dfa8ac316c5266ef3cf00820b1a0/src/runtimeContext.ts#L38) imports `vue` [by using `require`](getRegisteredVueOrDefault), I guess it might be the wrong build for SSR.

I am not familiar with SSR, if someone has any idea of this, please let us know. Thanks.

**Comment by antfu** [comment]
Found a workaround in #546
