### ISSUE TITLE
Cannot work with i18n Single File Components

### ISSUE THREAD

**Issue by kgrandemange** [vuejs/composition-api#54]
setup (props, context) cannot work with [i18n Single File Compoents](https://kazupon.github.io/vue-i18n/guide/sfc.html#single-file-components), because root.$t is defined but can't find the string key.
Works in template and works with global `en.json` file.

**Comment by antfu** [comment]
@kgrandemange Can you try this workaround? https://github.com/vuejs/composition-api/issues/21#issuecomment-583947620

BTW, you can also want to have a look at [vue-i18n-next](https://github.com/intlify/vue-i18n-next) :)

**Comment by antfu** [comment]
Closing this for now as it's probably been covered by th
