### ISSUE TITLE
Using `shallowRef` is error in the Nuxtjs.

### ISSUE THREAD

**Issue by LemonAppleMo** [vuejs/composition-api#541]
Nuxt Link: https://codesandbox.io/s/objective-lovelace-di0lg?file=/pages/index.vue

Error message: Cannot read property 'dep' of undefined

**Comment by LemonAppleMo** [comment]
Version: v1.0.0-beta.14

**Comment by antfu** [comment]
Should be the same problem as #537, please keep track of it instead.
