### ISSUE TITLE
bootstrap vue is showing error for this new version of vue in vue cli.

### ISSUE THREAD

**Issue by binoysarker** [vuejs/composition-api#542]
Here is my package.json in vue cli 4.5.6
```
{
  "name": "test-app2",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint"
  },
  "dependencies": {
    "bootstrap-vue": "^2.17.3",
    "core-js": "^3.6.5",
    "vue": "^3.0.0-0",
    "vue-router": "^4.0.0-0",
    "vuex": "^4.0.0-0"
  },
  "devDependencies": {
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-router": "~4.5.0",
    "@vue/cli-plugin-vuex": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0-0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^7.0.0-0",
    "node-sass": "^4.12.0",
    "prettier": "^1.19.1",
    "sass-loader": "^8.0.2"
  }
}

```
But when i install bootstrap by following the doc. It is showing this error
![image](https://user-images.githubusercontent.com/26120595/94359253-d6f7fb80-00c7-11eb-8e74-d6c5c650ec8e.png)
![image](https://user-images.githubusercontent.com/26120595/94359290-073f9a00-00c8-11eb-8153-f5bdac6153ca.png)

**Comment by danielroe** [comment]
@binoysarker This repository is for the Vue 2 Composition API plugin - not for [Vue 3](https://github.com/vuejs/vue-next).

However, I think I can say pretty safely that the issue is that the version of bootstrap-vue that you are using evidently does not have support for Vue 3.

**Comment by posva** [comment]
Hi, thanks for your interest but Github issues are for bug reports and feature requests only. You can ask questions on the [forum](http://forum.vuejs.org/), the [Discord server](https://vue-land.js.org/) or [StackOverflow](http://stackoverflow.com/tags/vue.js).
