### ISSUE TITLE
Error "No vue dependency found"

### ISSUE THREAD

**Issue by schl3ck** [vuejs/composition-api#544]
I get the following error upon loading the app in my browser:

![vue-composition-api-error](https://user-images.githubusercontent.com/42554556/94667341-03518900-030f-11eb-8a0b-917e52bfb03c.png)

I don't know why it suddenly popped up, but I didn't manage to load my app again since then.

You can find a repro with instructions here: https://github.com/schl3ck/vuejs-composition-api-issue-544

I think the issue is here in line 42. Shouldn't that be ``assert(constructor, `No vue dependency found.`)``?

https://github.com/vuejs/composition-api/blob/5484bb7fec15dfa8ac316c5266ef3cf00820b1a0/src/runtimeContext.ts#L38-L46

In my case `vueConstructor` is falsey and `vueDependency` has a value.

**Comment by dorianamouroux** [comment]
I had the same issue, it's because you are declaring any reactive elements (ref() / reactive()) before the plugin is installed in your Vue instance.

You can fixing by calling `Vue.use(VueCompositionAPI)` before importing any of your components/store

**Comment by schl3ck** [comment]
Thanks for the hint.

Rearranging the imports didn't solve the error, but I got it working by importing the views dynamically instead of at the top of `router/index.js`.

**Comment by azamat-sharapov** [comment]
This is happening starting release 1.0.1. I don't know what exactly is causing this, here are changes in that release: https://github.com/vuejs/composition-api/compare/v1.0.0...v1.0.1
