### ISSUE TITLE
Errors invoke by call "Vue.use" in window scope out of bundled Vue

### ISSUE THREAD

**Issue by dushon** [vuejs/composition-api#545]
Hi there,
I created standalone widgets using this library, but if widgets are imported into environment (project) where Vue is accessible in window object (e.g. other version than bundled vue ) widgets broke. The problem is on 26 line in index.tx. Would be possible to condition this code or do you have any idea how solve this problem?

Thx for reply.

https://github.com/vuejs/composition-api/blob/730da9664a798eac663e11aeebd8715604a0b47c/src/index.ts

**Comment by antfu** [comment]
What's the problem you are facing? Can you share a minimal reproduce repo?

**Comment by dushon** [comment]
Hi, sorry for my delayed reply..I created example in codesandbox(link below). For fix you need to comment seventh line. 

https://codesandbox.io/s/pedantic-lichterman-qkkul?file=/src/main.js
