### ISSUE TITLE
[TypeScript] Props type infer

### ISSUE THREAD

**Issue by GodofHope** [vuejs/composition-api#55]
I met a problems here. And here is my solution. I wonder if there is any other solution which is better?

```
props:{
  src: { type: String, required: true }
},
setup(props){
    onMounted(() => {
      const img = new Image(); // Create new Image instance

      img.src = props.src as unknown as string;

      ...
    });
}
```

**Comment by PatrykWalach** [comment]
1. If you don't need typescript types
```typescript
export default createComponent({
 
  setup(props) {
    return {}
  },
  props: {
    simple: {
      type: String,
      required: true
    },
  } as const
})

interface Props {
  simple: string
}
```
2. If you need typescript types

```typescript
export default createComponent({
 
  setup(props) {
    return {}
  },
  props: ({
    advanced: {
      required: true
    },
  } as const) as Props
})

interface Props {
  advanced: {
    a: string
    b: number
  }
}
```

**Comment by GodofHope** [comment]
THX very much

**Comment by GodofHope** [comment]
I still got error:

```
Conversion of type '{ readonly list: ArrayConstructor; }' to type 'Props' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'list' are incompatible.
    Type 'ArrayConstructor' is missing the following properties from type 'GridMenuList[]': pop, push, concat, join, and 27 more.Vetur(2352)
Conversion of type '{ readonly list: ArrayConstructor; }' to type 'Props' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Types of property 'list' are incompatible.
    Type 'ArrayConstructor' is not comparable to type 'GridMenuList[]'.
```

when

```ts

interface Props {
  list: GridMenuList[]
}

const DropdownGrid = createComponent({
  props: ({
    list: Array
  } as const) as Props,
  setup(props) {
  ...
```

So maybe I still need to convert to unknown first?

**Comment by PatrykWalach** [comment]
There was an error in my example, I've fixed it.

**Comment by GodofHope** [comment]
I got error when 

- `as unknown as Props as const`
- `as unknown as const as Props`

and no const effect when  `as const as unknown as Props`

So how should I do?

**Comment by GodofHope** [comment]
Oh thx, so when I want types I can not convert to const, is that right?

**Comment by GodofHope** [comment]
By the way, I don't think we need that parentheses(I am not sure whether I spell right). It seems ok when I remove it.

**Comment by PatrykWalach** [comment]
I don't use `as const` with `interface Props` If you want to be sure to not assign to props I think you can do `as unknown as Readonly<Props>`

**Comment by PatrykWalach** [comment]
My linter adds parenthesis but It's not required

**Comment by liximomo** [comment]
@GodofHope Try v2.2.0.

**Comment by GodofHope** [comment]
🆗，I'll try ^-^

**Comment by GodofHope** [comment]
Excuse me ,waht's impoving? I cannot feel any enhancement. Could you tell me more specificitly?

**Comment by GodofHope** [comment]
I stitll catch error whtn writing originally, yet I still needs to convert to unknown

**Comment by liximomo** [comment]
@GodofHope Can you show me your codes?

**Comment by ycmjason** [comment]
Here is a really ugly hack to help with declaring required props.

https://github.com/ycmjason/perfect-colour/blob/master/src/helpers/vue-types.ts

Usage:

```ts
{
  props:{
    src: RequiredProp(String),
    awesome: RequiredProp<'amazing' | 'cool'>(String),
  },
}
```

Hope it helps.
