### ISSUE TITLE
Bug: PropType not working on some types

### ISSUE THREAD

**Issue by Mister-Hope** [vuejs/composition-api#555]
Vue3:

![image](https://user-images.githubusercontent.com/33315834/95451440-5aec9600-099a-11eb-82ae-1a2f353c06ce.png)

---

composition-api:

![image](https://user-images.githubusercontent.com/33315834/95451547-866f8080-099a-11eb-9b2d-903143b7b1a8.png)

Could this be fixed?

**Comment by IndexXuan** [comment]
@Mister-Hope 
Bro, PropType<'foo' | 'bar'> works but PropType<1 | 2> still not working, just number result

**Comment by Mister-Hope** [comment]
> @Mister-Hope
> Bro, PropType<'foo' | 'bar'> works but PropType<1 | 2> still not working, just number result

Could you try it in Vue3 and see if it works?

**Comment by Mister-Hope** [comment]
Hey bro @IndexXuan I ask a friend to test it for me.

![image](https://user-images.githubusercontent.com/33315834/98539425-45cf9380-22c7-11eb-9a1f-56c36aa17f53.png)
![image](https://user-images.githubusercontent.com/33315834/98539446-4ff19200-22c7-11eb-92ba-c22b45e7f079.png)
![image](https://user-images.githubusercontent.com/33315834/98539470-58e26380-22c7-11eb-9af6-951ad86d50bd.png)

It seems that it's working well.

**Comment by IndexXuan** [comment]
@Mister-Hope amazing, it works, thanks a lot !
