### ISSUE TITLE
should i look forward to script setup?

### ISSUE THREAD

**Issue by cereschen** [vuejs/composition-api#556]
Is it possible to support it for vue2?

**Comment by Mister-Hope** [comment]
It is not possible to get fully support, just see readme. Vue 3 is using proxy, and some of the features can not  be done under Vue 2 useing getter and setters.

**Comment by danielroe** [comment]
I think this should be possible for Vue 2 - it's a matter for vue-loader.

**Comment by antfu** [comment]
This is out-of-scope of this project. Please file an issue to vue-compiler. Thanks.

**Comment by lizy0329** [comment]
> This is out-of-scope for this project. Please file an issue to vue-compiler instead. Thanks.

What is vue-compiler? It that mean [vue-component-compiler](https://github.com/vuejs/vue-component-compiler)? or other?

**Comment by cereschen** [comment]
You are right, but still need defineProps useContext and so on.
