### ISSUE TITLE
Cannot find module 'vue/types/umd', cannot use namespace 'Vue' as a type with TypeScript

### ISSUE THREAD

**Issue by bbugh** [vuejs/composition-api#569]
When adding @vue/composition-api and installing the plugin in a non-CLI project, we have these typescript errors:

```
TS2307: Cannot find module 'vue/types/umd'.
TS2709: Cannot use namespace 'Vue' as a type.
```

Here's an example from our CI: 
```
ERROR in /home/circleci/circleci-build/node_modules/@vue/composition-api/dist/index.d.ts
ERROR in /home/circleci/circleci-build/node_modules/@vue/composition-api/dist/index.d.ts(2,52):
TS2307: Cannot find module 'vue/types/umd'.

ERROR in /home/circleci/circleci-build/node_modules/@vue/composition-api/dist/index.d.ts
ERROR in /home/circleci/circleci-build/node_modules/@vue/composition-api/dist/index.d.ts(99,141):
TS2709: Cannot use namespace 'Vue' as a type.
```

I've tried replacing every instance of `Vue.extend` with `defineComponent` and that hasn't changed either. The code works, but I can't find any way to get past this TypeScript error.

**Other potentially related info**

- We are using `babel-preset-typescript-vue`, upgrading to latest did not work
- We're not using the class API, just basic object API
- We're not using `import * as Vue from 'vue'`, just `import Vue from 'vue'`
- Vue is aliased in webpack to `'vue': 'vue/dist/vue.runtime.esm.js',`
- It's not this `vue-typed` issue: https://github.com/vue-typed/vue-typed/issues/23 because we're not using this library, but maybe it will help?
- We're not using Vuex, so it's not this: https://github.com/vuejs/vue-next/issues/1042
- As mentioned [here](https://github.com/vuejs/vue-router/issues/960#issuecomment-270049860), upgrading to the latest `vue-router` did not work

**Comment by bbugh** [comment]
There was a combination of issues between these packages that upgrading them all resolved:

```
yarn upgrade --latest babel-preset-typescript-vue vue vue-template-compiler vuelidate @types/vuelidate
```

**Comment by fxxjdedd** [comment]
For those who cannot upgrade Vue, I found this way:

https://gist.github.com/fxxjdedd/f4dceac2917f0cf57953511b73cea1aa
