### ISSUE TITLE
Object API "this" is not defined on types with defineComponent

### ISSUE THREAD

**Issue by bbugh** [vuejs/composition-api#570]
We're incrementally adding the composition-api using `defineComponent`, and ran into a snag with one of our components that uses `$route` in the `data` function:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/438465/96373183-61b0a100-1130-11eb-9099-d8caf849634f.png">

This code works fine with `defineComponent`, it's just the typing that doesn't.

Possibly related to https://github.com/vuejs/composition-api/issues/338?

**Comment by antfu** [comment]
Can you share a reproduction on CodeSandbox? It looks fine to me.

**Comment by bbugh** [comment]
Sure, here's a [reproduction CodeSandbox](https://codesandbox.io/s/vue-template-forked-fsty6?file=/src/App.vue). The error appears in App.vue. 

<img width="290" alt="image" src="https://user-images.githubusercontent.com/438465/96804782-96915200-13d5-11eb-92f9-2657f3e370e4.png">


<img width="690" alt="image" src="https://user-images.githubusercontent.com/438465/96804670-4c0fd580-13d5-11eb-9033-15351dcbcc41.png">

**Comment by meschg** [comment]
Hello,
I come to this issue through #338 #406 but I am not sure which issue is the right one - sorry :/. 
Code execution is working in Browser without any error just VS Code does not know what to make out of it...
![20201031_112625_type-comp-error](https://user-images.githubusercontent.com/5106318/97776956-d4783e00-1b6c-11eb-9c2a-29e7dba09087.png)

"minimal" sample project:
https://github.com/meschg/vue-stack-cesium/blob/53755243c08f36ea1c3a93181ef8b643556ef81c/src/components/HelloCompositionAPIExternal.vue#L65

Thanks for all your effort!
kind regards

**Comment by pikax** [comment]
@meschg the reason is because of your `computed: mapState` is breaking the types. That's a known typescript issue with vue, nothing can be done aside of setting a type to it.

**Comment by meschg** [comment]
> 
> 
> @meschg the reason is because of your `computed: mapState` is breaking the types. That's a known typescript issue with vue, nothing can be done aside of setting a type to it.

@pikax Ah good to know - wasn't sure. But I think your answer will also help others with the same error :). Thank you
