### ISSUE TITLE
How can I change the properties of a child component dynamically?

### ISSUE THREAD

**Issue by SoldorosGit** [vuejs/composition-api#574]
I write a parent component like 
```
<div>
  <slot></slot>
</div>
```
 and it has props
```
props:{
  color:string
}
```
A child component like
```
<div>
  <p></p>
</div>
```
now I write a button to change the props color and watch the props color in parent component,
how can I change the p color in parent component or let the child component know I have changed the color

**Comment by antfu** [comment]
Can you share a reproduction?

**Comment by LinusBorg** [comment]
I don't see how this is related to this plugin.

**Comment by SoldorosGit** [comment]
vue 2.x  I can write
```
 props: {
            separator: {
                type: String,
                default: '/'
            }
        },
methods:{
  updateChildren () {
                this.$children.forEach((child) => {
                    child.separator = this.separator;
                });
            }
},
watch: {
            separator () {
                this.updateChildren();
            }
        }
```
but vue 3.0 I can't get $children and provide can only write in setup

**Comment by LinusBorg** [comment]
So this is related to $children being removed in Vue 3?

Then not relevant to this plugin. Open an issue in the vue-next repo or use chat vuejs.org to ask for help how to solve the problem in Vue 3.
