### ISSUE TITLE
fix release notes for v.0.6.0: missing breaking change

### ISSUE THREAD

**Issue by carsoli** [vuejs/composition-api#577]
https://github.com/vuejs/composition-api/pull/311 
> Breaking
> Watch effect now follows the same behaviour as v3

could you maybe include this change in [release notes](https://github.com/vuejs/composition-api/releases/tag/v0.6.0) for 0.6.0?

**Comment by antfu** [comment]
I think we have covered that part

https://github.com/vuejs/composition-api/blob/master/CHANGELOG.md#breaking-change

![image](https://user-images.githubusercontent.com/11247099/97286321-51aa6700-187e-11eb-8832-bbad14e71db9.png)

**Comment by carsoli** [comment]
there is no mention of the changes to `watchEffect`, only the changes to `watch` options, two different things here.
please check the PR I linked in the first line.

**Comment by carsoli** [comment]
https://github.com/vuejs/composition-api/pull/311/commits/d6af20e410d51220ac4be3a4d4f0db86d371f478#diff-90b36b2aed04378af8cdb81032a8854cdaba402e4fd10eae4f4bf0b73727f880R86-R96 

the function actually implmenets `watchEffect` as intended --> (immediately invoked) 
this change alone was breaking to a project, and we had to make sure we are tackling the now-immediate `watchEffect` with data that is only available on mounting

**Comment by antfu** [comment]
Mind making a PR to add the changelog? Thanks.

**Comment by carsoli** [comment]
i can't request changes to releases/tag/0.6.0.

i think it needs to align with `CHANGELOG.md`

**Comment by pikax** [comment]
updated https://github.com/vuejs/composition-api/releases/tag/v0.6.0

thank you
