### ISSUE TITLE
provide at root component

### ISSUE THREAD

**Issue by yoyoys** [vuejs/composition-api#583]
```js
const plugin = {
  install: app => {
    const instance = myInstance();
    // !! Property 'provide' does not exist on type 'VueConstructor<Vue>'.ts(2339)
    app.provide('getMyInstance', instance);
    console.log(app)
  },
};
```
Is there any way to provide an instance to root component at Vue2 plugin installation?

This is useful for vue3 plugin develop, but I can only get options 😔 .

**Comment by kiroushi** [comment]
You will probably have to follow a strategy based on mixins (which will run on all components), while checking `$options` to look for you parent and provide there (you will probably want to have a `isProvided` flag to make sure it only happens once at your root component).

A similar approach is commonly taken among many Vue 2 plugins, including [Vuex](https://github.com/vuejs/vuex/blob/c9dbb13d4138d0e7d82d103dd3275fc18fa72d28/dist/vuex.js#L12-L46) and [vue-router](https://github.com/vuejs/vue-router/blob/dev/src/install.js#L21-L36).
