### ISSUE TITLE
Ref and Reactive don't work well after build as lib

### ISSUE THREAD

**Issue by frank994** [vuejs/composition-api#587]
Ref and reactive has lost their reactivity after use vue-cli-service build
      as a lib
[with el-input(element-ui)](https://codesandbox.io/s/billowing-dawn-6ihhf?file=/src/App.vue)
[plain input](https://codesandbox.io/s/trusting-dewdney-401m3?file=/src/App.vue)
What should I do with composition-api used in an ui library?

**Comment by antfu** [comment]
What's your libs source code?

**Comment by frank994** [comment]
inside packages folder.

**Comment by frank994** [comment]
inside the packages: source code,
lib contains the files I've build locally.
It blocks me, plz reply to me asap, Thanks very much.

**Comment by antfu** [comment]
Can't build your code locally

```
 ERROR  Failed to compile with 1 errors                                                                                                      2:56:02 PM

This relative module was not found:

* ./packages/vantop-ui in ./index.js
```

**Comment by frank994** [comment]
Just recorrect some spelling error and have checked it, plz retry it [plain input](https://codesandbox.io/s/trusting-dewdney-401m3?file=/packages/plain-input/src/plain-input.vue).

**Comment by shaydoc** [comment]
Same issue here, i built this as a commonjs, externalized vue and composition api, npm link and installed in my App, the reactivity just isn't working

```
<template>
  <div>
    <button @click="inc2">
      Increment {{ count2 }}
    </button>
    <button @click="inc">
      Composition Api Increment {{ state.count }}
    </button>
  </div>
</template>

<script>
import { defineComponent, reactive } from 'vue-demi';

export default defineComponent({
  setup() {
    const state = reactive({ count: 0 });

    return {
      state,
      inc() {
        state.count += 1;
      },
    };
  },
  data() {
    return {
      count2: 0,
    };
  },
  methods: {
    inc2() {
      this.count2 += 1;
    },
  },
});
</script>

```

```
import Demo from '@/components/Demo';
 
export { Demo };
 
function install(Vue) {
  Vue.component('Demo', Demo);
}

// Export the library as a plugin
// @vue/component
export default { install };
```

**Comment by noook** [comment]
I'm interested as well in how to resolve this issue, this is quite blocking.

I was wondering, what's the externalization thing, and how could that help us here ?

**Comment by noook** [comment]
It seems I finally managed to make it work by using this portions of code in `vue.config.js`

```js
module.exports = {
  chainWebpack: (config) => {
    config.externals({
      ...config.get('externals'),
      '@vue/composition-api': '@vue/composition-api',
      vue: 'vue',
    });
  },
};
```

**Comment by antfu** [comment]
Close for now as a solution for the problem is provided.
