### ISSUE TITLE
Doesn't generate `props` type when using interfaces with all optional fields

### ISSUE THREAD

**Issue by Razi91** [vuejs/composition-api#588]
Plugin doesn't define `props` type correctly, when one of props type is casted as `Partial` (or just interface/type with all fields optional)

```ts
import { defineComponent, PropType } from "@vue/composition-api";

interface Foo {
  foo: string;
  bar: number;
}
const Component = defineComponent({
  name: "FooComponent",
  props: {
    foo: {
      type: Object as PropType<Partial<Foo>>,
    },
  },
  setup(props) {
    console.log(props.foo.bar);
  },
});
```
The same code works with Vue 3 correctly

**Comment by jacekkarczmarczyk** [comment]
Looks ok for me
![image](https://user-images.githubusercontent.com/15625235/98666342-2e3aee00-234d-11eb-9db4-c91d56cc2c57.png)

**Comment by Razi91** [comment]
It doens't look ok, it says that `props` is `undefined`, while it should be defined. If you remove `Partial` part, or add any field to Foo that is not optional, it works fine.

```ts
interface Foo {
  foo?: string;
  bar?: number;
}
const Cmp = defineComponent({
  name: "FooComponent",
  props: {
    foo: {
      type: Object as PropType<Foo>,
      required: true
    },
  },
  setup(props) {
    console.log(props.foo.bar);
  },
});
```

vs

```ts
interface Foo {
  foo: string;
  bar?: number;
}
const Cmp = defineComponent({
  name: "FooComponent",
  props: {
    foo: {
      type: Object as PropType<Foo>,
      required: true
    },
  },
  setup(props) {
    console.log(props.foo.bar);
  },
});
```

First one throws that `props` is undefined, second gives access to `bar` without problem.

**Comment by jacekkarczmarczyk** [comment]
> it says that props is undefined

No, it says that `props.foo` can be `undefined` (not `props`), which is fine because this prop is optional
Your code from the issue description doesn't have `required: true`

**Comment by Razi91** [comment]
Right, my bad, I forgot about `required: true` in first one.
```ts
interface Foo {
  foo: string;
  bar: number;
}
const c = defineComponent({
  name: "FooComponent",
  props: {
    foo: {
      type: Object as PropType<Partial<Foo>>,
      required: true,
    },
  },
  setup(props) {
    console.log(props.foo.bar);
  },
});
```
Now the error is:
`TS2339: Property 'bar' does not exist on type 'unknown'.`
but `required: true` states that `foo` must not be unknown and is `Partial<Foo>`

**Comment by jacekkarczmarczyk** [comment]
Still works fine for me, no errors in IDE or in TS console

![image](https://user-images.githubusercontent.com/15625235/98670244-b40d6800-2352-11eb-9c9d-8f8776606767.png)
![image](https://user-images.githubusercontent.com/15625235/98670265-c12a5700-2352-11eb-85b6-6a58a268b563.png)
![image](https://user-images.githubusercontent.com/15625235/98670358-e3bc7000-2352-11eb-8f9d-fe2f6c16a942.png)

Maybe TS version issue?

**Comment by Razi91** [comment]
I guess it's tsconfig problem:

```
{
  "extends": "@quasar/app/tsconfig-preset",
  "compilerOptions": {
    "baseUrl": "./",
    "experimentalDecorators": true,
    "target": "es5",
    "allowJs": true,
    "sourceMap": true,
    "lib": ["esnext", "dom"],
    "module": "esNext",
    "strict": true,
    "strictNullChecks": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "resolveJsonModule": true,
    "importHelpers": true,
    "suppressImplicitAnyIndexErrors": true,
    "typeRoots": ["node_modules/@types"]
  },
  "include": [
    "./src/**/*.js",
    "./src/**/*.ts",
    "./src/**/*.vue",
    "*.js"
  ],
  "exclude": [
    "node_modules",
    "./**/*.spec.ts",
    "./test/**.js",
    "./test/**.ts"
  ]
}

```
I still have errors even or 4.1.1-rc (I had latest stable 4.0.5)

**Comment by sufengyong** [comment]
Have you solved the problem？
