### ISSUE TITLE
tsx 环境下 v-model不生效

### ISSUE THREAD

**Issue by CharlieLau** [vuejs/composition-api#589]
求助大佬🧍‍♂️
在tsx 环境下 v-model 不生效  
```
import { defineComponent, ref } from 'vue-demi'

export const Hello2Component = defineComponent({
  props: {
    a: String
  },
  setup(props) {
    const text = ref(props.a)
    return () => (
      <div>
        {/* 不生效 */}
        <input v-model={text.value} ></input>
        {/* 生效 */}
        <input value={text.value} on-input={e => text.value = e.target.value}></input>
      </div>
    )
  }
})

```
.babelrc 配置
```
{
  "presets": [
    "@babel/env",
    "@babel/preset-typescript",
    [
      "@vue/babel-preset-jsx",
      {
        "vModel": false,
        "compositionAPI": true
      }
    ]
  ],
  "plugins": [
    [
      "@babel/plugin-proposal-decorators",
      {
        "legacy": true
      }
    ],
    "@babel/proposal-class-properties",
    "@babel/proposal-object-rest-spread"
  ]
}
```

**Comment by danielroe** [comment]
@CharlieLau Shouldn't that be `vModel`? And haven't you disabled the vModel directive in `.babelrc`? (See [more info](https://github.com/vuejs/jsx/blob/dev/packages/babel-sugar-v-model/README.md).)

I don't think this is an issue with the Composition API plugin.

**Comment by CharlieLau** [comment]
readme  tell me can  follow this:  https://github.com/vuejs/jsx/tree/dev/packages/babel-preset-jsx#usage

when  i  set  
.babelrc
```
// "vModel": false,
  "plugins": [
    "module:@vue/babel-sugar-v-model",
    ...
]
```
hello.tsx
```
...
export const Hello2Component = defineComponent({
  props: {
    a: String
  },
  setup(props) {
    const text = ref(props.a)
    return () => (
      <div>
        <input vModel={text.value} ></input>
      </div>
    )
  }
})
```

but, errors:
[!] (plugin babel) TypeError: */packages/kabuta-mtd/src/hello.tsx: Cannot read property 'body' of undefined
@nibfe/xx-package: src/hello.tsx
@nibfe/xx-package: TypeError: */packages/kabuta-mtd/src/hello.tsx: Cannot read property 'body' of undefined
@nibfe/xx-package:     at MemberExpression (*/node_modules/@vue/babel-sugar-composition-api-render-instance/dist/plugin.js:1:1179)
@nibfe/xx-package:     at NodePath._call (*/node_modules/@babel/traverse/lib/path/context.js:55:20)
@nibfe/xx-package:     at NodePath.call (*/node_modules/@babel/traverse/lib/path/context.js:42:17)
@nibfe/xx-package:     at NodePath.visit (*/node_modules/@babel/traverse/lib/path/context.js:92:31)
@nibfe/xx-package:     at TraversalContext.visitQueue (*/node_modules/@babel/traverse/lib/context.js:112:16)
@nibfe/xx-package:     at TraversalContext.visitSingle (*/node_modules/@babel/traverse/lib/context.js:84:19)
@nibfe/xx-package:     at TraversalContext.visit (*/node_modules/@babel/traverse/lib/context.js:140:19)

**Comment by LemonAppleMo** [comment]
use this -> https://github.com/luwanquan/babel-preset-vca-jsx

**Comment by antfu** [comment]
Keep track on https://github.com/vuejs/jsx/issues/169 instead. Closing.

**Comment by LancerComet** [comment]
Please take a look on this:

https://github.com/vuejs/jsx/issues/169#issuecomment-772315535
