### ISSUE TITLE
SetupContext `attrs` doesn't contain `listeners`

### ISSUE THREAD

**Issue by Edge00** [vuejs/composition-api#590]
According to the document https://vue-composition-api-rfc.netlify.app/api.html#setup  
```typescript
interface Data {
  [key: string]: unknown
}

interface SetupContext {
  attrs: Data
  slots: Slots
  emit: (event: string, ...args: unknown[]) => void
}

function setup(props: Data, context: SetupContext): Data
```
There is no listeners in SetupContext.  
So i  use `v-bind="attrs"` to pass event to component.  
But event listeners didn't passed to component.

Will this usage be aligned at vue3 or keep it is now?

**Comment by pikax** [comment]
Can you provide reproduction code and show what you trying to achieve?

**Comment by Edge00** [comment]
> Can you provide reproduction code and show what you trying to achieve?

I'm trying to pass events to component by using `v-bind="$attrs"` like this:
```vue
<template>
  <label>
    <input type="text" v-bind="$attrs" />
  </label>
</template>
<script>
export default {
  inheritAttrs: false
}
</script>
```
However it doesn't work.
Referance: https://v3.vuejs.org/guide/migration/listeners-removed.html#_3-x-syntax

**Comment by antfu** [comment]
@pikax I think they are taking about this:

```html
<input v-bind="$attrs" v-on="$listeners">
```

where `$lisnters` get removed in Vue 3

@Edge00 I think this is a misalignment and probably can't be polyfilled by this plugin. You might need to keep using the $ prefixed variables in the templates of Vue 2 at this moment and do the migration when upgrading to Vue 3.

**Comment by Edge00** [comment]
> @pikax I think they are taking about this:
> 
> ```
> <input v-bind="$attrs" v-on="$listeners">
> ```
> 
> where `$listeners` get removed in Vue 3
> 
> @Edge00 I think this is a misalignment and probably can't be polyfilled by this plugin. You might need to keep using the $ prefixed variables in the templates of Vue 2 at this moment and do the migration when upgrading to Vue 3.

Exectly. it would be great if this usage can be aligned at Vue 3.

**Comment by ZouMagic** [comment]
遇到了同样的问题 ，现在修复了吗 通过v-on 绑定事件 setupContext 没有检测到我的 listeners

**Comment by vilbergs** [comment]
It's a bit strange that these values are not accessible anymore. We have multiple cases where we explicitly call the listeners in order to access their return values. It seems we have no other choice but to refactor these functions to be props.
