### ISSUE TITLE
Private fields cause type errors on ref values

### ISSUE THREAD

**Issue by fango256** [vuejs/composition-api#591]
We have a fairly large vue/typescript project that occasionally runs into type issues when working with the composition api. I think it has something to do with private fields going through Ref/UnwrapRef. I think our usage is valid, but we are still getting to grips with it.

In the code below the myArray variable throws up the following error with TS 4.0.5:

```
import { ref } from "@vue/composition-api";

class MyClass {
  private memberVariable: string = "";
}

const myArray: MyClass = ref(new MyClass()).value;
         ^^ TS2741: Property 'memberVariable' is missing in type '{}' but required in type 'MyClass
```

**Comment by jacekkarczmarczyk** [comment]
Likely related to https://github.com/vuejs/vue-next/issues/2557

**Comment by antfu** [comment]
Close for now in favor of https://github.com/vuejs/vue-next/issues/2557, please continue the discussion there. If it gets resolved and the patch gets shipped, we can then update this plugin to match their behavior.
