### ISSUE TITLE
getCurrentInstance is not available inside lifecycle hooks for Options API

### ISSUE THREAD

**Issue by SeregPie** [vuejs/composition-api#592]
Works for Vue 3.
https://codepen.io/SeregPie/pen/QWERRKd

Does not work for Vue 2.
https://codepen.io/SeregPie/pen/YzWbbpo

Why is this important?
For example for plugins that support both Composition API and Options API.

**Comment by pikax** [comment]
it only works on the lifecycles in the `setup`, for the Options API lifecycle please use `this`

```js

  setup(){
    onMounted(()=> {
        console.log(getCurrentInstance() === null);
    })
    return {}
  }
```
