### ISSUE TITLE
defineComponent 返回的组件类型与v3不一致 

### ISSUE THREAD

**Issue by zzzz-Z** [vuejs/composition-api#598]
使用泛型传递props时 获取不到props的类型 
![image](https://user-images.githubusercontent.com/28984303/100094678-5883c400-2e94-11eb-9d1c-1d9e671f3373.png)
![image](https://user-images.githubusercontent.com/28984303/100094739-718c7500-2e94-11eb-9fed-c0b9886881d4.png)
![image](https://user-images.githubusercontent.com/28984303/100094769-79e4b000-2e94-11eb-8bcf-d8399292fed6.png)
![image](https://user-images.githubusercontent.com/28984303/100094801-879a3580-2e94-11eb-8314-d1efae74c702.png)

**Comment by pikax** [comment]
Describing props by a interface is not supported, is not valid vue too, because if you are passing something that's not described on the `props` it will be available on `$attrs`
