### ISSUE TITLE
Provides functionality common to all JavaScript objects.

### ISSUE THREAD

**Issue by likeswinds** [vuejs/composition-api#606]
``` vue 

import { defineComponent, PropType } from '@vue/composition-api'
import { ComponentOption } from '@dx/shared'

export default defineComponent({
  props: {
    component: {
      type: Object as PropType<ComponentOption>
    }
  }
}
```
eslint error ?

![image](https://user-images.githubusercontent.com/7099174/100982976-a7f87d00-3583-11eb-8958-a329db7c0397.png)

**Comment by antfu** [comment]
Make sure you are using TypeScript and your issue does not relate to this project. Ask questions on Stackoverflow, Discord or forum next time.

**Comment by danielroe** [comment]
@likeswinds Yes, that is an eslint issue, nothing to do with the composition API. Make sure your eslint understands TypeScript - see https://github.com/typescript-eslint/typescript-eslint

**Comment by likeswinds** [comment]
Sorry and thanks @danielroe , problem solved , `parserOptions.parser:'babel-eslint' `  ->  `parserOptions.parser:'@typescript-eslint/parser' `
