### ISSUE TITLE
test variable with Jest and Vue 3 composition api 

### ISSUE THREAD

**Issue by Giova262** [vuejs/composition-api#608]
Hello!

i m trying make a test for a variable but i get undefined when i try access to the value

**Component where i defined the variable**

setup(props, context) {
    const name = ref('Josue');
    return {
      name,
    }
 }

**TEST**

import { mount, createLocalVue, shallowMount } from '@vue/test-utils'
import QBUTTON from './demo/QBtn-demo.vue'
import index from '../../../src/pages/Index.vue'
import * as All from 'quasar'
import compositionApi from '@vue/composition-api';

const localVue = createLocalVue()
localVue.use(compositionApi)

describe('Index', () => {
  it('is a Vue instance',async () => {
    const wrapper = mount(index, { localVue })
    await wrapper.vm.$forceUpdate();
    expect(wrapper.vm.$data.nombre).toBe('Josue')
  })
})

**ERROR**

  Expected: "Josue"
  Received: undefined

      116 |     const wrapper = mount(index, { localVue })
      117 |     await wrapper.vm.$forceUpdate();
    > 118 |     expect(wrapper.vm.$data.nombre).toBe('Josue')
          |                                     ^
      119 |   })
      120 | })

i got undefined from wrapper.vm.$data.nombre , but if i use 

data () {
    return {
      name: 'Josue',
    }
},

it Work, i dont know how access to a variable when i use composition api

**Comment by antfu** [comment]
Shouldn't that be `expect(wrapper.vm.$data.name).toBe('Josue')`?

**Comment by alvarosaburido** [comment]
If you are using the Vue 3 support version for Vue Test Utils (2.0.0-beta.10) along with a `setup` function (Using composition API)  be aware that `vm` will not have the `const name = ref('Josue');` in your data `vm.$data`.

Quoting from [Knowing what tot test](https://vue-test-utils.vuejs.org/guides/#knowing-what-to-test):

**Comment by jcjp** [comment]
As for me I was able to access my data directly referencing it from `wrapper.vm`, here is my code:

```TypeScript
describe('lifecycle: onBeforeMount', () => {
    it('should be able to get the page terms content from contentful upon load', async() => {
      await createComponent()
      expect(wrapper.vm.myData.value).toBe(expectedObject)
   })
})
````

```TypeScript
setup() {
  const myData= reactive({value: {}})

  onBeforeMount(async() => {
   const {$graphql} = useContext()
   const query = ... // omitted for privacy reason

   myData.value = await $graphql.default.request(query)
   console.log(myData.value) // This has value in unit test
  })

  console.log(myData.value) // This has no value in unit test

  return {
    myData
  }
},
```

This is working as expected on my browser when visiting my local website, however I am running into an error in unit test. It seems that a property of the value is undefined however it is render properly on the browser with no error.

**Comment by jcjp** [comment]
I solve my unit test problem here is the link to my solution: [help: reactive data not properly set in Jest unit test](https://github.com/nuxt-community/composition-api/issues/477#issuecomment-839464264)

**Comment by rulrok** [comment]
In my case, my inspecting the `vm.$data` (which also contained the values) I accidentally discovered that jest was running with a cached version of my previous code that I changed.

I ran 
> npx jest --clearCache

and the `vm.[mydata]` worked without having to use `vm.$data.[mydata]`
