### ISSUE TITLE
Defining unknown properties as exist properties is wrong

### ISSUE THREAD

**Issue by yoyo930021** [vuejs/composition-api#609]
From https://github.com/vuejs/vetur/issues/2505

The `@vue/composition-api` define unknown properties as exist properties.

Wrong:
https://user-images.githubusercontent.com/15092120/100864081-cb44fe80-3495-11eb-8fa2-abd0a9e049ea.png

Wanted:
https://user-images.githubusercontent.com/15092120/101005269-16781380-3561-11eb-8ab7-f54982776e84.png

**Comment by pikax** [comment]
Can you provide a reproduction, from the issue mention it seems it's been using `@nuxtjs/composition-api` and `nuxt-property-decorator`.

If you can provide an reproduction of using `@vue/composition-api` it would be great

**Comment by yoyo930021** [comment]
> Can you provide a reproduction, from the issue mention it seems it's been using `@nuxtjs/composition-api` and `nuxt-property-decorator`.
> 
> If you can provide an reproduction of using `@vue/composition-api` it would be great

Repro case:
https://github.com/yoyo930021/vue2-composition-api-unknown-property

![Dec-07-2020 18-29-46](https://user-images.githubusercontent.com/9126398/101340065-376e9a80-38ba-11eb-96d8-164527d8c19a.gif)
