### ISSUE TITLE
Using a vue-2 composition-api component in a Vue 3 project

### ISSUE THREAD

**Issue by scottnath** [vuejs/composition-api#612]
I have created some components using the composition-api in a project which uses Vue 2.
I want to import those components into a Vue 3 project, but I'm getting the following error:

`Uncaught (in promise) Error: [vue-composition-api] No vue dependency found.`

In my Vue-2 project, the components are generally written like so:

```
import { defineComponent, computed, ref } from '@vue/composition-api';

export default defineComponent({
  props: {
    name: String,
  },
  setup (props) {
...
```

Is there a way to import components written in this way into a Vue-3 project?

If not, is there a way to write components using composition-api that would allow them to work in both projects?

note: I'm trying to have a _single_ shared repo that feeds components to both projects.

thank you!

**Comment by pikax** [comment]
Is not possible to use `@vue/composition-api` on a vue3 project, since vue3 has already composition-api built in.

You can have a look on [vue-demi](https://github.com/antfu/vue-demi) which exports the correct API based on the vue package dependency.
