### ISSUE TITLE
vuex-composition-helpers stopped working with beta.22

### ISSUE THREAD

**Issue by Landen13** [vuejs/composition-api#616]
`vuex-composition-helpers` stopped working since `@vue/composition-api` `beta.22`

![image](https://user-images.githubusercontent.com/3704014/102900894-9b29c380-4475-11eb-8cc6-3924c6aaa7a9.png)

![image](https://user-images.githubusercontent.com/3704014/102900963-af6dc080-4475-11eb-87bf-5fa8ab9abe0e.png)

**Comment by pikax** [comment]
There was breaking changes on the last release, please open an issue on the `vuex-composition-helpers` 

https://github.com/vuejs/composition-api/blob/master/CHANGELOG.md#breaking-changes
