### ISSUE TITLE
【Bug】vue-composition-api.esm.js?a6f4:37 Uncaught Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.

### ISSUE THREAD

**Issue by djkloop** [vuejs/composition-api#621]
```sh

# I have used it first at the top of main.js, but the browser still reports an error

```
![image](https://user-images.githubusercontent.com/21050914/103403781-5811d380-4b8c-11eb-8e35-f73701e81826.png)

![image](https://user-images.githubusercontent.com/21050914/103403823-7972bf80-4b8c-11eb-9ca3-a12eab6c155d.png)

**Comment by pikax** [comment]
You're most likely using `ref`/`reactive` outside setup or before vue is initialized.

```ts
// composables/test.ts
import { ref } from '@vue/composition-api'

const store = ref({}) // <- this will cause an error, because javascript will run before vue is initialized.

function useStore(){
 return ref({}) // works if called inside of setup or after vue initialized
}
```

**Comment by sibbng** [comment]
I think line 4 must be after the imports.

**Comment by djkloop** [comment]
> You're most likely using `ref`/`reactive` outside setup or before vue is initialized.
> 
> ```ts
> // composables/test.ts
> import { ref } from '@vue/composition-api'
> 
> const store = ref({}) // <- this will cause an error, because javascript will run before vue is initialized.
> 
> function useStore(){
>  return ref({}) // works if called inside of setup or after vue initialized
> }
> ```

you are right...

**Comment by GeekyMonkey** [comment]
What's the fix if I need to have a global ref variable?
