### ISSUE TITLE
Bumping to newest version (beta.22) broke pages

### ISSUE THREAD

**Issue by kepi0809** [vuejs/composition-api#623]
Hi guys, first of all nice work and keep up the good work :+1: 

The following MR broke our pages where composition API was used with vue-i18n together:
`Bump @vue/composition-api from 1.0.0-beta.21 to 1.0.0-beta.22`

When we update to the latest version then the following code won't work:
```js
    const vm = getCurrentInstance();
    const translation = vm.$i18n.t(...)
```

$i18n will be undefined, maybe the approach I was doing is wrong, but this is the only one way being suggested everywhere. 

Thanks for you help in advance!

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/composition-api/releases/tag/v1.0.0-beta.22

**Comment by kepi0809** [comment]
oh sorry for the waste of your time :grimacing:
