### ISSUE TITLE
Export ExtractPropTypes for shared props

### ISSUE THREAD

**Issue by kiroushi** [vuejs/composition-api#628]
It would be good that this type was exported so it could help with props that are shared with other components (formerly mixins).

Example use case:

```ts
export const sharedProps = {
  disabled: Boolean,
}

export function getSharedPropBindings (props: ExtractPropTypes<typeof sharedProps>) {
  return computed(() => ({
    disabled: props.disabled,
  }))
}
```

Later in component:

#### Script
```ts
import { sharedProps, getSharedPropBindings } from './sharedProps'

// setup block
const sharedPropBindings = getSharedPropBindings(props)
```

#### Template
```html
<component v-bind="sharedPropBindings" />
````

**Comment by antfu** [comment]
vue-next exports it as well. I don't see any reason why we shouldn't. Would you like to draft a PR for it? Thanks.

**Comment by antfu** [comment]
Heading for a release, I will fix it for now. Thanks!

**Comment by kiroushi** [comment]
Apologies @antfu, was pretty busy and I couldn’t find a spot to get with it. Thanks for taking care of it 💪
