### ISSUE TITLE
`toRefs` result assigned to a `ref` unwraps to plain object

### ISSUE THREAD

**Issue by IlCallo** [vuejs/composition-api#629]
Keywords: ref, toRefs, shallowRef, reactive

```js
    const pojo = ref({});
    const reactivePojoRefs = ref({});

    watch(pojo, (newPojo) => {
      // cloneDeep taken from lodash, safeguard since `reactive` mutates object when using composition API
      const clonedPojo = cloneDeep(newPojo);
      const pojoRefs = toRefs(reactive(clonedPojo));

      console.log(cloneDeep(pojoRefs)); // outputs: { first: RefImpl, second: RefImpl, third: RefImpl }

      reactivePojoRefs.value = pojoRefs;

      console.log(reactivePojoRefs.value); // outputs: { first: 'value', second: 4, third: undefined }

      console.log(reactivePojoRefs.value === newPojo); // outputs: false
      console.log(reactivePojoRefs.value === clonedPojo); // outputs: false
      console.log(reactivePojoRefs.value === pojoRefs); // outputs: true
    });

    pojo.value = {
      first: "value",
      second: 4,
      third: undefined,
    };
```

The intent of the code is to take an object which can change at execution time, via `pojo.value = {...}`, and generate refs for all its fields to use somewhere else. Since the "reactivity chain" is interrupted by the result of `toRefs` which is a POJO, I wrongly thought unwrapping won't happen in this case.

The problem is solved by using `const reactiveFields = shallowRef({})`, still that part of the API isn't covered by much literature, so I thought it could be interesting to share this scenario in case anyone else got stuck.

Not really a bug, since it seems to be intended behaviour, but a disclaimer on `toRefs`/`ref` could be useful I guess, like other warnings on what to do/don't on the readme.

Feel free to close if no action should be taken

**Comment by LinusBorg** [comment]
is `fieldRefs` meant to be `pojoRefs` or vice versa? runnable code would remove th risk of typos in your code sample (and suffice the issue rules of providing a runnable reproduction).

**Comment by pikax** [comment]
A fully working codesanbox or SFC would be useful, I'm also having a hard time understanding the intent of this.

The rule on the unwrapping with the plugin is, if you assign an object to reactive/ref it will be unwrapped,  because of the Vue2 reactivity the source object will be mutated.

eg: 
```ts
import { defineComponent, ref } from "@vue/composition-api";

export default defineComponent({
  name: "App",

  template: `<div>
   <p>x: {{ x }}</p> // { "aaa": { "d": 1, "b": { "r": { "a": 1 } } } }  - all unwrap
    <p>o: {{ o }}</p> // { "r": { "a": 1 } } - unwrapped because it was assigned to x.value.aaa
  </div>`,

  setup() {
    const o = {
      r: ref({
        a: 1,
      }),
    };

    const x = ref({ aaa: true });

    x.value.aaa = {
      d: ref(1),
      b: o,
    };

    return {
      x,
      o,
    };
  },
});
```

**Comment by IlCallo** [comment]
> is fieldRefs meant to be pojoRefs or vice versa? Other variables introduced later on are also never initialized anywhere, so I have a hard time following and don't really get the issue.

Sorry, my brain probably half-melted while renaming stuff, I forgot to change half of those.
I edited initial code.

Is there already a codesandbox with SFC and `@vue/composition-api` to fork?

**Comment by pikax** [comment]
> Is there already a codesandbox with SFC and @vue/composition-api to fork?

If you search on the templates for `composition api` you find a few, you can fork this one https://codesandbox.io/s/epic-bogdan-8wh4g?file=/src/App.vue

**Comment by IlCallo** [comment]
Thanks, here is the example working. Open dev console and click on the button to see stuff happen.

https://codesandbox.io/s/holy-grass-znfsf?file=/src/App.vue

**Comment by pikax** [comment]
Thank you, can you guide me on what do you expect to happen? 

```ts
// this will unwrapped the pojoRefs and modify the pojoRefs object
reactivePojoRefs.value = pojoRefs;
```

**Comment by IlCallo** [comment]
```ts
console.log(cloneDeep(pojoRefs)); // outputs: { first: RefImpl, second: RefImpl, third: RefImpl }

reactivePojoRefs.value = pojoRefs;

console.log(reactivePojoRefs.value); // outputs: { first: 'value', second: 4, third: undefined }
```

I expected the two logs to be the same, but I see why they aren't, and why `shallowRef` is the right function to use in these cases.

-----
This is written on the [Vue3 API docs](https://v3.vuejs.org/api/refs-api.html#ref).

> If an object is assigned as a ref's value, the object is made deeply reactive by the reactive method.

It could be useful to add a note which further explains the implication of this sentence there.
Suggestion, based on my use case, but could be generalized:

> This also means all nested `reactive` and `ref` objects will be unwrapped. As an example, `ref(toRefs(reactive({ property: 'value' })))` returns the same result as `ref({ property: 'value' })`.
> If you want to keep the object "as is", avoiding the unwrap of its internal refs, you should use `shallowRef` instead.

**Comment by pikax** [comment]
> I expected the two logs to be the same, but I see why they aren't, and why `shallowRef` is the right function to use in these cases.

when you assign a value to a `reactive` it will unwrap all the nested `refs` on that same object.  - basically you will never have `ref` on a reactive object.

**Comment by IlCallo** [comment]
Can this formulation be added on the docs API? It's much more clear than "it's made deeply reactive"

**Comment by pikax** [comment]
> Can this formulation be added on the docs API? It's much more clear than "it's made deeply reactive"

Added some examples, suggestions are welcome

https://github.com/vuejs/docs-next/pull/814

**Comment by IlCallo** [comment]
Cool, much clearer now, thanks!

> this is how vue-router-next does something similar

Interesting! Thanks again 😄

**Comment by IlCallo** [comment]
I saw the docs update has been merged, closing this
