### ISSUE TITLE
createComponent in TypeScript not inherit from Vue ComponentOptions

### ISSUE THREAD

**Issue by TrungRueta** [vuejs/composition-api#63]
from Vue 2.x , when use with TypeScript we always write shims file `d.ts` whichs support static type property used inside vue component object. 
ex: in Nuxt, each component use as `page` need defined `$options.layout = 'layout name'` like this:
```js
{
    name: 'page',
    layout: 'myLayout'
}
```
To typesafe this custom property, they provide `d.ts`:
```ts
// ComponentOptions is declared in types/options.d.ts
declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    layout?: string
  }
}
```

For now `vue-function-api` provide function `createComponent` to help TS's developer can inherit typesafe from package. View `d.ts` file i see function defined:

```ts
export declare function createComponent<PropsOptions, RawBindings>(options: ComponentOptions<PropsOptions, RawBindings>): VueProxy<PropsOptions, RawBindings>;

export interface ComponentOptions<PropsOptions = ComponentPropsOptions, RawBindings = Data, Props = ExtractPropTypes<PropsOptions>> {
    props?: PropsOptions;
    setup?: SetupFunction<Props, RawBindings>;
}
```
This not inherit from Vue ComponentOptions , so we lost all typesafe from shims file.

A modify d.ts code will help a lot to inherit from Vue 2.x setup env .
Thankyou!

**Comment by TrungRueta** [comment]
ps: After more research out package, i found that in `index.d.ts` file we had modify Vue Component Options really;

`vue-function-api/dist/index.d.ts`:

```ts
import Vue, { VueConstructor } from 'vue';
import { SetupFunction, SetupContext } from './ts-api';
import { Wrapper } from './wrappers';
declare module 'vue/types/options' {
    interface ComponentOptions<V extends Vue> {
        setup?: SetupFunction<{}, {}>;
    }
}
....
```

I dont know why we had define `setup` function into Vue Component Options but not use it when define `createComponent` function, but use custom interface which lack of inherit from Vue. But from this point i had work around for component:

`shims-vue.d.ts`
```ts
// ComponentOptions is declared in types/options.d.ts
declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    myOption?: string;
  }
}
```

```ts
import Vue, { ComponentOptions } from 'vue';
import { createComponent } from 'vue-function-api';
import { ComponentPropsOptions } from 'vue-function-api/dist/ts-api/componentProps';

export default createComponent({
  setup(props, context) {
    return {};
  },
  myOption: 'yes it work'
} as ComponentOptions<Vue>);
```

Hope this will help we fix issue faster. Thank again for your good stuff before new age of Vue 3 💃

**Comment by PatrykWalach** [comment]
If you use `as` assignment wrapping the code in `createComponent` does nothing.
If you want to use `createComponent` you have to extend the interface used by the function as an argument.

```typescript
import { ComponentOptions } from 'vue-function-api/dist/ts-api/component'

declare module 'vue-function-api/dist/ts-api/component' {
  interface ComponentOptions {
    myOption?: string
  }
}

```

**Comment by IlCallo** [comment]
It seems that not being an instance of `Vue` anymore, but a `VueProxy` instead, this change broke most testing methods (eg. `shallowMount()`, `mount()`) an not they cannot infer `wrapper.vm` type, effectively breaking typehints for useful test.

**Comment by TrungRueta** [comment]
> If you use `as` assignment wrapping the code in `createComponent` does nothing.
> If you want to use `createComponent` you have to extend the interface used by the function as an argument.
> 
> ```ts
> import { ComponentOptions } from 'vue-function-api/dist/ts-api/component'
> 
> declare module 'vue-function-api/dist/ts-api/component' {
>   interface ComponentOptions {
>     myOption?: string
>   }
> }
> ```

i have update version of @PatrykWalach :

```ts
import { ComponentOptions } from 'vue-function-api/dist/ts-api/component';
import Vue, { ComponentOptions as VueComponentOptions } from 'vue';

declare module 'vue-function-api/dist/ts-api/component' {
  interface ComponentOptions extends VueComponentOptions<Vue> {}
}
```

like this we will have all properties typesafe from vue constructor 2.x. and still allow Infer prop parameter of `setup`. 

in case you dont want input all properties, can do:
```ts
import { ComponentOptions } from 'vue-function-api/dist/ts-api/component';
import Vue, { ComponentOptions as VueComponentOptions } from 'vue';

declare module 'vue-function-api/dist/ts-api/component' {
  interface ComponentOptions extends Pick<VueComponentOptions<Vue>, 'name' | 'components' |....> {
  }
}
```

**Comment by IlCallo** [comment]
Shouldn't it be

```ts
declare module 'vue-function-api/dist/ts-api/component' {
  import { ComponentOptions } from 'vue-function-api/dist/ts-api/component';
  import Vue, { ComponentOptions as VueComponentOptions } from 'vue';
  
  interface ComponentOptions
    extends Exclude<VueComponentOptions<Vue>, 'props'> {}
}
```
?

Otherwise you're overwriting `props` typings with their v2 counterparts.

**Comment by TrungRueta** [comment]
@IlCallo hm... this depend on how many property you need ship from vue 2.x into vue-function-api typechecking. Actually i not need all of them , only need `name`, `components` to make Vue2.x system work.

**Comment by IlCallo** [comment]
Yeah, I'm talking about the first mode you used, which adds everything.
Even doing as I did (leaving off `props` from original type) rises a warning in TS I actually don't understand.

```
Interface 'ComponentOptions<PropsOptions, RawBindings, Props>' incorrectly extends interface 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Record<string, any>>, Record<string, any>>'.
  Types of property 'props' are incompatible.
    Type 'PropsOptions | undefined' is not assignable to type 'string[] | RecordPropsDefinition<Record<string, any>> | undefined'.
      Type 'PropsOptions' is not assignable to type 'string[] | RecordPropsDefinition<Record<string, any>> | undefined'.
        Type 'PropsOptions' is not assignable to type 'string[]'.
```

**Comment by TrungRueta** [comment]
@IlCallo i see, you right my first trick will raise issue with typechecking, in this case my only way i think good is manual transfer properties from Vue 2.x we really need into Vue3.x type:

```ts
import { ComponentOptions } from 'vue-function-api/dist/ts-api/component';
import Vue, { ComponentOptions as VueComponentOptions } from 'vue';

declare module 'vue-function-api/dist/ts-api/component' {
  type d = VueComponentOptions<Vue>;

  interface ComponentOptions {
    name?: d['name'];
    components?: d['components'];
    methods?: d['methods'];
  }
}
```

This is my `d.ts` file , i only need `methods` , `components`, `name` for basic vue component.

also about question what the import api component line doing: I think it is for reference to `ComponentOptions` of `vue-function-api`, no ?

this is file `d.ts` to extend `ComponentOptions` of vue , i pick from Vue TS document and Nuxt project:

```ts
import Vue, { ComponentOptions } from 'vue';
import { VeeValidateComponentOptions } from 'vee-validate';

declare module 'vue/types/vue' {
  // Global properties can be declared
  // on the `VueConstructor` interface
  interface VueConstructor {}
}

// ComponentOptions is declared in types/options.d.ts
declare module 'vue/types/options' {
  interface ComponentOptions<V extends Vue> {
    $_veeValidate?: VeeValidateComponentOptions;
  }
}
```

my project i store both 2 d.ts file, one for extend for custom option, `buefy` type etc etc into v2.x Vue `ComponentOptions`, like normal, and second file is extends what property i want into `vue-function-api`'s `ComponentOptions` . with my last suggest trick above i nolonger meet typechecking fails anymore. can you try .

**Comment by hzgotb** [comment]
<img width="696" alt="WX20190821-220125@2x" src="https://user-images.githubusercontent.com/50480095/63438647-3fa18d00-c45f-11e9-8b97-5c662b30bb3b.png">
vue-router error.

**Comment by IlCallo** [comment]
> also about question what the import api component line doing: I think it is for reference to ComponentOptions of vue-function-api, no ?

You actually don't need it. You are defining in the `vue-function-api` namespace a new interface with the same name of the old one and they are merged because of TypeScript interface merging capabilities. Importing it won't do anything because you are not actually referencing it.

> with my last suggest trick above i nolonger meet typechecking fails anymore. can you try .

Will check it next week, tomorrow I go on vacation :P
I already solved using your second way of just selecting the needed properties, anyway. I needed just `name` and `components` too.

**Comment by manuelojeda** [comment]
> 
> 
> <img alt="WX20190821-220125@2x" width="696" src="https://user-images.githubusercontent.com/50480095/63438647-3fa18d00-c45f-11e9-8b97-5c662b30bb3b.png">
> vue-router error.
> 
> ```ts
> import SignIn from './views/SignIn.vue';
> 
> export default new Router({
>   mode: 'history',
>   base: process.env.BASE_URL,
>   routes: [
>     {
>       path: '/sign-in',
>       name: 'SignIn',
>       component: SignIn,   // use createComponent
>     },
>   ],
> });
> ```
> 
> ![image](https://user-images.githubusercontent.com/50480095/63480226-af496380-c4c3-11e9-92fd-5eab0bf1a32e.png)

Actually the fix to this is pretty simple, just they haven't add it to the VueCLI, you need to add a type into the Route Array, you can check this:
https://github.com/vuejs/vue-cli/pull/4805
