### ISSUE TITLE
Way to access $route through the composition api

### ISSUE THREAD

**Issue by stormtroop** [vuejs/composition-api#630]
Hi guys

I am looking for a way to use the current $route instance inside of components,
im using Vuejs 2 with the latest release of the composition-api.

I know that Vuejs 3 provides functions like `useRoute` / `useRouter` but due to the lack of documentation
i could not find any solution for this use-case. We have a simple Breadcrumb Component and when a client uses
a `router-link` i want to update the new route inside to match the Breadcrumb.

Any idea how to solve this?

**Comment by danielroe** [comment]
@stormtroop 

```js
function useRoute() {
  const vm = getCurrentInstance()
  if (!cm) throw new Error('must be called in setup')

  return vm.proxy.$route
}
```

**Comment by willwinberg** [comment]
This solution seems not to be be reactive.
example: 
```
const isFooRoute = computed(() => {
      return (
        [
          'foo',
          'bar',
          'huu',
          'rah',
        ].includes(route.name as string) || route.query.type === 'foo'
      )
    })
```
This computed prop does not update when the route changes though. Am I missing something here?

**Comment by ambit-tsai** [comment]
> This solution seems not to be be reactive.
> 
> `isFooRoute` does not update when the route changes though. : [ Am I missing something here?

Package [vue2-helpers](https://github.com/ambit-tsai/vue2-helpers#vue2-helpers) provide a  reactive `useRoute()`
```js
import { useRoute } from 'vue2-helpers/vue-router';

const route = useRoute();
```
