### ISSUE TITLE
how can i forbid auto install?

### ISSUE THREAD

**Issue by cereschen** [vuejs/composition-api#631]
Or During the second installation, no errors are thrown?
I had trouble using WebComponent.

**Comment by antfu** [comment]
@cereschen Can you provide more context?

**Comment by cereschen** [comment]
If I use composition-api in WebComponent,
 I can only use the CDN approach (including projects that use the WebComponent), 
otherwise composition-api might be installed several times and throw an error.
I can use plugininstAlledFlag to determine whether to install it, but only if it doesn't install automatically

**Comment by antfu** [comment]
How about importing `@vue/composition-api` before importing `vue`?

**Comment by cereschen** [comment]
> How about importing `@vue/composition-api` before importing `vue`?

Since I'm using  vue in the cdn, it's hard to avoid this problem, so I decided to use the cdn as well for comperation-api, but even so, hopefully there's a way to lower the error level so that the program runs smoothly.
