### ISSUE TITLE
watchEffect is not same as vue3 watchEffect?

### ISSUE THREAD

**Issue by gitHber** [vuejs/composition-api#633]
```
setup() {
    const num = ref(0);
    watchEffect(() => {
      console.log("num change will not trigger this effect");
      num.value = 1;
    });
    setTimeout(() => {
      num.value++;
    }, 5000);
    return {
      num
    };
  }
```
in vue3, it's right, watchEffect only triggered by value getter(not setter), in composition-api, it will triggered by value setter which means it's not right

vue3-demo https://stackblitz.com/edit/vue-qfisdz
sorry, I did't create a demo for @vue/composition-api.

**Comment by prigaux** [comment]
NB : this bug breaks the `asyncComputed` function suggested in https://github.com/foxbenjaminfox/vue-async-computed/issues/104 .

(i'm trying to transition from vue2->vue3 by gradually migrating from "options API" to "composition API" with vue2)

**Comment by gitHber** [comment]
> NB : this bug breaks the `asyncComputed` function suggested in [foxbenjaminfox/vue-async-computed#104](https://github.com/foxbenjaminfox/vue-async-computed/issues/104) .
> 
> (i'm trying to transition from vue2->vue3 by gradually migrating from "options API" to "composition API" with vue2)

just for additional, watch api only triggered when watcher value change, but watchEffect api would triggered when watcher value set

**Comment by ygj6** [comment]
Solved by https://github.com/vuejs/composition-api/pull/786.
