### ISSUE TITLE
TS2345: Argument of type 'Date' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by DarkLite1** [vuejs/composition-api#634]
Good morning , after the update to `"@vue/composition-api": "1.0.0-beta.26"` we have an issue.

Consider the following function:
```ts
export const convertToDate = (isoDate: string, locale: string) => {
  const date = new Date(isoDate)
  const options = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }
  return date.toLocaleDateString(locale, options)
}
```
This function is being consumed in a component like this:
```ts
export default defineComponent({
  props: {    fromDate: { type: Date, required: false },  },
  setup(props) {
    const { locale } = useI18n()
    const date = computed(() => {
      if (props.fromDate) return convertToDate(props.fromDate, locale.value)
    })
```

After the upgrade to beta 26 the following error is thrown::

> TS2345: Argument of type 'Date' is not assignable to parameter of type 'string'.

When changing the function argument type:
```ts
export const convertToDate = (isoDate: Date, locale: string) => {
```
We get this error:

> TS2345: Argument of type 'string' is not assignable to parameter of type 'Date'.

The isoDate we feed the function/component with v-bind is new Date(). So it really is a date type that we send to the component.

**Comment by pikax** [comment]
Morning, this is working for me:

```ts

export const convertToDate = (isoDate: Date, locale: string) => {
  const date = new Date(isoDate)
  const options = {
    weekday: 'long',
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  }
  return date.toLocaleDateString(locale, options)
}

defineComponent({
  props: { fromDate: { type: Date, required: false } },
  setup(props) {
    if (props.fromDate) return convertToDate(props.fromDate, 'localeString')
  },
})
```

I'm not getting any typescript error on `beta.26`

Can you please provide a small repo with the error?

**Comment by DarkLite1** [comment]
Thank you for getting back to me. After testing this further I found the culprit. You are correct, it's not an issue with the composition Api. It just improved and found a TypeScript bug that wasn't visible with an older version. So closing this one as solved.

**Comment by DarkLite1** [comment]
You are correct, it's not an issue with the Vue Composition Api. It improved in a recent version and showed me a TypeScript error that wasn't visible before. Thank you, closing this one.
