### ISSUE TITLE
There is a problem with the attribute named render in the setup function

### ISSUE THREAD

**Issue by StarFishing** [vuejs/composition-api#635]
There is an attribute named render in the setup function, which will cause it to be mistaken for the system render function, resulting in an error that $createElement cannot be found.
~~~code
  setup() {
    const columns = [
      {
       title: '操作',
      slot: 'action',
       align: 'center',
       width: '200',
      render: (h, params) => { // here is error code but it shoud be write
        return (
          <div class="action">
               <span class="color-error">删除</span>
             </div>
           );
         },
      },
    ];
    return {  columns };
  },

**Comment by antfu** [comment]
Might be a bug in the JSX plugin, please report it in the corresponding repo.

**Comment by StarFishing** [comment]
> Might be a bug in the JSX plugin, please report it in the corresponding repo.

but the file is .vue,the columns is just a prop of table component

**Comment by pikax** [comment]
Can you please provide an reproduction somewhere and provide more description of the error, at the first sight is seems this is related with JSX plugin, just like @antfu said.

> but the file is .vue,the columns is just a prop of table component

But the `render` on the column is returning an JSX, which will make the plugin to change the "file". If you can reproduce it without JSX (eg: by `h('')`) please let us know

**Comment by StarFishing** [comment]
> Can you please provide an reproduction somewhere and provide more description of the error, at the first sight is seems this is related with JSX plugin, just like @antfu said.
> 
> > but the file is .vue,the columns is just a prop of table component
> 
> But the `render` on the column is returning an JSX, which will make the plugin to change the "file". If you can reproduce it without JSX (eg: by `h('')`) please let us know


this the file .vue

<template>
    <div class="option">
      <Button type="primary">click</Button>
    </div>
</template>
<script>
import { defineComponent, ref, reactive } from '@vue/composition-api';
  setup() {
//  Here is just a statement，the error is  "TypeError: Cannot read property '$createElement' of undefined"
const columns = [
      {
        key: 'course_type',
        render: (_, { row }) => {
          return <span></span>;
        },
      },
    ];
return {columns}
},
// if in the data.it will be right
data(){
return {
columns: [
      {
        key: 'course_type',
        render: (_, { row }) => {
          return <span></span>;
        },
      },
    ]
}

}
</script>

**Comment by StarFishing** [comment]
> Can you please provide an reproduction somewhere and provide more description of the error, at the first sight is seems this is related with JSX plugin, just like @antfu said.
> 
> > but the file is .vue,the columns is just a prop of table component
> 
> But the `render` on the column is returning an JSX, which will make the plugin to change the "file". If you can reproduce it without JSX (eg: by `h('')`) please let us know

i have been solved the problem,
It may be caused by the lower vue cli version. I updated the cli version and reconfigured the babel file
![image](https://user-images.githubusercontent.com/41889222/105623880-2ffa5500-5e58-11eb-8dd0-58ef0cba80c3.png)

I added this line of configuration and solved the problem, but it seems that there is no such option. Thank you for your suggestions and inspiration.
