### ISSUE TITLE
vue2  computed  value not change when depend on a reactive array  

### ISSUE THREAD

**Issue by Hucy** [vuejs/composition-api#637]
vue3 is ok  [vue3  demo](https://codesandbox.io/s/vue3-computed-reactive-array-ou3gf?file=/src/App.vue:341-349)

[vue2 demo](https://codesandbox.io/s/vue2-reactive-computed-array-6h0hc?file=/src/App.vue:277-285)

**Comment by tuomas2** [comment]
Also watches (with `watch()`) do not work for reactive arrays.

**Comment by tuomas2** [comment]
Related / duplicate of #521

**Comment by tuomas2** [comment]
If reactive array is encapsulated within ref() then it works.

**Comment by iheyunfei** [comment]
It's expected behaviors for current codes.  https://github.com/vuejs/composition-api/issues/581#issuecomment-848617944
