### ISSUE TITLE
export `UseContextReturn`

### ISSUE THREAD

**Issue by dzcpy** [vuejs/composition-api#642]
I was trying to get the `cookie-universal-nuxt` module work in my project. I need to get `$cookies` from the context returned by `useContext`. However it `$cookies` doesn't exist in `UseContextReturn` and there's no way for me to extend it since it's not exported. Can you please export this type?
By the way, I ended up using this workaround, which seems to be a bit ugly:
```ts
const {
  $axios,
  $cookies,
}: {
  $axios: NuxtAxiosInstance
  $cookies: NuxtCookies
} = useContext() as any
```

**Comment by danielroe** [comment]
@dzcpy This issue should be raised at https://github.com/nuxt-community/composition-api instead. 😃

**Comment by dzcpy** [comment]
@danielroe Sorry I made a mistake
