### ISSUE TITLE
Wrong TypeScript inference in template for unwrapped computed values (In WebStorm only)

### ISSUE THREAD

**Issue by lyle45** [vuejs/composition-api#643]
Edit: This is an issue with WebStorm and not this npm package. https://youtrack.jetbrains.com/issue/WEB-48792

Typescript is not aware of computed props unwrapping in template variables and requires a value prop although that would break at runtime due to unwrapping. result is the variables from v-for's or anything else will be casted to any by TS

![image](https://user-images.githubusercontent.com/17912606/107356067-02104400-6ad9-11eb-9ce5-efaac59b500c.png)

![image](https://user-images.githubusercontent.com/17912606/107356530-98446a00-6ad9-11eb-8b11-463570c4aea3.png)

![image](https://user-images.githubusercontent.com/17912606/107356202-2b30d480-6ad9-11eb-938e-2fc033613239.png)

Note, this is a typescript issue only. behavior works as expected

Note 2, this is unrelated to what the computed fn returns. be it Array or anything else

**Comment by jacekkarczmarczyk** [comment]
https://youtrack.jetbrains.com/issue/WEB-48792

**Comment by lyle45** [comment]
@jacekkarczmarczyk Oh wow, didn't occur to me it could be an error with WebStorm and not this package.
Thank you

Should we keep this issue open with a reference to the issue tracker in WebStorm for other people? If not, this can be closed

**Comment by jacekkarczmarczyk** [comment]
imho it could be closed, but i guess core member's opinion will be more valuable

**Comment by lyle45** [comment]
Leaving this open has value as for people who use WebStorm would either search google or  come here looking for answers (like me). How would you know to go to JetBrains

Leaving for core members discretion. Thank you

**Comment by antfu** [comment]
Thanks for bringing this up! Wish it could be fixed by WebStorm soon. Closing this as it's not related to the project itself and this issue is already good enough for people who run into similar situations to find the info. Thanks.
