### ISSUE TITLE
PropType not working with dynamic Interfaces

### ISSUE THREAD

**Issue by popovicieduard** [vuejs/composition-api#645]
The following code:
```js
interface PaginatorContract<T> {
  meta: PaginatorMeta
  data: T[]
}

 @Prop({
    required: true,
    type: Object as PropType<PaginatorContract<Account>>,
  })
  accounts!: PaginatorContract<Account>
```

will show me the following type when passing down props:
```
(property) accounts: any
```

changing the prop type to:
```js
type: Object as PropType<Account>,
```

will give me the right type:
```
(property) accounts: Account
```

Is it possible to have this type of prop type ?

**Comment by antfu** [comment]
Can't tell if it's a bug from class component or this plugin, if you believe it's a bug here, can you share a reproduction without using the class component?
