### ISSUE TITLE
Typescript: wrong ref type narrowing

### ISSUE THREAD

**Issue by lyle45** [vuejs/composition-api#646]
I'm not sure the cause of this but it seems narrowing ref value in an if statement narrows the wrong item

Typescript error is thrown

![image](https://user-images.githubusercontent.com/17912606/107876829-28672280-6ed1-11eb-829a-733aba6309b3.png)

You can see qTree is narrowed but value is not, although qTree did not go through presence check and value did

**Comment by jacekkarczmarczyk** [comment]
That's a typescript issue, not the plugin
https://github.com/microsoft/TypeScript/issues/9998

**Comment by lyle45** [comment]
Ok gotcha thank you. Hope this can be resolved
