### ISSUE TITLE
How to access a ref nested inside a named slot

### ISSUE THREAD

**Issue by trufavarela** [vuejs/composition-api#647]
In my code I have something that looks like this:

```
<template>
  <div>
     <template v-slot:content>
        <div ref="ele">
            ...

```

and inside my setup function I have:

```
const ele = ref(null)

... 
onMounted(() => {
      
  console.log(rlr)

});

...
return {
  ele
}
```

This works great as long as the div is outside the nested template tag:

```
<template>
  <div>
    <div ref="ele" />
    <template v-slot:content>
       ...
```

Not sure how to access it if it's nested.

I've tried accessing it via giving some parent a `ref` and then doing something like:

```
.$scopedSlots.content()[0]
```

I see a Vue element but not really the DOM element.

Thank you!

**Comment by dpschen** [comment]
I didn't try this out, but I think in this case the ref gets assigned to the parent, since it's mounted there. Did you try to access it via `$parent.$refs.ele` ?
Also I think that depending on where you try to access it you might need to wait for nextTick() until it's mounted :)
