### ISSUE TITLE
watch over array of refs has incorrect types inferrence in CB

### ISSUE THREAD

**Issue by lyle45** [vuejs/composition-api#649]
As you can see changed value param types are (number | string)[] in this example. Meaning any indexed access can be any of watched array value types. While they should be of type [number, string] as orders of passed value param are identical to watched ones (I think)

![image](https://user-images.githubusercontent.com/17912606/108816111-3a764e80-75be-11eb-8195-8b4bdd27eec7.png)

**Comment by pikax** [comment]
You need to cast `as const`  otherwise typescript will infer the type as `Array<string|number>`

```ts
watch([ref(0, ref('hello')] as const, //
```

**Comment by lyle45** [comment]
@pikax Is it documented somewhere or should I have known this from somewhere else?
And also, why is that?

**Comment by LinusBorg** [comment]
That's Typescript being Typescript. An array that contains two different types`a` and `b` is inferred to be of type `Array<a | b>` unless explicitly defined as a tuple or const.

So TS reads your first wathc parameter as `Array<Ref<number> | Ref<string>>`, and consequently, the argument for the callback is unwrapped to `Array<string | number>`.

**Comment by lyle45** [comment]
@LinusBorg possible solution for invoking CB with correct types

```
function tupleArray<T extends any[]>(...v: T) {
    return v;
}
const WEEKDAYS_SHORT_INFFERED =  tupleArray('Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam')  // INFFERED AS [string, string, string, string, string, string, string]
const WEEKDAYS_SHORT: [string, string, string, string, string, string, string] = WEEKDAYS_SHORT_INFFERED
```

**Comment by lyle45** [comment]
Possible solution for this problem

https://stackoverflow.com/a/46013198
