### ISSUE TITLE
Type inference for raw bindings not work in `render` when `props` used

### ISSUE THREAD

**Issue by NateScarlet** [vuejs/composition-api#650]
Raw binding becomes to `Record<string, unknown>` when props used.

```
@vue-composition/api: 1.0.0-rc.1, 1.0.0-rc.2
typescript: 3.9.7, 4.2.2
vue: 2.6.11, 2.6.12
```

```typescript
import { defineComponent, ref } from '@vue/composition-api';

export default defineComponent({
  name: 'test',
  props: {},
  setup: props => {
    const text = ref('');
    return { text };
  },
  render(h) {
    const v = this.text;
    return h('div', v);
  },
});
```

![image](https://user-images.githubusercontent.com/21083014/109117333-d057d800-777c-11eb-95d9-dd221cfa2a99.png)

It is ok when not use `props` in `setup`:
```typescript
import { defineComponent, ref } from '@vue/composition-api';

export default defineComponent({
  name: 'test',
  props: {},
  setup: () => {
    const text = ref('');
    return { text };
  },
  render(h) {
    const v = this.text;
    return h('div', v);
  },
});
```

And also ok when not return it in `render`:
```typescript
import { defineComponent, ref } from '@vue/composition-api';

export default defineComponent({
  name: 'test',
  props: {},
  setup: () => {
    const text = ref('');
    return { text };
  },
  render(h) {
    const v = this.text;
    h("div", v)
    return h("div");
  },
});
```

![image](https://user-images.githubusercontent.com/21083014/109118156-eca84480-777d-11eb-9599-8113c9e4efc1.png)

**Comment by wai-lin** [comment]
I'm also experiencing similar problem. I think what I'm experiencing is also related to this issue.

In my case, the `setup` parameter **props** become `any` type when the **props**  contain `validator`  function. I'm using `nuxt-composition-api` with typescript. And this is my code.

```typescript
import {
  computed,
  defineComponent,
  PropType,
  reactive,
} from '@nuxtjs/composition-api'

import { TBaseButtonTagNames } from '@/types'

export default defineComponent({
  name: 'BaseButton',
  props: {
    tagName: {
      type: String as PropType<TBaseButtonTagNames>,
      default: 'button',
      validator(v: string) {
        return ['button', 'a', 'n-link', 'nuxt-link'].includes(v)
      },
    },
    isCircle: { type: Boolean, default: false },
    isLoading: { type: Boolean, default: false },
    isDisabled: { type: Boolean, default: false },
  },
  setup(props) {
    const { isCircle, isDisabled } = reactive(props)

    const dynClassNames = computed(() => {
      let c = 'px-4 py-2'
      if (isCircle) c = 'p-0 w-10 h-10 rounded-full'
      if (isDisabled) c += ' text-gray-600 bg-gray-200'
      return c
    })

    return {
      dynClassNames,
    }
  })
```

### This is the error with validator in `tagName` props.

![image](https://user-images.githubusercontent.com/18464030/111861568-b2e1ec80-897d-11eb-9ebe-025681c53038.png)

### The `props` is fine when there is no validator.

![image](https://user-images.githubusercontent.com/18464030/111861587-cb520700-897d-11eb-8499-fee29ca6b142.png)

**Comment by pikax** [comment]
@wai-lin not the same as this issue, please read the [docs on annotating props](https://v3.vuejs.org/guide/typescript-support.html#annotating-props)

In your case if you convert your validator to an arrow function or typing `this: null` it will fix it.

--- 

Not related with typescript, but `const { isCircle, isDisabled } = reactive(props)` this will not be `reactive` - Please go to [discord server](https://vue.land) to the #composition-api channel if you need further info in regards to this.

**Comment by wai-lin** [comment]
@pikax thanks for reply. I got it right.

**Comment by NateScarlet** [comment]
workaround for this

```typescript
import type { ExtractPropTypes, SetupFunction } from '@vue/composition-api';
import { defineComponent, ref } from '@vue/composition-api';

const propsOptions = {
  prop1: {
    type: String,
  },
};

type Props = ExtractPropTypes<typeof propsOptions>;

const setup = (props: Props, ctx: SetupFunction) => {
  const text = ref('');
  return { text };
};

export default defineComponent<Props, ReturnType<typeof setup>>({
  name: 'test',
  props: propsOptions,
  setup,
  render(h) {
    const v = this.text;
    return h('div', v);
  },
});
```

**Comment by wangxdmm** [comment]
Anyone solve this issue?
