### ISSUE TITLE
How do I pass ref to child component?

### ISSUE THREAD

**Issue by rationalthinker1** [vuejs/composition-api#652]
After a whole day of debugging, I found a problem with passing ref to a grandchild element in vue 3.
Basically, my setup is like this:
`Form` -> `CustomInput` -> `Input`

in `Form`, when I use `ref`, I want it to refer to `Input`.
```javascript
<template>
  <custom-input ref="address"/>
</template>
<script>
setup(props, context) {
    const address = ref();
    const { initAutoComplete } = useGoogleMaps();

    onMounted(() => {
      initAutoComplete(address.value);
    });

    return {
      address,
    };
  },
</script>
```
Right now, the value of `address.value` is undefined.
How can I solve this? Please give example.

Thank you.

**Comment by pikax** [comment]
Is this related to vue2 (you mentioned `vue 3`)?

**Comment by rationalthinker1** [comment]
Oh sorry.  I meant vue 2 using this plugin.

**Comment by pikax** [comment]
Do you mind providing an full reproduction? A repo, or codesandox would be really helpful

**Comment by Made-of-Clay** [comment]
@rationalthinker1 Two questions:
1. Did you get this figured out?
2. Are you abbreviating your `script` contents here? You're missing the `export default defineComponent({` opening/closing, so if you aren't abbreviating the `script` contents, that's your problem.
