### ISSUE TITLE
Incorrect type determining required props

### ISSUE THREAD

**Issue by scottbedard** [vuejs/composition-api#654]
I believe we have a bug with how we're determining required vs optional props...

https://github.com/vuejs/composition-api/blob/be9de86a248c8f5e8f52aec1beeee78cc2e3519a/src/component/componentProps.ts#L29-L31

The second half of this condition looks backwards. We should be flagging props as required when they extend `{ default: never }`, not `{ default: any }`. Having a default value means the prop _isn't_ required, correct?

To demonstrate the problem, create a component with the following prop...

```ts
foo: {
  type: String,
  default: 'asdf',
}
```

Then attempt to render that component without defining `foo`.

```
Type '{}' is not assignable to type '{ foo: string; } & {}'.
Property 'foo' is missing in type '{}' but required in type '{ foo: string; }'.
```

As you can see, our optional prop is incorrectly ending up on the required side of [this intersection type](https://github.com/vuejs/composition-api/blob/be9de86a248c8f5e8f52aec1beeee78cc2e3519a/src/component/componentProps.ts#L65-L66).

It looks like this bug also exists in 3.x. If this is correct and I'm not misunderstanding how `default` should be effecting prop types, let me know and I'll open a PR there as well!
https://github.com/vuejs/vue-next/blob/4a965802e883107a2af00301a59fb7f403b6acf7/packages/runtime-core/src/componentProps.ts#L70

**Comment by antfu** [comment]
@scottbedard Looks like the approach is not correct, I am reverting it for now.

About the problem, I think we have two different props, one for outer and one for inter while your problem looks like about outer props that pass into the component instead of the props for the setup function. Can you share a snippet about how you get this error?

**Comment by scottbedard** [comment]
@antfu Ah, I did not realize that `props` is not the same in both contexts. I am in the process of migrating a large codebase to vue 3 + typescript, and we have many root components. The goal here was to build a helper for mounting those root components, while maintaining type coverage.

Here is a minimal reproduction
https://github.com/scottbedard/required-prop-types-demo

**Comment by scottbedard** [comment]
Quick update here, it looks like we can't need to make any changes. It looks like I can get the type I need by using `ExtractDefaultPropTypes`

```ts
type ExtractPropTypesExternal<T, U = ExtractDefaultPropTypes<T>> = Partial<U>
  & Omit<ExtractPropTypes<T>, keyof U>;
```
