### ISSUE TITLE
How to modify an array index inside of a reactive object

### ISSUE THREAD

**Issue by ctwhome** [vuejs/composition-api#656]
I am having a hard time to make this work:
```js
const todos = reactive({
  data: [],
  count: 0,
  error: null,
  fetching: false,
})

// payload is a object {}
realtime.on('UPDATE', (payload) =>{
   todos.data[index] = reactive(payload)
})
```

is there a way to update the array element inside the reactive object?
I have the feeling that I am close but it doesn't want to work.

**Comment by jacekkarczmarczyk** [comment]
https://vuejs.org/v2/guide/reactivity.html#For-Arrays
