### ISSUE TITLE
Template Interpolation doesn't work when component extends from defineComponent 

### ISSUE THREAD

**Issue by mercs600** [vuejs/composition-api#662]
Issue moved from vetur github, because propably this bug is related with vuejs/composition-api  (https://github.com/vuejs/vetur/issues/2767) 

## Info
- Package version: 1.0.0-rc.3
- Platform: macOS
- Vetur version: 0.33.1
- VS Code version: Version: 1.54.1

## Problem

We're using https://github.com/vuejs/composition-api to define components. 
```vue
<script lang="ts">
import { defineComponent } from '@vue/composition-api'
export default defineComponent({
  name: 'CeHeader'
})
</script>
```

Then we have component which extends previous one and also use defineComponent ( but can be also defined by Vue.extend) 
```ts
export default defineComponent({
  extends: CeHeader,
})
```

In extended components template interpolation provided by vetur doesn't work

### BaseComponent:
```vue
<template>
  <div>
    {{ headerTag }}
  </div>
</template>

<script lang="ts">
import { computed, defineComponent } from '@vue/composition-api'
import useSharedProps from '../../composables/useSharedProps'

export default defineComponent({
  name: 'CeHeader',
  props: {
    ...useSharedProps()
  },
  setup (props) {
    const headerTag = computed((): string => {
      return `h${props.headerLayout || 1}`
    })

    return {
      headerTag
    }
  }
})
</script>
```
<img width="720" alt="Zrzut ekranu 2021-03-11 o 15 52 01" src="https://user-images.githubusercontent.com/7935392/110805817-bab8d700-8281-11eb-9a81-632ee25864a0.png">

###  Extended components:
```vue
<template>
  <div>
    {{ headerTag }}
  </div>
</template>
<script lang="ts">
import { defineComponent } from '@vue/composition-api'
import CeHeader from './CeHeader.vue'
export default defineComponent({
  extends: CeHeader,
  computed: {
    iShouldGetTagAddnotation (): string {
      return this.headerTag
    }
  }
})
</script>
```
<img width="664" alt="Zrzut ekranu 2021-03-11 o 15 53 33" src="https://user-images.githubusercontent.com/7935392/110806007-f0f65680-8281-11eb-852c-9bb7532becd5.png">

## Solution
Any ideas how can I resolve it ? 

#### edit
I can use as separator, but then I can't extend my new components with new props/methods etc.
<img width="952" alt="Zrzut ekranu 2021-03-11 o 17 35 13" src="https://user-images.githubusercontent.com/7935392/110821732-a6300b00-8290-11eb-8163-b2034edcd5f3.png">

**Comment by pikax** [comment]
the implementation of the `extends` and `mixins` is implemented in `vue 3`, but it would required quite a lot of work to implement on the vue2, and there's some discussions to improve typescript support on `vue 2.7` to align it better with `vue3` (nothing official yet)

As a workaround you can do something like to get it on the template, but not on `this`
```html
<template>
  <div>
    {{ headerTag }}
  </div>
</template>
<script lang="ts">
import { defineComponent } from "@vue/composition-api";
import CeHeader from "./CeHeader.vue";
const comp = defineComponent({
  extends: CeHeader,
  computed: {
    iShouldGetTagAddnotation(): string {
      // this type will not be supported until there's support for extends
      return this.headerTag;
    },
  },
});

export default comp as typeof CeHeader & typeof comp;
</script>
```

**Comment by mercs600** [comment]
@pikax it make sense, thank you for quick reply.
