### ISSUE TITLE
defineComponent did you register the component correctly

### ISSUE THREAD

**Issue by Dd-ouni** [vuejs/composition-api#665]
There is no problem with vue3, but the defineComponent of vue2 does not take effect.
![image](https://user-images.githubusercontent.com/34804413/112086929-0e071f80-8bc8-11eb-8449-87afa85ac9a4.png)
![image](https://user-images.githubusercontent.com/34804413/112087197-7ce47880-8bc8-11eb-9bbf-4ac9d8489752.png)

babel.config.js 
![image](https://user-images.githubusercontent.com/34804413/112087163-6d652f80-8bc8-11eb-910b-bddcfc478f2b.png)

**Comment by pikax** [comment]
This is caused by a limitation of vue 2. 

Returning from `setup` is equivalent as returning from `data`. 

For Vue2 you should be able to use: 
```html
<component :is="TestEl"/>
```
