### ISSUE TITLE
app.provide not defined

### ISSUE THREAD

**Issue by ThaDaVos** [vuejs/composition-api#666]
Currently following other plugins developers to write my own plugin and I see all using `app.provide` inside their install methods - but with the composition-api plugin it seems `provide` isn't defined on the App class. See as an example VuetifyJs:
https://github.com/vuetifyjs/vuetify/blob/70c0d00c712b445c4cb02eb38e2b87ec6781310b/packages/vuetify/src/framework.ts

**Comment by dongnaebi** [comment]
any solutions?
