### ISSUE TITLE
Is it acceptable to add watch during lifecycle hook like onMounted?

### ISSUE THREAD

**Issue by bcronje** [vuejs/composition-api#667]
Will watchers added inside lifecycle hook like `onMounted` (as opposed to during `setup()`)be cleaned up automatically, or would I have to stop them manually when the component is unmounted?

**Comment by pikax** [comment]
--- 

Please use issues for bugs or incorrect behaviour, for questions use [discord](https://vue.land) or [forum](https://forum.vuejs.org/).
