### ISSUE TITLE
tsx cannot be rendered

### ISSUE THREAD

**Issue by shlroland** [vuejs/composition-api#670]
i configure babel.config.js
![image](https://user-images.githubusercontent.com/45024986/112572307-e1037880-8e24-11eb-88ec-a0f760b0a356.png)
but it show
<img width="1268" alt="Snipaste_2021-03-26_11-13-10" src="https://user-images.githubusercontent.com/45024986/112572322-ea8ce080-8e24-11eb-931f-218ebf2c518b.png">

heres my repo [repo](https://github.com/shlroland/demo-composition-api-tsx)

**Comment by almost-no-one** [comment]
@shlroland, Try to use arrow function 
`setup() {
    return () => {
        return <div>bar</div>
    };
  },`

**Comment by pikax** [comment]
TSX is handled by other libraries.
