### ISSUE TITLE
Estimated plans / roadmap for 1.0 release

### ISSUE THREAD

**Issue by thebanjomatic** [vuejs/composition-api#671]
Hello, I'm wondering now that things are in the release-candidate stage if there is a known target for when to expect a 1.0 release, or if additional clarification could be made regarding the intent to commit (or not commit) breaking changes now that things have reached rc.

I'm interested in using the composition-api, but the presence of breaking changes (due to it being a pre-1.0 release presumably) has made it difficult to support when used within component libraries where we have less control over which version of the plugin will ultimately be resolved and used within an application. A 1.0 release doesn't solve all of these problems, but it does make it a bit easier to manage.

**Comment by pikax** [comment]
Currently I don't believe there's breaking changes for 1.0, there's also no breaking changes on the vue-next that could affect composition-api plugin.

**Comment by DRoet** [comment]
I guess this one can be closed now 😄
