### ISSUE TITLE
Composition Function Not Working in Production

### ISSUE THREAD

**Issue by rationalthinker1** [vuejs/composition-api#679]
This code is working in development but not in production. Basically, what this composition function does is set the initial values onto `data`.

```typescript
export default function useSetInitialValues(props: Data, key: string = 'initValues') {
    const data = reactive({});
    if (key in props) {
        const initValues = props[key];
        Object.keys(initValues).map(key => {
            if (!!initValues[key]) {
                data[key] = initValues[key];
            }
        });
    }
    return data;
}
```

This is the component that I am using on

```typescript
export default {
  name: 'job-edit',
  setup(props, context) {
    const data = useSetInitialValues(props, 'job');
    return {
      ...data
    };
  },
  ...
```
Everything else is working. Other components are working. There is no error, and `console.log` of `data` in the function returns the data that I want for the component.

**Comment by antfu** [comment]
Please read the docs
https://github.com/vuejs/composition-api#ref-unwrap

There are some caveats in Vue's reactivity system where you need to use `set()` to assign new properties to reactivity objects. 

Also, please use Stackoverflow or Discord to ask questions.

Thanks.

**Comment by rationalthinker1** [comment]
Thank you, I got it to work. It was weird that it wasn't working on production mode though.

```typescript
export default function useSetInitialValues(props: Data, key: string = 'initValues') {
    const data = reactive({});
    if (key in props) {
        const initValues = props[key];
        Object.keys(initValues).map(key => {
            if (!!initValues[key]) {
                set(data, key, initValues[key]);
            }
        });
    }

    return data;
}
```

**Comment by rationalthinker1** [comment]
I figured out what the issue was.

basically, my component already had a variable `id`, which was set to `null`. It development mode, it overwrites it and while in production mode, it doesn't overwrites it.

@antfu I think that it is a bug with this library.


Example:

```typescript
export default {
  name: 'job-edit',
  setup() {
    const data = reactive({
      id: 42,
    });
    return data;
  },
  data() {
    return {
    id: null,
  }
}
```

it development, the value of `id` would be 42, while in production, it's null.

**Comment by antfu** [comment]
Thanks, will investigate.

**Comment by rationalthinker1** [comment]
Any update on this? There are some other functions that I cannot use because of this. It works in development, but not in production.

**Comment by rationalthinker1** [comment]
```javascript
it('should work merge with data', async () => {
    const opts = {
      template: `<div>{{a}}</div>`,
      setup() {
        const a = ref(42)

        return {
          a: a.value,
        }
      },
      data() {
        return {
          a: null,
        }
      }
    }
    const Constructor = Vue.extend(opts).extend({})

    const vm = new Vue(Constructor).$mount()
    expect(vm.$el.textContent).toBe("42")
  })
```

**Comment by pikax** [comment]
> There are some other functions that I cannot use because of this. It works in development, but not in production.
> 
> ```js
>  setup(props, context) {
>             useGoogleMaps('#address', context.emit);
> 
>             return {};
>         },
> ```
> 
> works in development, but not in production.

@rationalthinker1 That doesn't look the same error as the order of assignments being different on `dev` and `prod`  when mixed with options api.

--- 

I tried to reproduce it in [jsfiddle](https://jsfiddle.net/apL8ycev/2/), but getting `null` on `prod` and `dev` 
[vue-composition-api-test.zip](https://github.com/vuejs/composition-api/files/6390215/vue-composition-api-test.zip)


The merge behaviour seems to be consistent across dev/prod and web/node builds. 

Please provide a reproduction.

**Comment by ygj6** [comment]
I found that the demo was modified like [codesandbox](https://codesandbox.io/s/brave-currying-4qdmg?file=/src/App.vue) so that the problem could be reproduced.

**Comment by xinpingwang** [comment]
> I tried to reproduce it in [jsfiddle](https://jsfiddle.net/apL8ycev/2/), but getting `null` on `prod` and `dev`
> [vue-composition-api-test.zip](https://github.com/vuejs/composition-api/files/6390215/vue-composition-api-test.zip)
> 
> The merge behaviour seems to be consistent across dev/prod and web/node builds.
> 
> Please provide a reproduction.

@pikax  seems the problem is about HMR: when you first open the page, the value is `null`, but when you type some text in the html, the value changed to `42`.

```diff
- <div>{{ id }} - {{ JSON.stringify(id) }}</div>
+ <div>{{ id }} - {{ JSON.stringify(id) }} 11</div>
```

then add more data to data function or setup return block, the value changed to `null`.
```diff
 setup() {
   const data = reactive({
     id: 42,
+     a: 2
   });
   return data;
 },
 data() {
   return {
     id: null,
+     b: 3
   };
 }
```
