### ISSUE TITLE
`watch` does not work for reactive 

### ISSUE THREAD

**Issue by sogud** [vuejs/composition-api#682]
### Description
The watch function does not work when using an hooks file

### Minimal reproduction
Vue 2 example (broken):
[https://codesandbox.io/s/modest-fermat-0dh92?file=/src/App.vue](https://codesandbox.io/s/modest-fermat-0dh92?file=/src/App.vue)

Constrast this with the equivalent implentation in Vue 3, which works as expected:
[https://codesandbox.io/s/kind-resonance-tikku?file=/src/App.vue](https://codesandbox.io/s/kind-resonance-tikku?file=/src/App.vue)

**Comment by antfu** [comment]
There are some limitations of reactive arrays, should use like this

```ts
const countNumbers = useCount(toRef(count, "numbers"));
```

```ts
// hook.js
countNumbers.value = numbers.value.map((item) => item++);
```
