### ISSUE TITLE
if I mount some properties on a function，these properties will disappear when the function is passed 

### ISSUE THREAD

**Issue by shlroland** [vuejs/composition-api#687]
[here‘s a demo](https://codesandbox.io/s/funny-bhaskara-p8o3s?file=/src/components/HelloWorld.vue)

i cann't take the other properties which mounted on the function

**Comment by ygj6** [comment]
@shlroland 
**Change:**
`const testFn = () => {
      console.log(1);
    };`
**To:**
`const testFn = ref(() => {
      console.log(1);
    });`

will solve your problem!

**Comment by ygj6** [comment]
@shlroland Sorry, the description is not clear. Please refer to [this link](https://codesandbox.io/s/headless-flower-p7dvs?file=/src/App.vue) for details.
