### ISSUE TITLE
setup cannot use this pointer in vue2

### ISSUE THREAD

**Issue by lanweipeng** [vuejs/composition-api#691]
在vue2不能使用this指针。我想要使用this.$forceUpdate();

**Comment by pikax** [comment]
Please read [composition-api docs](https://v3.vuejs.org/guide/composition-api-introduction.html#basics-of-composition-api).

--- 

Please use issues for bugs or incorrect behaviour, for questions use [discord](https://vue.land) or [forum](https://forum.vuejs.org/).
