### ISSUE TITLE
When i use setup function in vue2 project i get some error in console

### ISSUE THREAD

**Issue by SKADaddy** [vuejs/composition-api#693]
```typescript
<script lang="ts">
import {
  defineComponent,
  ref,
  reactive,
  computed,
  onActivated,
  getCurrentInstance,
  ComponentInternalInstance,
  onBeforeMount,
  onMounted,
  SetupContext
} from '@vue/composition-api';
import DownloadDialog from '@/components/dialog/downloadDialog.vue';
import EmptyList from '@/components/emptyList/index.vue';
import Pagination from '@/components/Pagination/index.vue';
import ProtocolViewer from '@/components/protocolViewer/index.vue';
import * as dateUtil from '@/utils/dateUtil';
import { isPositiveNum } from '@/utils/formValidate';
import { clearObjectValue } from '@/utils/utils';
// import { Component, Ref, Vue } from 'vue-property-decorator';
import agreementMixin from '../composables/agreement.js';

interface IBillStatusItem {
  name: string;
  value: string;
}

export default defineComponent({
  components: { EmptyList, ProtocolViewer, DownloadDialog, Pagination },
  data() {
    return {};
  },
  setup(props: any, context: SetupContext) {
    let hasData = ref(false),
      billStatus: Array<IBillStatusItem> = reactive([]),
      form = reactive({
        billCode: '',
        billMaxMoney: '',
        billMinMoney: '',
        maturityDate: [],
        outputDate: [],
        inputName: '',
        outputName: '',
        queryType: ''
      }),
      pageSize = ref(10),
      pageNum = ref(1),
      total = ref(0),
      list: any = ref([]),
      blockHeight = ref(0),
      maturityStartDate = computed(() => {
        return form.maturityDate && form.maturityDate[0]
          ? dateUtil.getValueOfDateStart(form.maturityDate[0])
          : '';
      }),
      maturityEndDate = computed(() => {
        return form.maturityDate && form.maturityDate[1]
          ? dateUtil.getValueOfDateEnd(form.maturityDate[1])
          : '';
      }),
      outputStartDate = computed(() => {
        return form.outputDate && form.outputDate[0]
          ? dateUtil.getValueOfDateStart(form.outputDate[0])
          : '';
      }),
      outputEndDate = computed(() => {
        return form.outputDate && form.outputDate[1]
          ? dateUtil.getValueOfDateEnd(form.outputDate[1])
          : '';
      }),
      { proxy } = getCurrentInstance() as ComponentInternalInstance;
    const getList = async () => {
        console.log('getList');
      },
      resetSearch = () => {
        // some logic
      },
      exportExcel = () => {
        // some logic
      };

    onBeforeMount(() => {
      console.log('beforeMount')
    });
    onMounted(() => {
      console.log('mounted!');
    });
    onActivated(async () => {
      getList();
    });

    return {
      hasData,
      billStatus,
      form,
      pageSize,
      pageNum,
      total,
      list,
      blockHeight,
      maturityStartDate,
      proxy,
      ...agreementMixin(),
      getList,
      resetSearch,
      exportExcel
    };
  }
});
</script>
```
it show this error in console
![image](https://user-images.githubusercontent.com/38986298/117596144-48774c80-b175-11eb-842e-a11c7c1562d4.png)

and if my getList,resetSearch,exportExcel these 3 function return at the end.Vue will warn
``` javascript
 return {
      ...
      getList,
      resetSearch,
      exportExcel
    };
  }
```
![image](https://user-images.githubusercontent.com/38986298/117596359-c9cedf00-b175-11eb-97d9-7e480749f199.png)

but if i put them at the beginning like this,it will be fine
```javascript
      return {
         getList,
         resetSearch,
         exportExcel
         ...
         ...agreementMixin
}
```
but the `[Vue warn]: Error in data(): "TypeError: Cannot use 'in' operator to search for '__ob__' in undefined"` error still show up in the console
![image](https://user-images.githubusercontent.com/38986298/117743818-1f6cbf80-b23a-11eb-9841-9403560bca5c.png)

**Comment by SKADaddy** [comment]
> Do you mind provide a repository with reproducible code?
> 
> The code you provided relies heavily on code that's not provided.

sry,these code not comes from my own project.
But i use vue-cli create an vue2 project with the v4.5.10 and the error still show up in the console
![image](https://user-images.githubusercontent.com/38986298/117755814-8779d080-b24f-11eb-91c4-d42ce4ccd7b0.png)
and i put the code snippets in this project [vue2-composition-test](https://github.com/SKADaddy/vue2-composition-test)

This is my first time new an issue, my english is so bad :(. I hope this can help <3

**Comment by xinpingwang** [comment]
I created a [repo](https://github.com/xinpingwang/vue-composition-api-setup) to reproduce this issue, this issue is cause by the flowing code:

```
import { getCurrentInstance } from '@vue/composition-api'

export default {
  name: 'App',
  setup() {
    const { proxy } = getCurrentInstance()
    return { proxy }
  }
}
```

**Comment by ygj6** [comment]
@SKADaddy Use it like below, will work fine.

```
import { getCurrentInstance,onMounted } from '@vue/composition-api'

export default {
  name: 'App',
  setup() {
    let proxy
    onMounted(() => {
            proxy = getCurrentInstance()
          })
    return { proxy }
  }
}
```

**Comment by SKADaddy** [comment]
@xinpingwang if destruct the `proxy` from `getCurrentInstance()` will cause the problem, how can i access the function which on the Vue prototype

**Comment by xinpingwang** [comment]
@SKADaddy Don't know how you want to use the proxy. In my sense:
1. if you want to use function on Vue prototype inner `setup` function, you do not need to return it;
2. if you have other option like methods or lifecycle hooks, you can you `this` inner that function.

**Comment by SKADaddy** [comment]
@ygj6 but if i want to use `proxy` in `beforeCreate` or `created` hook like vue2, how can i achieve that.I watch the document it said `setup` function replace `beforeCreate` and `create`

**Comment by xinpingwang** [comment]
I tracked the call stack, and find the the cause of this issue.

the returned `proxy` has a `_renderProxy` prop, which is a `Proxy` instance defined in [Vue](https://github.com/vuejs/vue/blob/0603ff695d2f41286239298210113cbe2b209e28/src/core/instance/proxy.js#L68-L89), with `getHandler`.

<div style="display: flex">
<img src="https://user-images.githubusercontent.com/41824968/118145122-d4bc9480-b43f-11eb-95ae-c456aef931fc.png" width="400">
<img src="https://user-images.githubusercontent.com/41824968/118145691-70e69b80-b440-11eb-8389-cc52ec94cd2a.png" width="400">
</div>

and inner `initSetup` will goes into call `hasReactiveArrayChild` at line 128 https://github.com/vuejs/composition-api/blob/7955e2879754a26db57ca7ef7da35d3098c84480/src/mixin.ts#L119-L137.

then `hasReactiveArrayChild` will check if `_renderProxy` `isRaw`. https://github.com/vuejs/composition-api/blob/7955e2879754a26db57ca7ef7da35d3098c84480/src/mixin.ts#L184

inner `isRaw` will try to get `__ob__` and `__ob__.__raw__` of `_renderProxy`.
https://github.com/vuejs/composition-api/blob/7955e2879754a26db57ca7ef7da35d3098c84480/src/reactivity/reactive.ts#L9-L11

since `_renderProxy` is a `Proxy` instance, then `getHandler` called. but `_renderProxy.$data` is `undefined`, error occurs.  

https://github.com/vuejs/vue/blob/0603ff695d2f41286239298210113cbe2b209e28/src/core/instance/proxy.js#L68-L76

**Don't this issue should fix in vuejs/vue or this project.** 

@pikax Any suggestion?

**Comment by rizwanullah313** [comment]
[Vue warn]: Property or method "getList" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

found in

---> <App> at resources/js/vue/app.vue
       <Root> app.js:35021:15
