### ISSUE TITLE
vModel: __currentInstance.$set is not a function

### ISSUE THREAD

**Issue by Tarrowren** [vuejs/composition-api#699]
```tsx
// error
import { defineComponent, ref } from "@vue/composition-api";

export const App = defineComponent({
  name: "App",
  setup: () => {
    const name = ref("");
    return () => (
      <div>
        <div>{name.value}</div>
        <input type="text" vModel={name.value} />
      </div>
    );
  }
});
```

When I input, it throws:
![image](https://user-images.githubusercontent.com/35626141/119107054-7a2fc380-ba51-11eb-8b6c-c4209acff0e1.png)

```

TypeError: __currentInstance.$set is not a function
at input (App.tsx?1c6d:8)
at invokeWithErrorHandling (vue.runtime.esm.js?2b0e:1854)
at HTMLInputElement.invoker (vue.runtime.esm.js?2b0e:2179)
at HTMLInputElement.original.\_wrapper (vue.runtime.esm.js?2b0e:6917)

```

```tsx
// It's OK to write like this
import { defineComponent, ref } from "@vue/composition-api";

export const App = defineComponent({
  name: "App",
  setup() {
    const name = ref("");
    return { name };
  },
  render() {
    return (
      <div>
        <div>{this.name}</div>
        <input type="text" vModel={this.name} />
      </div>
    );
  }
});
```

**Comment by HIMISOCOOL** [comment]
setup () => {} is very different to setup() { }

I couldnt tell you the specifics but vue 2 only really works with method syntax and render is the official way for using jsx in vue2, does your example work if setup is a method but returns an arrow function?

**Comment by antfu** [comment]
Looks like it's related to the JSX plugin, maybe it's better to raise the issue there.

**Comment by waynecz** [comment]
Seems after this PR https://github.com/vuejs/composition-api/commit/1495a46ca9d571fc174eceb6abe61984196a2838,  the compiled `__currentInstance` from `getCurrentInstance()` doesn't have `$set` directly, but the `__currentInstance.proxy` does, [babel-sugar-v-model](https://github.com/vuejs/jsx-vue2/tree/dev/packages/babel-sugar-v-model) needs to update
