### ISSUE TITLE
cant reset the object value in setup

### ISSUE THREAD

**Issue by SKADaddy** [vuejs/composition-api#705]
Im using `composition-api` in `vue2` project 
```javascript
export const clearObjectValue = function(obj) {
  let result = _.merge({}, obj);
  for (let key in result) {
    result[key] = '';
  }
  return result;
};
```
```typescript
setup(){
  const { proxy } = getCurrentInstance() as ComponentInternalInstance;
  let Model = reactive({});

  // use $set set the property into the Model
  proxy.$set(Model, item.props.key, item.props.value ? item.props.value : '');
}
```
But when i want to reset the object,the `Model` will not be reactive
```typescript
  // will be not reactive
  Model = clearObjectValue(Model);
  

  // if use Object.assign it will work properly
  Object.assign(Model, clearObjectValue(Model));
  // but if use Object.assign to a new Object will not work too
  Object.assign({},Model,clearObjectValue(Model))

  // if not in setup()
  // this.Model = clearObjectValue(this.Model) will work
```
that make me confused because in the doc
[vue2 docs](https://vuejs.org/v2/guide/reactivity.html#For-Objects)
![image](https://user-images.githubusercontent.com/38986298/119434832-92525c00-bd4b-11eb-8dec-12d57ec7fb35.png)

**Comment by antfu** [comment]
Tried this?

```ts
reactive(Object.assign({},Model,clearObjectValue(Model)))
```

**Comment by SKADaddy** [comment]
> Tried this?
> 
> ```ts
> reactive(Object.assign({},Model,clearObjectValue(Model)))
> ```

@antfu
i try your code and it seems like it works,cause the value get reset
``` ts
console.log('before');
console.log(Model);
Model = reactive(Object.assign({}, Model, clearObjectValue(Model)));
console.log('after');
console.log(Model);
```
![image](https://user-images.githubusercontent.com/38986298/119761571-9b276700-bede-11eb-9482-4d3a95f4c9e7.png)
But i dont know why the data doesnt update? I check the dev tool which the new one can work in Vue2 or Vue3
it still stay at the before i reset the `Model` object
![image](https://user-images.githubusercontent.com/38986298/119761761-fd806780-bede-11eb-8eda-d9e3866d118f.png)
