### ISSUE TITLE
`emits` property for Vue 2.7

### ISSUE THREAD

**Issue by miralize** [vuejs/composition-api#708]
### What problem does this feature solve?
Could we introduce the [emits](https://v3.vuejs.org/guide/migration/emits-option.html) property in Vue 2.7, it might be helpful in transitioning to vue 3. 

Even if it was *only* mentioned in the docs , as its useful for documenting the component and it assists in migration. 

### What does the proposed API look like?
```js
export default {
  name: 'ComponentName'
  emits: ['open', 'close']
  setup(props, { emit }) {
    const close = () => {
      emit('close')      
    }
    const open = () => {
      emit('open')      
    }
    return {
      open,
      close,
    }
}
```

**Comment by Alanscut** [comment]
[emits](https://v3.vuejs.org/guide/migration/emits-option.html) is not a part of `compositon-api`, [vue-compat](https://github.com/vuejs/vue-next/tree/master/packages/vue-compat) allows you to use `emits` in a `Vue 2` project, it may help you.

**Comment by posva** [comment]
I transferred this issue thinking it could be a feature request for typings of `emits` in `defineComponent`. @antfu @pikax I'm sorry if it created any inconvenience, I should have commented at the time I transferred the issue.

**Comment by miralize** [comment]
My point was more to maybe encourage people on vue 2 to start getting into the habit of documenting the events?

**Comment by Djaler** [comment]
Also this can be typechecked via vue-tsc/volar

**Comment by Djaler** [comment]
> [emits](https://v3.vuejs.org/guide/migration/emits-option.html) is not a part of `compositon-api`, [vue-compat](https://github.com/vuejs/vue-next/tree/master/packages/vue-compat) allows you to use `emits` in a `Vue 2` project, it may help you.

vue-compat can't be used in many scenarious due to limitations. For example, mine - is a Vuetify that used undocumented behavior of Vue 2
