### ISSUE TITLE
export `Prop<T>` type

### ISSUE THREAD

**Issue by sidelong44** [vuejs/composition-api#71]
I want to implement a mixin factory with dynamic prop like this:
```typescript
export default mixinFactory<P extends string, T>(prop: P, options: Prop<T>) {
    return createComponent({
        props: {
            [prop]: options
        },
        setup(props, ctx) {
            // Something code
        }
}
```
But, since the `Prop<T>` type is not exported, I have to use the `PropValidator<T>`. Because of this, *TypeScript* will throw an error:
```
TS4058: Return type of exported function has or is using name 'PropOptions' from external module "<project>/node_modules/vue-function-api/dist/ts-api/componentProps" but cannot be named.
```
Why is the `Prop<T>` type not exported from `vue-function-api/dist/ts-api/componentProps.d.ts`?

**Comment by pikax** [comment]
@liximomo can't the Prop and other types being imported from `vue` types? 

Since the most of the types in componentProps.ts seem to be almost the same as the ones in the the `vue/types/options`
