### ISSUE TITLE
How do I set the type when I pass ref to child component

### ISSUE THREAD

**Issue by LaamGinghong** [vuejs/composition-api#711]
I want to call the method of the child component in the parent component, so how do I set the type of the child component in the parent component.

This is my code, which cannot get the type correctly in webstorm:

```vue
<template>
   <child-component ref="childRef"/>
</template>

<script lang="ts">
import { defineComponent, ref } from '@vue/composition-api';

import ChildComponent from './ChildComponent.vue'

export default defineComponent({
  components: { ChildComponent },
  setup() {
    const childRef = ref<InstanceType<typeof ChildComponent> | null>(null)
    
    const handleClick = () => {
        childRef.value!.childComponentMethod() // can't get types correctly
   }
  return { childRef }
 }
})
</script>
```

The version is `1.0.0-rc..8`

**Comment by ygj6** [comment]
@LaamGinghong Whether the `ChildComponent` is wrapped with `defineComponent`?

**Comment by LaamGinghong** [comment]
> @LaamGinghong Whether the `ChildComponent` is wrapped with `defineComponent`?

yes

**Comment by ygj6** [comment]
I've written a [demo](https://codesandbox.io/s/condescending-northcutt-phpbm?file=/src/App.vue) that doesn't seem to have the problem you described. Could you share your `ChildComponent` code?

**Comment by LaamGinghong** [comment]
Your demo looks as same as my code. In my code, if I write the code correctly in the parent component, although I can get the correct type hint, it is more like the IDE gets it through its own guesses rather than through the correct type inference.

**Comment by LaamGinghong** [comment]
I’m very sorry, because of the confidentiality agreement, I can’t show the real code to you.

**Comment by LaamGinghong** [comment]
So, currently I can only manage by defining an additional interface type
