### ISSUE TITLE
watch breaks for ref with shallowReadonly

### ISSUE THREAD

**Issue by schTi** [vuejs/composition-api#712]
Version: v1.0.0-rc.10

After aligning the watch behavior in the latest release, my watchers are broken for `ref` variables, that have a `shallowReadonly` around them. This is because `isRef` does not return `true` for these kind of variables and so the getter will throw an error, that it got an invalid watch source.

Any chance to get this fixed?

**Comment by iheyunfei** [comment]
Could you provide an online example? That would be very helpful.
