### ISSUE TITLE
how to ues golbalAPI in setup like this.$message?

### ISSUE THREAD

**Issue by feiyu1995** [vuejs/composition-api#713]
setup(props, ctx) {
   const { $message } = ctx.root
}

Vetur Tip: 'root' is deprecated。

What are the alternatives？

**Comment by iheyunfei** [comment]
Just use `getCurrentInstance`.
like `const { $message } = getCurrentInstance()`

**Comment by danielroe** [comment]
You may need to do:
```js
const { $message } = getCurrentInstance().proxy
```

However, this would need to be updated when you migrate to Vue 3. If it's within your control, I'd suggest a more idiomatic behaviour, such as by using provide/inject.

**Comment by feiyu1995** [comment]
> You may need to do:
> 
> ```js
> const { $message } = getCurrentInstance().proxy
> ```
> 
> However, this would need to be updated when you migrate to Vue 3. If it's within your control, I'd suggest a more idiomatic behaviour, such as by using provide/inject.

thanks
