### ISSUE TITLE
Incorrect check isReactive for Proxy objects

### ISSUE THREAD

**Issue by Djaler** [vuejs/composition-api#715]
I have this code that using some DI container:
```
setup() {
   const readApi = container.resolve(ReadApi);

   return { readApi }
}
```

In my tests I replace value, provided by container, with mock object, created using jest-mock-extended. Under the box it's just a `Proxy` object.

It works well until I updated to version `rc.9`.
Here we have this change: https://github.com/vuejs/composition-api/commit/8c27d80#diff-40aa26982716adc75031925664c28d5fb4fc6dac8c7ce4d6f5122b61c1ed773eR27
And now I have such errors: `Cannot read property 'depend' of undefined`.
That's because isReactive checks for `__ob__` property of object, which is exists, but it's a mock function. So, `propValue.__ob__.dep` is undefined. Maybe you can add additional check in isReactive or just do something like `isReactive(propValue) && propValue.__ob__.dep)`

**Comment by iheyunfei** [comment]
maybe use this to mock your value ?

https://github.com/vuejs/composition-api/blob/2c342d5778850904e1b35e680178b8aeb80b30d7/src/reactivity/reactive.ts#L130-L140

**Comment by Djaler** [comment]
I don't think this should be exposed to client side

**Comment by Djaler** [comment]
Can you please answer is this supposed to be fixed or I should search for a workaround?

**Comment by iheyunfei** [comment]
@Djaler I think core team will fix this eventually, but I'm not sure when and how. Since `composition-api` will move into vue2's codebase, which maybe also has an effect on fixing.

For your case, a workaround should be good for now.
