### ISSUE TITLE
Ref not unwrapping other refs set with `set` on Node

### ISSUE THREAD

**Issue by posva** [vuejs/composition-api#721]
- Clone https://github.com/posva/bug-report-vca
- `yarn`
- `node index.js`

It should log an object `{ old: false, new: true }` but it logs `{ old: false, new: { value: true }}`

There is also an index.html file to show the (expected) behavior on a browser

**Comment by iheyunfei** [comment]
It looks like the root cause is lacking of `__ob__` on reactive object in SSR.
