### ISSUE TITLE
Add and example of usage template refs with v-if

### ISSUE THREAD

**Issue by Ky6uk** [vuejs/composition-api#725]
Hello. I've spent a lot of time and found the `v-if` just doesn't work with template refs. Replacing to `v-show` will not help because some components have rendering logic on the `mounted` lifecycle.

It would be useful to add some examples to documentation with this case to show how to migrate existing-working logic from Vue 2 to Vue 3, for code like this:

```vue
<template>
  <div>
    <!-- ... -->

    <DialogComponent 
      v-if="hasDialog"
      ref="dialogRef"
    />
  </div>
</template>
```

**Comment by iheyunfei** [comment]
Could you gave more information about the problem or a reproduction link.

**Comment by iheyunfei** [comment]
It works in this example. https://codesandbox.io/s/lingering-lake-k2fdc?file=/src/components/HelloWorld.vue

**Comment by Ky6uk** [comment]
@iheyunfei Hmm. Thanks. 👍 

I was also got some deep diving here and have found it may be an issue of usage `portal-vue`. The component with the issue has been rendered inside the portal. I think this one can be closed.
