### ISSUE TITLE
Pushing to a shallowReactive Array leads to reactive elements

### ISSUE THREAD

**Issue by bkuster** [vuejs/composition-api#728]
# Issue
When pushing to a reactive array created with `shallowReactive`, the elements which are pushed _after_ creating the reactive variable are watched.

# Reproduction
```javascript
const elem1 = {};
const array = shallowReactive([elem1]);
isReactive(elem1); // false
const elem2 = {};
array.push(elem2);
isReactive(elem1); // false
isReactive(elem2); // true
```

# Expected behavior (vue3)
The pushed element is _not_ reactive.

**Comment by ygj6** [comment]
@bkuster From the following `vue` source code, it seems not easy.
https://github.com/vuejs/vue/blob/612fb89547711cacb030a3893a0065b785802860/src/core/observer/array.js#L24-L44

**Comment by bkuster** [comment]
Hey @ygj6, thanks for the feedback. Without knowing too much about the code base, would it be a viable solution to apply the patch _again_ for `shallowReactive` Arrays and just omit the part where the inserted element gets observed?
