### ISSUE TITLE
Computed on xstate context

### ISSUE THREAD

**Issue by allestaire** [vuejs/composition-api#733]
How do we use computed on xstate context?
I tried
```javascript

const Machine = createMachine({
 ...
 context: {},
...
})
export default {
 ...
 setup() {
 const {state, send} = useMachine(Machine, {
  ...
  })
  const hasArr= computed(() =>  state.context.arr.length>0)
  return {state, send, hasArr}
 }
}
```

This code will code the Vue Dev Tools to not function, but removing the computed coded, the component will be back to normal.

On this state, the component will keep loading.
![image](https://user-images.githubusercontent.com/68372409/122675184-ddf10c00-d20a-11eb-8812-928f0d986814.png)
Removed computed values which is dependent to xstate context
![image](https://user-images.githubusercontent.com/68372409/122675222-07119c80-d20b-11eb-9c22-303dfa61bbe9.png)

**Comment by ygj6** [comment]
@allestaire I think the `state`  should be set to `ref/reactive`. If you could provide a simple reproduction demo, it might be easier to solve the problem.

**Comment by allestaire** [comment]
Sorry I can provide yet a reproduction demo.
 Still got problem when using the `reactive` it does not work properly as what the documentation stated.
I still doing testing to make thing work, but if there are any response to this issue and Im glad to read it and to get some clues in order to work with it.

By the ways thanks for the response, this will help me :)

**Comment by allestaire** [comment]
Also you are right, computed only reacts to a reactive variable. It only listens to the reactive variables changes. but still I will do some testing :)
