### ISSUE TITLE
watcher not stop normally

### ISSUE THREAD

**Issue by ailtariel** [vuejs/composition-api#763]
It's very complicated. Sorry for my poor English.

1. You have a persistent variable, like:

```
<app.vue> 
provide('foo', foo)

<test.vue>
const foo = inject('foo')
```
The foo will not be destroyed by leave test.vue, all right?

2. watch foo and do some await in setup.

```
<test.vue>
setup() {
  onMounted( async () => {
    await dosomething...
    watch( foo, (val, oldval, oninvalidate ) => {
      oninvalidate( () => { console.log('goodbye') }
      console.log(foo)
    }
  }
}
```

3. Now, visit test.vue, then visit another page.You will not see 'goodbye', the watcher still exist.
BECAUSE, await makes some kind of BLOCK.
If you remove the await, goodbye, everthing is fine.

4. Now, you have a unstopped watcher, you have a persistent foo.
Visit test.vue again( for example, press backward ), and try to change foo, you can see console log twice.
Of course, you can stack and stack the watcher by switch pages.

**Comment by antfu** [comment]
Aright, I have wrote a blog post for you, and hope it could answers your questions.

https://antfu.me/posts/async-with-composition-api

**Comment by ailtariel** [comment]
> 
> 
> Aright, I have just wrote a blog post for you, and hope it could answers your questions.
> 
> https://antfu.me/posts/async-with-composition-api

Very helpful to me. THANKS very much!
