### ISSUE TITLE
Initialization problem in 1.0.3

### ISSUE THREAD

**Issue by GeekyMonkey** [vuejs/composition-api#769]
Version 1.0.2 works fine in my project, but when I tried to go to 1.0.3 I get this

"[vue-composition-api] must call Vue.use(VueCompositionAPI)"

I've tried adding this at the top of main.ts

    Vue.use(VueCompositionApi);

But that didn't help.  Rolling back to 1.0.2 for now.

**Comment by Ttou** [comment]
same issue

**Comment by ygj6** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by GeekyMonkey** [comment]
@ygj6 Sorry, I've a big hairy project and under time pressure at the moment so I can't make a minimal version. Hopefully someone else with the problem can share.

**Comment by schillerenrico** [comment]
same here

**Comment by tobidalhof** [comment]
https://github.com/vueuse/vueuse/issues/640 related?

**Comment by lpj145** [comment]
Same here, i simple install latest version of composition-api and vue-use, and when i call Vue.use(CompositionApi) i have unexpected error:
![image](https://user-images.githubusercontent.com/11980109/126528780-b9964d65-01e9-444d-8d65-93224b5971d3.png)

The steps is:
yarn add @vue/composition-api
yarn add @vueuse/core

and create component and try to use `onClickOutside`

**Comment by lpj145** [comment]
@antfu something about vue-composition is installing when it's imported.

**Comment by ygj6** [comment]
This  [line](https://github.com/vueuse/vue-demi/blob/8815cc616f236e156d65433fd2caf8bfb0285a41/scripts/utils.js#L39) :
```
export { ${exports.join(', ')} } from '@vue/composition-api/dist/vue-composition-api.esm.js'
 ```
caused both `vue-composition-api.esm.js` and `vue-composition-api.mjs` versions to be used at the same time.

And the [install function](https://github.com/vuejs/composition-api/blob/2ba5a66d29dfe9441fcaac9f667c74f6821692d8/src/install.ts#L42):
```
export function install(Vue: VueConstructor)
```
 of composition-api was not called in `vue-composition-api.mjs`.

So it caused the problem.
