### ISSUE TITLE
Altering a ref to a ref changes the original

### ISSUE THREAD

**Issue by SatelliteThrow** [vuejs/composition-api#781]
consider the following:

    const foo = ref(false)
    const bar = ref(foo)
    bar.value = true;
    console.log(foo.value) // true. foo has been altered by assigning a new value to bar

Setting a new value to the bar reference should not impact foo.

**Comment by LinusBorg** [comment]
then don't wrap the ref.

```js
const foo = ref(false)
const bar = ref(foo.value)
bar.value = true;
console.log(foo.value) // false.
```
