### ISSUE TITLE
Props don't update on ref change

### ISSUE THREAD

**Issue by SatelliteThrow** [vuejs/composition-api#782]
This outer SFC
    `<template>
      <div>
        outer: {{foo}}
        <Inner :foo="foo"/>
      </div>
    </template>`

    <script>
    import { ref, watch } from "vue";
    import Inner from '@/components/Test_inner.vue'

    export default {
      components: {Inner},
      setup() {
        const foo = ref('foo');
        setTimeout(() => {
          foo.value = 'bar'
        }, 2000);

        return {foo}
      },
    };
    </script>

------------------------------
with this inner:
    `<template>
      <div>inner: {{foo}}</div>
    </template>`

    <script>
    export default {
      props: ['foo'],
      setup(props) {
        return {foo: props.foo}
      }
    }
    </script>

will result in
outer: bar
inner: foo

Isn't this supposed to be reactive recursively?

**Comment by SatelliteThrow** [comment]
Additionally, adding a parameter "bar" like this:

    const bar = computed(() => foo)

results in 

outer_foo: bar outer_bar: { "_rawValue": "bar", "_shallow": false, "__v_isRef": true, "_value": "bar" }
inner_foo: foo inner_bar: { "_rawValue": "bar", "_shallow": false, "__v_isRef": true, "_value": "bar" }

so the actual reactive is being passed instead of the value.

**Comment by jacekkarczmarczyk** [comment]
don't return props from setup()

**Comment by antfu** [comment]
Props is a reactive object, return the entire object as is, or use toRef(props, 'foo')
