### ISSUE TITLE
嵌套的watch调用无法正常运行

### ISSUE THREAD

**Issue by dnt1996** [vuejs/composition-api#783]
```javascript
export default {
  name: "App",
  components: {
    HelloWorld,
  },
  setup() {
    const a = ref("a");
    const b = ref("b");

    watch(
      a,
      (_, __, onInvaild) => {
        const stopWatchB = watch(b, console.log);
        onInvaild(() => {
          console.log("stop watch b");
          stopWatchB();
        });
      },
      { immediate: true } //immediate 为false时正常
    );
    setTimeout(() => {
      a.value = "aa";
    }, 1000);
  },
};

```
`[Vue warn]: Error in onCleanup(): "RangeError: Maximum call stack size exceeded"`

https://codesandbox.io/s/inspiring-mahavira-4cl4q?file=/src/App.vue:275-736

**Comment by albumnyc** [comment]
`
export default {
  name: "App",
  components: {
    HelloWorld,
  },
  setup() {
    const a = ref("a");
    const b = ref("b");

   const stopWatchB = watch(b, console.log);
   
 
    watch(
      a,
      (_, __, onInvaild) => {
       
        onInvaild(() => {
          console.log("stop watch b");
          stopWatchB();
        });
      },
      { immediate: true } //immediate 为false时正常
    );
    setTimeout(() => {
      a.value = "aa";
    }, 1000);
  },
};

`
watch本身就需要在setup中直接执行。无法动态化

**Comment by dnt1996** [comment]
> `
> 
> export default {
> 
>   name: "App",
> 
>   components: {
> 
>     HelloWorld,
> 
>   },
> 
>   setup() {
> 
>     const a = ref("a");
> 
>     const b = ref("b");
> 
> 
> 
>    const stopWatchB = watch(b, console.log);
> 
>    
> 
>  
> 
>     watch(
> 
>       a,
> 
>       (_, __, onInvaild) => {
> 
>        
> 
>         onInvaild(() => {
> 
>           console.log("stop watch b");
> 
>           stopWatchB();
> 
>         });
> 
>       },
> 
>       { immediate: true } //immediate 为false时正常
> 
>     );
> 
>     setTimeout(() => {
> 
>       a.value = "aa";
> 
>     }, 1000);
> 
>   },
> 
> };
> 
> 
> 
> `
> 
> watch本身就需要在setup中直接执行。无法动态化

我记得Vue3里ref, reactive, watch是支持setup外调用的

**Comment by albumnyc** [comment]
> > `
> > export default {
> > name: "App",
> > components: {
> > ```
> > HelloWorld,
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > },
> > setup() {
> > ```
> > const a = ref("a");
> > 
> > const b = ref("b");
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > const stopWatchB = watch(b, console.log);
> > ```
> > watch(
> > 
> >   a,
> > 
> >   (_, __, onInvaild) => {
> > 
> >    
> > 
> >     onInvaild(() => {
> > 
> >       console.log("stop watch b");
> > 
> >       stopWatchB();
> > 
> >     });
> > 
> >   },
> > 
> >   { immediate: true } //immediate 为false时正常
> > 
> > );
> > 
> > setTimeout(() => {
> > 
> >   a.value = "aa";
> > 
> > }, 1000);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > },
> > };
> > `
> > watch本身就需要在setup中直接执行。无法动态化
> 
> 我记得Vue3里ref, reactive, watch是支持setup外调用的

报错的代码。
Error in onCleanup()，在watch和watchEffect会被调用，用来执行nexttick的回调。
  const registerCleanup: InvalidateCbRegistrator = (fn: () => void) => {
  // 赋值给cleanup，执行结果为fn（）

  // 组件加载后，watchEffect() 中的 effect 回调被立即执行
  // 此时能在 effect() 函数中，能访问到目标值
  // 在 nextTick 中，onCleanup 被赋值为一个函数，即源码中的 registerCleanup(fn) => void
  // 同时，onCleanup 只是被声明创建出来，其真正生效的 fn 参数尚不会被立即执行
  // 同时，在 effect 回调中能访问到目标的初始值
  // 对目标赋值
  // 在 nextTick 中，effect 回调中能访问到目标的新值
  // 此时，由于目标变化，onCleanup 被执行一次
  // 销毁 vue 实例后的 nextTick 中，onCleanup 再被执行一次

    cleanup = () => {
      try {
        fn()
      } catch (error) {
        logError(error, vm, 'onCleanup()')
      }
    }
  }
  // cleanup before running getter again
  // 执行cleanup并重置
  const runCleanup = () => {
    if (cleanup) {
      cleanup()
      cleanup = null
    }
  }


这里的实现和vue3的实现方式是一致的奥～

**Comment by dnt1996** [comment]
> > > `
> > > export default {
> > > name: "App",
> > > components: {
> > > ```
> > > HelloWorld,
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > },
> > > setup() {
> > > ```
> > > const a = ref("a");
> > > 
> > > const b = ref("b");
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > const stopWatchB = watch(b, console.log);
> > > ```
> > > watch(
> > > 
> > >   a,
> > > 
> > >   (_, __, onInvaild) => {
> > > 
> > >    
> > > 
> > >     onInvaild(() => {
> > > 
> > >       console.log("stop watch b");
> > > 
> > >       stopWatchB();
> > > 
> > >     });
> > > 
> > >   },
> > > 
> > >   { immediate: true } //immediate 为false时正常
> > > 
> > > );
> > > 
> > > setTimeout(() => {
> > > 
> > >   a.value = "aa";
> > > 
> > > }, 1000);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > },
> > > };
> > > `
> > > watch本身就需要在setup中直接执行。无法动态化
> > 
> > 
> > 我记得Vue3里ref, reactive, watch是支持setup外调用的
> 
> 报错的代码。
> Error in onCleanup()，在watch和watchEffect会被调用，用来执行nexttick的回调。
> const registerCleanup: InvalidateCbRegistrator = (fn: () => void) => {
> // 赋值给cleanup，执行结果为fn（）
> 
> // 组件加载后，watchEffect() 中的 effect 回调被立即执行
> // 此时能在 effect() 函数中，能访问到目标值
> // 在 nextTick 中，onCleanup 被赋值为一个函数，即源码中的 registerCleanup(fn) => void
> // 同时，onCleanup 只是被声明创建出来，其真正生效的 fn 参数尚不会被立即执行
> // 同时，在 effect 回调中能访问到目标的初始值
> // 对目标赋值
> // 在 nextTick 中，effect 回调中能访问到目标的新值
> // 此时，由于目标变化，onCleanup 被执行一次
> // 销毁 vue 实例后的 nextTick 中，onCleanup 再被执行一次
> 
> ```
> cleanup = () => {
>   try {
>     fn()
>   } catch (error) {
>     logError(error, vm, 'onCleanup()')
>   }
> }
> ```
> 
> }
> // cleanup before running getter again
> // 执行cleanup并重置
> const runCleanup = () => {
> if (cleanup) {
> cleanup()
> cleanup = null
> }
> }
> 
> 这里的实现和vue3的实现方式是一致的奥～

可是相同的代码在vue3是正常运行的
