### ISSUE TITLE
<script setup> ready in 1.1.0 ?

### ISSUE THREAD

**Issue by lizy0329** [vuejs/composition-api#785]
@vue/composition-api 1.1.0 - align with Vue v3.2

Is mean we can use <script setup> for my project?

**Comment by ygj6** [comment]
Currently does not support `<script setup>`.

**Comment by es3154** [comment]
@ygj6 Is there a follow-up support plan?

**Comment by antfu** [comment]
`<script setup>` is not part of Composition API and it should be done at the compiler side.

**Comment by lizy0329** [comment]
> `<script setup>` is not part of Composition API and it should be done at the compiler side.

Can you write some description?

**Comment by antfu** [comment]
Now you have this:
https://github.com/antfu/vue2-script-setup-transform
