### ISSUE TITLE
The callback function of watchEffect will not be triggered to execute.

### ISSUE THREAD

**Issue by ygj6** [vuejs/composition-api#787]
**Version**
1.1.1

**Reproduction link**
https://codesandbox.io/s/quizzical-driscoll-ekmu0?file=/src/App.vue

**Steps to reproduce**
click the button.

**What is expected?**
The callback function of `watchEffect` will be triggered to execute.

**What is actually happening?**
The callback function is not triggered.

**Comment by Djaler** [comment]
I don't think it should be triggered, because num.value not `getted` inside watchEffect, only `setted`
