### ISSUE TITLE
Template Ref in Root definition is null

### ISSUE THREAD

**Issue by kylerberry** [vuejs/composition-api#789]
**Version:**
Vue 3.1.4

**Description:** 
My root component is attempting to retrieve a template reference in `onMounted()` but `myRef.value` is coming up `null`. However, using `getCurrentInstance().refs.myRef` does get the correct value. 

**Reproduce-able Link**
https://codesandbox.io/s/flamboyant-bush-86hu9?file=/src/App.vue

**Expectaction**
`myRef.value` should not be null

**Comment by ygj6** [comment]
I think you should submit an issue in the `vue-next` community: https://github.com/vuejs/vue-next/issues

**Comment by antfu** [comment]
Because you didn't return the ref. Please use Discord or Forums to ask question.

**Comment by kylerberry** [comment]
🤦
