### ISSUE TITLE
Throws exception on the "Basic Example" inside "computed" getter

### ISSUE THREAD

**Issue by mickeyvip** [vuejs/composition-api#79]
I am trying to play with the new composition API.

Installed the plugin and copied the "Basic example" from https://vue-composition-api-rfc.netlify.com/#basic-example.

It throws an exception inside the `computed` getter.

```
[Vue warn]: Error in setup(): "TypeError: Cannot read property 'count' of undefined"

found in

---> <Counter> at src/components/Counter.vue
       <App> at src/App.vue
         <Root>
```

The `state` is declared as follows:

```js
setup() {
    const state = reactive({
      count: 0,
      double: computed(() => state.count * 2)
    })
   //...
}
```

Am i doing something wrong or is this not supported yet in the plugin?

Thank you.

**Comment by doncatnip** [comment]
It would seem that the computed property is called immediately, so state is not known yet.
This should work:

      const state = reactive({
        count: 0,
      })
      state.double = computed(() => state.count * 2)

**Comment by mickeyvip** [comment]
@doncatnip , thank you.

Seems like this plugin is not 100% compliant with the RFC?

**Comment by doncatnip** [comment]
It certainly isn't. Some shortcomings are documented. This one isn't (if it is indeed one, and not a mistake in the example).

**Comment by mickeyvip** [comment]
Got it.

Thank you

**Comment by albumnyc** [comment]
您好，我没理解到为什么使用Object.seal可以解决这个问题呢。  可以指导下嘛

**Comment by albumnyc** [comment]
您好，我没理解到为什么使用Object.seal可以解决这个问题呢。 可以指导下嘛
@liximomo 
Hello, I did not understand why using Object.seal can solve this problem. Can you guide me
