### ISSUE TITLE
@vue/composition-api doesn't work when bundled in multiple libraries

### ISSUE THREAD

**Issue by johannes-z** [vuejs/composition-api#792]
I'm loading `vue` and 2 of my own component libraries `package-a` and `package-b` via requirejs. Both of my component libraries bundle `@vue/composition-api`, and install the plugin:

```js
import Vue from 'vue'
import VueCompositionAPI from '@vue/composition-api'

Vue.use(VueCompositionAPI)
```

`package-b` imports components from `package-a`, which results in this runtime error: `TypeError: Cannot read property 'config' of null`. 

I've noticed, that the plugin sets a flag on Vue to skip multiple install statements: https://github.com/vuejs/composition-api/blob/master/src/install.ts#L43. This flag is set on Vue, but the second *instance*  of `@vue/composition-api` bundled within `package-b` never calls `setVueConstructor`, because it detects the plugin as installed. This causes the `Ctor` in https://github.com/vuejs/composition-api/blob/master/src/utils/helper.ts#L25 to be null, causing the mentioned error. `package-a` calls `setVueConstructor` and works normally.

**Comment by johannes-z** [comment]
By moving `setVueConstructor(Vue)` (https://github.com/vuejs/composition-api/blob/master/src/install.ts#L76) up to be the very first line in the `install` function, the issue is fixed...

**Comment by johannes-z** [comment]
Related issue https://github.com/vuejs/composition-api/issues/228

`@vue/composition-api` apparently cannot be used when both the component library and the consuming app use and bundle `@vue/composition-api`. This is a big issue, since you cannot use the component library without also using `@vue/composition-api` in the consuming app.

**Comment by antfu** [comment]
Yes. It requires you are have only one instance of the plugin in user's app. You should external it in the lib.

**Comment by johannes-z** [comment]
This means that you cannot import the components in for example an UMD environment and use the components directly, unless you also import `@vue/composition-api`. 

I found two workarounds for my particular issue:
1. externalize `@vue/composition-api` from all bundles, and import it via UMD.
2. export `@vue/composition-api` from the component library and import it in the consuming app.

**Comment by antfu** [comment]
Yes. That's the current solution. You will need to ask user to install @vue/composition-api themselves to avoid duplication (same as the `vue` dep, you externalize it). On the other side, when Vue 2.7 comes out, @vue/composition-api will be directly shipped with it so the extra step will no longer be needed.

**Comment by fish-uncle** [comment]
能说明白点吗？我也遇到了同样的问题

**Comment by duoWB** [comment]
> 问题说明白点吗？我也能遇到同样的问题

请问您解决了吗？

**Comment by kkkkh** [comment]
> > 问题说明白点吗？我也能遇到同样的问题
> 
> 请问您解决了吗？


> Yes. That's the current solution. You will need to ask user to install @vue/composition-api themselves to avoid duplication (same as the `vue` dep, you externalize it). On the other side, when Vue 2.7 comes out, @vue/composition-api will be directly shipped with it so the extra step will no longer be needed.

2.7 will resolve

目前好像只能

> 1. externalize `@vue/composition-api` from all bundles, and import it via UMD.
> 2. export `@vue/composition-api` from the component library and import it in the consuming app.
