### ISSUE TITLE
Watchers created inside Options API hooks should be bound to the current Vue 2 instance

### ISSUE THREAD

**Issue by chearon** [vuejs/composition-api#797]
In Vue 3, you can call `watch`, `watchEffect`, etc. from Options API hooks like `created`, and they will be torn down when the VM is destroyed. It's highly useful to use these functions outside of just the `setup` API because they can be imported and used by supporting libraries.

In `@vue/composition-api`, you can do this, but the VM that gets used is the fallback VM, which is global, so doing this is effectively a memory leak.

I have a test and a patch that I'll submit soon.

**Comment by antfu** [comment]
I don't think you should use composition-api inside options api. Even tho it might work in Vue 3, it's an undocumented behavior and you would like to avoid doing that in production.

**Comment by chearon** [comment]
> I don't think you should use composition-api inside options api

I was surprised to learn this, but after digging a bit and some discussion on Discord it sounds like the Vue-recommended way is to use `setup`.

The Vue source looks pretty intentional about setting the active VM in Options API hooks and tying `watch` et al to it. Oh well. If I decide to do that I can use a fork of this repo. Thanks!
