### ISSUE TITLE
user-select change to none

### ISSUE THREAD

**Issue by nishuonishuo** [vuejs/composition-api#801]
Vue.use(VueCompositionAPI) cause my text cant be selected and all input can not focus by click

**Comment by nishuonishuo** [comment]
vue version is 2.6.11   plugin versio is 1.1.3

**Comment by antfu** [comment]
Can't help without a proper reproduction.

**Comment by nishuonishuo** [comment]
![image](https://user-images.githubusercontent.com/33366731/130387916-339dafff-c715-4f75-a408-073230cf794b.png)

**Comment by nishuonishuo** [comment]
![image](https://user-images.githubusercontent.com/33366731/130387973-e891ae15-4ca3-4d37-9121-5330d7aa5522.png)
when i do this , can be work

**Comment by antfu** [comment]
Sorry this is not so call "reproduction". And please narrow down to a minimal repro.

**Comment by nishuonishuo** [comment]
but i can not use this plugin anymore

**Comment by antfu** [comment]
If you want help, please at least provide enough effort about the context.

**Comment by nishuonishuo** [comment]
sorry, but when my code Vue.use(VueCompositionAPI) ,my inpu element can not focus....and all text can not selected
