### ISSUE TITLE
`createElement()` has been called outside of render function.  when handleSuccessMessage function used

### ISSUE THREAD

**Issue by nishuonishuo** [vuejs/composition-api#804]
![image](https://user-images.githubusercontent.com/33366731/130744601-c99a194f-e23f-42d9-9aff-e0cab3768e81.png)
![image](https://user-images.githubusercontent.com/33366731/130744629-b747410c-f181-4c2a-8f64-1a7b291c612d.png)

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by nishuonishuo** [comment]
https://codesandbox.io/s/sleepy-lederberg-50px2?file=/src/main.js
![image](https://user-images.githubusercontent.com/33366731/130773683-e42eb61b-3844-4b4c-9991-a457cfb16fa5.png)
you can visit it and click for bug

**Comment by Ttou** [comment]
1.2.1 has same problem, 1.1.5 is ok

**Comment by k644606347** [comment]
em...same problem, v1.2.4

**Comment by Hyphon** [comment]
v1.4.3 has same problem.

**Comment by MinatoHikari** [comment]
use `setup: () => {}` to avoid this warning.

**Comment by hisuwh** [comment]
Any updates on this?

**Comment by MinatoHikari** [comment]
Let's check about `createElement.ts`

```javascript
export const createElement = function createElement(...args: any) {
  const instance = getCurrentInstance()?.proxy
  if (!instance) {
    __DEV__ &&
      warn('`createElement()` has been called outside of render function.')
    if (!fallbackCreateElement) {
      fallbackCreateElement = defineComponentInstance(
        getVueConstructor()
      ).$createElement
    }

    return fallbackCreateElement.apply(fallbackCreateElement, args)
  }

  return instance.$createElement.apply(instance, args)
} as CreateElement
```

`const instance = getCurrentInstance()?.proxy`
This is the cause of warning.

**Remember that we can't get instance out of `setup` with `getCurrentInstance`.**
It returns null when you call it in click event.

The solution is calling h in setup function 
https://codesandbox.io/s/lingering-currying-l03w6f?file=/src/components/HelloWorld.vue

**Comment by antfu** [comment]
PR welcome to bypass the warning in this case.

**Comment by Dcx199302** [comment]
> 用于`setup: () => {}`避免此警告。

content: () => h('div', {}, [h('p', '使用函数返回正确执行')]),

**Comment by Dcx199302** [comment]
> 用于`setup: () => {}`避免此警告。

content: () => h('div', {}, [h('p', '使用函数返回正确执行')])     
content: h('div', {}, [h('p', '直接调用报错上面提到的警告')]

**Comment by MinatoHikari** [comment]
> > 用于`setup: () => {}`避免此警告。
> 
> content: () => h('div', {}, [h('p', '使用函数返回正确执行')]) content: h('div', {}, [h('p', '直接调用报错上面提到的警告')]

这个是错的，需要给h绑定vm

**Comment by Dcx199302** [comment]
> > > 用于`setup: () => {}`避免此警告。
> > 
> > 
> > content: () => h('div', {}, [h('p', '使用函数返回正确执行')]) content: h('div', {}, [h('p', '直接调用报错上面提到的警告')]
> 
> 这个是错的，需要给h绑定vm

该如何去做呢，该段代码我并没有（也不需要）在template写任何html代码

**Comment by MinatoHikari** [comment]
> > > > 用于`setup: () => {}`避免此警告。
> > > 
> > > 
> > > content: () => h('div', {}, [h('p', '使用函数返回正确执行')]) content: h('div', {}, [h('p', '直接调用报错上面提到的警告')]
> > 
> > 
> > 这个是错的，需要给h绑定vm
> 
> 该如何去做呢，该段代码我并没有（也不需要）在template写任何html代码

const vm = getCurrentInstance()
const createElement = h.bind(vm)

**Comment by mike1936** [comment]
> > > > > 用于`setup: () => {}`避免此警告。
> > > > 
> > > > 
> > > > content: () => h('div', {}, [h('p', '使用函数返回正确执行')]) content: h('div', {}, [h('p', '直接调用报错上面提到的警告')]
> > > 
> > > 
> > > 这个是错的，需要给h绑定vm
> > 
> > 
> > 该如何去做呢，该段代码我并没有（也不需要）在template写任何html代码
> 
> const vm = getCurrentInstance() const createElement = h.bind(vm)

This works when `createElement` is called in the `setup()`, but I still get the warning when the initialized `const createElement` is called inside a function defined inside `setup()`.
```
// ...
setup() {
  const vm = getCurrentInstance()
  const createElement = h.bind(vm)
  function createMessage(message) {
    createElement('div', message) // warning
    //..
  }
  // ...
}
// ...
```
I have tried to work out this way according to this post of this issue: https://github.com/vuejs/composition-api/issues/804#issuecomment-1100737557
```
// ...
setup() {
  const vm = getCurrentInstance()
  function createMessage(message) {
    const createElement = vm.proxy.$createElement
    createElement('div', message) // no warning
    // ...
  }
  // ...
}
// ...
```
