### ISSUE TITLE
useRoute is not reactive

### ISSUE THREAD

**Issue by willwinberg** [vuejs/composition-api#809]
I've try to mirror vue-router 4 `useRoute` with,
```
function useRoute() {
  const vm = getCurrentInstance()
  if (!vm) throw new Error('must be called in setup')

  return vm.proxy.$route
}
```
but it is not reactive. How can I set this up to have the same behavior has `vue-router` 4?

example use case where the result of `useRoute` is not reactive:

```
...
import { useRoute } from '@/composables/router'

export default defineComponent({
  setup() {
    const route = useRoute()
    const isFlinkCluster = computed(() => {
      return (
        [
          'clusters',
          'cluster',
          'FlinkClusters',
          'CreateFlinkCluster',
          'sql',
          'Sql',
          'SqlCreate'
        ].includes(route.name as string) || route.query.type === 'flink'
      )
    })
...
```

**Comment by antfu** [comment]
Maybe try `return computed(() => vm.proxy.$route)`

**Comment by willwinberg** [comment]
> Maybe try `return computed(() => vm.proxy.$route)`

@antfu That may work, but then I'd have to call `useRoute().value` in my use cases which is not Router 4 syntax. My main goal here is to mirror Vue 3/vue-router 4 syntax while using the composition-api plugin with vue 2. I feel like this shouldn't be that hard of an issue but I'm in so deep now, I gotta figure it out. lol

**Comment by ambit-tsai** [comment]
> > Maybe try `return computed(() => vm.proxy.$route)`
> 
> @antfu That may work, but then I'd have to call `useRoute().value` in my use cases which is not Router 4 syntax. My main goal here is to mirror Vue 3/vue-router 4 syntax while using the composition-api plugin with vue 2. I feel like this shouldn't be that hard of an issue but I'm in so deep now, I gotta figure it out. lol

Here's a package ([vue2-helpers](https://github.com/ambit-tsai/vue2-helpers#vue2-helpers)) to meet your needs.
It has implemented some utils, such as reactive `useRoute()`

**Comment by ambit-tsai** [comment]
> Here's a package ([vue2-helpers](https://github.com/ambit-tsai/vue2-helpers#vue2-helpers)) to meet your needs.
> It has implemented some utils, such as reactive `useRoute()`
```js
import { useRoute, onBeforeRouteLeave } from 'vue2-helpers/vue-router';

const route = useRoute();
```
