### ISSUE TITLE
a ref of an array is marked as readonly

### ISSUE THREAD

**Issue by posva** [vuejs/composition-api#811]
See https://jsfiddle.net/bqct135h/

```js
isReadonly(ref([])) // true
```

But it should be false: [SFC Playground](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgaXNSZWFkb25seSB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgbXNnID0gcmVmKGlzUmVhZG9ubHkocmVmKFtdKSkpXG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8aDE+e3sgbXNnIH19PC9oMT5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge31cbn0ifQ==)

**Comment by webfansplz** [comment]
`readonly()` is provided as API alignment with Vue 3 on type-level only. Use `isReadonly()` on it or it's properties can not be guaranteed.


In `@vue/composition-api`, Use `isReadonly()`  always return true for reactive object , because:
```ts
export function createRef<T>(options: RefOption<T>, readonly = false) {
  const r = new RefImpl<T>(options)
  const sealed = Object.seal(r)
  readonlySet.set(sealed, true) // always trigger
  return sealed
}
```
