### ISSUE TITLE
与vueuse冲突

### ISSUE THREAD

**Issue by kailong321200875** [vuejs/composition-api#816]
"@vue/composition-api": "^1.2.1",
"@vueuse/core": "^6.4.1",

![image](https://user-images.githubusercontent.com/32283845/134450625-d14c4719-9d01-45fd-b519-0bfc202f43fa.png)

当使用了vueuse中的某个方法，如useTitle，就会报如上的错误

**Comment by antfu** [comment]
VueUse use `vue-demi` under the hood, which install the plugin automatically. You can omit the installation statement when using with VueUse.
