### ISSUE TITLE
import from @vue/runtime-core

### ISSUE THREAD

**Issue by 984035589** [vuejs/composition-api#822]
Import the package separately from "vue" and  "@vue/runtime-core"，when 'onMounted'  from @vue/runtime-core，The  code does not execute  'onMounted'，but from "vue" can execute，What is the reason, please answer, thank you

import { onMounted, onUnmounted, reactive } from "vue";

// import { onMounted, onUnmounted, reactive } from "@vue/runtime-core";

export default function useMousePosition() {
  const point = reactive({
    x: 1,
    y: 0,
  });

  const handleMouseDown = (event: MouseEvent) => {
    point.x = event.pageX;
    point.y = event.pageY;
  };

  onMounted(() => {
    document.addEventListener("click", handleMouseDown);
  });

  onUnmounted(() => {
    document.removeEventListener("click", handleMouseDown);
  });

  return point;
}

**Comment by antfu** [comment]
Wrong repo.
