### ISSUE TITLE
Support "functional" components with multiple VNodes

### ISSUE THREAD

**Issue by caugner** [vuejs/composition-api#831]
**Background**: We're still using Vue.js 2.6, because we're depending on bootstrap-vue to support Vue 3, but we're already migrating to composition-api using `@vue/composition-api`.

**Problem**: We have a handful of functional components that return multiple VNodes, but when we convert these to composition-api, the component doesn't render and we get a `[Vue warn]: Multiple root nodes returned from render function. Render function should return a single root node.`. However, we rely on multiple VNodes, because the affected components are part of a CSS Grid layout, so wrapping them in a `<div>` is not an option.

**Example**: [Vue 2 without composition-api (CodeSandbox)](https://codesandbox.io/s/vue-2-render-function-with-multiple-vnodes-eb88f) vs [Vue 2 with composition-api (CodeSandbox)](https://codesandbox.io/s/vue-2-composition-api-render-function-with-multiple-vnodes-92vlg?file=/src/components/HelloWorld.vue)

I suppose the problem is that there is no distinction between functional and regular components when using `setup()` (which cannot be combined with `functional: true`), as apposed to using `render()` with `functional: true` + `render()`. On the other hand, it seems to me that returning a render function in `setup()` is almost equivalent to a functional component, so maybe it could work accordingly?

PS: This has been asked before on the forum, but without any sufficient answer: https://forum.vuejs.org/t/can-i-create-functional-stateless-component-with-the-composition-api/89355

**Comment by DennisChungTW** [comment]
> wrapping them in a `<div>` is not an option

Just providing another solution to CSS grid layout issue, `display: contents`.

It can notify the layout engine to treat this element as Fragments container, which efficiently ignore its layout logic and expose its children directly.

Although there's still some accessibility bug in [current Safari](https://caniuse.com/css-display-contents),
but I think it could solve the mutiple VNode problem in most of the case.
