### ISSUE TITLE
dynamic directive argument is undifined

### ISSUE THREAD

**Issue by beicause** [vuejs/composition-api#838]
I define `eventName`in setup and bind a dynamic directive `@[eventName]`, but it cannot work and an error occurs:  

`vue.runtime.esm.js:619 [Vue warn]: Property or method "eventName" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.`  

Then, I insert a text `{{ eventName }}` into the template, for vue2-script-setup plugin, the dynamic directive works.
However, I try using setup function without script setup, and it still does not work.

**Comment by edwardnyc** [comment]
@beicause could you please provide reproduction?

**Comment by beicause** [comment]
> @beicause could you please provide reproduction?

https://github.com/beicause/vue2-cll-project

**Comment by xiaoxiangmoe** [comment]
@beicause try `"unplugin-vue2-script-setup": "^0.7.3"`

**Comment by xiaoxiangmoe** [comment]
try `"unplugin-vue2-script-setup": "^0.7.3"`
