### ISSUE TITLE
Bug: changing prop causes rerender to lose attributes

### ISSUE THREAD

**Issue by rikbrowning** [vuejs/composition-api#840]
Ok bear with me this is difficult to explain. I put together a repro at https://github.com/rikbrowning/vue-comp-bug. 

Essentially what happens is that when I trigger a prop change on a component it is getting re rendered but it is missing all the computed attributes from the component. The first render is perfect but any subsequent changes seem to cause it to lose those attributes.

In my example if you view the dom inspector so you can see both the Parent and Child div. Then click on the "Child" text and notice that the Parent loses it's computed attributes.

Now if you remove the composition API from the project it works as expected.

**Comment by vansant23** [comment]
I'm running into the same exact issue on my end.  Everything was working fine prior to the release of version 1.3.0 five days ago.  No errors appear to be thrown, but the components now appear to be getting rerendered and losing all attributes in the process.

**Comment by edwardnyc** [comment]
I found the cause of the problem because your variable name is attr, which is the attribute of `ctx` on `Vue-composition-API` @rikbrowning  It exists to keep the API synchronized with vue3

**Comment by rikbrowning** [comment]
Ok, but we use the same variables etc. in our Vue3 version with no issue. Whilst I understand this is good alignment to Vue3 it has introduced a breaking change to users of certain variable names which hasn't been documented.
