### ISSUE TITLE
npm build fail with pinia v2.0.0 and vue2.6.14(@vue/composition-api 1.3.0)

### ISSUE THREAD

**Issue by SD-Gaming** [vuejs/composition-api#841]
Reproduction
run 'npm run build', see error.

Expected behavior
build success

Actual behavior
build fail with error below:
node v16.13.0
npm 8.1.0
![image](https://user-images.githubusercontent.com/25575589/139783848-71bf4847-cbdf-4517-b2b3-818a3692e4c4.png)
![image](https://user-images.githubusercontent.com/25575589/139783860-bbac22ee-f342-4045-94ed-0356a2cbae2f.png)
![image](https://user-images.githubusercontent.com/25575589/139783970-92cae8e0-e200-4760-a2ab-07cb3c01e8df.png)
![image](https://user-images.githubusercontent.com/25575589/139784322-430a847c-aaab-49f4-9b70-31897ce0cb3a.png)

**Comment by edwardnyc** [comment]
Looks like you used a property that vue2 doesn't exist @SD-Gaming

**Comment by SD-Gaming** [comment]
> Looks like you used a property that vue2 doesn't exist @SD-Gaming

Thank reply.
Yes, the direct error is from pinia, but the v1.3.0 is changed to .mjs, so I think maybe somebody would know this problem.

I found the reason is pinia wants to import vue-demi {DebuggerEvent, Plugin}, which should export from @vue/composition-api, but it isn't exported.

![image](https://user-images.githubusercontent.com/25575589/139812260-9034f12a-d59c-42f9-bcbd-5ff3eaea2ae6.png)

![1635843017(1)](https://user-images.githubusercontent.com/25575589/139814992-b4282b27-e0c1-40f1-b1e9-800671e00f21.png)

**Comment by edwardnyc** [comment]
[log](https://github.com/vuejs/composition-api/pull/837) @SD-Gaming

**Comment by SD-Gaming** [comment]
Today I try to build, the error is gone.
Maybe restarting vscode could fix the problem. 😄
Thank everyone.
