### ISSUE TITLE
`toRaw()` doesn't expose Refs like in Vue 3

### ISSUE THREAD

**Issue by posva** [vuejs/composition-api#844]
It seems like `toRaw()` on a reactive object doesn't expose the original properties like it does in Vue 3:

- [Vue 3 example](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgcmVhY3RpdmUsIHRvUmF3LCBpc1JlZiwgaXNSZWFjdGl2ZSB9IGZyb20gJ3Z1ZSdcbiAgXG4gIGNvbnN0IHN0b3JlID0gcmVhY3RpdmUoeyByOiByZWYoMCkgfSlcbiAgXG5cbmNvbnN0IGlzUmVmVmFsID0gaXNSZWYodG9SYXcoc3RvcmUpLnIpXG5jb25zdCBpc1JlYWN0aXZlVmFsID0gaXNSZWFjdGl2ZSh0b1JhdyhzdG9yZSkucilcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPlxuICAgIGlzUmVmOiB7eyBpc1JlZlZhbCB9fVxuICAgIGlzUmVhY3RpdmU6IHt7IGlzUmVhY3RpdmVWYWwgfX1cbiAgPC9wPlxuPC90ZW1wbGF0ZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59In0=): isRef: true isReactive: false
- [Vue 2 example](https://codepen.io/posva/pen/BadJLZX?editors=1010): isRef: false isReactive: false

**Comment by posva** [comment]
I'm unsure of what the correct fix is here since Vue 2 modifies the object in place with methods like `Vue.observable()` (used in reactive and ref) differently from Vue 3, which creates a Proxy (`reactive(obj) != obj`).
We could save a raw copy of the object passed to `reactive()` but it would require a deep copy and could have a small perf implication.

**Comment by posva** [comment]
.

**Comment by Benleie** [comment]
So, how to do with it?

**Comment by imguolao** [comment]
Is there a solution now？
