### ISSUE TITLE
SetupContext expose is deprecated.

### ISSUE THREAD

**Issue by A-Ota** [vuejs/composition-api#849]
I need to use context.expose function because, I declare render function and return it from setup.
And, I also want to declare component method.
https://stackoverflow.com/questions/67861109/how-to-expose-component-methods-in-render-function-in-vue3-with-ts

```
setup (props, context) {
  const someFunction = () => {}
  // @deprecated — not available in Vue 2
  context.expose({
    someFunction()
  })
  return () => h('div', 'Hello world.')
}
```
But, context.expose function is deprecated.
It cause runtime error.(context.expose is not a function)

Is there a way to resolve it?

**Comment by MaybeQHL** [comment]
我也遇到了这个问题

**Comment by MaybeQHL** [comment]
i have same question.

**Comment by chris-zhu** [comment]
i have same question too,  and it's not export `defineExpose` api.

**Comment by antfu** [comment]
It's not possible in Vue 2 to have the ability of `expose`. In Vue 2 all data are exposed to the instance (you can't hide them), while in Vue 3 it has two internal and public instances of each instance to make the exposure possible.
