### ISSUE TITLE
Can't get instance type from component definition

### ISSUE THREAD

**Issue by Djaler** [vuejs/composition-api#850]
I have this utility function for cases when I know for sure that template ref is exists. Also, it provides me correct typing for this ref methods.
```
type VueClass<V extends Vue = Vue> = (new (...args: any[]) => V) & typeof Vue

export function useComponentRef<T extends VueClass>() {
    return ref<InstanceType<T>>(undefined!) as Ref<InstanceType<T>>;
}
```
Usage:
```
const foo = useComponentRef<typeof Foo>();
 
onMounted(() => {
    foo.value.bar(); // method bar strictly typed 
}
 ```

But after update to 1.4.0 this doesn't work.
Now I receive this error:
```
TS2344: Type 'VueProxy<{}, void, Data, {}, {}, {}, {}, {}>' does not satisfy the constraint '(new (...args: any[]) => Vue) & VueConstructor<Vue>'.   Type 'VueProxy<{}, void, Data, {}, {}, {}, {}, {}>' is not assignable to type 'new (...args: any[]) => Vue'.     Construct signature return types 'ComponentRenderProxy<{} & {}, void, Data, {}, {}, {}, {}, {}, {} & {}, {}, true>' and 'Vue' are incompatible.       The types of '$attrs' are incompatible between these types.         Type 'Data' is not assignable to type 'Record<string, string>'.
```
I found that it was broken because of this change: https://github.com/vuejs/composition-api/commit/b980175426a25400a5d0ba9f684eee44901fae65#diff-5d5edc98cf929d645f9b70ae45d64d3a58088caddcc1b99f433b256aa93d4a90R91
If I replace `Omit<VueConstructor, never>` back to `VueConstructor`, my typing works good.

**Comment by MinatoHikari** [comment]
Yea, because of that change, type of VueProxy does not satisfy the constraint VueConstructor, I can't mixins Components defined bt `defineComponent` with `vue-class-component`

**Comment by xiaoxiangmoe** [comment]
@Djaler If we change `Omit<VueConstructor, never>` to `VueConstructor`, volar type check for $emits will fail.

**Comment by xiaoxiangmoe** [comment]
@Djaler If we change `Omit<VueConstructor, never>` to `VueConstructor`, volar type checking for $emits will fail.

**Comment by xiaoxiangmoe** [comment]
You can rewrite it as follows:
```ts
export function useComponentRef<T extends new () => T>() {
    return ref<InstanceType<T> | null>(null) as Ref<InstanceType<T> | null>;
}
```

Don't remove `| null` because the value of ref is null if the component was unmounted.

---

Also, there exist some vue instance not extends VueConstructor, for example —— vue router:

https://github.com/vuejs/vue-router-next/blob/075b066d72f23e5d27fce4c0b38cff6b2d9d21a9/src/RouterLink.ts#L253-L271
https://github.com/vuejs/vue-router-next/blob/075b066d72f23e5d27fce4c0b38cff6b2d9d21a9/src/RouterView.ts#L194-L208

**Comment by xiaoxiangmoe** [comment]
@Djaler @MinatoHikari 

If we change `Omit<VueConstructor, never>` to `VueConstructor`, volar type checking for $emits will fail.

for example:

```ts
import { VueConstructor } from "vue";

declare const Input: {
  new (): {
    $emit: ((event: "foo", value: number) => void) & ((event: "bar", value: string) => void)
  }
} & Omit<VueConstructor, never>

declare const input: InstanceType<typeof Input>
const emit = input['$emit']

// @ts-expect-error value should be string
emit('bar',1)
```

If you change `Omit<VueConstructor, never>` to `VueConstructor`, type check will fail.

**Comment by MinatoHikari** [comment]
> @Djaler @MinatoHikari
> 
> If we change `Omit<VueConstructor, never>` to `VueConstructor`, volar type checking for $emits will fail.
> 
> for example:
> 
> ```ts
> import { VueConstructor } from "vue";
> 
> declare const Input: {
>   new (): {
>     $emit: ((event: "foo", value: number) => void) & ((event: "bar", value: string) => void)
>   }
> } & Omit<VueConstructor, never>
> 
> declare const input: InstanceType<typeof Input>
> const emit = input['$emit']
> 
> // @ts-expect-error value should be string
> emit('bar',1)
> ```
> 
> If you change `Omit<VueConstructor, never>` to `VueConstructor`, type check will fail.

The problem is not `Omit<VueConstructor, never>`.

There are 2 problem types in `VueProxy`.
in `vue-composition-api.d.ts`

```
declare type VueProxy<PropsOptions, RawBindings, Data = DefaultData<Vue$1>, Computed extends ComputedOptions = DefaultComputed, Methods extends MethodOptions = DefaultMethods<Vue$1>, Mixin = {}, Extends = {}, Emits extends EmitsOptions = {}> = ComponentOptions<Vue$1, ShallowUnwrapRef<RawBindings> & Data, Methods, Computed, PropsOptions, ExtractPropTypes<PropsOptions>> & VueConstructorProxy<PropsOptions, RawBindings, Data, Computed, Methods, Mixin, Extends, Emits>;
declare type ComponentPublicInstance<P = {}, // props type extracted from props option
B = {}, // raw bindings returned from setup()
D = {}, // return from data()
C extends ComputedOptions = {}, M extends MethodOptions = {}, E extends EmitsOptions = {}, PublicProps = P, Defaults = {}, MakeDefaultsOptional extends boolean = false> = {
    $: ComponentInternalInstance;
    $data: D;
    $props: MakeDefaultsOptional extends true ? Partial<Defaults> & Omit<P & PublicProps, keyof Defaults> : P & PublicProps;
    $attrs: Data;
    $refs: Data;
    $slots: Slots;
    $root: ComponentPublicInstance | null;
    $parent: ComponentPublicInstance | null;
    $emit: EmitFn<E>;
    $el: any;
    $forceUpdate: () => void;
    $nextTick: typeof nextTick;
    $watch(source: string | Function, cb: Function, options?: WatchOptions): WatchStopHandle;
} & P & ShallowUnwrapRef<B> & UnwrapNestedRefs<D> & ExtractComputedReturns<C> & M;
```
`$emit: EmitFn<E>;` has a `void` return type
`$attrs` has a `Record<string,unknown>`

But type Vue in vue2 has a different type
in `vue.d.ts`
```
export interface Vue {
  readonly $el: Element;
  readonly $options: ComponentOptions<Vue>;
  readonly $parent: Vue;
  readonly $root: Vue;
  readonly $children: Vue[];
  readonly $refs: { [key: string]: Vue | Element | (Vue | Element)[] | undefined };
  readonly $slots: { [key: string]: VNode[] | undefined };
  readonly $scopedSlots: { [key: string]: NormalizedScopedSlot | undefined };
  readonly $isServer: boolean;
  readonly $data: Record<string, any>;
  readonly $props: Record<string, any>;
  readonly $ssrContext: any;
  readonly $vnode: VNode;
  readonly $attrs: Record<string, string>;
  readonly $listeners: Record<string, Function | Function[]>;

 $emit(event: string, ...args: any[]): this;
```
You can see the conflicts.
`$attrs: Record<string, string>`
`$emit(event: string, ...args: any[]): this`

After I changed vue2's `$emit(event: string, ...args: any[]): this` to `$emit(event: string, ...args: any[]): void`
and vca's `$attrs: Data;` to '$attrs:Record<string,string>;'
The type error disappeared.
