### ISSUE TITLE
watch old and new value are the same

### ISSUE THREAD

**Issue by reinoldus** [vuejs/composition-api#851]
Using the "watch" function the old and new value seem to be identical:

Reproduction link: https://codepen.io/reinoldus/pen/QWMJjJW?editors=0011

**Comment by edison1105** [comment]
see https://v3.vuejs.org/guide/reactivity-computed-watchers.html#watching-reactive-objects

**Comment by reinoldus** [comment]
@edison1105 Thank you! Didn't find it
