### ISSUE TITLE
Update to 1.4.0 produces typescript error

### ISSUE THREAD

**Issue by fluffynuts** [vuejs/composition-api#852]
I've seen this popping up at our CI server as of today, when our builds have brought in 1.4.0:

node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(140,20): error TS1110: Type expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(140,46): error TS1005: '(' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(142,21): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(142,24): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(142,43): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(142,51): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(142,53): error TS1109: Expression expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(142,70): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(142,73): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(142,80): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(234,23): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(244,9): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(276,9): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(277,45): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(278,12): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(278,35): error TS1005: ',' expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(278,39): error TS1146: Declaration expected.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(278,40): error TS1161: Unterminated regular expression literal.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(279,8): error TS1161: Unterminated regular expression literal.
node_modules/@vue/composition-api/dist/vue-composition-api.d.ts(281,1): error TS1128: Declaration or statement expected.

My solution has been to pin the package to 1.3.3, but I wanted to bring it to the attention of the maintainers of this project.

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by fluffynuts** [comment]
Hi

Apologies, but this is in a company project, so I'm unable to, however, here's our full package dependencies:

```
    "dependencies": {
        "@codeo/vue-burger-menu": "^2.1.0",
        "@mapbox/mapbox-gl-geocoder": "^4.7.0",
        "@mapbox/mapbox-sdk": "^0.11.0",
        "@vue/composition-api": "^1.0.0-rc.11",
        "@vuelidate/core": "^2.0.0-alpha.19",
        "@vuelidate/validators": "^2.0.0-alpha.16",
        "axios": "^0.18.0",
        "dotenv": "^6.1.0",
        "fast-safe-stringify": "^2.0.7",
        "google-maps": "^3.3.0",
        "inobounce": "^0.1.6",
        "js-cookie": "^2.2.0",
        "lodash": "^4.17.15",
        "luxon": "^1.27.0",
        "mapbox-gl": "^1.12.0",
        "md5": "^2.2.1",
        "mitt": "^2.1.0",
        "pure-uuid": "^1.6.2",
        "register-service-worker": "^1.6.2",
        "shave": "^2.5.2",
        "smart-app-banner": "^2.0.0",
        "socket.io-client": "^4.0.0",
        "swiper": "^4.4.2",
        "urijs": "^1.19.1",
        "v-autocomplete": "git+https://github.com/jondrummond-codeo/v-autocomplete.git",
        "vue": "2.6.12",
        "vue-class-component": "^6.2.0",
        "vue-currency-filter": "3.2.0",
        "vue-i18n": "^8.24.4",
        "vue-mixin-decorator": "^1.0.0",
        "vue-property-decorator": "^7.2.0",
        "vue-router": "3.0.7",
        "vuex": "^3.0.1",
        "vuex-class": "^0.3.1",
        "vuex-persist": "^2.0.0"
    },
    "devDependencies": {
        "@babel/polyfill": "^7.2.5",
        "@google/maps": "^0.5.5",
        "@types/datejs": "0.0.31",
        "@types/faker": "^4.1.4",
        "@types/geojson": "^7946.0.7",
        "@types/glob": "^7.1.1",
        "@types/googlemaps": "^3.43.3",
        "@types/grecaptcha": "^3.0.1",
        "@types/jest": "^23.1.4",
        "@types/js-cookie": "^2.2.0",
        "@types/js-levenshtein": "^1.1.0",
        "@types/lodash": "^4.14.136",
        "@types/luxon": "^1.26.5",
        "@types/mapbox-gl": "^1.11.2",
        "@types/node": "^10.12.0",
        "@types/semver": "^7.3.4",
        "@types/socket.io": "^2.1.0",
        "@types/swiper": "^4.4.1",
        "@types/urijs": "^1.15.38",
        "@types/vue-i18n": "^7.0.0",
        "@types/vuelidate": "^0.7.14",
        "@types/webpack-env": "^1.13.6",
        "@types/which": "^1.3.1",
        "@types/yargs": "^15.0.9",
        "@types/zenscroll": "^4.0.0",
        "@vue/cli-plugin-babel": "^3.0.0",
        "@vue/cli-plugin-pwa": "^3.0.0",
        "@vue/cli-plugin-typescript": "^3.0.0",
        "@vue/cli-plugin-unit-jest": "^3.0.0",
        "@vue/cli-service": "^3.0.0",
        "@vue/test-utils": "^1.0.0-beta.20",
        "babel-cli": "^6.26.0",
        "babel-core": "^6.26.3",
        "babel-preset-es2015-ie": "^6.7.0",
        "babel-preset-stage-0": "^6.24.1",
        "better-opn": "^3.0.0",
        "chalk": "^2.4.2",
        "copy-webpack-plugin": "^5.0.0",
        "cross-env": "^5.2.0",
        "datejs": "^1.0.0-rc3",
        "debug": "^4.1.1",
        "esbuild-loader": "^2.10.0",
        "exec-step": "^0.3.0",
        "expect-more-jest": "^2.3.0",
        "faker": "^4.1.0",
        "glob": "^7.1.3",
        "graceful-fs": "https://github.com/mekwall/node-graceful-fs.git#patch-1",
        "html-webpack-externals-plugin": "^3.8.0",
        "install-changed": "^1.0.7",
        "jest": "26.6.0",
        "jest-junit": "^5.2.0",
        "mkdirp": "^0.5.1",
        "mutation-observer": "^1.0.3",
        "node-notifier": "^5.3.0",
        "node-sass": "^4.9.3",
        "nodemon": "^1.18.4",
        "npm-run-all": "^4.1.3",
        "pem": "^1.14.4",
        "polyfill-crypto.getrandomvalues": "^1.0.0",
        "pre": "^0.1.3",
        "promise-parallel-throttle": "^3.3.0",
        "promisify": "0.0.3",
        "rimraf": "^2.6.3",
        "sass-loader": "^7.1.0",
        "semver": "^7.3.2",
        "serve": "^10.1.1",
        "ts-jest": "26.4.1",
        "ts-node": "^8.0.2",
        "typescript": "^3.9.7",
        "vue-cli-plugin-webpack-bundle-analyzer": "^4.0.0",
        "vue-segment-analytics": "^0.3.1",
        "vue-template-compiler": "2.6.12",
        "wait-port": "^0.2.9",
        "webpack-bundle-analyzer": "^4.4.0",
        "webpack-cdn-plugin": "^3.3.1",
        "which": "^1.3.1",
        "yafs": "^1.14.0",
        "yargs": "^16.1.0",
        "zenscroll": "^4.0.2"
    },
```
so I hope that helps? Perhaps seeding a minimal project with those deps would give the same error?

**Comment by Zclhlmgqzc** [comment]
use typescript-4.x

**Comment by fluffynuts** [comment]
we can't because of other legacy stuff - can't you emit types for < 4?

**Comment by xiaoxiangmoe** [comment]
@fluffynuts
We need use template literal types for `$emit` support.
See https://github.com/vuejs/composition-api/pull/846/files#diff-5d5edc98cf929d645f9b70ae45d64d3a58088caddcc1b99f433b256aa93d4a90R30

**Comment by mikana0918** [comment]
I couldn't upload an exact reproduction for this case, but it does happen on my code too.
For me removing  `^` did a job.  But it does not do any jobs for compiling with v1.4.0 though...

```json
"@vue/composition-api": "^1.3.3"
"@vue/composition-api": "1.3.3"
```

if you do not need to use 1.4x, above could be an option?

**Comment by antfu** [comment]
The document is already clear that this package requires TS >= 4.2. Please consider ungrading.

https://github.com/vuejs/composition-api#typescript-support
