### ISSUE TITLE
ref<T>() returns T instead of Ref<T>

### ISSUE THREAD

**Issue by Akryum** [vuejs/composition-api#857]
Since version 1.4.0

```ts
const foo = ref<MyObj>({ ... })
```

1.4.0 result:

```ts
MyObj
 ```

1.3.3 result:

```ts
Ref<MyObj>
```

**Comment by Akryum** [comment]
This is causing the vue-devtools frontend to fail building ([commit](https://github.com/vuejs/devtools/commit/69a15056d05413a9e0fac8cdccd3bc148d265f88) [yarn.lock](https://github.com/vuejs/devtools/blob/69a15056d05413a9e0fac8cdccd3bc148d265f88/yarn.lock#L1923))

**Comment by antfu** [comment]
Can't reproduce that
![image](https://user-images.githubusercontent.com/11247099/143293846-3797aae8-adcd-4533-8007-f84c3d5b3f78.png)

**Comment by Akryum** [comment]
Here is a branch where there is the issue (diff with `main` is upgrading to 1.4.0): https://github.com/vuejs/devtools/tree/issue-composition-api-types
![image](https://user-images.githubusercontent.com/2798204/143442244-fa89ba7b-8925-449a-878e-0f383b731449.png)

**Comment by Akryum** [comment]
![image](https://user-images.githubusercontent.com/2798204/143442545-a37f14e1-7c52-4ec6-9f19-188f3e26fba8.png)

**Comment by Zclhlmgqzc** [comment]
> Here is a branch where there is the issue (diff with `main` is upgrading to 1.4.0): https://github.com/vuejs/devtools/tree/issue-composition-api-types
> 
> https://github.com/vuejs/vue-devtools/blob/627ee47dc90614cf112de78a0fee655346409162/packages/app-frontend/src/features/components/composable/components.ts#L18
> 
> ![image](https://user-images.githubusercontent.com/2798204/143442244-fa89ba7b-8925-449a-878e-0f383b731449.png)
> 
yarn.lock
'''
typescript@^3.8.3: 
version "3.9.10"
'''

**Comment by Akryum** [comment]
Did the requirement on typescript change?

**Comment by xiaoxiangmoe** [comment]
@Akryum Yes.

TypeScript version >4.2 is required.

**Comment by Akryum** [comment]
Or maybe mention it in the release notes?

**Comment by antfu** [comment]
I think we did?
![image](https://user-images.githubusercontent.com/11247099/143604390-cc4d5175-4e82-4ab2-b23b-0f74b0741446.png)

**Comment by Akryum** [comment]
Oh ok it was on the readme, I did 't see it. Was browsing the release notes to see when it changed.
