### ISSUE TITLE
Using custom v-model for component

### ISSUE THREAD

**Issue by marciado** [vuejs/composition-api#858]
The v-model has breaking changes in [Vue 3](https://v3.vuejs.org/guide/migration/v-model.html#v-model).  So we have to use:
 `:modelValue` & `@update:modelValue="customHandler"`

 instead of :`value` & `@input="customHandler"`.

Therefore it is not possible to only use `v-model` at the parent component, so you have to use it like above right? 
And vue 3 support  of v-model naming (like `v-model:name="customModelValue"`) is also not possible?

Has this plugin a solution for custom v-models inside of the composition api?

**Comment by antfu** [comment]
Sorry this is not possible and out-of-scope of this project.

**Comment by naquiroz** [comment]
Do you know if this is implemented in vue 2.7?
