### ISSUE TITLE
Error  use composition-api within vue2.x☹😭

### ISSUE THREAD

**Issue by SJanJan** [vuejs/composition-api#86]
# Project by CLL3😢😣
## In main.js:
```js
import VueCompositionApi from '@vue/composition-api';
Vue.use(VueCompositionApi);
```

## In App.vue:
```html
<template>
  <button @click="increment">
    Count is: {{ state.count }}, double is: {{ state.double }}
  </button>
</template>

<script>
import { reactive, computed } from 'vue'

export default {
  setup () {
    const state = reactive({
      count: 0,
      double: computed(() => state.count * 2)
    })

    function increment () {
      state.count++
    }

    return {
      state,
      increment
    }
  }
}
</script>
```

# But console output error,codes is not work! I'm very sad!  help me?

_vue.runtime.esm.js?2b0e:619 [Vue warn]: Error in data(): "TypeError: Object(...) is not a function"

**Comment by liximomo** [comment]
Can you provide an online example?

**Comment by SJanJan** [comment]
> Can you provide an online example?

https://github.com/SJanJan/compositionTest

**Comment by liximomo** [comment]
The composition API is exported from `@vue/composition-api`, not `vue`.

```js
import { reactive, computed } from '@vue/composition-api'
```

**Comment by SJanJan** [comment]
> The composition API is exported from `@vue/composition-api`, not `vue`.
> 
> ```js
> import { reactive, computed } from '@vue/composition-api'
> ```

my god ! thanks🥰😘

**Comment by xieyezi** [comment]
vue 3 have not publish,so must write like this: import { reactive, computed } from '@vue/composition-api'

**Comment by hitautodestruct** [comment]
I think the source of confusion may be in the docs for example in the [RFC](https://vue-composition-api-rfc.netlify.app/#basic-example) the import is taken from vue
```
import { reactive, computed } from 'vue'
```

The correct way using the plugin is as mentioned:
```
import { reactive, computed } from '@vue/composition-api'
```
