### ISSUE TITLE
How do I extend like this.$store in component?

### ISSUE THREAD

**Issue by kmq116** [vuejs/composition-api#860]
I want to use like  this.$store or this.$myCustom in .vue file ，but this occurs an Error with Vetur. 
`
Property '$store' does not exist on type 'ComponentRenderProxy<unknown, { PAGE_TYPE: { CREATE: number; EXIST: number; SEARCH: number; }; }, { PAGE: number; exist: boolean; inputText: string; searchText: string; JDWD: any; existList: any[]; }, { headHeight(): "12.1%" | "7.4%"; mapCenterData(): any; }, { ...; }, unknown, {}, false>'.Vetur(2339)`

I tried to use this method [vue3 doc](https://v3.cn.vuejs.org/guide/typescript-support.html#%E4%B8%BA-globalproperties-%E6%89%A9%E5%85%85%E7%B1%BB%E5%9E%8B)  , but it didn't work. 🙄🙄🤞

**Comment by kmq116** [comment]
The solution is to execute `npm install vuex --save`

**Comment by zach-at-healthpilot** [comment]
If  you're trying to do it in a setup function, I've had to do the following (although you get a note that it's deprecated syntax): 

```ts
import {computed} from 'vue-composition-api'

// ... defineComponent or whatever you use ... 

    setup(props, context) {
      const store = context.root.$store
      const storeThing = computed( () => store.get('storeModule/thing') )

    // more setup code ...
   }
```

**Comment by flrnt** [comment]
I think you loose reactivity, getters seems not to be sync
