### ISSUE TITLE
`watch` and `watchEffect` don't avoid unnecessary duplicate invocation as it does in Vue3

### ISSUE THREAD

**Issue by leafstark** [vuejs/composition-api#867]
Here is an example:

[Vue2](https://codepen.io/leafstark/pen/RwLPEPQ?editors=1011)
[Vue3](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiwgd2F0Y2hFZmZlY3QsIGNvbXB1dGVkLCB3YXRjaCB9IGZyb20gJ3Z1ZSdcbiAgXG5jb25zdCBudW0gPSByZWYoMClcbmNvbnN0IGZhdGhlciA9IHJlZignb25lJylcbmNvbnN0IGZpcnN0TmFtZSA9IHJlZignTWljaGFlbCcpXG5jb25zdCBsYXN0TmFtZSA9IHJlZignSmFja3NvbicpXG5jb25zdCBuYW1lID0gY29tcHV0ZWQoKCkgPT4gZmlyc3ROYW1lLnZhbHVlICsgJyAnICsgbGFzdE5hbWUudmFsdWUpXG5cbmNvbnN0IGNoYW5nZUZhdGhlciA9ICgpID0+IHsgZmF0aGVyLnZhbHVlID0gZmF0aGVyLnZhbHVlID09PSAnb25lJz8gJ3R3bycgOiAnb25lJ31cblxud2F0Y2hFZmZlY3QoKCk9PntcbiAgaWYoZmF0aGVyLnZhbHVlID09PSAnb25lJyl7XG4gICAgbGFzdE5hbWUudmFsdWUgPSAnSm9yZGFuJ1xuICB9ZWxzZXtcbiAgICBsYXN0TmFtZS52YWx1ZSA9ICdKYWNrc29uJ1xuICB9XG59KVxud2F0Y2goW2ZhdGhlcixuYW1lXSwoKT0+e1xuICBudW0udmFsdWUgKz0gMVxufSlcbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDxwPlxuICAgIG51bToge3sgbnVtIH19XG4gIDwvcD5cbiAgICA8cD5cbiAgICBmYXRoZXI6IHt7IGZhdGhlciB9fVxuICA8L3A+XG4gICAgPHA+XG4gICAgbmFtZToge3sgbmFtZSB9fVxuICA8L3A+XG4gIDxidXR0b24gQGNsaWNrPVwiY2hhbmdlRmF0aGVyXCI+XG4gICAgY2hhbmdlIGZhdGhlclxuICA8L2J1dHRvbj5cbjwvdGVtcGxhdGU+IiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSJ9)

Normally, every time you click the button, the number should increase by 1, but it increases by 2 when using `@vue/composition-api` in Vue2.

**Comment by MinatoHikari** [comment]
It needs a dependence collection like vue3.
