### ISSUE TITLE
Can i usage composition-api in my production project?

### ISSUE THREAD

**Issue by SJanJan** [vuejs/composition-api#87]
Is it stable enough? I'm worry about still has bugs

**Comment by posva** [comment]
Yes, you can use it. The only thing you have to take into account is that it's following an RFC (it's in the Readme) and things may change. Also, there are some limitations compared to Vue 3

**Comment by ux-engineer** [comment]
When I was in VueConf Toronto, heard speakers saying "don't use it in production" in regards to Composition API. Why is that?
