### ISSUE TITLE
Unable to use reactive outside of setup

### ISSUE THREAD

**Issue by shadskii** [vuejs/composition-api#872]
Calling `reactive` outside of a component's setup function or composable results in the following error message:

```
Uncaught Error: [vue-composition-api] must call Vue.use(VueCompositionAPI) before using any function.
```
see [replit](https://replit.com/@shadskii/vue-composition-api-reactive)
<details>
<summary>Example Code</summary>

```vue
<template>
  <div>
    {{store}}
  </div>
</template>

<script>
import {defineComponent,reactive} from '@vue/composition-api';

const store = reactive({a: '1'});

export default defineComponent({
  setup(){
    return{
      store
    }
  }
})
</script>

```
</details>

### Expected behavior

`reactive` should not throw an error and should behave as `Vue.observable` when used outside of `setup` or a composable and return a reactive object.

Creating reactive object stores outside of components in Vue 3 using `reactive` is a legitimate pattern  ([see](https://dev.to/vuesomedev/you-might-not-need-vuex-with-vue-3-52e4)) and supporting it in the `@vue/composition-api` will help ease the upgrade to Vue 3. 

If this is not possible to implement, this limitation should be documented in the readme.

**Comment by posva** [comment]
The error is pretty self explanatory: you are not calling `Vue.use(VueCompositionAPI)` before calling `reactive()`. You have to ensure it's called in the right order. E.g:

```js
// a.js
export default reactive({})
```

```js
// plugins
Vue.use(VueCompositionAPI)
```

```js
// main.js
import state from './a.js'
import './plugins' // too late!
```

Instead, do


```js
// main.js
import './plugins'
import state from './a.js'
```

---

Remember to use the [forum](http://forum.vuejs.org/) or the [Discord chat](https://vue-land.js.org/) to ask questions!

**Comment by shadskii** [comment]
@posva thanks for the solution. Importing my plugins as a side effect _before_ my main component did the trick. A very frustrating and nuanced error. Hopefully this issue can serve to help anyone with a similar problem in the future. 

Thanks for the help!
