### ISSUE TITLE
[BUG] setup doesn't support return object with type of Module 

### ISSUE THREAD

**Issue by xialvjun** [vuejs/composition-api#874]
The bug( or maybe not bug) code is at https://github.com/vuejs/composition-api/blob/a43090d098b37388798d6db12cc2292177828b49/src/mixin.ts#L118

Sorry I can not offer an codesandbox or stackblitz link, because this bug is related to the building enviroment.

My local build enviroment is: vite + vite-plugin-vue2;

The build script is just `"build": "vite build",` without `tsc &&` because esbuild support typescript.

Then with code:

App.vue
```vue
<template><div @click="a++">{{a}}</div></template>
<script lang="ts">
import { defineComponent } from "@vue/composition-api"
import * as refs from "./refs"; // refs is just a ts file with some global ref state.

export default defineComponent({
  setup() {
    return { ...refs }; // refs is of type "[object Module]", and `{ ...refs }` is also of type "[object Module]", so isPlainObject return false.
    // I need to convert it to
    const spread = obj => Object.keys(obj).reduce((acc, cv) => ({...acc, [cv]: obj[cv]}), {});
    return { ...(spread(refs)) }; // then it works.
  }
});
</script>
```

refs.ts
```ts
import {} from '@vue/composition-api';
export const a = ref(0);
export const b = ref('');
```

**Comment by MinatoHikari** [comment]
You should not directly export const something = ref()
```

export const useRef = () => {
    const a = ref()

    return { a }
}
```

**Comment by LinusBorg** [comment]
@MinatoHikari exporting a ref like OP does is totally fine.

**Comment by xialvjun** [comment]
I don't have a need to SSR, so I just export a global ref.

**Comment by xialvjun** [comment]
I think changing `isPlainObject` to `val => val !== null && typeof val === 'object'` is enough, because vue3 is just like this https://github.com/vuejs/vue-next/blob/87c86e4cc2/packages/runtime-core/src/component.ts#L688
