### ISSUE TITLE
tsx emit无法正常运行

### ISSUE THREAD

**Issue by 0scarecrow0** [vuejs/composition-api#880]
![image](https://user-images.githubusercontent.com/45458124/148187035-a5a83b40-ef19-4914-828c-93ead82bdac0.png)
![image](https://user-images.githubusercontent.com/45458124/148187118-6ac85560-5b0e-4c85-9b66-1f763ba562c2.png)
![image](https://user-images.githubusercontent.com/45458124/148187171-327670a3-6ed7-436c-bfa0-81db72d7c12c.png)
![image](https://user-images.githubusercontent.com/45458124/148187251-d49369dc-338a-4174-b3d7-08607ea01bd8.png)
![image](https://user-images.githubusercontent.com/45458124/148187445-40f45842-7657-4242-ba13-31827d1b905d.png)

事件可以正常触发，但是ts报错

**Comment by 0scarecrow0** [comment]
![image](https://user-images.githubusercontent.com/45458124/148187839-e19e3b25-71e1-474f-8637-aad5bbcfb067.png)

**Comment by MinatoHikari** [comment]
onEmitChange
