### ISSUE TITLE
why I use composition-api tsx in child compent parent when i use ref can't get children componet methods?

### ISSUE THREAD

**Issue by jetBn** [vuejs/composition-api#883]
why I use composition-api tsx in child compent parent when i use ref can't get children componet methods?

**Comment by jetBn** [comment]
parent component is use vue2.x option api

**Comment by jetBn** [comment]
when i child componet write template not use tsx return method parent can get .

**Comment by LinusBorg** [comment]
you need to `expose()` them.

https://v3.vuejs.org/guide/composition-api-setup.html#usage-with-render-functions

**Comment by xiaoxiangmoe** [comment]
It seems that  `expose()` is not available in Vue 2.

**Comment by LinusBorg** [comment]
Yes.

**Comment by jetBn** [comment]
> you need to `expose()` them.
> 
> https://v3.vuejs.org/guide/composition-api-setup.html#usage-with-render-functions

i expose() them, is not get also. in Vue2

**Comment by Jinwan5290** [comment]
> > you need to `expose()` them.
> > https://v3.vuejs.org/guide/composition-api-setup.html#usage-with-render-functions
> 
> i expose() them, is not get also. in Vue2

so How did you solve it in the end
