### ISSUE TITLE
Type of unref is incorrect

### ISSUE THREAD

**Issue by stellR42** [vuejs/composition-api#887]
This was fixed in Vue 3, but seems to not have been updated in this package.
The type should be `<T>(ref: T | Ref<T>): T` but is currently `<T>(ref: T): T extends Ref<infer V> ? V : T`
See https://github.com/vuejs/vue-next/issues/3954.

In general, how up to date is this package with the Vue 3 repository? If an issue has been fixed there, can I reasonably expect it to have been fixed here as well, or is that not the case?

**Comment by MinatoHikari** [comment]
That issue is created by me, wait a minute and let me fix the type of unref and https://github.com/vuejs/composition-api/issues/882.
