### ISSUE TITLE
Is using .value required in the template when using ref(...)?

### ISSUE THREAD

**Issue by ShetlandJ** [vuejs/composition-api#89]
I'm experimenting with the new API, and I've just switched all my previous `= value("foo")` to `= ref('bar')` and I have to unwrap refs in the template suddenly. 

##Code example

My input text field:
```
            <v-text-field
                clearable
                v-model="newPet"
                id="newPet"
                name="newPet"
                label="Adopt a new pet!"
                @keyup.enter="addPet"
            />
```

In my `<script>` export:

`let newPet = ref("");`

I use the newPet in the above text-field component, and it returns as an object with .value property:

![image](https://user-images.githubusercontent.com/29278616/63685622-bdff8580-c7f7-11e9-9efe-84df935b0de5.png)

I note also that this seems to be the case for computed properties too. An example:

```
 const praisedPetString = computed(() => {
            if (!chosenPet.value) {
                return "Select a pet!";
            }

            return `${chosenPet.value} is amazing!`;
        });

```

and

`<v-list-item>{{praisedPetString}}</v-list-item>`

Outputs this:

![image](https://user-images.githubusercontent.com/29278616/63686003-b5f41580-c7f8-11e9-8678-6c696e5d5131.png)

In my text-field component, if I change my v-model to newPet.value, it works. Is this expected behaviour?

**Comment by LinusBorg** [comment]
Doesn't happen for me. Can you provide a reproduction?

**Comment by ShetlandJ** [comment]
Hi Linus, if I generate a new Vue project (cli.3) and try it works fine, so it leads me to believe it's something in my existing project that's stopping it from working.

This is the file in question:

```
<template>
    <v-card>
        <v-flex xs12 class="add-pet">
            <v-text-field
                clearable
                v-model="newPet"
                id="newPet"
                name="newPet"
                label="Adopt a new pet!"
                @keyup.enter="addPet"
            />
        </v-flex>

        <v-list-item>
            <h2>{{petList.numberOfPetsString}}</h2>
        </v-list-item>
        <v-list-item v-for="(pet, index) in petList.pets" :key="index">
            <v-btn @click="setChosenPet(pet)">{{pet}}</v-btn>
        </v-list-item>
        <v-list-item>{{praisedPetString}}</v-list-item>
    </v-card>
</template>

<script>
import { computed, ref, reactive } from "@vue/composition-api";

export default {
    setup() {
        // Pet list
        const petList = reactive({
            pets: ["Bark Twain", "Chairman Meow", "Christopher Squawken"],
            numberOfPets: computed(() => petList.pets.length),
            numberOfPetsString: computed(() => `${petList.numberOfPets} pets.`)
        })

        // Pet addition
        let newPet = ref("");
        const addPet = () => {
            petList.pets = [...petList.pets, newPet.value];
            newPet.value = "";
        };

        // Pet actions
        let chosenPet = ref("");

        const setChosenPet = pet => {
            chosenPet.value = pet;
        };

        const praisedPetString = computed(() => {
            if (!chosenPet.value) {
                return "Select a pet!";
            }

            return `${chosenPet.value} is amazing!`;
        });

        return {
            addPet,
            newPet,
            petList,
            praisedPetString,
            setChosenPet
        };
    }
};
</script>
<style scoped>
.done {
    text-decoration: line-through;
}

.add-pet {
    margin: 5px;
}
</style>
```

In my main.js file, I just add it to Vue before any other plugins (Vuex, Vuetify etc), like so:

```
import VueCompositionApi from '@vue/composition-api';

Vue.use(VueCompositionApi);
```

**Comment by LinusBorg** [comment]
just to be sure I'd try and clear the cache in `node_modules/.cache`

**Comment by ShetlandJ** [comment]
I've removed node_modules and re-installed it but unfortunately the problem persists

**Comment by ShetlandJ** [comment]
The branch in question. The "PETLIST" tab is where the problem exists

https://github.com/ShetlandJ/Vue3Todo/tree/upgrade-to-composition-api

**Comment by LinusBorg** [comment]
You have both the old and new version of this plugin installed in main.js

**Comment by ShetlandJ** [comment]
Thanks Linus, I noticed that just at the same time that you did! 

cheers
