### ISSUE TITLE
Type definition of props is too strict and generate errors when we apply valid HTML attributes or vue reserved keywords to a custom component

### ISSUE THREAD

**Issue by Eygle** [vuejs/composition-api#891]
## Version
[v1.4.4](https://github.com/vuejs/composition-api/releases/tag/v1.4.4)

## Bug description

In the following code, the `key` is consider by the composition-api type as a props and must be declared inside the component `TodoItem`. Same for the `class` attribute

```vue
<template>
  <div>
    <TodoItem v-for="(item, i) in list" :key="`item-${i}`" :item="item" class="foobar" />
  </div>
</template>
```

If we don't we have this error when running `vue-tsc --noemit` :
```
Type '{ key: string; item: TodoItem; }' is not assignable to type 'Readonly<Partial<{ item: any; }> & Omit<{ item: any; } & {}, "item">>'.
  Property 'key' does not exist on type 'Readonly<Partial<{ item: any; }> & Omit<{ item: any; } & {}, "item">>'.
```

Here is `TodoItem` definition :

```vue
<script lang="ts">
import { defineComponent } from '@vue/composition-api'

export default defineComponent({
  props: [
    'item',
    // 'key', // TODO: Un comment to fix typescript error
    // 'class', // TODO: Un comment to fix typescript error
  ],
})
</script>
```

The problem is also present with valid HTML attributes such as `id`, etc.

## What was expected
We should be able to apply any HTML attributes we want to a custom component defined using `defineComponent` function and only the one declared as props should be consider as it is.

## Probable cause

I think I isolated the problem here in the generated `node_modules/@vue/composition-api/dist/vue-composition-api.d.ts` at line 146 :
``` typescript
declare type ComponentRenderProxy<P = {}, // props type extracted from props option
B = {}, // raw bindings returned from setup()
D = {}, // return from data()
C extends ComputedOptions = {}, M extends MethodOptions = {}, Mixin = {}, Extends = {}, Emits extends EmitsOptions = {}, PublicProps = P, Defaults = {}, MakeDefaultsOptional extends boolean = false> = {
    $data: D;
    $props: Readonly<MakeDefaultsOptional extends true ? Partial<Defaults> & Omit<P & PublicProps, keyof Defaults> : P & PublicProps>;
    $attrs: Record<string, string>;
    $emit: ComponentRenderEmitFn<Emits, keyof Emits, ComponentRenderProxy<P, B, D, C, M, Mixin, Extends, Emits, PublicProps, Defaults, MakeDefaultsOptional>>;
} & Readonly<P> & ShallowUnwrapRef<B> & D & M & ExtractComputedReturns<C> & Omit<Vue$1, '$data' | '$props' | '$attrs' | '$emit'>;
```

If you replace the definition of `$props` by that following code the problem disapear (of course this is not the solution as we would loose the definition) :
```typescript
    $props: any;
```

**Comment by Eygle** [comment]
I found a workaround if anyone is blocked like me : in the `tsconfig.json`, adding the rule `"skipLibCheck": true,` works (for obvious reason)

**Comment by imguolao** [comment]
please reopen this issue, the problem still exists. @antfu

**Comment by Eygle** [comment]
> please reopen this issue, the problem still exists in v1.4.9. @antfu

I can't (maybe someone should repost it).
Personnally I used a boilerplate I found and finally I didn't have the problem anymore (no idea why though)

**Comment by dyf19118** [comment]
any progress？still have problem in version 1.7.0

**Comment by harmony-netizen** [comment]
I can confirm that this is an issue starting from version 1.4 onwards up to the latest 1.7.1.
Version 1.3 is the last version that doesn't have this issue.

Recently encountered this in my vue 2 project.

Please fix this in the later versions. For now my only solution is to downgrade to version 1.3.
