### ISSUE TITLE
Bug: Undefined variable defined in `setup` will be reactive

### ISSUE THREAD

**Issue by thomasaull** [vuejs/composition-api#892]
I want to define a variable to be used in the component, which should not be reactive. A way to do this would be to:

```js
setup() {
  return {
    myVariable: undefined,
  };
},
```
and use it later like:
```js
mounted() {
  this.myVariable = new MyThingWhichShouldNotBeReactive()
}
```
However, doing it like this with the `composition-api-plugin` will make `myVariable` reactive. The same pattern used with vue3 will not.

###  vue2 with `composition-api-plugin`: 
Codesandbox: https://codesandbox.io/s/silent-monad-v4khh?file=/src/components/HelloWorld.vue

Logging the test variable reveals the reactive getter/setter added by vue:
![image](https://user-images.githubusercontent.com/227756/150572483-2455c2a2-6b35-4176-a951-19971817b654.png)

### vue3
Codesandbox: https://codesandbox.io/s/fervent-poincare-quiqw?file=/src/components/HelloWorld.vue

Logging the test variable, no reactivity whatsoever:
![image](https://user-images.githubusercontent.com/227756/150572719-5dc5d25d-7a7d-453a-8a58-3ab67db5982f.png)

## Workaround

Defining the variables as an empty object or array seems to prevents them from becoming reactive:

```js
setup() {
  return {
    myVariable: {},
  };
}
```

**Comment by alexrafael10** [comment]
Looks like they are making anything that is not reactive, object or function reactive

![image](https://user-images.githubusercontent.com/21692735/151246856-da0f4bab-3516-4aab-9abd-573fc43137d7.png)

I wonder why :D

**Comment by thomasaull** [comment]
Thanks for investigating @alexrafael10 yeah seems a bit weird especially when vue3 does not show the same behaviour
