### ISSUE TITLE
Type error of ref()

### ISSUE THREAD

**Issue by wjw99830** [vuejs/composition-api#90]
```typescript
const loading = value(false);
```
Typeof loading is `Ref<{}>`, but when i try this in src file of composition-api, it works fine (`Ref<boolean>`).
If change definition of ref() to
```typescript
function ref<T = unknown, R = RefValue<T>>(
  raw: T
): Ref<R>;
```
It will be solved and still work fine for `{ a: Ref<number> }`.

**Comment by drafu** [comment]
<img width="236" alt="image" src="https://user-images.githubusercontent.com/8282894/63747044-dc748800-c8ae-11e9-8530-eba673ccbde9.png">
Having the same issue

**Comment by drafu** [comment]
Successfully reproduced it in single-file component (.vue file) in `<script lang="ts">` section in clean project. Works fine in .ts files.


Works fine: (.ts)
```ts
import Vue, {CreateElement} from 'vue';
import {createComponent, ref} from '@vue/composition-api';

export default createComponent({
  setup() {
    const test = ref(true); // Ref<boolean>
  },
  render: (h: CreateElement) => h('div')
});
```

Type error: (.vue)
```vue
<script lang="ts">
  import Vue, {CreateElement} from 'vue';
  import {createComponent, ref} from '@vue/composition-api';

  export default createComponent({
    setup() {
      const test = ref(true); // Ref<{}>
    },
    render: (h: CreateElement) => h('div')
  });
</script>
```

**Comment by liximomo** [comment]
It about the version of TypeScript you are using. Make sure to check `useWorkspaceDependencies`
in `vetur`.

![image](https://user-images.githubusercontent.com/9816225/63820737-f5e40580-c97c-11e9-8600-a329b07ebb76.png)
