### ISSUE TITLE
`provide` with symbol not work

### ISSUE THREAD

**Issue by yaquawa** [vuejs/composition-api#900]
I can't `provide()` value with symbol, is this intended?

it gives such an error:
`[Vue warn]: injection "undefined" not found.`

reproduce:
https://codesandbox.io/s/vue-2-composition-api-forked-k7unx?file=/src/App.vue

**Comment by xiaoxiangmoe** [comment]
This is because you have a circular dependency.

Move `export const ConditionIK = Symbol("Condition");` to another file and import it.
