### ISSUE TITLE
类型错误 style class  ref scopedSlots

### ISSUE THREAD

**Issue by zzzz-Z** [vuejs/composition-api#908]
<img width="396" alt="image" src="https://user-images.githubusercontent.com/28984303/154611673-0d427b4e-c5b9-4666-9506-0d4d19f3e62b.png">
<img width="292" alt="image" src="https://user-images.githubusercontent.com/28984303/154611682-cf852067-d278-4c16-af74-6362347ab1f6.png">
<img width="182" alt="image" src="https://user-images.githubusercontent.com/28984303/154611713-5518defc-9223-47ac-9190-eaff31548a00.png">
<img width="887" alt="image" src="https://user-images.githubusercontent.com/28984303/154611793-aa2c55f5-90a0-403a-b135-87fa0ffc8910.png">

**Comment by zzzz-Z** [comment]
class style ref  不应该被检测吧

**Comment by xiaoxiangmoe** [comment]
Can you provide a minimal reproduction?

**Comment by galenjiang** [comment]
用最新的vue-cli引入，composition-api, 配好dts, 必现

**Comment by galenjiang** [comment]
我装了好几个版本，发现1.4.0引入的bug, 1.3.3之前都是可以的
