### ISSUE TITLE
[babel-preset-vca-jsx] new feat: Support allocating `template refs` with `JSX` on the render function returned by `setup()`

### ISSUE THREAD

**Issue by luwanquan** [vuejs/composition-api#91]
I wrote a babel plugin that automatically imports `createElement as h` when writing JSX and `functional` syntax that supports only `setup()` and `template refs` that supports `setup()`.

Github see [babel-preset-vca-jsx](https://github.com/luwanquan/babel-preset-vca-jsx)

Example see [babel-preset-vca-jsx-example](https://codesandbox.io/s/babel-preset-vca-jsx-example-7k5xs)

### Prerequisite
Project with `@vue/composition-api` and `@vue/babel-preset-app` installed

### Feature
1. Automatically import `createElement as h` when writing `JSX`
1. The functional component syntax of the `setup()` by default
    ```javascript
    const Hello = (prop, ctx) => {
        const state = ref('hello world');
        return () => <h1>{state.value}</h1>;
    };
    ```
1. Allocating template refs with `JSX` on the render function returned by `setup()`
    ```javascript
    const Hello = createComponent({
        setup() {
            const root = ref(null);
            watch(() => console.log(root.value)); // <h1>...</h1>
            /*
            return () => h('h1', {
                ref: root
            }, 'hello world!');
            */
            return () => <h1 ref={root}>hello world!</h1>
        }
    });
    ```

**Comment by drewstewart** [comment]
hey mate this is awesome, can't wait to try it out. also, tsx ftw!

**Comment by luwanquan** [comment]
> 嘿，伙伴，这太棒了，迫不及待想试试看。还有，tsx ftw！

Yes, tsx also supports.

**Comment by luwanquan** [comment]
> hey mate this is awesome, can't wait to try it out. also, tsx ftw!

Yes, tsx also supports.

**Comment by luwanquan** [comment]
babel-preset-vca-jsx@v0.1.0 has been released.

Thanks to the author @liximomo  for making createElement independent and making JSX more free.

**Comment by NikitaIT** [comment]
@luwanquan it doesn’t quite work now.
```
export const refUse = () =>
  createComponent({
    setup() {
      const root = useRef();
      watch(() => console.log(root.root.value)); // null
      /*
    return () => h('h1', {
        ref: root
    }, 'hello world!');
    */
      return () => <h1 ref={root.root}>hello world!</h1>;
    }
  });
function useRef() {
  const root = ref(null);
  return { root };
};
```

**Comment by luwanquan** [comment]
Hi, @NikitaIT 

Sorry for the late reply

Encapsulation is not supported here, `const root = ref (null)` must be in `setup ()`

And the initial value of `ref (null)` must be `null`

**Comment by antfu** [comment]
Just add a link to your plugin in the upcoming readme changes 01a036f4598b6a698826558a63451c48badd7778. Let me know if there are any updates, I can update the readme according to them. Thanks.
