### ISSUE TITLE
defineComponent不支持tree-shaking

### ISSUE THREAD

**Issue by KesionX** [vuejs/composition-api#910]
我在组件库内使用capi，发现它会导致打包的时候无法tree-shaking

eg:
组件A
``` javascript
export default defineComponent({
   name: 'xx',
   setup() {}
})

```
index.js
```
import A from 'a.vue'

// not use A
console.log('hello');
```

打包后仍然会把A打入

**Comment by xiaoxiangmoe** [comment]
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example).
