### ISSUE TITLE
`$scopedSlots` is not mirrored correctly in `context.slots`

### ISSUE THREAD

**Issue by tomasz-pucka** [vuejs/composition-api#911]
### Version
1.4.9

### Reproduction link
[Vue 2](https://codesandbox.io/embed/vue2-with-composition-api-slots-presence-updating-test-g2td8s?autoresize=1&expanddevtools=1&fontsize=12&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark)
[Comparison with Vue 3](https://codesandbox.io/embed/vue3-slots-presence-updating-test-is4cv8?autoresize=1&expanddevtools=1&fontsize=12&hidenavigation=1&module=%2Fsrc%2FApp.vue&theme=dark)
If there are some issues with running the preview, try to refresh it using the refresh button in the console.

### Steps to reproduce
Toggle the checkbox in the preview and observe the conditionally rendered content and slot objects values in the console. Try to change the initial `showSlots` value in the `App` component to `false` and observe the difference.

### What is expected?
The `context.slots` property should be updated when slots are rendered conditionally and contain up-to-date value in the `updated` hook. Behaviour should be identical to the vue 3 example.

### What is actually happening?
The value of `context.slots` doesn't seem to be updated after component initialization.

**Comment by xiaoxiangmoe** [comment]
2333

**Comment by skytt** [comment]
The same problem.... got empty context.slots object when the slot was updated after mounted lifecycle. Using getCurrentInstance().vnode.componentInstance.$scopedSlots.default?.({}) can get the current slots content, but context.slots cannot
