### ISSUE TITLE
有关在script setup上面的问题 

### ISSUE THREAD

**Issue by mhxy13867806343** [vuejs/composition-api#915]
刚刚遇到一个问题
如果使用这种<script setup></script> 无法使用 
  import {useContext, defineProps, defineEmit } from '@vue/composition-api'
这种 
只能使用
setup(props,ctx){
 ....
return {}
},
@vue/composition-api版本号:^1.4.6 号  请问何时支持？

**Comment by mhxy13867806343** [comment]
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/4418166/159437559-4c96fc2d-795a-462d-a6f1-17062f18be1c.png">

刚刚用空白页面测试了，出现问题

**Comment by mhxy13867806343** [comment]
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/4418166/159438011-876c5dfc-37f1-4f59-b3d3-6406e066e5a2.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/4418166/159438030-c8dfa357-bee2-4c17-847d-410065819e60.png">

有关uniapp项目中使用出现的问题

**Comment by xiaoxiangmoe** [comment]
defineProps, defineEmit is build time macro and useContext is deprecated.

The script setup support is in https://github.com/antfu/unplugin-vue2-script-setup
