### ISSUE TITLE
"export 'value' was not found in '@vue/composition-api'

### ISSUE THREAD

**Issue by ChrisMichaelPerezSantiago** [vuejs/composition-api#92]
Hi devs,

I'm having trouble importing `import {value} from '@vue/composition-api'`. 

I don't know if it is no longer necessary to use value ....?

I had a complete project done with vue-function-api and now everything stopped working. 😠

**Comment by drewstewart** [comment]
`value` has been replaced by `ref`

**Comment by pangao66** [comment]
https://vue-composition-api-rfc.netlify.com/   you can read the documention
