### ISSUE TITLE
请问为什么没有导出VueProxy这个类型

### ISSUE THREAD

**Issue by liuzaijiang** [vuejs/composition-api#923]

**Comment by antfu** [comment]
非 Vue3 API

**Comment by liuzaijiang** [comment]
> 非 Vue3 API

请问是否可以提供DefineComponent这个类型，这个是vue3提供的类型，因为发现在tsx中使用defineComponent定义的组件时，是没办法推倒出class，style等htmlAttributes的，在vue3中我们可以通过
```
DefineComponent<Omit<HTMLAttributes, keyof compProps> & compProps>
```
实现，这里的VueProxy是不是可以理解为vue3的DefineComponent 这个类型呢？

**Comment by antfu** [comment]
> 请问是否可以提供DefineComponent这个类型

PR welcome! `VueProxy` 是内部类型，当时Vue3应该还没有 `DefineComponent` 这个概念
