### ISSUE TITLE
Reactivity in v-for does not work

### ISSUE THREAD

**Issue by brolnickij** [vuejs/composition-api#928]
### Problem
Solving a trivial problem, using `@vuejs/composition-api`, I came across a reactivity problem in `v-for`, namely
```vue
<template>
  <div 
    v-for="(item, itemIndex) in items" 
    :key="itemIndex"
  >
    <p v-if="states[itemIndex]">{{ item.name }}</p>
    <button @click="onSwitch(itemIndex)">switch</button>
  </div>
</template>


<script setup>
  const items = ref([
    { name: "test" },
    { name: "test 1" },
    { name: "test 2" },
    { name: "test 3" }
  ])
  const states = ref(new Array(items.value.length).fill(false))

  // when changing value (states.value[index]), reactivity does not work
  function onSwitch(index) {
    states.value[index] = !states.value[index]
  }
</script>
```

### Examples
[Vue.js 3](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8ZGl2XG4gICAgdi1mb3I9XCIoaXRlbSwgaXRlbUluZGV4KSBpbiBpdGVtc1wiIFxuICA+XG4gICAgPHAgdi1pZj1cInN0YXRlc1tpdGVtSW5kZXhdXCI+e3sgaXRlbS5uYW1lIH19PC9wPlxuICAgIDxidXR0b24gQGNsaWNrPVwib25Td2l0Y2goaXRlbUluZGV4KVwiPnN3aXRjaDwvYnV0dG9uPlxuICA8L2Rpdj5cbjwvdGVtcGxhdGU+XG5cblxuPHNjcmlwdCBzZXR1cD5cbmltcG9ydCB7IHJlZiB9IGZyb20gJ3Z1ZSdcblxuY29uc3QgaXRlbXMgPSByZWYoW1xuICB7IG5hbWU6ICd0ZXN0JyB9LFxuICB7IG5hbWU6ICd0ZXN0IDEnIH0sXG4gIHsgbmFtZTogJ3Rlc3QgMicgfSxcbiAgeyBuYW1lOiAndGVzdCAzJyB9XG5dKVxuY29uc3Qgc3RhdGVzID0gcmVmKG5ldyBBcnJheShpdGVtcy52YWx1ZS5sZW5ndGgpLmZpbGwoZmFsc2UpKVxuXG5mdW5jdGlvbiBvblN3aXRjaChpbmRleCkge1xuICBzdGF0ZXMudmFsdWVbaW5kZXhdID0gIXN0YXRlcy52YWx1ZVtpbmRleF1cbn1cbjwvc2NyaXB0PlxuIiwiaW1wb3J0LW1hcC5qc29uIjoie1xuICBcImltcG9ydHNcIjoge1xuICAgIFwidnVlXCI6IFwiaHR0cHM6Ly9zZmMudnVlanMub3JnL3Z1ZS5ydW50aW1lLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSJ9) | work
[Vue.js 2 + vuejs/composition-api](https://codesandbox.io/s/vue-composition-api-example-forked-slyttz?file=/src/App.vue) | doesnt work

--

P.S. many thanks to the vue.js team for developing this wonderful tool

**Comment by jacekkarczmarczyk** [comment]
https://v2.vuejs.org/v2/guide/reactivity.html?redirect=true#For-Arrays

**Comment by LinusBorg** [comment]
we provide `set` and `delete` helpers for this:

```js
import { set } from '@vue/composition-api'
// ...
set(states.value, index, !states.value[index])
```

**Comment by brolnickij** [comment]
@LinusBorg thank you for your help!
