### ISSUE TITLE
渲染函数h()设置属性或prop不生效？

### ISSUE THREAD

**Issue by zhchjiang95** [vuejs/composition-api#932]
<img width="737" alt="image" src="https://user-images.githubusercontent.com/39526442/167999304-7beec866-a297-4922-94ac-3b2864ff1ca4.png">
<img width="737" alt="image" src="https://user-images.githubusercontent.com/39526442/167999540-1e1e4acf-df1c-4eca-97c4-d3e9c6db6d5a.png">

如图，实际页面id和innerHTML都未生效！
创建一个ElementUI组件，传入props也无法生效，是否不支持还是BUG？

<img width="460" alt="image" src="https://user-images.githubusercontent.com/39526442/167999842-7c9a9f4f-d0de-4910-857b-8c1fa9eeaea2.png">

**Comment by MinatoHikari** [comment]
```
// 普通的 HTML attribute
  attrs: {
    id: 'foo'
  },
 // 组件 prop
  props: {
    myProp: 'bar'
  },
```
这不是vue3

**Comment by zhchjiang95** [comment]
> 确实是这样，受教👏
