### ISSUE TITLE
Can't set new reactive key using 'set' function asynchronously

### ISSUE THREAD

**Issue by bigggge** [vuejs/composition-api#933]
```javascript
setup(){
    const a = reactive({})
    // set(a, 'testValue', 1) // worked
    setTimeout(() => {
      set(a, 'testValue', 2) // not worked
    })
    return {
      ...toRefs(a)
    }
  }
```

**Comment by jelle-r** [comment]
i have the same problem.

**Comment by xiaoxiangmoe** [comment]
@bigggge @jelle-r Can you provide me a minimal reproducible example?

**Comment by xiaoxiangmoe** [comment]
@bigggge @jelle-r Can you provide me a minimal reproducible example?
How do this code perform on vue 3?

**Comment by jelle-r** [comment]
I am not able to provide an example anymore, since we moved to the vue3 stack in the meantime.

**Comment by shrpne** [comment]
It may be related to #580

Test case: https://codesandbox.io/s/beautiful-feather-qrjq4n?file=/src/components/TestCase.vue
(computed property not updated)

**Comment by shrpne** [comment]
not stale

**Comment by shrpne** [comment]
not stale

**Comment by shrpne** [comment]
Not stale

**Comment by xiaoxiangmoe** [comment]
not stale

**Comment by Anubarak** [comment]
Did someone ever found a solution?
I face the same issue
