### ISSUE TITLE
About expose

### ISSUE THREAD

**Issue by LancerComet** [vuejs/composition-api#936]
This package didn't come with the function `expose`, but the way to implement it is quite straightforward:

```tsx
const expose = (exposing: Record<string, any>) => {
  const instance = getCurrentInstance()
  if (!instance) {
    throw new Error('expose should be called in setup().')
  }

  const keys = Object.keys(exposing)

  keys.forEach(key => {
    instance.proxy[key] = exposing[key]
  })

  onBeforeUnmount(() => {
    keys.forEach(key => {
      instance.proxy[key] = undefined
    })
  })
}

const App = defineComponent({
  setup () {
    expose({
      greet: () => console.log('Greeting')
    })

    return () => (
      <div>Something</div>
    )
  }
})
```

Because using composition API doesn't need to take care of context and responsiveness, I think it is okay to assign functions to the instance directly, and it turns out it works quite well. So how about adding it back?

**Comment by nooooooom** [comment]
他们在 #849 讨论说 Vue2 中不可能有 export，但是我觉得既然 setup 可以在 mixins 中使用，为什么不可以把 expose 作为混入的一种情况呢，收集所有的 expose 以及 return，return 为函数的就丢给 render，expose 合并继续 proxy 就好了

**Comment by wobsoriano** [comment]
Vue 2.7 now comes with `expose`

```js
setup (_props, { expose }) {
  expose({ fn1, fn2 })
}
```

**Comment by LancerComet** [comment]
Since Vue 2.7 has its expose function, this issue has became unnecessary, closed.

**Comment by cloydlau** [comment]
I think it's still useful since `@vue/composition-api` is inherently for Vue 2.6.
