### ISSUE TITLE
On the rigor of type checking in volar

### ISSUE THREAD

**Issue by hexf00** [vuejs/composition-api#940]
A component declared through `definecomponent` has a defect in type verification.

Perhaps the definition of `Data` does not apply to all occasions?

I tried to delete the definition of unknown. I found that `ComponentPropsOptions` still need to accept the generics defined by unknown. Otherwise, the `required` definition of props will not be recognized, resulting in the attribute being considered optional.

I have explored here for the time being and found no other problems.

> ![Snipaste_2022-05-26_00-59-22](https://user-images.githubusercontent.com/9587872/170319833-21c82c17-dfbe-4a8c-8540-42d985a36a1e.png)
> 
> I use https://github.com/johnsoncodehk/volar-starter vue2 branch.
> 
> I propose this issue because the Class API or Vue.extend performs better.
> 
> ![Snipaste_2022-05-26_01-07-37](https://user-images.githubusercontent.com/9587872/170320884-57dab79f-b527-4217-abef-6fc3cf37ce43.png)

https://github.com/johnsoncodehk/volar/issues/1350#issue-1248417358

> This is `@vue/composition-api` behavior from https://github.com/vuejs/composition-api/blob/032f2c75992043a02a61e05d5f1493d78738ae72/src/component/common.ts#L1.

https://github.com/johnsoncodehk/volar/issues/1350#issuecomment-1140293350

**Comment by CRMaxime** [comment]
Experiencing the same issue :( this should be reopened.
