### ISSUE TITLE
Cannot read properties of undefined (reading '$createElement')

### ISSUE THREAD

**Issue by qiYuei** [vuejs/composition-api#943]
Create projects with Vuecli5 ,When writing a jsx function in setup, h = this.$createElement will be automatically injected, but there is no this in setup, and h has been injected import {h} from '@vue/composition-api'

Console error message
![image](https://user-images.githubusercontent.com/48666945/174205511-c736b891-0661-4072-bba9-4ff0f487e73c.png)

![image](https://user-images.githubusercontent.com/48666945/174205338-e7eed742-cce3-4947-9531-5b615fff0fa0.png)

version
[platform]:window10
[node]:14.16.1
 "@vue/composition-api": "^1.6.1"
 "@vue/babel-helper-vue-jsx-merge-props": "^1.2.1",
 "@vue/babel-preset-jsx": "^1.2.4",

```js
// babel.config.js
module.exports = {
  presets: [
    "@vue/cli-plugin-babel/preset",
    ["@vue/babel-preset-jsx", { compositionAPI: true }], // 开启 jsx
  ],
  plugins: [
    ["@babel/plugin-transform-typescript", { isTSX: true }], // 开启 typescript
    "@babel/plugin-proposal-optional-chaining",
  ],
};

```

**Comment by Mr-xzq** [comment]
also meet this problem
