### ISSUE TITLE
Type error of ref in webstorm

### ISSUE THREAD

**Issue by theWorkFsz** [vuejs/composition-api#95]
when I use `ref` in webstorm will get the type error messages  like this
```ts
const test = ref(1)
test.value = 2
```

```
Assigned expression type 2 is not assignable to type HasDefined extends true ? S : RefValue
...
  Type 2 is not assignable to type RefValue
    Type 2 is not assignable to type T extends Ref ? V : UnwrapRef
      Type 2 is not assignable to type UnwrapRef
```
anyone know how to fix this ?

**Comment by drafu** [comment]
Possibly related to #90. There is something wrong with typings of a ref function.
As a temporary solution, try explicitly typing your variables like that
```ts
const test: Ref<number> = ref(1);
test.value = 2;
```
That must not throw errors while we wait for a fix.

**Comment by liximomo** [comment]
Upgrade your typescript.
