### ISSUE TITLE
打包到UAT环境，vue-composition-api就会报错，本地测试没问题

### ISSUE THREAD

**Issue by aadelina** [vuejs/composition-api#951]
![image](https://user-images.githubusercontent.com/48461605/177902854-14d24210-0d0b-489a-85e7-1b81f68a8389.png)
![image](https://user-images.githubusercontent.com/48461605/177902895-717dfef4-3d28-4a41-9091-fdce920cdba9.png)
线上环境获取不到watcher

**Comment by aadelina** [comment]
![image](https://user-images.githubusercontent.com/48461605/177932611-5f4a3913-f56b-4d90-bd0f-48317b875850.png)
问题找到了，vue自己将版本升级上去了

**Comment by AlanKnightly** [comment]
@aadelina 谢谢大哥！我这边刚刚也遇到一模一样的这个问题，正排查这，看来索性锁死vue相关版本就好了。我们是一个老旧项目引入composition-api。再次感谢
