### ISSUE TITLE
The setup binding property "xxx" is already declared.

### ISSUE THREAD

**Issue by youuss** [vuejs/composition-api#963]
hi, when i use vue2.6.11 with @vue/composition-api@1.7.0, i got a vue warnning  `The setup binding property "test" is already declared.`. I also provide a simple demo in https://codesandbox.io/s/objective-cohen-qf0uxk
plz check that, thx

**Comment by jacekkarczmarczyk** [comment]
Your reproduction uses 2.7.x and it conflicts with composition api plugin, so either remove the plugin or use vue 2.6.x

**Comment by youuss** [comment]
> Your reproduction uses vue 2.7.x and it conflicts with composition api plugin, so either remove the plugin or use vue 2.6.x

<img width="481" alt="image" src="https://user-images.githubusercontent.com/34266177/185857862-58e3de43-1cce-4496-87c7-11309ef0cd14.png">
I just find vue 2.6.x

**Comment by lmh-justdo** [comment]
Maybe you need to check the vue version in node_modules actually has been installed. if the version >= 2.7, you just need to  `import from vue`, when the version < 2.7, you need to follow the @vue/composition-api md steps.

**Comment by Tzdy** [comment]
把^2.6.11的^去掉，否则会下载2.7.x

**Comment by youuss** [comment]
> 把^2.6.11的^去掉，否则会下载2.7.x

嗯 但是老项目 不锁版本直接去install，如果不关注node_modules很容易产生类似情况
