### ISSUE TITLE
Variables created with ref in <templete>,do not automatically expand value

### ISSUE THREAD

**Issue by yang49519845** [vuejs/composition-api#969]
Vue version is V2.6.14
@vue/composition-api: 1.7.1

https://codesandbox.io/p/github/yang49519845/vue2-composition-api/draft/romantic-darwin?file=%2Fsrc%2FApp.vue&selection=%5B%7B%22endColumn%22%3A13%2C%22endLineNumber%22%3A19%2C%22startColumn%22%3A13%2C%22startLineNumber%22%3A19%7D%5D

In local development, everything is normal. When this component is encapsulated into a global component, the value will not be automatically expanded into the template

**Comment by rangeldor** [comment]
Did you manage to resolve this issue?

I am with the same bug.

**Comment by yang49519845** [comment]
> Did you manage to resolve this issue?
> 
> I am with the same bug.

I used version 2.6.14 to run test cases. The first one was not passed. I passed 2.6.10

**Comment by rangeldor** [comment]
This bug still exists and it would be nice to be fixed in the next version
