### ISSUE TITLE
Methods returned to template context won't be added to the vm when testing with Jest

### ISSUE THREAD

**Issue by IlCallo** [vuejs/composition-api#97]
I'm unit testing with Jest and the new Composition API.
Whenever I return a function to template scope ([like into the basic example](https://vue-composition-api-rfc.netlify.com/#basic-example)), using it somewhere (in my case into a `v-if`, I don't know if it's a special case) and try to `shallowMount` the component, I get a

`Error in render: "TypeError: _vm.<functionName> is not a function"`

I'm using TypeScript.
The error appear only during testing, the app compile and build without problem.

Simplified version of the SFC I'm using
```vue
<script lang="ts">
import { createComponent } from '@vue/composition-api';

export default createComponent({
  setup() {
    function trial() {
        return true;
    }
    return { trial };
  },
});
</script>
<template>
    <div>
        <span v-if="trial()"></span>
    </div>
</template>
```

**Comment by liximomo** [comment]
Did you make sure to install the CompositionAPI plugin in test？

Paolo Caleffi <notifications@github.com> 于 2019年8月27日周二 22:47写道：

**Comment by IlCallo** [comment]
Gotcha.
Adding `localVue.use(VueCompositionApi);` solved the issue.
