### ISSUE TITLE
why setup run twice in vue2

### ISSUE THREAD

**Issue by zhoufanglu** [vuejs/composition-api#970]
i install @vue/composition-api  at vue 2.6。
* in setup
```js
<script>
export default {
  setup() {  // run twice
    console.log('test composition =================')
  }
}
</script>
```
* in created
```js
  created() {  // run  at a time
    console.log('test composition =================')
  }
```

**Comment by xiaoxiangmoe** [comment]
Can you provide me a reproduction demo?

**Comment by zhoufanglu** [comment]
> Can you provide me a reproduction demo?

sorry, this is company project,  rather old, later i use vue2 syntax

**Comment by alexdeia** [comment]
I have the same problem with vue 2 and composition api. But in onMounted hook code runs once.

**Comment by houcheng** [comment]
Is there any progress on this issue?
For reproducing, Just create a vue 2 project and write a component in composition API. The setup would be called twice.
Below is a simple vue for reproducing this issue:

<script setup lang="ts">
import {ref} from "@vue/composition-api";

const a = ref('aa')
const b = ref('bb')
console.log('call setup')
</script>

<template lang="pug">
span haha {{a}} {{b}}
</template>

**Comment by spart4k** [comment]
hey?

**Comment by marcel-wtfoxtrot** [comment]
Hey @xiaoxiangmoe ,

i just ran into the exact same issue using vue 2.7.14 and composition-api@1.7.2

here is a Reproduction Demo: https://codesandbox.io/s/confident-architecture-p6jm5p?file=/src/App.vue

Just have a look at the terminal. You'll find Setup being printed twice, mounted only once.

**Comment by xiaoxiangmoe** [comment]
Hi，@marcel-wtfoxtrot 
In vue 2.7, you needn't use composition-api, just use vue

**Comment by wsxiao** [comment]
> 我在 vue 2.6 安装@vue/composition-api。
> 
> * 在设置中
> 
> ```js
> <script>
> export default {
>   setup() {  // run twice
>     console.log('test composition =================')
>   }
> }
> </script>
> ```
> 
> * 在创建的
> 
> ```js
>   created() {  // run  at a time
>     console.log('test composition =================')
>   }
> ```



> i install @vue/composition-api at vue 2.6。
> 
> * in setup
> 
> ```js
> <script>
> export default {
>   setup() {  // run twice
>     console.log('test composition =================')
>   }
> }
> </script>
> ```
> 
> * in created
> 
> ```js
>   created() {  // run  at a time
>     console.log('test composition =================')
>   }
> ```

Have you found the reason?

**Comment by wsxiao** [comment]
Have you found the reason?
