### ISSUE TITLE
安装时，报vue版本范围错误

### ISSUE THREAD

**Issue by quixote1304629** [vuejs/composition-api#990]
![image](https://github.com/vuejs/composition-api/assets/32378929/10ecd783-69a7-4e77-b342-5440af953521)

vue2.7.14 

目前我项目使用2.7.14版本，因其他原因不能降级，这@vue/composition-api目前限制了vue 2.7. 有办法“破解”么

**Comment by zhhbstudio** [comment]
@quixote1304629  vue 2.7 已经支持 composition-api 不需要装这个包了
