### ISSUE TITLE
【BUG】watch() 传入reactive类型的数据，vue3.4与3.3表现不一致

### ISSUE THREAD

**Issue by Oumae-Kumiko** [vuejs/composition-api#992]
3.2、3.3版本的watch() 传入reactive类型监听源，即使deep设置为false，源码上会默认设置为true，修改深层属性会触发监听回调。
但在3.2升到3.4版本时，代码不变，deep依旧是false，此时修改reactive里深层的属性，不会触发监听！

**Comment by dews** [comment]
This repo is for vue2. I think you go to the wrong place.
