### ISSUE TITLE
Getting the property set by the `set` method through a function is not reactive

### ISSUE THREAD

**Issue by cscxj** [vuejs/composition-api#993]
In the template, I obtained the newly set property of the reactive object through a function, and the view was not reactive, but directly taking this value was reactive. I used Vue 3 to implement the same logic, and it was reactive.
[Vue 2 example](https://codesandbox.io/p/sandbox/sparkling-haze-hx6f36?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxl654fz0006356j3e7iwdnh%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxl654fz0002356juxt4ceb4%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxl654fz0003356j7nmybbdk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxl654fz0005356jxez41lfq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B44.25328640183895%252C55.74671359816105%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxl654fz0002356juxt4ceb4%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl654fz0001356jpwwwfv4p%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clxl654fz0002356juxt4ceb4%2522%252C%2522activeTabId%2522%253A%2522clxl654fz0001356jpwwwfv4p%2522%257D%252C%2522clxl654fz0005356jxez41lfq%2522%253A%257B%2522id%2522%253A%2522clxl654fz0005356jxez41lfq%2522%252C%2522activeTabId%2522%253A%2522clxl654fz0004356jtu7k484m%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl654fz0004356jtu7k484m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522isCloud%2522%253Afalse%252C%2522id%2522%253A%2522clxl65uez004v356jcg1aq7kw%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%252C%2522clxl654fz0003356j7nmybbdk%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clxl654fz0003356j7nmybbdk%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
[Vue 3 example](https://codesandbox.io/p/devbox/vue3-demo-7s5tyl?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clxl6uzvv0007356johq2nap0%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clxl6uzvv0002356jd5hppu49%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clxl6uzvv0004356jj7wksvhw%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clxl6uzvv0006356jom026hly%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clxl6uzvv0002356jd5hppu49%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl6uzvv0001356j297lil9f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clxl6uzvv0002356jd5hppu49%2522%252C%2522activeTabId%2522%253A%2522clxl6uzvv0001356j297lil9f%2522%257D%252C%2522clxl6uzvv0006356jom026hly%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl6uzvv0005356jm2tiqi0f%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clxl6uzvv0006356jom026hly%2522%252C%2522activeTabId%2522%253A%2522clxl6uzvv0005356jm2tiqi0f%2522%257D%252C%2522clxl6uzvv0004356jj7wksvhw%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clxl6uzvv0003356jld49b337%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522id%2522%253A%2522clxl6uzvv0004356jj7wksvhw%2522%252C%2522activeTabId%2522%253A%2522clxl6uzvv0003356jld49b337%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by jacekkarczmarczyk** [comment]
https://github.com/vuejs/vue/issues/12774#issuecomment-1274141924

**Comment by cscxj** [comment]
> [vuejs/vue#12774 (comment)](https://github.com/vuejs/vue/issues/12774#issuecomment-1274141924)

Thanks.
